- manifests/vagrant-bosh.yml
New installation via vagrant-bosh plugin using garden linux 0.34 fails to run Diego Inigo tests with http response 500.
> Bump garden linux to 0.117.0

- docs/deploying/bosh.scrbl
I'm not 100% sure this is right, this is what I have in my environment, and it's working. It's also following the convention found here: https://github.com/concourse/concourse/blob/master/manifests/aws-vpc.yml
> jobs.worker.gate.atc.username --> jobs.web.properties.tsa.atc.username

- manifests/bosh-lite.yml
&web-ip is not used so can be removed,
same as https://github.com/concourse/concourse/pull/24 but now on the right branch.
> Cleanup unused anchor

- manifests/aws-vpc.yml
- instead of c3.
- use 30GB of ephemeral disk.
> Use c4.large instances types for compilation.

- docs/deploying/vagrant.scrbl
Now that no-pipeline screen exists, the binaries are in the centre, not bottom-right.
> Update fly install instructions

- docs/getting-started.any
--paused=false instead of --pause=false
> docs: fix typo

- docs/serious/bosh.any
fix typo in the variable name for jobs.worker.properties.garden.btrfs_store_size_mb from jobs.worker.properties.garden.btrfs_store_size_mv
> fix typo in btrfs_store_size_mb

- manifests/cloudformation.json
Otherwise VPC is created with no name.
Signed-off-by: Jim Park <spark@pivotal.io>
> add name to VPC

- jobs/consul-agent/templates/agent_ctl.sh.erb
resolvconf isn't installed on CentOS
[fixes #171]
> agent_ctl doesn't fail if resolvconf isn't installed.

- jobs/groundcrew/templates/beacon_ctl.erb
After conversation with @vito yesterday we added timeouts so that workers can reconnect when their connection fails.
> Add timeouts to SSH tunnel so we can reconnect when it fails.

- docs/running-tasks.any
When running the provided example using Concourse v0.72.1, I got the following error:
```
resource script '/opt/resource/check []' failed: exit status 1
stderr:
failed to read request: json: cannot unmarshal number into Go value of type string
errored
```
This changes the value in the example YAML to be a string rather than a number, which fixes the issue.
> `image_resource` `tag` should be a string

- docs/steps/attempts.any
Clearer to me at least.
(As discussed in slack) I was a little confused by the use of the word "retry" in the docs, as that seemed to imply the number of attempts was the number of times after the first attempt it would be retried, however this wasn't the case and it is intended to be the total number of times the step will be tried (with me so far? :) ).
Reword things in an attempt (heh) to make things clearer.
> Make 'attempts' doc a little clearer

- docs/using-concourse/running-tasks.any
Going through the documentation I found a couple of things that may need correction. For the code sample, I'm not sure if the golang reference was in reference to the sample yaml. If it was, this may make things less confusing.
> Fixed doc typos

- docs/index.any
As suggested by olefriis in your Slack channel:
> olefriis [8:14 AM]
> Hi there! I'm just starting to read about Concourse and spinning up a
> Vagrant machine following the instructions on http://concourse.ci/ - it's a
> really nice way of getting a demo environment up and running quickly.
>
> [8:14]
> However, the link to the server inside the VM is an https URL, but the
> server is running plain old http.
>
> [8:14]
> ...which means that following the link from the concourse.ci front-page will
> just get me an error.
>
> [8:15]
> (It's in the "The web server will be running at 192.168.100.4:8080." part of
> the Concourse main page.)
>
> [8:16]
> If any of you guys know how to remove that "s" in the link, you'll save a
> lot of people a couple of minutes of frustration
> Change concourse/lite URL to HTTP

- docs/using-concourse/resource-types.any
- existing docs point to resource that does not work with newer versions of concourse and is not maintained
> Reference cloudfoundry-community slack resource in docs

- jobs/atc/spec
When we upgraded and added this property, we did not include the protocol. This caused the basic auth login page to generate invalid links.
> Provide example for `external_url` property.

- jobs/groundcrew/monit
When deploying Concourse, I always am forced to run `bosh deploy` again because it thinks the workers failed to update.
```
Director task 4396
Started preparing deployment > Preparing deployment. Done (00:00:00)
Started preparing package compilation > Finding packages to compile. Done (00:00:00)
Started updating job web > web/0 (77fab7e0-b22d-4c87-b7a8-2562070e3479) (canary). Done (00:03:25)
Started updating job worker-aws
Started updating job worker-aws > worker-aws/0 (8a0de851-f090-45b3-92d7-cdfe9f1df64c) (canary). Failed: `worker-aws/0 (8a0de851-f090-45b3-92d7-cdfe9f1df64c)' is not running after update. Review logs for failed jobs: beacon, jettison, baggageclaim, garden (00:04:32)
```
ssh-ing onto the worker-aws/0 and running `monit summary` will show that all the monit processes are …
> Allow beacon and jettison to have 60 seconds to start before timing out

- docs/setting-up/installing.any
Apparently
> Vagrant can not and does not automatically download the updated box and update the machine because...updating the machine requires destroying it and recreating it
https://www.vagrantup.com/docs/boxes/versioning.html
Not ideal that the machine needs to be re-created, but it doesn't look like there's an easy way to upgrade otherwise.
> add instructions about how to upgrade Concourse in Vagrant

- docs/using-concourse/resource-types.any
Add the resource https://github.com/redfactorlabs/concourse-smuggler-resource/ to the list of third party resources.
Although it is not a resource per sé, but a framework to quickly implement resources and lower the entry barrier.
> Add smuggler generic resource framework to docs

- docs/using-concourse/resource-types.any
Made a resource to work with branch/PR statuses if you think a reference would be useful to the community.
> Add GitHub Commit Status third-party resource

- docs/using-concourse/implementing-resources.any
When i develop my first resource it was hard to see how I can put trace and how to have colors to the web interface. I had to look on other resource code.
I added these small information in the doc.
> Add useful information in "implementing resource" doc

- jobs/tsa/spec
- jobs/tsa/templates/tsa_ctl.erb
We want to be able to deploy Concourse v1.1.0 with bosh-init. bosh-init does not support the `link()` method and `spec.address` used in the TSA template file.
Use of the `link()` method and `spec.address` is now conditional. This was tested using bosh-init v0.0.87, as that stubs the `if_link()` method to always return false. 
**Note:** This stub method is available in bosh-init from v0.0.82.
Required adding explicit property `tsa_atc_address` and testing for `spec.address` as it is not available in bosh-init.
* Deploy Concourse v1.1.0+ using bosh and bosh-init
* Test template renders correctly
* Test Concourse still works
> Make Concourse v1.1.0 compatible with bosh-init

- docs/using-concourse/resource-types.any
This PR adds a link to a new resource to the appropriate docs page, one which notifies Bitbucket (yet another web-based Git service) of build statuses.
> Add Bitbucket build status resource

- docs/setting-up/installing.any
- manifests/concourse.yml
The example BOSH manifest for Concourse hardcodes vm types and does not specify what values the user should change. Since there is no de facto cloud config, we wanted to update the example manifest to accommodate for various cloud configs by using REPLACE_MEs. Then the user can drop in their own values from their own cloud config.
We also added in vm_extensions to notify the user that there needs to be a load balancer on the web vm and an ephemeral disk on the worker vm.
Hopefully this will help educate users on how to populate their manifests when deploying Concourse. Let us know if this looks like it could be merged.
Thanks,
Christian Ang and @kkallday
> Replace hardcoded vm types with REPLACE_MEs in example manifest

- docs/using-concourse/resource-types.any
The [devpi server](http://doc.devpi.net/latest/) is a PyPI mirror and development package server for Python packages. The [concourse-devpi-resource](https://github.com/mdomke/concourse-devpi-resource) allows it to track and upload packages from a devpi server.
> Add link to devpi-resource

- docs/using-concourse/resource-types.any
The original email resource ([pivotal-cf/email-resource](https://github.com/pivotal-cf/email-resource)) didn't include a
MTA and was therefore more complicated to configure and setup as I think
it should be.
> Add alternative email resource.

- docs/configuring/resources.any
Provide a pointer to the acceptable options, so users can understand what values work.
> Add details on `check_every` options.

- jobs/baggageclaim/spec
- jobs/baggageclaim/templates/baggageclaim_ctl.erb
This was previously created to be the same size as the `/var/vcap/data`
filesystem. This is a problem because this filesystem is also used by
other things (bosh packages and jobs, garden's graph and depot, logs
etc).
When the btrfs volume starts to get full, this can lead to errors when the
btrfs driver gets a `no space on device` error when writing to the
sparse image file. This in turn causes a kernel error, and the loopback
filesystem gets remounted read-only.
To reduce the likelihood of this, this changes the init script to allocate
10Gig less than the filesystem size. This PR also adds a property to allow
overriding the size for cases when 10Gig of overhead isn't enough.
> Reduce size of baggageclaim btrfs image file.

- docs/using-concourse/resource-types.any
We create a resource to control Open Build Service from Concourse. Would it be possible to add it to the resource types page in the documentation?
> Add open build service resource to resource types

- docs/using-concourse/fly-cli.any
- We were initially confused when the `ref:` prefix didn't work with the
bosh-io-release resource
- Our goal was to point out that the prefix is resource-dependent
Signed-off-by: Brian Cunnie <bcunnie@pivotal.io>
> Clarify use of from flag in check-resource CLI command

- jobs/atc/spec
- jobs/atc/templates/atc_ctl.erb
This PR allows user to specify custom Rieman taggs so they can be used for metrics filtering. 
Tags should be a dictionary under Riemann key in ATC properties. 
```
- name: atc
properties:
riemann:
tags:
foo: bar
```
We like to use disposable environments with one Concourse per env. Each concourse uses Riemann to send metrics to Datadog shared account. It's much easier to filter metrics if tags are set properly.
> Allow to specify Riemann tags

- docs/using-concourse/teams.any
- jobs/atc/spec
- jobs/atc/templates/atc_ctl.erb
This PR fixes an "oops, I forgot" that goes along with concourse/atc#112
> Update documentation and atc job for generic oauth scope verification

- docs/using-concourse/resource-types.any
I created a resource for tracking RSS feeds. This PR is to create a link in the docs, pointing to the resource's github page.
> Add link to RSS resource

- docs/using-concourse/resource-types.any
This pull request adds a [calendar resource](https://github.com/henrytk/calendar-resource) to the list of third party resources. The resource currently only supports Google Calendars, but could be extended to other providers.
> Add calendar resource

- docs/Gemfile
- docs/using-concourse/fly-cli.any
Some users asked how to show more builds in `fly builds`. Seems like this could go in the docs too.
> document -c flag for fly builds command [Obvious Fix]

- dev/setup
- dev/tsa
- docs/setting-up/installing.any
The documentation specifies "host_key" so we should be consistent (see https://concourse.ci/binaries.html)
It's also an issue with the Docker container. Don't know where that's created though.
Obvious Fix
> Use "host_key" as the default TSA host key name

- jobs/baggageclaim/templates/baggageclaim_ctl.erb
Check that the assigned IMAGE_SIZE is non-negative; if so then just default to the size of the persistent disk.
This fixes #818, #759 and #745.
> Fix bug where baggageclaim cannot start with small disk

- docs/using-concourse/fly-cli.any
As a followup to [Issue 660](https://github.com/concourse/concourse/issues/660) and [Pull request 114](https://github.com/concourse/fly/pull/114). This is the documentation for the `logout` command.
> Adding documentation for the logout command

- docs/using-concourse/running-tasks.any
When reading the Task documentation, it is not clear how to use an artifact resource as the task image. This PR adds a note to that refers the reader to the plan task step documentation which covers this topic.
> Add note about how to use artifact images

- docs/concourse-docs/lib/concourse/css/single-page.css
> Use max/min-widths to enforce sidebar width.

- docs/using-concourse/resource-types.any
We implemented a new 3rd party resource type to deployment resources with kubernetes helm.
See the documentation in the linked github repo: https://github.com/linkyard/concourse-helm-resource
> Add link to helm resource.

- docs/release-notes/v2.7.2.any
Fixes `s/configuratoin/configuration/`
> Fix typo in 2.7.2 release notes

- docs/steps/get.any
The documentation previously made it seem like `get:` always was the name matching what was declared up in the `resources:` section. But it confused people because it's not -- it's only that it typically does unless you use the `resource:` attribute.
> Documentation: Clarify `get:` step

- docs/setting-up/installing.any
When starting the docker-compose file, the web container typically starts faster than postgres and exits with a db connection error. Adding `restart: unless-stopped` will restart the web container until it becomes healthy (after postgres is up) and is the easiest way to handle this scenario. 
See also https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y
> docs: improve docker-compose instructions

- docs/steps/try.any
I believe a `params:` is missing here since `from:` isn't documented in the put step - https://concourse.ci/put-step.html
> fix typo in usage of put

- jobs/atc/templates/atc_ctl.erb
When deploying concourse with an external postgresql db and supplying the postgres ca, client cert, and client key, we saw the following in the atc logs when it failed to deploy:
```
failed to migrate database: pq: Private key file has group or world access. Permissions should be u=rw (0600) or less.
```
This PR changes the mode/owner on the postgresql cert/key file in the same manner as the other certs.
> set restricted mode on postgres ca, client cert, key

- docs/using-concourse/running-tasks.any
Pet-peeve, but in node projects the `node_modules` directory is not prefixed with a `.`
> Remove . from .node_modules in docs

- jobs/atc/templates/atc_ctl.erb
We modified the atc_ctl script manually and restarted with monit to validate this fix works as expected.
fixes #1355
Signed-off-by: Steve Katen <steve.katen@rackspace.com>
> Add path prefix into the template file

- docs/lit/setting-up/credential-management.lit
The documentation uses the wrong (old?) version of the flag name. In the current version of Concourse, it seems to have been renamed. We update the documentation so that people are not trying to use the wrong flag name.
> Fix --vault-path-prefix flag name

- docs/lit/setting-up/credential-management.lit
I had to look into the code to find out how the parameter has to be written. It's better to clarify it in the docs.
edit: Found the key name to use here:
https://github.com/concourse/atc/blob/3c7785c3aab803fd966d8f604f3b239626d5e3e8/creds/vault/vault.go#L41
> Clarify Vault field name to write for parameters

- docs/lit/using-concourse/resource-types.lit
Fix reference to point to `concourse/docs/lit/using-concourse/resource-types.lit` instead of `concourse/docs/using-concourse/resource-types.any`
> Fix reference

- docs/lit/using-concourse/teams.lit
There is no need, as far as I can tell from reading the code, for Concourse to need a `client_credentials` grant with `cloud_controller.admin`.
Allowing a `client_credentials` grant with `cloud_controller.admin` authority lets Concourse authenticate on its own behalf to UAA to get a token with full access to Cloud Controller (<https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-Security.md#client-tokens>) without a user being present.
Since we always have a user present, who is doing a standard OAuth flow, we shouldn't make the OAuth client more powerful than it needs to be.
> Remove dangerous and unneeded options from UAA example

- jobs/atc/templates/atc_ctl.erb
Previous code incorrectly passed a boolean value to a boolean flag.
This is wrong because the flag parser silently ignores values for boolean flags, and simply sets the value to true.
(I have a separate ATC PR to return an error when an unrecognized positional argument like this is received).
As such all bosh deployments of atc are skipping TLS verification whether you want it or not for CredHub and Vault.
There's a good chance this change will break existing installations that thought they were verifying TLS, but really weren't, and may not be configured correctly to do so.
> Stop always skipping TLS verification for credential managers

- manifests/single-vm.yml
`testflight` is not a common vm_type/network name for anyone's cloud-config
> Pass vm_type + network name into single-vm.yml as variables

- jobs/atc/spec
- jobs/atc/templates/atc_ctl.erb
- jobs/atc/templates/token_signing_key.erb
- jobs/groundcrew/spec
- jobs/groundcrew/templates/beacon_ctl.erb
- jobs/groundcrew/templates/drain.erb
- jobs/groundcrew/templates/tsa_host_key.pub.erb
- jobs/groundcrew/templates/worker_key.erb
- jobs/tsa/spec
- jobs/tsa/templates/token_signing_key.erb
- jobs/tsa/templates/tsa_ctl.erb
- jobs/tsa/templates/tsa_host_key.erb
- jobs/tsa/templates/worker_key.pub.erb
- manifests/single-vm.yml
- packages/generated_signing_key/packaging
- packages/generated_signing_key/spec
- packages/generated_tsa_host_key/packaging
- packages/generated_tsa_host_key/spec
- packages/generated_worker_key/packaging
- packages/generated_worker_key/spec
This would be helpful for [issue 1559](https://github.com/concourse/concourse/issues/1559) as it would allow us to generate our own token signing key and pass it through the appropriate jobs using the existing option flags.
> Expose token_signing_key option

- jobs/atc/spec
- jobs/atc/templates/atc_ctl.erb
BOSH properties or it didn't happen.
> Add prometheus properties.

- jobs/groundcrew/templates/known_hosts.erb
This fixes the `known_hosts` rendering problem in https://github.com/concourse/concourse/issues/1862.
On [jobs/groundcrew/templates/known_hosts.erb#L7](https://github.com/concourse/concourse/blob/v3.7.0/jobs/groundcrew/templates/known_hosts.erb#L7), the string that is supposed to be rendered by the erb is not within a scope where the erb can see it. We had to add a variable outside the block and set that for it to be brought within scope and rendered correctly.
@oozie and @christianang
> Render known_hosts entry

- jobs/atc/spec
- jobs/atc/templates/atc_ctl.erb
- jobs/atc/templates/generic_oauth_ca_cert.erb
PR for issue: https://github.com/concourse/concourse/issues/1914
Adds support for setting the generic oauth ca cert via bosh property.
> Support generic oauth ca cert.

- jobs/baggageclaim/templates/baggageclaim_ctl.erb
Fixes error where baggaeclaim will not start and
baggageclaim_ctl.log has error `chmod: cannot access
'/var/vcap/data/baggageclaim': No such file or directory`
> Add mkdir for /var/vcap/data/baggageclaim

- jobs/atc/spec
- jobs/atc/templates/atc_ctl.erb
Goes with https://github.com/concourse/skymarshal/pull/1 and https://github.com/concourse/atc/pull/249; see patch to skymarshal for details.
> Add cookie secure flag.

- CONTRIBUTING.md
As title implies, deprecates Slack in `CONTRIBUTING.md` for Discord and the forums.
> Deprecate Slack in CONTRIBUTING.md

- jobs/atc/templates/cf_ca_cert.erb
- jobs/atc/templates/github_ca_cert.erb
- jobs/atc/templates/oauth_ca_cert.erb
- jobs/atc/templates/oidc_ca_cert.erb
Spec was declaring certificates for authentication as `<auth_system>_auth.ca_cert` but all templates doesn't use prefix `_auth` to retrieve certificate.
In addition, `<auth_system>_auth.ca_cert` are typed as `certificate` so `<auth_system>_auth.ca_cert.certificate` in template seems to be necessary.
For the moment, it is impossible to set `ca_cert` on `cf_auth` for example. When setting `cf_auth.ca_cert`, atc can't start and give this kind of error:
```
server: Failed to open connector cf: failed to open connector: failed to create connector cf: no certs found in root CA file "/var/vcap/jobs/atc/config/cf_ca_cert
```
This PR rewrite key to find in template as `<auth_system>_auth.ca_cert.certificate`.
> Fix ca_cert templates

- jobs/atc/spec
I got an error when i created a password with a strength lower then 10 in the atc logs. This will make it clear that 10 or higher is required
> make it clear that you need 10 or bcrypt strength

- jobs/atc/spec
- jobs/atc/templates/atc_ctl.erb
Please let me know if there is Test that needs to be updated for this change.
Discord: @fsegui
Note: Concourse does 2 requests per credentials (1) pipeline level (2) team level. If my credential is at team level, concourse will cache it on the (2) request. Then it will still make request (1) every time to vault and not find the credential. After that, It will try (2) and find the cached credential. So --vault-cache will just halve the requests by eliminating (2) request.
> Added vault cache key to concourse bosh manifest

- jobs/atc/templates/atc_ctl.erb
The "--postgresql-client-cert" and "--postgresql-client-key" options should only depend on the `postgresql.client_cert` property, and not on the `postgresql.client_key` property, which was removed in 72fe707.
fixes #2397 
It's not really clear to me how I might add tests to cover use of atc postgres client certs, but since it's been broken for a while perhaps it'd be a good thing. If someone can provide me guidance on how to do so, I'm happy to do some work on it.
> fix postgres client cert handling in `atc_ctl.erb`

- atc/postgresrunner/postgresrunner.go
this makes it so the user running tests does not need write
access to /run/postgresql on distros that change it from the
postgresql default of /tmp
> force usage of /tmp for postgres socket file

- atc/postgresrunner/postgresrunner.go
- tsa/cmd/tsa/main_test.go
this resolves an issue where newer versions of openssh (7.8p1-1)
cause these tests to fail.
> don't shell to ssh-keygen to generate rsa keypairs

- skymarshal/skycmd/bitbucketcloud_flags.go
This adds Bitbucket flags to support the Bitbucket Dex connector in concourse/dex#3.
ref. concourse/concourse#2567
Note: To test this locally, I added the following to the end of my `go.mod`:
`replace github.com/concourse/dex => ./dex`
> Skymarshal: Add Bitbucket flags

- atc/db/open.go
We're in the middle of trying to track down a really weird issue whereby `atc` appears to hang on startup, but only when (a) we're on Xenial instead of Trusty, (b) we're in this environment, not our other one and (c) when Postgres SSL verification is enabled.
(The above is irrelevant to this PR, but I share the context in case anyone has some ideas to throw at us...)
Along the way I noticed that our `builds` table has 1.5 million entries, each with a `NULL` `engine_metadata` field.
No point fetching each of these rows upon server start when we skip over them a few lines later if a `NULL` value is found.
Now back to find a solution for our original issue...
> Don't fetch rows that we won't modify

- skymarshal/skycmd/bitbucketcloud_flags.go
The command-line flag descriptions for Bitbucket Cloud current reads:
`--main-team-bitbucket-cloud-team=ORG_NAME:TEAM_NAME`
but `ORG_NAME` shouldn't be there for Bitbucket Cloud.
> Fix Bitbucket Cloud command-line flag description for teams

- fly/commands/internal/setpipelinehelpers/atc_config.go
This fixes the colorization of the diff output on Windows. Note, it only solves the problem in a cmd shell. It would be desirable to support color in Powershell Core windows as well.
> Colorized diff output for Windows terminal.

- atc/api/jobs_test.go
- atc/api/jobserver/list_all.go
- atc/api/resources_test.go
- atc/api/resourceserver/list_all.go
Fix for [#2555]. 
Always creating an empty slice instead of zero-length slice.
> atc: Return empty array instead of null

- atc/metric/emitter/prometheus.go
concourse#2584 notes that it's difficult/impossible to use the Prometheus metric emitter's output to monitor specific jobs.
This PR goes some way towards addressing that by including a build's job name, alongside its team, pipeline and status, in the existing "builds_finished" counter.
This will increase the number of lines output by the Prometheus emitter by, at most, the `#jobs-in-each-pipeline`, replacing a single metric value with multiple values, labelled with job names.
For example, before this change, the Prometheus `/metrics` endpoint exposes the following:
```
concourse_builds_finished{pipeline="a-pipeline",status="failed",team="main"} 3
```
And after:
```
concourse_builds_finished{job="job-1",pipeline="a-pipeline",status="failed",team="main"} 1 …
```
> Teach Prometheus metric emitter to include job names in `builds_finished`

- atc/metric/emitter/prometheus.go
fix prometheus metric `concourse_resource_checks_total` has pipeline name in team label and team name in pipeline label. like `concourse_resource_checks_total{pipeline="main",team="firstpipeline"}`
> fix checks_total metric has wrong label values

- .github/CONTRIBUTING.md
- Dockerfile
- ci/dockerfiles/dev/Dockerfile
- hack/dlv/Dockerfile
- hack/trace
Hey,
from the commit message:
```
The commit introduces the script `./hack/trace` whose
goal is to make debugging a running `web` or `worker` instance
possible through the use of [dlv][1].
It updates `Dockerfile` and `ci/Dockerfile` in order to not make
use of the default optimizations so that `dlv` can leverage the
most of the running process.
The script is capable to attach to either a worker or a web instance
by sharing the PID namespace of those. It can also display the source
code of the lines that match a given trace/breakpoint by having the
source code mounted as a volume in the expected locations.
```
One great enablement of using something like `dlv` during development is the ability to not need to stop a process and add `print`s everywhere - attach a break/tracepoint and there …
> Adds ./hack/trace script

- fly/commands/fly.go
- fly/commands/resources.go
- fly/integration/resources_test.go
- go-concourse/concourse/concoursefakes/fake_team.go
- go-concourse/concourse/resource.go
- go-concourse/concourse/resource_test.go
- go-concourse/concourse/team.go
Implementation for this [issue](https://github.com/concourse/concourse/issues/869). 
Now sure how useful this will be since the `pause-resource` command is now removed? 
Shows resource name, paused/unpaused, and type of resource. Open to any suggestions on what else to show!
> fly: Add resources command to list all resources for given pipeline

- .github/style-guides/GO.md
- .github/styleguides/GO.md
A quick outline of a style guide for Concourse's Go Code
Here's the [rendered Markdown](https://github.com/concourse/concourse/blob/95155e59d07f66548cc819110ce5b832e08f2cda/.github/style-guides/GO.md)
Still TODO:
- Logging Suggestions
- Testing Strategy + Libraries Used
> Start a Concourse Go Style Guide

- atc/metric/emitter/prometheus.go
- atc/metric/metrics.go
This PR adds a missing metric that was added before (worker state).
In the case of `prometheus`, it gets named as `concourse_worker_info`,
where `state` is just a label that we can use to aggregate on while
still having per-worker information (which can be further increased
later).
concourse/concourse#2499
With the feature in:
```sh
curl --silent localhost:9391/metrics | ag concourse_workers_info
concourse_workers_info{info="running",worker="ffbbd436b4a5"} 1
```
This way we're able to perform:
*ps.: tests were previously added in https://github.com/concourse/concourse/commit/ff2e45ff73cdf6cf3a9c3158420b1a00dd47a7a6, the issue where the metric (under `metrics.go`) was created.*
cc @YoussB
> atc: Adds missing worker state metric to prometheus emitter

- Dockerfile
download and cache go mod dependencies first in a docker layer, then build
go mod dependencies won't be downloaded the next time you rebuild
> speed up dev builds

- atc/atccmd/command.go
- atc/creds/manager.go
- atc/creds/retryable_variables_factory.go
- atc/creds/retryable_variables_factory_test.go
- go.mod
- go.sum
- every manager has SecretRetry with retry params (attempts + interval)
- SecretRetry gets passed down to Get() into each cred manager
- Get() now performs a configured number of retries instead of a single
lookup and fail
- couple of unit tests added for retries (just for ssm, but they are
all the same)
> Added config params & retry logic for getting secrets. See #2542

- atc/metric/emit.go
- atc/metric/emitter/prometheus.go
- atc/metric/http.go
- atc/metric/http_test.go
- atc/metric/metrics.go
- atc/metric/periodic_test.go
- go.mod
Covering concourse/concourse#2745, this PR is about adding an extra tag to the fields of `HTTPResponseTime` so that we can also aggregate based on specific HTTP status codes of our interest.
> atc: Adds http response status code field to http response time metric

- atc/api/jobs_test.go
- atc/api/jobserver/list.go
Fix for this issue: [1112](https://github.com/concourse/concourse/issues/1112). 
**FYI**: Original issue references `pipeline.yml` to only have a resource declared. Seems like that isn't applicable anymore since the user will get an error `"resource 'resourceName' is not used"`. Reproduce this issue by having only a `resource_types` in the `pipeline.yml`.
> atc: return non-zero array instead of null for pipelines with no jobs

- README.md
This PR updates the repo's README to include a link to the Concourse GH Project board.
> README: include a link to the public GH Project board

- web/public/index.html
In reference to https://github.com/concourse/concourse/issues/2872#issuecomment-444931397 a quick fix of jQuery selector.
Having this will allow to use `.` in team names.
> Team name jQuery selector fix

- fly/commands/get_pipeline.go
- fly/integration/get_pipeline_test.go
Fix for [2400](https://github.com/concourse/concourse/issues/2400). 
Uses existing implementation from `PipelineConfig` which checks if pipeline is not found from the `GetConfig`.
> fly: add check to see if pipeline exists

- atc/worker/container_provider.go
- atc/worker/container_provider_test.go
re-check for creating and created containers in a loop if lock is not acquired
concourse/concourse#3043
Co-authored-by: Mark Huang <mhuang@pivotal.io>
> atc: fix mistake in previous refactor of FindOrCreateContainer

- ci/pipelines/concourse.yml
Hey,
This PR is intended to configure the worker rebalancing interval as introduced in the corresponding concourse-bosh-deployment PR: https://github.com/concourse/concourse-bosh-deployment/pull/135 .
This is my first time updating a bosh deployment; please let me know if I missed something :grin: 
Thanks!
--
*ps.: the pipeline has *not* been "set" yet under `ci`.*
> ci: Add worker-rebalancing to prod deployment

- atc/api/accessor/accessor.go
- atc/api/accessor/accessor_test.go
- fly/commands/teams.go
- fly/integration/teams_test.go
- skymarshal/token/issuer.go
- skymarshal/token/issuer_test.go
This reverts the role sorting.
It introduced a bug where any new handlers that weren't part of the accessor map would default to being granted access in the `accessor.HasPermission` method call. We want the default behaviour in this case to restrict access for unknown handlers.
We also added a new test to cover the case where the action doesn't exist in the role map.
> Revert role sorting

- .github/no-response.yml
- .github/stale.yml
Trying to have them not sound too stern but also not be too verbose. So the stale bot for example links to the wiki describing our stale issue process.
This, in combination with the new [How Issues are Managed](https://github.com/concourse/concourse/wiki/How-Issues-are-Managed) wiki fixes #3004.
> add config for stale and no-response bots

- web/elm/src/Dashboard.elm
- web/elm/src/Dashboard/Styles.elm
- web/elm/tests/DashboardTests.elm
Just think that ascii art not being selectable would be better... wdyt? 
vs.
> web: disable ascii art interaction

- ci/dockerfiles/rc/Dockerfile
- ci/pipelines/concourse.yml
- ci/tasks/rc-image.yml
Hey, 
This PR is intended to address the need for having an RC image being built in the pipeline (#3000) so that k8s-smoke, k8s-topgun, and hush-house can use that instead of `dev`.
To test it out, I used `fly execute` with the local changes, which seem to indicate that everything is working:
```sh
fly -t ci \
execute \
-c ./ci/tasks/rc-image.yml \
--input=concourse=./ \
--inputs-from=concourse/bin-smoke \
-p
```
ps.: when testing I included an extra `img login && img push cirocosta/concourse` so I could manually test the final artifact (the image) in k8s.
if I understood correctly, [`registry-image`](https://github.com/concourse/registry-image-resource) seems to not support dynamic tag versioning right now (see https://github.com/concourse/registry-image-resource/issues/7  for some …
> ci: bring back `concourse-rc` image to the pipeline [#3000]

- hack/dlv/Dockerfile
- hack/trace
this allows go modules to be debugged by including them in the container
here's an example of what that debugging the baggageclaim module looks like:
```
> github.com/concourse/baggageclaim/volume/driver.(*OverlayDriver).CreateVolume() /go/pkg/mod/github.com/concourse/baggageclaim@v1.3.3/volume/driver/overlay_linux.go:19 (PC: 0x1d53fe3)
14:
15:	func (driver *OverlayDriver) CreateVolume(path string) error {
16:		layerDir := driver.layerDir(path)
17:
18:		err := os.MkdirAll(layerDir, 0755)
=>  19:		if err != nil {
20:			return err
21:		}
22:
23:		err = os.Mkdir(path, 0755)
24:		if err != nil {
(dlv)
```
> hack: base delve image off concourse:local

- go.mod
- go.sum
effectively works around https://github.com/hashicorp/go-msgpack/pull/2 (they commented out the entire file upstream)
> bump hashicorp/go-msgpack to avoid bzr deps

- web/elm/src/Concourse/Cli.elm
- web/elm/src/Dashboard.elm
- web/elm/src/Dashboard/Footer.elm
- web/elm/src/Dashboard/Styles.elm
- web/elm/src/Pipeline.elm
- web/elm/tests/CliTests.elm
- web/elm/tests/DashboardTests.elm
> web: Mac cli link now goes to 'darwin' rather than 'osx'

- atc/api/accessor/accessor.go
- atc/api/accessor/accessor_test.go
- atc/api/cc_test.go
- atc/api/ccserver/get.go
- atc/api/ccserver/server.go
- atc/api/handler.go
- atc/routes.go
- atc/wrappa/api_auth_wrappa.go
- atc/wrappa/api_auth_wrappa_test.go
This PR tries to implement what's being asked for in #438.
Following the documentation in https://github.com/concourse/concourse/blob/master/.github/CONTRIBUTING.md#running-concourse one should yield the following.
Given the token from `~/.flyrc`:
```
$ curl 'http://localhost:8080/api/v1/teams/main/cc.xml' -H 'Authorization: Bearer YOUR_TOKEN'
```
```xml
<Projects>
<Project activity="Sleeping" lastBuildLabel="5" lastBuildStatus="Success" 
lastBuildTime="2018-11-05T20:02:57Z" name="example :: hello-world"
webUrl="http://localhost:8080/teams/main/pipelines/example/jobs/hello-world"></Project>
</Projects>
```
I've assumed that an aborted build shall be marked as failed. Apologies for mixed tabs and spaces, I've trusted GoLand to choose the right thing to do, it might have failed me horribly. …
> Support for cc.xml

- atc/db/migration/migrations/1548260637_cleanup_unused_objects.down.sql
- atc/db/migration/migrations/1548260637_cleanup_unused_objects.up.sql
Remove `best_if_used_by` column from `containers` table
Remove `volume_state_old` and `container_state_old` custom enum types
> atc/db: add cleanup migration removing unused types and column

- ci/pipelines/prs.yml
speeds up the build a bit as it avoids copying large artifacts
> ci: specify inputs for pr 'put' steps

- Dockerfile
otherwise this will blow up because the replacement directories aren't copied in
> skip mod cache warming if 'replace' rule detected

- ci/pipelines/concourse.yml
this makes more sense in the PR pipeline where we can compare to the upstream base
removing for now to unblock the pipeline since it's especially painful to unblock now that all changes to master come in through PRs
> ci: remove lint job

- ci/tasks/scripts/create-upgrade-downgrade-pipeline
- ci/tasks/scripts/downgrade-test
- ci/tasks/scripts/upgrade-test
- ci/tasks/scripts/verify-upgrade-downgrade-pipeline
- ci/tasks/scripts/watsjs
fixes #2149, improves the polling for worker to be available (important for worker version bumps), and also uh, makes them work again post-refactor (which was merged quicker to expedite `concourse/dev` fix)
this can be verified with:
```sh
env DOCKERFILE=ci/dockerfiles/dev-test/Dockerfile fly -t ci e -c ci/tasks/upgrade-test.yml -j concourse/watsjs -i concourse=$PWD -p
env DOCKERFILE=ci/dockerfiles/dev-test/Dockerfile fly -t ci e -c ci/tasks/downgrade-test.yml -j concourse/watsjs -i concourse=$PWD -p
```
> Fix upgrade/downgrade

- CONTRIBUTING.md
- package.json
- yarn.lock
I also investigated using [elm-coverage](https://www.npmjs.com/package/elm-coverage) but it seems to break on our use of native modules. Will revisit once we're at elm 0.19!
> web: add `yarn analyse` to do some static analysis

- ci/tasks/topgun.yml
- topgun/aws_ssm_test.go
- topgun/bbr_test.go
- topgun/credhub_test.go
- topgun/creds_test.go
- topgun/database_encryption_test.go
- topgun/exec.go
- topgun/fly.go
- topgun/k8s/kubernetes_creds_mgmt_test.go
- topgun/pipelines/credential-management.yml
- topgun/pipelines/secrets.yml
- topgun/suite_test.go
- topgun/tasks/credential-management-with-job-inputs.yml
- topgun/tasks/credential-management.yml
- topgun/vault_test.go
* centralize on one shared example (in creds_test.go)
* switch from smuggler to mock resource, make assertions and credential values clearer
* change AWS SSM suite to set up its own variables, rather than depending on things being set up beforehand
* note: this means it needs PutParameter access, though this should be fine since it's limited to a /concourse-topgun/* namespace anyway
> topgun: refactor and fix creds/encryption tests

- ci/pipelines/concourse.yml
- ci/tasks/check-distribution-env.yml
- ci/tasks/scripts/check-distribution-env/diff
rather than threading dev-image through bin-smoke (which doesn't need it), we'll run property checks against the built RC which comes out of it
> ci: run property checks against linux-rc

- atc/db/pipeline.go
- atc/db/team_test.go
This adds an `ORDER BY` to the resourceTypesQuery and resourcesQuery so that `fly get-pipeline` will return consistent, sorted configuration. This addresses #2814.
edit: I forgot to mention that I didn't order the other fields of the [config](https://github.com/concourse/concourse/blob/master/atc/api/configserver/get.go#L67-L70), because the pipeline groups are stored as a [single field](https://github.com/concourse/concourse/blob/master/atc/db/pipeline.go#L108) in the database, and the jobs query was already [sorted](https://github.com/concourse/concourse/blob/master/atc/db/pipeline.go#L523).
> Add ORDER BY for resourceTypesQuery and resourcesQuery

- Dockerfile
- ci/dockerfiles/dev/Dockerfile
this is causing build failures:
* https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/testflight/builds/486
* https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/watsjs/builds/482
> concourse/dev: don't preserve /src

- atc/worker/retryable_garden_connection.go
saw some pretty funky dumps on prod that showed huge call stacks of `.Wait` - this should fix it
this should return a non-retryable process, otherwise the `.Wait` calls will recurse each time the process is rehydrated
> atc: fix growing stack on process reattach

- hack/db
realized we're not familiar enough with `command` for it to be a useful choice, especially when almost everybody is on systems that have the more familiar `which` anyway. Plus we need to use a password now.
> fix hack/db script

- atc/syslog/drainer.go
fixes #3207 
`Build.Events()` spawns off a goroutine to do stuff with the db and needs to be closed.
> atc: fix syslog leaking goroutines

- atc/db/dbfakes/fake_resource_config_scope.go
- atc/db/resource_config_scope.go
- atc/db/resource_config_scope_test.go
- atc/radar/resource_scanner.go
- atc/radar/resource_scanner_test.go
- atc/radar/resource_type_scanner.go
- atc/radar/resource_type_scanner_test.go
Previously in Concourse, radar would give up trying to check a resource
if it was not able to acquire the lock (unless it was must complete).
This was changed so that if radar is unable to acquire the lock, it will
continue to attempt to acquire it every second. When it finally acquires
the lock, it will then check the last checked value for the resource
config scope and only run a check if the last checked is less than it's
interval.
This change was made because when Concourse is deployed with global
resources disabled, all resources that use the same resource config will
be checking on it's own interval but using only one check container
throughout the whole deployment. This change will allow all resources to
check for versions at every interval, instead of how it would be before
where …
> Continue acquiring resource scanning lock

- ci/pipelines/prs.yml
- ci/tasks/check-migration-order.yml
- ci/tasks/scripts/check-migration-order
Born out of a retro action item: 
If two PRs add migrations and one is merged before the other, there is a possibility that the PR with the newer migration version is merged first and the migration library doesn't run the older version when the second PR is merged. 
We determined that adding a CI task for PRs was the easiest way to detect this issue as early as possible. This task asserts that any new migrations have later versions than any migrations on master.
> ci: add task to ensure PRs add migrations in the right order

- web/elm/src/Build/Output.elm
- web/elm/src/Concourse/BuildEvents.elm
- web/elm/src/Native/EventSource.js
- web/elm/tests/BuildEventsTests.elm
Fixes #3235
I'd like to mention that the new regression test is pretty implementation-obsessed (indeed it exposes the `parseMsg` function which should otherwise be encapsulated). However, if we move forward with https://github.com/concourse/concourse/issues/3229 I believe we should be able to convert it to a more realistic 'integration-ey' test.
The new test only confirms that the underlying Elm code is resilient to receiving huge batches of events at once (and indeed does highlight the [exact source of the bug](https://github.com/concourse/concourse/commit/618c8113a9beb0102dd526f1facceb8b1684994b#diff-40f2536660c0f4a834dee118f978eb1eR133) where a function failed to be tail-recursive), but I've also made a change to the `EventSource` module to throttle the flow of events into Elm a bit …
> web: fix call stack crash

- ci/pipelines/prs.yml
- ci/tasks/scripts/check-migration-order
For context, this error sucks: https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/unit/builds/504#L5c5c72ab:1:4
I don't really know why we didn't see this problem when testing with `fly execute` before... Anyway it works when I test it with `fly execute` against prod now.
> ci: fix check-migration-order script

- web/assets/css/production.less
I don't know too much about css, but I believe this fixes issue #3164 where metadata could squish the build output when too long.
Notice that `message` is aligned in the middle. Not sure if that is the desired look or not.
> Fix issue #3164: Squishing of build-step output

- atc/db/build.go
- atc/db/resource.go
- atc/db/resource_config_scope.go
When we update the cache indexes for the all the pipelines that use a
resource config which we found new versions for, postgres can get into a
deadlock when two resource configs try to update the same pipeline's
cache indexes at the same time. By running all the cache index updates
by itself (not in a transaction), we will prevent that from happening.
> Prevent postgres deadlocking

- web/elm/src/Build.elm
- web/elm/src/Build/Models.elm
- web/elm/src/Dashboard.elm
- web/elm/src/FlySuccess.elm
- web/elm/src/Job.elm
- web/elm/src/Layout.elm
- web/elm/src/NewestTopBar.elm
- web/elm/src/Pipeline.elm
- web/elm/src/Resource.elm
- web/elm/src/Resource/Models.elm
- web/elm/src/Routes.elm
- web/elm/src/SubPage.elm
- web/elm/tests/BuildTests.elm
- web/elm/tests/DashboardTests.elm
- web/elm/tests/JobTests.elm
- web/elm/tests/NewestTopBarTests.elm
- web/elm/tests/PipelineTests.elm
- web/elm/tests/SubPageTests.elm
The route models now use our proper concourse identifiers. This also opens up the door to a nicer set of flags for page creation.
Refactor
> web: clean up routes

- atc/pipelines/radar_scheduler_factory.go
- atc/radar/resource_scanner.go
- atc/radar/resource_scanner_test.go
- atc/radar/resource_type_scanner.go
- atc/radar/resource_type_scanner_test.go
- atc/radar/scan_runner_factory.go
- atc/radar/scanner_factory.go
Instead of manually running a resource type scan within the resource
scanner when the resource uses a custom type with not versions, it will
wait on the resource type to receive a version from it's own resource
type scanning interval. This fixes the problem when many resources use
one resource type that has no versions yet, it will start off many scans
which all try to acquire the same lock. Resource type scanning also now
differs from the resource scanner because it does not loop if it fails
to acquire the lock, it will just exit with the error. We are able to do
this because even if global resources is disabled, resource type
versions are still shared within a concourse deployment so there is no
real need for them to pull in their own versions for each pipeline
resource.
[#3241]
> Resource type scanner does not loop on acquiring lock

- web/assets/css/build.less
- web/elm/src/BuildDuration.elm
This is a one line change for #3019  to make build events show date time in ISO8601 format.
I understand there might be more discussion on design side. But at least let's initiate something on the topic of date displaying.
> show date in build header instead of relative time

- ci/pipelines/concourse.yml
Temporarily bumping the production resources so we can get the extra
hotfix pipelines running smoothly.
Co-authored-by: Topher Bullock <cbullock@pivotal.io>
> ci: bump prod resources

- ci/pipelines/concourse.yml
it's causing a ruckus because of #3251
> temporarily disable fewest-build-containers

- atc/db/base_resource_type.go
- atc/db/worker_resource_type_test.go
- versions.go
If one worker registers with a unique base resource type, that base type gets persisted as unique permanatly.
> Permanent unique version history for base types

- CONTRIBUTING.md
Ran into some issues while running `atc/db` tests locally on a different machines and realized postgresql needed to be installed/updated. With the new `./hack/db` scripts, having postgresql (comes with psql) installed will create a more seamless experience when debugging.
> Update contributing guide to include postgresql as a dependency

- atc/worker/container_provider.go
Add log line to check if container locks are ever not acquired in containerProvider. We are using this as a metric to decide if we need to keep container locking since FindOrCreateContainer is always called within other held locks.
> atc/worker/: Add log to check if container lock is used

- ci/deployments/smoke/smoke.tf
verified this via 'fly execute' this time:
env \
GCP_PROJECT=cf-concourse-production \
GCP_KEY="((concourse_smoke_gcp_key))" \
SSH_KEY="((concourse_smoke_ssh_key))" \
DEPLOYMENT=smoke \
fly -t ci execute -c ci/tasks/terraform-smoke.yml \
-j concourse/bin-smoke -i concourse=.
> ci: fix bin-smoke provisioning

- atc/exec/garden_factory.go
- atc/template/template_resolver.go
- atc/template/template_resolver_test.go
- fly/commands/internal/templatehelpers/yaml_template.go
hey @vito
I've been testing task vars and was writing blog post on external tasks today. Found some oddness, which we need to fix. You actually mentioned this before, being unsure about the right order of passing params to the templating engine.
The current behavior is --- cred mgr first and then task vars. The problem with that approach is that it issues a lot of unnecessary lookups to cred mgrs, even though vars are specified (i.e. you specify a var and don't even expect Concourse to reach out to cred mgr, but it still goes there)
After thinking more about this, I think the behavior should be the opposite. If vars are specified, we should take a variable from there (it makes total sense. if it's specified explicitly, then take it! it overrides anything else). If it's not in vars, then …
> fix task variable lookup order

- web/elm/src/BuildDuration.elm
Signed-off-by: Twiknight <Twiknight@outlook.com>
Improve the timestamp display on build history according to https://github.com/concourse/concourse/issues/3321#issuecomment-464639912
Now if a time (any of started/finished) is
1. more than 24hrs ago -> show verbose date ( `"%b %d %Y %I:%M:%S %p"`), and use relative date (`sometime ago`) as tooltip
2. less than 24hrs ago -> show relative date and use verbose date as tooltip.
following is an example
> use github notion on build history start/finish timestamp

- ci/tasks/scripts/with-docker-compose
leaving the cluster running makes it easier to debug failing builds
> ci: stop docker only in the happy path

- ci/tasks/scripts/smoke
In a previous commit, `ATC_URL` was set to just use the IP, which is a
problem for the test as it expects the full address, including the
scheme and the port.
tl;dr: https://github.com/concourse/concourse/pull/3380 had a "whoops"
> ci: fix `ATC_URL` in smoke test

- ci/tasks/scripts/check-migration-order
I'm guessing this failed before when no migrations were added because it would effectively do `echo "" >> $expected_pr_migrations`, adding an erroneous trailing linebreak.
But if migrations are actually added, that linebreak had to be there. So instead just conditionally append `$new_on_pr` with a trailing linebreak.
> ci: fix check-migration-order again

- atc/db/migration/migrations/1551110547_add_indexes_for_versions_db.down.sql
- atc/db/migration/migrations/1551110547_add_indexes_for_versions_db.up.sql
these indexes greatly improve the time taken to load a pipeline's versions db
> atc: add indexes for build input/output joins

- ci/pipelines/concourse.yml
Previously the `try` step didn't have the right indentation, making
`concourse` think that the step was just a `task`, not a `try` of a
`task.`
We also missed leaving the `input_mapping` for `image-info` when
removing the mapping for `endpoint-info`.
Signed-off-by: Bishoy Youssef <byoussef@pivotal.io>
Co-authored-by: Ciro S. Costa <cscosta@pivotal.io>
> ci: fix `try` step and input_mapping in k8s-smoke

- ci/pipelines/concourse.yml
- ci/tasks/prep-release-assets.yml
- ci/tasks/scripts/extract-fly-assets
- ci/tasks/scripts/prep-release-assets
this way release assets don't have -rc.XXX in their filenames
fwiw: manually verified this task to expedite merging
> ci: rename rc files to final versions

- ci/tasks/scripts/k8s-deploy
- ci/tasks/scripts/k8s-smoke
Previously we were using `service` for port-forwarding the deployed
`web` instances to the network namespace used by the `k8s-smoke` task.
As services allow the routing to occur only after the underlying pods
get ready, this means that we need to wait for the readinessProbe to
return positive values.
By switching that to `deployment`, we'd be shortcutting that and going
straight to the `web` pods from the deployment, avoiding those failures
like https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-smoke/builds/980#L5c79f272:70:98
> ci: update k8s-smoke to use deployment instead of svc in port-forwarding

- CONTRIBUTING.md
- package.json
- web/elm/src/Build/Models.elm
- web/elm/src/Build/Msgs.elm
- web/elm/src/Dashboard/Group.elm
- web/elm/src/Dashboard/Msgs.elm
- web/elm/src/Job/Msgs.elm
- web/elm/src/NotFound.elm
- web/elm/src/Pipeline/Msgs.elm
- web/elm/src/Resource/Msgs.elm
- web/elm/tests/DashboardTests.elm
- web/elm/tests/SubPageTests.elm
Also ran it across the codebase and it wound up organizing some imports.
> web: add 'yarn format' to format Elm code

- atc/db/migration/migrations/1537546150_global_resource_version_history.down.go
- ci/pipelines/concourse.yml
`downgrade` job should run the correct task.
Also fixed an index issue with global resources down migration.
> ci: fix downgrade job

- cmd/concourse/worker_linux.go
- topgun/k8s/baggageclaim_drivers_test.go
- topgun/k8s/ephemeral_worker_test.go
- topgun/k8s/garden_config_test.go
- topgun/k8s/k8s_suite_test.go
- topgun/k8s/kubernetes_creds_mgmt_test.go
- topgun/k8s/prometheus_test.go
- topgun/k8s/rebalance_test.go
This ensures that our 5.x branch can have garden properties passed not only through environment variables as usual, but also ConfigMaps, which can be referenced through `CONCOURSE_GARDEN_CONFIG`.
fixes #3237
fixes #3405
> topgun/k8s: ensure garden configuration can be properly set for the worker pods

- CONTRIBUTING.md
Improved instructions, so people have easier time rebuilding Concourse from source. We ran into this just recently (i.e. the need to pull `concourse/dev`).
> need to pull concourse/dev sometimes

- atc/creds/vault/reauther.go
turns out there's a default max elapsed time of 15 minutes. this
resulted in `NextBackOff` returning `backoff.Stop`, i.e. 0, leading to a
tight loop of auth attempts after 15 minutes.
> vault: configure a max elapsed time of 0

- ci/pipelines/concourse.yml
- added an ops file to `concourse/prod` that adds procstat to web and
worker.
- this commits adds the use of the ops file.
depends on: concourse/prod#6
> ci: Add ops file to prod

- fly/commands/internal/setpipelinehelpers/atc_config.go
- fly/commands/internal/setpipelinehelpers/atc_config_test.go
- fly/commands/set_pipeline.go
- fly/integration/set_pipeline_test.go
This makes it easier to unpause newly-set pipelines.
> Fly prints the unpause-pipeline command after creating a pipeline

- atc/db/pipeline.go
Use a NOT IN instead of negative join for inputs/outputs
#3487 and #3426, oh jeez and #3459
This doesn't fully fix the problem, but it seems to be an improvement.
> Incremental performance gain for LoadVersionsDB

- ci/tasks/scripts/smoke
- ci/tasks/scripts/wait-worker
- As noticed in many smoke tests (K8s-smoke), the failure is usually due
to the `no workers`.
- Added a `wait-worker` script similar to `wait-atc` that makes sure a
worker is registered before running the test.
- Also, increased the default Max retries to 2 minutes before giving up.
---
Update from @cirocosta: fixes #3501
> smoke: Wait until worker(s) register

- fly/rc/targets.go
- fly/rc/targets_test.go
Fixes #2822
Previously, the `fly` command line tool would create its `.flyrc` file using default permissions `rwxrwxrwx` (0777), or fewer subject to the active `umask`, with 0755 being typical.  This is undesirable since the file is not actually executable, and also contains authentication information that should not be exposed to other users. Now, we will default to `rw-------` (0600). Due to the way that the underlying `open` syscall works, existing `.flyrc` files will retain their existing permissions: this only applies to newly created ones.
Signed-off-by: Alexander Gurney <alexander_gurney@cable.comcast.com>
> Create .flyrc with 0600 permissions instead of 0777

- atc/metric/emitter/prometheus.go
> atc: avoid nil dereference in prometheus metric

- atc/db/resource_config_scope_test.go
this was too sensitive to timing boundaries and would fail on a slower/overloaded system
> fix flaky atc test

- fly/commands/set_team.go
- fly/commands/teams.go
- fly/integration/set_team_test.go
- fly/integration/teams_test.go
new output looks like this:
```
~/w/concourse (fly-team-ux-tweaks) $ fly -t ci set-team -n resources --github-team concourse:pivotal
setting team: resources
role owner:
users:
none
groups:
- github:concourse:pivotal
apply team configuration? [yN]: 
```
> fly: ux tweaks for team commands

- web/elm/src/Build/StepTree/StepTree.elm
- web/elm/tests/BuildTests.elm
A partial implementation for #429
It makes all strings that looks like a url in area `build -> resource -> metadata` clickable. 
This is very useful when your resource returns information from an external website, for example GitHub or GitLab like below case:
- It only handles url-like strings (String starts with "http://" or "https://"), since in elm 0.19 we'll have official url lib, it would be duplication to implement https://tools.ietf.org/html/rfc3986 here 
- It only works in build page with the resource metadata. The reason is, to make all url-like stuff clickable would be larger change that impacts several files and ten more functions. I chose to start with build metadata, where in most cases, you would want a clickable link. When we decide this is a proper way or find a better …
> make values starts with https or http clickable in build metadata

- atc/api/ccserver/get.go
- atc/api/present/resource_version.go
- atc/api/resourceserver/versionserver/list.go
- atc/api/versions_test.go
- atc/build_inputs_outputs.go
- atc/config.go
- atc/db/dbfakes/fake_resource.go
- atc/db/resource.go
- atc/db/resource_test.go
- atc/metric/error_sink_collector_test.go
- atc/syslog/syslog.go
- atc/syslog/syslog_suite_test.go
- atc/syslog/syslog_test.go
- fly/integration/resource_versions_test.go
- fly/integration/resources_test.go
* Added `Public` to resource config. Resource metadata is no longer returned in resource versions endpoint when `Public` is set to false or not set and the user is not authenticated.
#1971
> Hide resource metadata for exposed pipeline

- fly/commands/execute.go
- fly/integration/execute_test.go
Despite it is a normal build or pipeline scoped build, `fly execute` will always output `../builds/:build_id` as build URL 
fixes concourse/concourse#3262
> Use one-off build url for pipeline scoped build created by fly exec

- fly/commands/prune_worker.go
I couldn't find any existing test checking the functionality of the existing prune-worker command and thus making a bit hard to add a test for this additional command.
I'm willing to try to add some test if given some general direction.
> Add option to prune all stalled workers instead of just one at the time.

- topgun/atc_shutdown_test.go
- topgun/fly.go
- topgun/operations/slow-tracking.yml
it's not super clear why that was necessary, and now the test fails
because fly executed builds aren't immediately run by the node that the
execute ran against. in any case, this should be testable by just
restarting the `web` nodes.
> topgun: don't depend on slow build tracker

- fly/commands/hijack.go
- fly/integration/hijack_test.go
- go-concourse/concourse/concoursefakes/fake_team.go
- go-concourse/concourse/containers.go
- go-concourse/concourse/containers_test.go
- go-concourse/concourse/team.go
Fix for this [issue](https://github.com/concourse/concourse/issues/1081).
Couldn't think of a short hand for handle since `-h` is reserved for `help` and `i` is aliased to `intercept`. Open to suggestions for this!
> Add --handle option to hijack(intercept)

- atc/creds/vault/manager.go
- atc/creds/vault/manager_test.go
- atc/creds/vault/vault.go
- atc/creds/vault/vault_factory.go
- atc/creds/vault/vault_suite_test.go
- atc/creds/vault/vault_test.go
We have a lot of shared secrets, that we have to copy into each team folder. Also sometimes we create vault secrets during provisioning, where we are not aware of the available teams in Concourse. 
This PR adds an optional `shared-path` to the vault credential lookup. Existing behaviour of the credential lookup rules stays the same, except that if the path is configured, and credentials are neither found in `/concourse/TEAM_NAME/PIPELINE_NAME/foo_param` or `/concourse/TEAM_NAME/foo_param` it will check the shared path `/concourse/SHARED_PATH/foo_param`.
Resolves: https://github.com/concourse/concourse/issues/2442
> added shared path for vault credential lookup

- atc/db/migration/migrations/1551384519_rename_build_engine_metadata.down.sql
- atc/db/migration/migrations/1551384519_rename_build_engine_metadata.up.sql
- atc/db/migration/migrations/1552943209_drop_tracked_by_from_builds.down.sql
- atc/db/migration/migrations/1552943209_drop_tracked_by_from_builds.up.sql
we also change one existing migration `rename_build_engine_metadata.down`(in master by the merge of #3307 ) that updates `builds` table to drop materialized views.
Since that migration is not deployed in Prod so should be safe to change it.
> Drop tracked_by from builds table

- CONTRIBUTING.md
- hack/dlv/Dockerfile
Hey,
I noticed that we don't provide guides around how one can fork a dependency like `baggageclaim` and have that forked version being used in a `docker-compose build` scenario, so this PR tries to address that.
It also fixes the `./hack/trace` script that was missing some updates in the Dockerfile, as noticed by @kcmannem and @topherbullock  the other day 😁  
Thanks!
> Update contributing guide - fix trace, add note about dependency forks

- ci/tasks/topgun.yml
- topgun/suite_test.go
this way release pipelines can run topgun without trampling on other pipelines
> topgun: make deployment name prefix configurable

- ci/dockerfiles/golang-builder/Dockerfile
- ci/pipelines/concourse.yml
- ci/tasks/build-golang-builder-image.yml
As part of switching to `ubuntu:bionic` for the resources, we need an intermediate image to build `go` files (we were using `golang:alpine` before).
This adds a new job to build and push the `golang-builder` image to docker-hub under `concourse/golang-builder`
Go version is configured in `ci/dockerfiles/golang-builder/Dockerfile`
> Bionic golang builder image

- ci/dockerfiles/dev/Dockerfile
- ci/pipelines/resources/template.jsonnet
Part of concourse/concourse#3266
Requires all resource repos to have a `dockerfiles/alpine/Dockerfile` and `dockerfiles/ubuntu/Dockerfile`
This will modify the resource pipelines to build both the `alpine` and `ubuntu` image when releasing to GitHub.
- the image with the `latest` tag on docker hub will remain alpine
- PR images will also remain alpine
- the GitHub release now has an extra tar, `resource-1.0.0-ubuntu.tgz` (the existing one will be renamed `resource-1.0.0-alpine.tgz`)
- builds will also be triggered on new releases of `ubuntu:bionic` docker image (similar to how it's currently triggered on new releases of `alpine:edge`
> build both alpine and ubuntu resources

- ci/deployments/bosh-smoke.yml
- ci/deployments/smoke/smoke.tf
- ci/overrides/docker-compose.latest.yml
- ci/overrides/docker-compose.no-build.yml
- ci/pipelines/concourse.yml
- ci/pipelines/release.yml
- ci/tasks/docker-semver-tags.yml
- ci/tasks/k8s-topgun.yml
- ci/tasks/scripts/docker-semver-tags
- ci/tasks/scripts/downgrade-test
- ci/tasks/scripts/generate-keys
- ci/tasks/scripts/k8s-topgun
- ci/tasks/scripts/upgrade-test
- ci/tasks/scripts/with-docker-compose
These are all the changes that were necessary for 5.0.1. There's also a release template pipeline, which should be re-usable for future minor releases.
Each commit has a little more context in its description. :+1:
> ci: release pipeline changes

- ci/tasks/yarn-build.yml
- ci/tasks/yarn-test.yml
hopefully this will remove the flakiness, and the builds seem to be super fast anyway.
> ci: remove task caches on elm builds

- atc/api/present/resource.go
- atc/api/resources_test.go
- atc/db/dbfakes/fake_build.go
- atc/db/dbfakes/fake_resource.go
- atc/db/dbfakes/fake_resource_config_scope.go
- atc/db/migration/migrations/1554128419_rename_resource_config_scope_last_checked.down.sql
- atc/db/migration/migrations/1554128419_rename_resource_config_scope_last_checked.up.sql
- atc/db/migration/migrations/1554133547_drop_cache_invalidator.down.sql
- atc/db/migration/migrations/1554133547_drop_cache_invalidator.up.sql
- atc/db/resource.go
- atc/db/resource_config_scope.go
- atc/db/resource_config_scope_test.go
- atc/radar/resource_scanner.go
- atc/radar/resource_scanner_test.go
- atc/radar/resource_type_scanner.go
- atc/radar/resource_type_scanner_test.go
- atc/scheduler/buildstarter.go
- atc/scheduler/buildstarter_test.go
- `last_checked` -> `last_check_start_time`
- `last_check_finished` -> `last_check_end_time`
- API returns `last_check_end_time`
- also drops `cache_invalidator` table since it's not used
fixes #3587
> Rename last_checked and last_check_finished

- web/elm/src/Build/StepTree/StepTree.elm
- web/elm/tests/BuildTests.elm
Signed-off-by: Twiknight <Twiknight@outlook.com>
This is a follow up of my previous patch on URLs:  https://github.com/concourse/concourse/pull/3398
Since we are now elm:0.19, naive `startsWith` should be replaced a real url parser.
After the change, URL-like non-URLs will not be displayed as hyperlink.
> use elm/url to determine url when display URL metadata

- ci/pipelines/concourse.yml
- ci/pipelines/release.yml
Currently, the K8s section of the pipeline is blocked on `check-params` failing.
While, this is a useful signal that needs to be addressed prior to shipping, it shouldn't block running smoke & topgun tests, as those could be worked on independently of params changes.
Hence, the PR switches the ordering of the jobs from;
`k8s-check-helm-params` => `k8s-smoke` => `k8s-topgun`
to 
`k8s-smoke` => `k8s-topgun` => `k8s-check-helm-params`
> Update ci pipeline k8s - Run smoke and topgun in parallel with the k8s-check-helm-params task

- ci/pipelines/prs.yml
These tests sometimes fail due to network flakiness when
the package manager fails to download certain packages.
Adding attempts here will save us time from manually
kicking off the jobs again for specific PR's.
> ci: add attempts to yarn steps in pr's pipeline

- atc/event/deprecated_events.go
- atc/event/events.go
- atc/event/parser.go
these versions are pretty misleading; they're compared via equality and
not actual semver.
follow-up to https://github.com/concourse/concourse/pull/3579 to fix upgrade/downgrade tests
> support parsing old finish-get/finish-put events

- ci/deployments/smoke/garden/garden.ini
- ci/deployments/smoke/smoke.tf
- ci/deployments/smoke/systemd/smoke-worker.conf
- web/wats/fixtures/smoke-internet-pipeline.yml
- web/wats/test/smoke.js
This fixes `--garden-config`/`$CONCOURSE_GARDEN_CONFIG` - previously it would fail because `gdn` accepts `-config`, not `--config`.
Added test coverage to `bin-smoke` that covers usage of this flag and tests network connectivity.
> cmd/smoke: fix garden -config flag, add coverage in bin-smoke

- atc/event.go
- atc/event/deprecated_events.go
- atc/event/parser.go
- atc/event/parser_test.go
- atc/event/suite_test.go
- ci/tasks/scripts/verify-upgrade-downgrade-pipeline
- fly/eventstream/render.go
This should make it easier to make backwards-compatible changes to build events in the future. Added some basic tests for event parsing which cover the version compatibility semantics, and commented out a part of the upgrade/downgrade tests that can't be expected to pass until we ship 5.1 (because the tests rely on using the old `fly` which won't have this fix).
> semver event parsing, patch downgrade job for now

- web/elm/src/Views/Styles.elm
fixes #3685 
Set height of content div to "100%" only when needed.
> do not display a scrollbar on build page when not needed

- topgun/k8s/baggageclaim_drivers_test.go
- topgun/k8s/container_limits_test.go
- topgun/k8s/ephemeral_worker_test.go
- topgun/k8s/external_postgres_test.go
- topgun/k8s/external_worker_test.go
- topgun/k8s/garden_config_test.go
- topgun/k8s/https_web_tls_termination_test.go
- topgun/k8s/k8s_suite_test.go
- topgun/k8s/kubernetes_creds_mgmt_test.go
- topgun/k8s/mainteam_role_test.go
- topgun/k8s/prometheus_test.go
- topgun/k8s/rebalance_test.go
Hey,
This PR:
- moves the cleanup code to a separate function, and
- updates the random number generator to generate smaller numbers as this was affecting the creation of internal k8s resources with names larger than 63 characters long.
fixes: #3710
cc @YoussB
> topgun/k8s: refactors and fix rand number generator

- atc/atccmd/command.go
- atc/integration/configuration_test.go
> atc: make x-frame-options secure by default

- ci/pipelines/concourse.yml
- ci/tasks/bump-concourse-blobs.yml
- ci/tasks/scripts/bump-concourse-blobs
- ci/tasks/scripts/ubuntu-replace-resource-types
- ci/tasks/ubuntu-image-replace.yml
We added a step in the job `bosh-bump` to replace `alpine` rootfs with `ubuntu` rootfs in the concourse linux-rc.
Link to a private note with more details is here: https://github.com/orgs/concourse/projects/33#card-19512105
> Ubuntu bosh release

- atc/api/configserver/save.go
- atc/config.go
- atc/decode_hook.go
- atc/engine/build_step.go
- atc/engine/exec_engine.go
- atc/engine/exec_engine_hooks_test.go
- atc/engine/exec_engine_test.go
- atc/exec/in_parallel.go
- atc/exec/in_parallel_test.go
- atc/exec/parallel.go
- atc/exec/parallel_test.go
- atc/job_config.go
- atc/job_config_test.go
- atc/plan.go
- atc/plan_factory.go
- atc/public_plan.go
- atc/public_plan_test.go
- atc/scheduler/factory/build_factory.go
- atc/scheduler/factory/factory_parallel_test.go
- atc/scheduler/factory/factory_put_test.go
- atc/testhelpers/match_plan_matcher.go
- atc/validate.go
- atc/validate_test.go
- examples/hello-world-every-minute.yml
- web/assets/css/modules.less
- web/elm/src/Build/StepTree/Models.elm
- web/elm/src/Build/StepTree/StepTree.elm
- web/elm/src/Concourse.elm
- web/elm/tests/StepTreeTests.elm
Closes #2628 by adding support for the following:
```yaml
jobs:
- name: example
plan:
- get: every-minute
trigger: true
- in_parallel:
limit: 1
fail_fast: true
steps:
- task: echo
config:
...
- task: echo
config:
...
```
InParallel ensures that `limit` steps are running at any one time and until all steps are complete. If `limit` is not specified, the default behavior is identical to an `aggregate` step and runs everything at once. Setting `limit` to 1 makes it behave like `do`. When cancelling a job, `in_parallel` will not schedule (`Run()`) the pending tasks and instead return the `ctx.Err()` as soon as possible. When setting `fail_fast`, `in_parallel` will abort all currently running tasks and refrain from scheduling pending tasks.
PS: Sorry for the big PR, but `parallel` is …
> Add in_parallel step

- tsa/client.go
- tsa/constants.go
- tsa/tsacmd/command.go
- go by default allows for some weak algorithms https://github.com/golang/crypto/blob/d864b10871cd4370fe574816b489c819c675ccc7/ssh/common.go#L69
- fixes https://github.com/concourse/concourse-bosh-release/issues/25
> Restrict SSH MAC algos to a smaller set

- cmd/concourse/worker_linux.go
- cmd/concourse/worker_nonlinux.go
set this flag to `required` false when running `concourse quickstart`
Signed-off-by: Rui Yang <ryang@pivotal.io>
> fix quickstart to ignore --worker-tsa-worker-private-key flag

- ci/pipelines/resources/template.jsonnet
- added a job to the template that creates and uploads a text file with
`dpkg -l` for use in OSLO pipelines
cc @xtreme-sameer-vohra
> ci/pipelines: Resource pipelines' template

- fly/commands/builds.go
> change flag of fly builds --team from t to n because t is already used

- ci/pipelines/concourse.yml
There are two issues in this PR. Each commit represents one issue. Let me know if this should be split into two PR's.
https://github.com/pivotal-cf/concourse-support/issues/69
This is setting `volume_sweeper_max_in_flight` to 1. The default is 5 and the runtime team thinks this is currently the root cause of the issues we're seeing with prod. We have some logs that appear to support this theory.
https://github.com/pivotal-cf/concourse-support/issues/70
We're moving secrets shared between the release pipelines into a shared path in vault. This commit is telling concourse where the shared path is. 
Secrets that aren't shared between release pipelines will remain in their pipeline specific paths.
> Update prod deployment

- atc/atccmd/command.go
- atc/config.go
- tsa/client.go
- tsa/constants.go
- tsa/tsacmd/command.go
- move tls & ssh config to a common file
- TLS: restrict cipher suites to a smaller set ( removed CBC )
- TLS: changed priority of tls curves
- SSH: restrict KeyExchange algos to a smaller set ( removed SHA1
variants )
> Update tls & ssh config

- topgun/k8s/external_worker_test.go
- topgun/k8s/https_web_tls_termination_test.go
- topgun/k8s/k8s_suite_test.go
- In order to test the worker only and web-only deployments, we updated
the external worker test to use separate deployments so we can be able
to make sure that the worker connects successfully to the ATC.
cc @taylorsilva
> topgun/k8s: external worker test to use separate deployments

- topgun/k8s/worker_lifecycle_test.go
- clean up even when test fails
- added 2 sleeps to reduce the flakiness as temporary solution
fixes #3749
Co-authored-by: Bin Ju <bju@pivotal.io>
> topgun/k8s: clean up for worker_lifecycle and reduce case flakiness.

- package.json
- web/elm/elm.json
- web/elm/src/Concourse.elm
- web/elm/src/Concourse/BuildEvents.elm
- web/elm/src/Network/Build.elm
- web/elm/src/Network/Pagination.elm
- web/elm/src/Network/Resource.elm
- web/elm/src/Routes.elm
- web/elm/tests/PaginationTests.elm
* use parser instead of regex
* use url builders instead of building strings by hand
Also, fixes #3622
> web: remove dependence on elm/regex

- fly/commands/prune_worker.go
Executing `fly prune-worker --all-stalled` should not return an error if no stalled workers are present to be more friendly toward automated systems.
Prints instead a warning and exits gracefully.
**More context**: when I've proposed #3248 I didn't realize that, if there are no stalled workers, fly exits with a return code of 1. This makes it unfriendly toward an automated system (eg a Concourse job) that only cares that no stalled workers are present.
> Fly command: warns if no stalled workers are present.

- ci/pipelines/concourse.yml
- ci/pipelines/release.yml
- ci/tasks/scripts/topgun
- ci/tasks/topgun.yml
- topgun/bbr_test.go
- topgun/operations/bbr.yml
After investigating using bbr in #2332, the use case we are confident in supporting for db restore is a clean deployment with the same version of concourse release and postgres release. We updated the tests to reflect this:
- Unpinned Postgres version for bbr
- Added test case for data consistence while the restore is failed.
- Refined the backup and restore process, delete the concourse deployment before restore
> Improve bbr topgun tests

- atc/creds/kubernetes/kubernetes.go
- atc/creds/kubernetes/kubernetes_factory.go
- atc/creds/kubernetes/kubernetes_suite_test.go
- atc/creds/kubernetes/kubernetes_test.go
Fixes #3821
Kubernetes secret manager was one of the two places I was worried about, because it didn't have any unit tests. I was moving methods between SecretsFactory and Secrets, and the right code ended up in a place where it was not being used :(
I moved it to the right place and added a basic unit test, which tests var -> secret name conversion.
> Fix regression in k8s credential manager

- topgun/fly.go
- topgun/k8s/k8s_suite_test.go
- topgun/k8s/worker_lifecycle_test.go
Hey,
By ensuring that we're able to rely less and less on time, this commit
addresses the concerns in https://github.com/concourse/concourse/issues/3795.
The idea here is to control the timing by explicitly writing to the file that the pipeline waits forever one.
Thus, the two cases come down to:
```
gracefully:
set pipeline
trigger job async
wait for a task container to appear 
(instead of waiting for `started`)
start scale down to 0 replicas 
(instead of killing the pod)
see that the worker is retiring
allow the task to finish
(by writing to a file, instead of waiting for some time)
see that build succeeded
see that there are no more workers
ungracefully:
set pipeline
trigger job async
wait for a task container to appear 
(instead of waiting for `started`)
start scale down to 0 replicas …
```
> topgun/k8s: remove flakiness from worker-lifecycle test

- topgun/k8s/kubernetes_creds_mgmt_test.go
With the introduction of cache secret lookups (see [1]), we updated the
helm chart to account for the fact that those can be configured (see
[2]).
This commit adds a test that validates that the caching occurs by
triggering the pipeline two times:
1. having the secret there in the namespace, and another
2. not having the secret in the namespace - just in-memory (cached).
[1]: https://github.com/concourse/concourse/pull/3628
[2]: https://github.com/helm/charts/pull/13295/commits/d9eef448812f0efcb3e8f6e7f52c7d83216c3075
> k8s/topgun: test k8s credential management caching

- web/elm/src/Dashboard/Pipeline.elm
- web/elm/src/Pipeline/Pipeline.elm
- web/elm/src/Views/PauseToggle.elm
- web/elm/src/Views/Styles.elm
- web/elm/tests/DashboardTests.elm
- web/elm/tests/PauseToggleTests.elm
- web/elm/tests/TopBarTests.elm
on dashboard pipeline cards:
on pipeline page:
fixes #2428
> web: tooltips on pause toggles

- atc/api/accessor/accessor.go
- atc/api/accessor/accessor_test.go
- atc/auditor/auditor.go
- atc/routes.go
Removed extra references to PauseResource and UnpauseResource since they have no routes any more.
> atc: clean up PauseResource and UnpauseResource actions

- atc/api/accessor/accessor.go
- atc/api/accessor/accessor_test.go
- atc/api/handler.go
- atc/api/teams_test.go
- atc/api/teamserver/get.go
- atc/routes.go
- atc/wrappa/api_auth_wrappa.go
- atc/wrappa/api_auth_wrappa_test.go
- fly/commands/fly.go
- fly/commands/get_pipeline.go
- fly/commands/get_team.go
- fly/integration/get_team_test.go
- go-concourse/concourse/concoursefakes/fake_team.go
- go-concourse/concourse/team.go
- go-concourse/concourse/teams.go
- go-concourse/concourse/teams_test.go
fix #3785 
I enabled to print **one** team config.
The team config is as follows.
```yaml                     
id: 2
name: mechanic
auth:
owner:
groups: []
users:
- local:mechanic
```
Admin users and users who belong to a team can view the team config.
And the viewer or higher authority can view it.
Before, the way to get one team config was below.
(concourseTeam is mechanic)
```
$ fly -t <target> teams -d --json | jq '.[] | if .name == "mechanic" then . else empty end'
{
"id": 2,
"name": "mechanic",
"auth": {
"owner": {
"groups": [],
"users": [
"local:mechanic"
]
}
}
}
```
After these changes, the way is below.
```                                           
$ fly -t <target> get-team -n mechanic 
name/role         users                    groups
mechanic /member  local:mechanic   none …
```
> Enable to print specified team config (fly get-team)

- CONTRIBUTING.md
Hey,
This is a missing piece of documentation that we (those maintaining
topgun/k8s) neglected. As it's a bit more accessible than the
bosh-specific topgun tests, I guess this might matter for contributors
wanting to ensure that k8s-related code works fine (maybe we could even
have people contributing to the coverage as well?)
Please let me know if the phrasing here makes sense.
Thanks!
> CONTRIBUTING: update guide to include instructions regarding topgun/k8s

- atc/engine/builder/delegate_factory.go
- atc/exec/get_step.go
- atc/exec/put_step.go
- atc/exec/task_step.go
This PR introduces a new logger session for get, put and task steps. It also attaches additional data to the logs to allow the identification of the step that produced a particular log line.
An example output of `docker-compose logs -f | grep get-step-run` while running the `testflight` test suite:
```
web_1     | {"timestamp":"2019-04-25T08:22:11.785874433Z","level":"info","source":"atc","message":"atc.pipelines.scheduler.tick.scheduling.try-start-next-pending-build.get-step-run.initializing","data":{"build-id":436,"build-name":"1","job-id":598,"pipeline":"tf-pipeline-1-320e3b2f-dc15-4d28-794e-0d0e7d709987","session":"17.172.4.3.4.6","step-name":"some-resource","team":"testflight"}}
web_1     | {"timestamp":"2019-04-25T08:22:11.806112779Z","level":"info","source":"atc","message":"atc.pipe …
```
> Improve observability of logs during step run

- atc/validate.go
- atc/validate_test.go
> atc: invalidate pipelines with duplicate groups

- cmd/concourse/concourse_suite_test.go
- cmd/concourse/concourse_test.go
- cmd/concourse/web.go
Fixes #3847 to see if `--session-signing-key` is specified.
I set up a test to check for this specific case, as well as a check for a minimal set of valid parameters.  Any suggestions on these tests?  I wasn't sure how best to approach it.  The `generateSSHKeypair` was copied from [here](https://github.com/concourse/concourse/blob/master/tsa/cmd/tsa/suite_test.go#L197) - not sure if there's a shared test package that I can move it to?
> Check if session-signing-key is nil

- cmd/concourse/quickstart.go
- cmd/concourse/worker_linux.go
- cmd/concourse/worker_nonlinux.go
this flag should be required for the worker commands, and only optional
in 'quickstart'
> cmd/concourse: fix worker private key flag

- atc/db/team.go
- atc/db/team_test.go
- atc/job_config.go
- testflight/fixtures/rename-simple.yml
- testflight/rename_job_test.go
Added functionality to update name of a job without losing history in response to issue [#1128](https://github.com/concourse/concourse/issues/1128). 
Also removing non active jobs to prevent wrong job history associated to a job. 
How it works:
Add `old_name` to config file where `old_name` is the current job name and update `name` field to new name.
> Retain job history

- atc/engine/builder/delegate_factory.go
- atc/engine/builder/delegate_factory_test.go
fixes #3835 
The timestamps were lost on events `FinishGet` and `FinishPut` during a refactor.
> add time for FinishGet and FinishPut events

- web/assets/css/build.less
Darken `.highlighted-line` a bit, switching from `@base02` (`#3d3c3c`) to `@base01` (`#2a2929`) which helps highlight the highlighted-line(s) pop a bit more:
Addresses https://github.com/concourse/concourse/issues/3805
> Set a darker background on highlighted-line

- atc/api/api_suite_test.go
- atc/api/handler.go
- atc/api/info_test.go
- atc/api/infoserver/info.go
- atc/api/infoserver/server.go
- atc/atccmd/command.go
- atc/info.go
The `/api/v1/info` path, in addition to giving the server and worker versions, now also gives the "external URL" - the canonical entry point for the installation. This is useful in cases where the API is accessed by IP address, through a proxy, etc., and we want to find out the proper URL instead. It also now gives the user-facing cluster name, if one is configured, which might in the future be picked up by fly or other clients (see #1077).
This PR doesn't currently have any consumers of this information, but it seems probably useful for it to show up in `fly targets` listings, at least. I'm not sure if the right thing is to display the external URL alongside the configured target URL, or if instead we should be _replacing_ whatever the user specified with whatever the cluster reports in …
> atc: info API yields the external URL and cluster name

- topgun/bbr_test.go
- topgun/operations/bbr-concourse-link.yml
- topgun/operations/bbr-with-properties.yml
Previously, there were no tests covering the use of the link provided by
the Concourse deployment through `concourse_db` - we were relying solely
on the use of properties.
Now, with the introduction of that type of configuration, we needed
tests for it.
> topgun: increase test coverage for bbr

- worker/retire/retire_runner.go
Fix issue : Not able to retire worker using tsa-team-authorized-keys only #3549
Before the patch :
```
root@01993a002c30:/src# concourse retire-worker --name $HOSTNAME
{"timestamp":"2019-05-28T12:02:56.757975470Z","level":"error","source":"retire-worker","message":"retire-worker.run.command-failed","data":{"command":"retire-worker","error":"Process exited with status 1","session":"2"}}
Process exited with status 1
{"timestamp":"2019-05-28T12:02:56.594409936Z","level":"debug","source":"atc","message":"atc.build-tracker.track.start","data":{"session":"16.27"}}
{"timestamp":"2019-05-28T12:02:56.597415009Z","level":"debug","source":"atc","message":"atc.build-tracker.track.done","data":{"session":"16.27"}}
{"timestamp":"2019-05-28T12:02:56.757792903Z","level":"error","source":"tsa","message":"t …
```
> fix retire worker using tsa-team-authorized-keys only

- README.md
The original link was pointing to a `404` page. This matches the path on concourse-ci.org.
My first contribution! 👋
> Update README Download Link

- package.json
This follows this documentation from the elm website:
https://elm-lang.org/0.19.0/optimize
The minified js (elm.min.js) goes from around 600k to 200k
Signed-off-by: Michiel Stigter <michiel.stigter@springer.com>
> add more optimizations in the elm compiling

- atc/atccmd/cert_cache.go
- atc/atccmd/command.go
- atc/config.go
- atc/db/migration/auto_cert_test.go
- atc/db/migration/migrations/1557237784_create_auto_cert_cache.down.sql
- atc/db/migration/migrations/1557237784_create_auto_cert_cache.up.sql
- atc/db/open.go
- go.mod
- go.sum
Instead of passing cert and key to serve over tls, the enable_autocert flag sets up ATC to get a certificate from Let's Encrypt.
Based on [this PR](https://github.com/concourse/atc/pull/199)
> Enable cert generation using Let's Encrypt

- topgun/k8s/worker_lifecycle_test.go
We were previously not accounting for the fact that it might take a
little while for the build to be marked as succeeded.
That race used to make our tests fail quite a good amount of times.
> topgun/k8s: reduce even more the flakiness of worker_lifecycle test

- ci/tasks/scripts/check-distribution-env/helm/list-actual
It was catching other things that had capital letters in them.
For example:
```
+ CONCOURSE_ENABLE_LETS_ENCRYPT
+ CONCOURSE_LETS_ENCRYPT_ACME_URL
- Y
```
What's that `Y` flag?? We don't care!
cc @taylorsilva
> Only check for env variables in the templates dir

- ci/tasks/scripts/k8s-deploy
Previously, it could happen that `web` didn't have its deployment fully
complete, which used to make `port-forward` fail quite consistently.
By leveraging `rollout status` we can wait for the underlying pods to
get to a `READY` state (instead of plain `RUN`) before moving forward.
> ci: wait for deployment rollout in k8s-deployment

- atc/db/migration/migrations/1557152441_separate_worker_task_cache.up.sql
- atc/db/migration/worker_task_cache_test.go
#3811 make sure migration succeeds if there are update conflicts
add tests for up and down migration as well.
> atc: make worker_task_caches miagration resilient

- topgun/worker_landing_test.go
Reverts concourse/concourse#3981
https://github.com/concourse/concourse/pull/3983 has been merged which should fix it
> Revert "topgun: pend flaky worker landing test"

- fly/commands/completion.go
- fly/commands/fly.go
As mentioned in #1309, users have to add a snippet to their .bashrc to enable autocompletion. This PR packages the snippet into the `fly` CLI, so the `.bashrc` entry can be reduced to one-line:
```
source <(fly completion bash)
```
Or using the `/etc/bash_completion.d` directory:
```
fly completion bash > /etc/bash_completion.d/fly
```
> Add `fly completion` as a command

- topgun/operations/bbr-concourse-link.yml
- topgun/operations/bbr-with-properties.yml
Change the postgres credentials to be non-default. Existing tests will only pass if the bosh job in our release uses the bosh links correctly.
Blocked by https://github.com/concourse/concourse-bosh-release/pull/41
> [topgun/bosh] Update tests for bosh links

- topgun/k8s/kubernetes_creds_mgmt_test.go
- topgun/tasks/simple-secret.yml
Fixes: https://github.com/concourse/concourse/issues/3809
Added some test coverage for one-off builds running against a helm deployed concourse that is using Kubernetes credential management.
CC @pivotal-bin-ju
> [topgun/k8s] Add test for one-off builds using secrets

- topgun/k8s/dns_proxy_test.go
- topgun/tasks/dns-proxy-task.yml
Hey,
Here we test the different cases where one is either able (or not) to access other services in a Kubernetes cluster from within garden containers when using the Helm chart.
Please see https://github.com/concourse/concourse/issues/3103 for the details on what are the differences between the scenarios.
closes #3103 
Thanks!
> topgun/k8s: add DNS behavior testing

- topgun/k8s/web_scaling_test.go
Hey,
This PR adds a test for verifying that, using the Helm chart, we're
able to go from 1 to 0 replicas (scaling in), then from 0 to 2 (scaling
out) using the standard helm primitives (updating `replicas` fields).
- closes #2851
Thanks!
> topgun/k8s: add test for scaling `web` in and out

- atc/atccmd/command.go
- atc/integration/configuration_test.go
- web/elm/src/Application/Application.elm
- web/elm/src/Concourse.elm
- web/elm/src/Dashboard/Dashboard.elm
- web/elm/src/Dashboard/Models.elm
- web/elm/src/Message/Callback.elm
- web/elm/src/Message/Effects.elm
- web/elm/src/Network/DashboardAPIData.elm
- web/elm/src/Network/Info.elm
- web/elm/src/Pipeline/Pipeline.elm
- web/elm/src/SubPage/SubPage.elm
- web/elm/tests/BuildTests.elm
- web/elm/tests/Common.elm
- web/elm/tests/DashboardTests.elm
- web/elm/tests/FlySuccessTests.elm
- web/elm/tests/JobTests.elm
- web/elm/tests/PipelineTests.elm
- web/elm/tests/ResourceTests.elm
- web/elm/tests/SideBarTests.elm
- web/elm/tests/TopBarTests.elm
- web/indexhandler/handler.go
- web/public/index.html
- web/wats/test/dashboard.js
When the web UI displayed the cluster name before, it did so because of server-side templating. Instead, we can now retrieve it dynamically from the `/info` API call, storing it in the session. This reduces the necessary plumbing around propagating the value, and we lose a lot of `clusterName = ""` test boilerplate.
The `FetchVersion` effect, which invoked the `/info` path, is now called `FetchClusterInfo` because we are interested in more of that API's data; some more things are renamed in order to match.
Fixes #3909.
Signed-off-by: Alexander Gurney <alexander_gurney@cable.comcast.com>
> web: Discover cluster name by API call instead of template injection

- package.json
- yarn.lock
More recent releases of `request` removed dependence on `stringstream`, which
is vulnerable to out-of-bounds reads in versions prior to 0.0.6.
> remove dependence on `stringstream` (via `less`)

- web/elm/src/Build/Styles.elm
- web/elm/src/Dashboard/Styles.elm
- web/elm/src/SideBar/Styles.elm
- web/elm/tests/BuildTests.elm
- web/elm/tests/DashboardTests.elm
- web/elm/tests/SideBarTests.elm
fixes #3956
```tex
\note{fix}{
A fix to a regression found recently involving 
\link{momentum based scrolling}{https://github.com/concourse/concourse/issues/3956}
on build pages on iOS browsers. 
Fix was also applied to the sidebar and the dashboard.
}
```
> fixed momentum scrolling on ios

- atc/db/migration/migrations/1561558376_add_type_to_resources.down.sql
- atc/db/migration/migrations/1561558376_add_type_to_resources.up.go
- atc/db/resource.go
- atc/db/team.go
This is so that we can join on parent `resource_types`. 
Considering the `resource_types` table already has a type column, this also makes things more consistent between the two.
> atc: add type column to resources

- topgun/placement_strategy_test.go
We are aware of an issue with the `fewest-build-containers` placement strategy where if multiple containers get kicked off in parallel, the strategy might not be honored (#3301).
This test has been flaky to begin with, and recent scheduling changes have made it more flaky. Since this is a known issue, we are pausing this test until we have a fix for the problem.
> pause the flaky fewest build containers test

- topgun/k8s/external_worker_test.go
Changed topgun/k8s to use the new `hosts` parameter
Blocked by https://github.com/helm/charts/pull/15220
cc @zoetian
> Update topgun/k8s test to use new hosts parameter

- atc/db/resource_config_scope.go
- atc/db/resource_test.go
> only update resource version metadata if the new value is not null

- fly/main.go
`fly` cli should show by executing `fly -h` or `fly --help`
```
$ fly help
Usage:
fly [OPTIONS] <command>
Application Options:
-t, --target=              Concourse target name
-v, --version              Print the version of Fly and exit
--verbose              Print API requests and responses
--print-table-headers  Print table headers even for redirected output
Help Options:
-h, --help                 Show this help message
```
But these commands end which `exit 1`.
```bash
$ fly -h
$ echo $?
1
$ fly --help
$ echo $?
1
```
And these commands output logs to stderr, so `grep` command, etc can't be used.
```bash
$ fly -h | grep volume
error: Usage:
fly [OPTIONS] <command>
Application Options:
-t, --target=              Concourse target name
-v, --version              Print the version of Fly …
```
> fly -h & fly --help exits successfully

- atc/api/artifacts_test.go
- atc/api/artifactserver/create.go
- atc/worker/client.go
- atc/worker/client_test.go
- atc/worker/workerfakes/fake_client.go
- fly/commands/execute.go
- fly/commands/internal/executehelpers/inputs.go
- fly/commands/internal/executehelpers/uploads.go
- fly/integration/execute_multiple_inputs_test.go
- fly/integration/execute_overriding_inputs_test.go
- fly/integration/execute_test.go
- fly/integration/execute_with_outputs_test.go
- go-concourse/concourse/artifacts.go
- go-concourse/concourse/artifacts_test.go
- go-concourse/concourse/concoursefakes/fake_team.go
- go-concourse/concourse/team.go
concourse/concourse#3803
when uploading local inputs for fly execute it will send "platform" of task config to create artifact endpoint. Then it will include platform info in worker spec for choosing a worker for artifact volume initializing.
> fix file permission when uploading local input during fly execute

- atc/exec/put_step.go
- atc/exec/put_step_test.go
- atc/resource/resource.go
- atc/resource/resource_get.go
- atc/resource/resource_put.go
- atc/resource/resource_put_test.go
- atc/resource/resourcefakes/fake_resource.go
- atc/resource/versioned_source.go
We used to return a `VersionedSource` from the PutStep, which had `StreamIn` and `StreamOut` implemented using streaming from the container rather than from a volume. We don't really call this anywhere though. Let's get rid of it.
The motivation to do so comes from our refactor in #4052 for which we are trying to invert the dependency between a `Resource` and a `Container` (i.e. a `Resource` should create a container and not be passed one in the constructor)
Signed-off-by: Nader Ziada <nziada@pivotal.io>
> return VersionResult from PutStep

- topgun/k8s/k8s_suite_test.go
fixes: #4124
Previously, we had the seed for random being configured only at the
suite level, which lead to us having problems with name colisions.
Now, having it being seeded every time (+ having a bigger random number
size) we need a random name, we're able to better ensure that we won't
have collisions even when running in parallel.
> topgun/k8s: move random seed to release+ns setup

- topgun/k8s/baggageclaim_drivers_test.go
- topgun/k8s/container_limits_test.go
- topgun/k8s/k8s_suite_test.go
Hey,
@taylorsilva and I started working on making the tests that currently fail on PKS (https://github.com/concourse/concourse/issues/4098#issuecomment-508549862) possible to run there.
Our approach is to conditionally `Skip()` based on the Kubernetes IAAS set (through environment variables). Trying to just fit another `if` in the current tests revealed that the code would become hard to reason about, so we started refactoring them:
Thanks!
> topgun/k8s: refactor tests to support targeting PKS

- topgun/k8s/tsa_node_port_test.go
This PR is related to this github issue: https://github.com/concourse/concourse/issues/4094
- set value for `web.service.type` and `web.service.tsaNodePort` to see if concourse chart can be deployed succesfully
cc: @cirocosta 
We're still waiting for the response from that github issue.
> Topgun: Add tests for TSA web service nodeport

- fly/commands/get_team.go
long flag for the team name in `get-team` was different from others.
e.g. 
`set-team`'s long flag (`team-name`)
https://github.com/concourse/concourse/blob/c16d62872e4ae2055efe2a27cf4a9903d9d009f5/fly/commands/set_team.go#L27
`login`'s long flag (`team-name`)
https://github.com/concourse/concourse/blob/c16d62872e4ae2055efe2a27cf4a9903d9d009f5/fly/commands/login.go#L29
> Aligned long flag of get-team with other

- fly/commands/targets.go
- fly/integration/fixtures/flyrc-badtoken.yml
- fly/integration/targets_test.go
I don't know go at all, but this seemed like a pretty straightforward change. Let me know if there is anything else to add (e.g. tests) but please keep in mind I might need some guidance. 
Thanks.
Fixes: https://github.com/concourse/concourse/issues/4107
Change-type: patch
Signed-off-by: Giovanni Garufi <giovanni@balena.io>
> Check that the jwt token is valid when running fly targets

- atc/api/present/resource_version.go
- atc/api/resourceserver/versionserver/list.go
- atc/api/versions_test.go
- atc/db/build_test.go
- atc/db/dbfakes/fake_resource.go
- atc/db/job_test.go
- atc/db/pipeline_test.go
- atc/db/resource.go
- atc/db/resource_test.go
- fly/commands/curl.go
- fly/integration/curl_test.go
refer to https://github.com/concourse/concourse/issues/3932
a related side work is fixing `fly curl` with query params (since there is no concourse api needed passing query until this one) as before there was no way to pass query and if one using `fly curl /api/v1/path?param=value`, it will encode the `?` and produces a wrong url cause `404 not found`
> Support querying resource versions by fields

- web/elm/src/Build/StepTree/StepTree.elm
- web/elm/tests/BuildTests.elm
fixes #3942 
This PR kept the first-build-log-line-id to be 1, as it was before.
```tex
\note{fix}{
Fixed a bug where the 
\link{timestamps}{https://github.com/concourse/concourse/issues/3942}
on build logs were off by one.
}
```
> fixed build log timestamps being off by one

- web/elm/benchmarks/Benchmarks.elm
- web/elm/src/Build/Build.elm
- web/elm/src/Build/Output/Output.elm
- web/elm/src/Build/StepTree/StepTree.elm
branched off of #4110, please merge it first.
There was a lot of delicate research that went into this PR, documented at
https://github.com/pivotal-jamie-klassen/lazy (in `story.md`). We will probably
publish a technical blog post documenting these findings. Long story short,
it wasn't the map of functions that caused the problem, but some leakiness
in record update syntax in Elm.
fixes #4061
> web: fix lazy-rendering on build page

- web/elm/src/Dashboard/Group/Tag.elm
- web/elm/tests/TagTests.elm
The tag, is longer than the currently designed box allowing 8 characters
of text. This is not elegant and could look a little better.
This does however mean, all the tags are now not fixed and have variable
width.
- Sanity check
- Perhaps run it and test it (I've only tested this by fiddling with dev tools)
> Fix the `pipeline-operator` tag

- web/assets/css/notauthorized.less
This fixes https://github.com/concourse/concourse/issues/4190
> Fixes a bug where the 'not authorized' div covers the sidebar

- web/elm/src/Build/StepTree/StepTree.elm
- web/elm/src/Build/Styles.elm
- web/elm/tests/BuildTests.elm
fixes #3921 and also the same bug in the duration tooltip on the right hand side of steps.
before and after:
> use position fixed so tooltips can 'float' outside the container

- web/elm/src/Build/StepTree/StepTree.elm
- web/elm/src/Build/Styles.elm
- web/elm/tests/BuildTests.elm
fixes #4111
```tex
\note{feature}{
We noticed after \link{PR #4058}{https://github.com/concourse/concourse/pull/4058} 
(where build steps are collapsed by default) that it wasn't very easy to see failing steps.
Now a failed step has a simple red border around its header and an erroring step has an
orange border
\link{#4164}{https://github.com/concourse/concourse/pull/4164} 
}
```
> web: add red border to failing steps

- atc/task.go
- atc/task_test.go
- fly/integration/execute_test.go
fixes #4205
As I thought, #3505 was the culprit. The fly integration test technically only covers fly's use of this unmarshalling, but I performed another manual test. If you run:
1.
$ fly -t dev set-pipeline -n -p pipeline -c <(cat <<EOF
jobs:
- name: job
plan:
- task: create-task
config:
source: {repository: busybox}
outputs:
- name: output
run:
path: sh
args:
- -c
- |
cat > output/task.yml <<EOT
source: {repository: busybox}
params:
PARAM:
run:
path: env
EOT
- task: run-task
file: output/task.yml
EOF
)
1. `fly -t dev up -p pipeline`
1. `fly -t dev tj -w -j pipeline/job`
you get the expected output with `PARAM=` instead of `PARAM=null`. This means that the right logic is being …
> fix coercion of null task params to strings

- atc/db/lock/lock.go
- atc/exec/task_step.go
- atc/worker/client.go
As part of merging in changes from `limit-active-tasks` and refactoring the task step, we accidentally introduced an error in the logs where we tried to decrease the number of active tasks even if we were not using `limit-active-tasks`.
This PR fixes that, as well as cleaning up other logging and naming for better clarity.
Co-authored-by: Divya Dadlani <ddadlani@pivotal.io>
> clearer errors and logging for limit-active-tasks

- atc/worker/image/image.go
- atc/worker/image/image_test.go
fixes #4224
This should get rid of our "no image plugin configured" errors.
Signed-off-by: kcmannem <kmannem@pivotal.io>
> returning error when creating volume fails for image fetching

- fly/commands/targets.go
- fly/integration/targets_test.go
* #4181 fixed the segfault, but introduced exiting 1
if any targets had an expired or invalid token in .flyrc
* Append error message inline to display after "n/a" for each target
Co-authored-by: Sameer Vohra <svohra@pivotal.io>
> Change `fly targets` to not error and bail

- atc/worker/db_worker_provider_test.go
- atc/worker/worker.go
- atc/worker/worker_test.go
Fixes #4244.
Co-authored-by: Nader Ziada <nziada@pivotal.io>
We also need to find a solution to delete the existing orphaned creating containers from users' databases. A migration, perhaps?
> remove EnsureDBContainerExists

- .github/CODEOWNERS
~This pings everyone on every PR~
Actually I think its because modifications to the `db` package aren't assigned to a team. We should probably just remove this anyway. Thoughts?
> Remove wildcard in codeowners

- atc/resource/resource_get_test.go
- atc/resource/resource_put_test.go
- atc/resource/run_script.go
- atc/worker/client.go
- atc/worker/client_test.go
When querying Garden for a property that does not exist, Garden
logs an error message. This error message pollutes the Worker
logs as it doesn't really indicate that something wrong has
been going on.
By querying all properties and checking if the interested one
is among them we obtain the same result while avoiding Garden
to log an error.
> [bugfix] Do not trigger Garden error when asking for container property.

- web/elm/src/Build/Styles.elm
- web/elm/tests/BuildTests.elm
fixes #4248
```tex
\note{feature}{
Having red and orange borders for failing and erroring steps were such a \link{big hit}{https://github.com/concourse/concourse/pull/4164}, we decided to add another!
Now running steps have a nice yellow border, making it easy to see what is currently running. \link{#4250}{https://github.com/concourse/concourse/pull/4250} 
}
```
> web - add yellow border to running steps

- atc/worker/client.go
- atc/worker/client_test.go
- atc/worker/pool.go
- atc/worker/workerfakes/fake_pool.go
This fixes a bug where the active_tasks counter (used in the limit-active-tasks strategy)
would be increased even if the container running the task is already present in the worker.
The above bug can manifest, for instance, if the ATC restarts.
To detect if a container is already present on a worker a small helper function is added
to Pool and queried it only when usign the limit-active-tasks strategy.
A test case is added to ensure the active_tasks counter is not increased when the container
is already present on the worker.
@xtreme-sameer-vohra first noticed this issue while reviewing #4118.
If this PR is accepted I'll also remove from the docs the warning that workers needs to be restarted to reset the counter.
> [bugfix] Do not increase active_tasks if the container is already present.

- .github/CODEOWNERS
fixes #4260
Originally we added the CODEOWNERS file intending to have various teams own entire directory trees, not just their top levels.
From https://help.github.com/en/articles/about-code-owners:
>        # In this example, @doctocat owns any files in the build/logs
>        # directory at the root of the repository and any of its
>        # subdirectories.
>        /build/logs/ @doctocat
>
>        # The `docs/*` pattern will match files like
>        # `docs/getting-started.md` but not further nested files like
>        # `docs/build-app/troubleshooting.md`.
>        docs/*  docs@example.com
> remove *'s from CODEOWNERS

- atc/atccmd/command.go
After many profiles, it became clear that at high transaction levels the system was spending substantial amounts of it's time reaping and re-establishing TLS connections in order to grab locks or run queries against Postgres.  
This change resulted in a 30% reduction in CPU for our web processes.  The dominate calls now are around marshaling and un-marshaling JSON.
Signed-off-by: Eric Billingsley <eric@calculi.com>
> [#4200] prevent reconnect floods to Postgres

- fly/commands/internal/setpipelinehelpers/atc_config.go
- fly/commands/internal/setpipelinehelpers/atc_config_test.go
- fly/integration/login_test.go
- fly/integration/set_pipeline_test.go
- fly/integration/version_test.go
- fly/main.go
- fly/rc/target.go
Test:
$ fly/fly -t tt sp -c pipeline.yml -p pp
...
the pipeline is currently paused. to unpause, either:
- run the unpause-pipeline command:
fly/fly -t tt unpause-pipeline -p pp
- click play next to the pipeline in the web ui
Fixes: #4283
> fly: when prompt a fly command to run, use full fly path the is invoked instead of just hardcode "fly".

- atc/api/accessor/accessor.go
- atc/api/builds_test.go
- atc/api/buildserver/list.go
- atc/api/jobs_test.go
- atc/api/jobserver/list_all.go
- atc/api/pipelines_test.go
- atc/api/pipelineserver/list_all.go
- atc/api/resources_test.go
- atc/api/resourceserver/list_all.go
- atc/api/workers_test.go
- atc/api/workerserver/list.go
- atc/db/build_factory.go
- atc/db/build_factory_test.go
- atc/db/dbfakes/fake_build_factory.go
- atc/db/dbfakes/fake_job_factory.go
- atc/db/dbfakes/fake_resource.go
- atc/db/dbfakes/fake_resource_factory.go
- atc/db/job_factory.go
- atc/db/job_factory_test.go
- atc/db/pagination.go
- atc/db/resource_factory.go
- atc/db/resource_factory_test.go
tl;dr: Modify endpoint behavior to return everything when the user is an `Admin` i.e. owner of the main team
- We modified the following methods to behave properly for an admin user:
- ListAllPipelines
- ListAllJobs
- ListBuilds
- ListAllResources
- ListWorkers
- Added the appropriate tests.
- this is currently functional, that the admin user is able to see all the pipelines when logging in from the web ui.
- fly hits team endpoints, so still not working as per this PR, we will address that in #4195.
- Also, applying actions to pipelines in the web ui (unpause, expose, trigger job), this should be addressed in #4194. 
cc: @youssb 
fixes: #4193
> atc/api: Super admin user first steps

- atc/worker/client.go
- atc/worker/client_test.go
Whenever ContainerInWorker returned an error the Active Tasks Lock
would never be released, blocking any task to check for available
workers and thus to start.
Here the bug is fixed, by releasing the lock if the ContainerInWorker
returns an error.
Additionally the unit tests are expanded to verify that for every
lock acquisition a lock release is also called.
> [BUGFIX] Release lock if pool.ContainerInWorker errors.

- atc/worker/client.go
The tasks count decreasing (used in the limit-active-tasks strategy) can be
executed concourrently as the DB transaction will make sure that the end
value is consistent.
Trying to acquire a lock when decreasing the tasks count in a system with
several flying task can easily result in a race to acquire lock and eventually
even a "de facto" dead lock.
We observed this issue on our Production CI where it eventually all just hanged, what happens is the following:
- New tasks acquire the lock to check if a worker is free and all are busy
- Completed tasks try to acquire a lock to decrease the task and free the worker
- More tasks enter the queue and try to acquire a lock
- The decrease-active-tasks is can perform its operation once in a blue moon making the situation worse and worse
@deniseyu …
> Do not acquire lock when decreasing task count.

- go.mod
- go.sum
With the bump to go 1.13, there's a more strict validation against
the tags used in the [pseudo versions], meaning that it ends up really
reaching out to the source provider to validate if the sha matches the
tag (which, in this case, doesn't):
git show v2.0.0-alpha.1
commit d81cb85237595f720d83eda492bae8f6162fc5c0 (tag: v2.0.0-alpha.1)
By removing the tag, we can then let go perform the validation against
just the SHA.
[pseudo versions]: https://golang.org/cmd/go/#hdr-Pseudo_versions
> fix go.mod to properly comply to 1.13 strict rules

- web/elm/src/Concourse.elm
- web/elm/src/UserState.elm
- web/elm/tests/DashboardTests.elm
- web/elm/tests/PauseToggleTests.elm
- web/elm/tests/ResourceTests.elm
- web/elm/tests/TopBarTests.elm
- web/elm/tests/UserStateTests.elm
fixes #4194 
There are a few areas in the web UI where the client tries to figure out if you're authorized to perform a certain action. These are:
- pause/unpause a pipeline
- force a check resource
- expose a pipeline
This commit changes this behaviour to allow a user to perform these functions from the web ui.
@pivotal-jamie-klassen is there anywhere that we could be adding tests? thx!
cc @taylorsilva
> [Web] add super admin web ui functionalities 

- release-notes/v5.5.0.md
- web/assets/css/globals.less
The default scrollbar was hurting my eyes. So I tried applying the concourse styling to it. I used colors from the sidebar item active/inactive states.
> adding styling to scrollbars

- atc/db/pipeline_factory.go
- atc/db/pipeline_factory_test.go
- atc/db/team.go
- atc/db/team_test.go
- release-notes/v5.5.0.md
Fixes #4346
My thinking is that for acceptance:
1. Be a super admin
1. `fly login -n main`
1. `fly set-pipeline -p pipeline`
1. `fly set-team -n team`
1. `fly login -n team`
1. `fly set-pipeline -p pipeline`
1. Look at the sidebar - take note of the team order (`main`, `team`).
1. (still logged in to `team`) `fly order-pipelines -p pipeline`
1. Look at the sidebar - the team order should be the same (if you did this test on master, they'd be reversed).
> atc: fix ListAllPipelines ordering

- atc/exec/get_step.go
- atc/exec/get_step_test.go
- atc/fetcher/fetcher.go
- atc/fetcher/fetcher_test.go
- atc/fetcher/fetcherfakes/fake_fetch_source_factory.go
- atc/fetcher/fetcherfakes/fake_fetcher.go
- atc/fetcher/resource_instance_fetch_source.go
- atc/fetcher/resource_instance_fetch_source_test.go
- atc/resource/resource.go
- atc/worker/image/image_resource_fetcher.go
- atc/worker/image/image_resource_fetcher_test.go
I really don't know why we had this resource.Session wrapper. It did nothing so I got rid of it. It removes references to `db.conatinerMetadata` from the resource package as a benefit as well.
> remove reference to db.containerMetadat from resource package

- atc/atccmd/command.go
- cmd/concourse/web.go
- tsa/tsacmd/command.go
When multiple Concourse clusters send logs to a single log server, this will be super helpful to decide where a log line comes from.
Say cluster name is "dev", them sample log lines are as below: (notice "source" field in logs)
web_1     | {"timestamp":"2019-09-09T08:38:20.133553327Z","level":"info","source":"dev.tsa","message":"dev.tsa.connection.channel.command.register.done","data":{"command":"forward-worker","remote":"172.19.0.4:32946","session":"1.4.1.2","worker-address":"127.0.0.1:44903","worker-platform":"linux","worker-tags":""}}
web_1     | {"timestamp":"2019-09-09T08:38:21.008126381Z","level":"info","source":"dev.atc","message":"dev.atc.pipelines.radar.scan-resource-type.interval-runner.tick.running-worker.garden-connection.retryable-http-client.retrying","data":{"error":"dial …
> Include cluster name in log line.

- atc/atccmd/command.go
- atc/db/check.go
- atc/db/check_factory.go
- atc/db/check_factory_test.go
- atc/db/check_test.go
- atc/db/dbfakes/fake_check.go
- atc/db/dbfakes/fake_check_factory.go
- atc/engine/builder/builder.go
- atc/engine/builder/builderfakes/fake_delegate_factory.go
- atc/engine/builder/delegate_factory.go
- atc/engine/builder/delegate_factory_test.go
- atc/exec/check_step.go
A topgun test was failing for lidar changes because we saved the check plan into the DB with variables interpolated and the topgun test checks to make sure there are no secrets stored in the DB. We changed it so that we will interpolate the vars in the check step instead.
> Don't store secrets in the check plan

- CONTRIBUTING.md
I was reading the contributing (I'd like to start helping this project :D) and noticed that a reference to the old `/ci` folder was still here.
Signed-off-by: Vittorio Camisa <vittorio.camisa@gmail.com>
> chore: removed /ci folder reference from CONTRIBUTING.md

- fly/commands/set_team.go
- fly/integration/set_team_test.go
- skymarshal/skycmd/bitbucketcloud_flags.go
- skymarshal/skycmd/cf_flags.go
- skymarshal/skycmd/flags.go
- skymarshal/skycmd/github_flags.go
- skymarshal/skycmd/gitlab_flags.go
- skymarshal/skycmd/ldap_flags.go
- skymarshal/skycmd/oauth_flags.go
- skymarshal/skycmd/oidc_flags.go
In response to: https://github.com/concourse/concourse/issues/4348
The current wording seems to suggest a list is a valid input to any of these flags, where a single value is instead what is required.
I believe this brings the fly documentation more in line with: https://concourse-ci.org/github-auth.html
> Documentation: https://github.com/concourse/concourse/issues/4348

- atc/config.go
- atc/config_test.go
- release-notes/latest.md
This pr fixes the bug #4236. An error is now returned when there is a non-string value in the version config.
> Enforced all version fields to be strings

- release-notes/v5.6.0.md
* Addition of secrets duration flag
* Expose GARDEN_NETWORK_POOL in BOSH release
> Add release notes for v5.6.0

- atc/worker/container.go
This meta data will greatly improve our ability to identify the origin of container / volume errors.
> container: add worker name to logger data

- topgun/common/common.go
since each suite is in a subdirectory of `topgun/`. This should fix failures like https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bosh-topgun-pcf/builds/19#L5d7beaf3:578.
> topgun: fix manifest path

- atc/resource/resource_put.go
- atc/resource/resource_put_test.go
We ran in to a *fun* instance where incorrectly configured resources in users' pipelines were crashing the `atc`.  This covers that case and prevents it from happening.
I didn't _really_ know what to include as an error message, so I just jotted down something that loosely makes sense.  I'm kinda expecting to have to change it during review.
> atc/resource/resource_put: prevent a nil VersionResult from crashing atc

- atc/db/migration/migrations/1568056691_create_resource_config_versions_version_index.down.sql
- atc/db/migration/migrations/1568056691_create_resource_config_versions_version_index.up.sql
- atc/db/resource.go
- atc/db/resource_test.go
implements #3990 
one can pin a version in get step or resource config by only giving partially matched field(s). If there are multiple partially matched versions existing, it will pick one version that has highest check order (latest).
> atc: partial version matching for pinned version

- topgun/both/both_suite_test.go
- topgun/common/common.go
- topgun/core/atc_login_session_test.go
- topgun/core/aws_ssm_test.go
- topgun/core/containers_scoped_to_team_test.go
- topgun/core/core_suite_test.go
- topgun/core/credhub_test.go
- topgun/core/creds_test.go
- topgun/core/database_encryption_test.go
- topgun/core/syslog_test.go
- topgun/core/unique_versions_test.go
- topgun/core/vault_test.go
- topgun/fly.go
- topgun/pcf/bbr_test.go
- topgun/pcf/pcf_suite_test.go
- topgun/runtime/runtime_suite_test.go
When splitting up topgun tests into individual packages, there were some issues when trying to share certain functions and variables that would be used commonly by those newly created packages.
This exposes many more variables to be used by the suites.
We also had some issues where some deploy arguments were being appended to more times than we wanted.
This is hopefully the last part in our ongoing series of `fixing topgun`.
> Fix topgun by exposing more common variables

- topgun/k8s/container_limits_test.go
- topgun/k8s/dns_proxy_test.go
- topgun/k8s/https_web_tls_termination_test.go
- topgun/k8s/kubernetes_creds_mgmt_test.go
the tests failing here: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/1955 were a result of changing the command directory in the `FlyCli` `Start` function that is inherited from the main topgun tests.
> fix topgun test affected by splitting the main topgun tests

- topgun/common/common.go
- topgun/pcf/bbr_test.go
The first time a release gets deployed, it needs to be 'compiled' from bosh's perspective. Since we are now using a new release name (`concourse-((suite))`) each topgun suite has to compile on the first deploy, and this means that parallel ginkgo nodes in the same test run will contend for the compilation lock. Whoever loses will end up failing their first test. This PR aims to fix this case.
> topgun: wait for compile locks before deploying

- atc/db/lock/lock.go
- atc/db/lock/lock_test.go
fixes #4393 
In the lockFactory, when acquiring a lock, it can get stuck talking to the database. Future calls will block on the mutex.Lock. This can lead to an avalanche of goroutines from the buildtracker, scheduler, and lidar as each tick piles on more work.
We want to add a timeout to the mutex.Lock so that new goroutines will die quicker when they can't fetch the lock.
> Add a timeout when acquiring mutex lock

- fly/commands/workers.go
- fly/integration/workers_test.go
- release-notes/v5.6.0.md
It should be very helpful to provide age info to Concourse cluster ops. Output looks like below:
$ ./fly -t test workers
name                                          containers  platform  tags  team  state    version  age
worker-sc-prd-vc010-10.160.142.107-jMxSReSOV  54          linux     none  none  running  2.2      6h14m
worker-sc-prd-vc066-10.161.108.40-ozpIkYSBE   81          linux     none  none  running  2.2      6h15m
worker-sc-prd-vc075-10.193.7.99-QA8snquPr     63          linux     none  none  running  2.2      6h15m
> feat(fly): add "age" column to "fly workers" command.

- atc/metric/error_sink_collector_test.go
- atc/metric/http_test.go
- atc/metric/metric_suite_test.go
- atc/metric/periodic_test.go
metric.Initialize was being called multiple times in parallel, causing a race
for the emitters global constant. Fixed by only calling metric.Initialize once
before the suite and passing around a shared logger.
sample failure:
https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/unit/builds/1098#L5d8a5acb:543:625
> atc: fix metric test data race

- topgun/common/common.go
We have seen some topgun logs where a test process was waiting just because
2 out of 3 compile locks were claimed. This change should make greater use of
the available compilation VM pool, and so hopefully reduce the total running
time for topgun suites.
> topgun: tolerate multiple compile locks

- .github/pull_request_template.md
Changes proposed in this pull request
* Add link to anti-patterns page to PR template
> Add wiki links to pr template

- fly/commands/workers.go
Resolve #4545
Signed-off-by: Chao Li <chaol@vmware.com>
> fix(fly workers): showed wrong age if a worker is younger than 1 hour

- release-notes/v5.6.1.md
Release notes for a patch version release which will contain a fix for the git-resource. concourse/git-resource#273
> Adding release notes for v5.6.1

- fly/commands/ordering_pipeline.go
- fly/integration/ordering_pipelines_test.go
Add an '--all' option to the order-pipelines command to sort all the pipelines of a given target in alphabetical order.
> Add option to sort all pipelines alphabetically.

- release-notes/v5.6.1.md
> Added release note for fly workers age fix

- release-notes/latest.md
- release-notes/v5.6.1.md
Cleans up release notes for v5.6.1, and adds a note for #4507.
No code changes.
> Clean up v5.6.1 release notes

- atc/gc/build_log_collector.go
- atc/gc/build_log_collector_test.go
- atc/gc/build_log_retention_calculator.go
- atc/gc/build_log_retention_calculator_test.go
- atc/job_config.go
- atc/validate.go
When minimum_succeeded_builds is specified, at least such success builds' logs will
be retained, which will be helpful for developing and debugging a job.
This commit changes the original algorithm of build log collector a little bit:
- no longer specially handle build id 1
- use ReapTime field to decide if a build's log has been reaped
- FirstLoggedBuildID now points to the first build whoes log is not reapped
Unit tests are updated.
If some user requests to support min_fail_builds in future, it would be easy
to support.
Resove #4026
Close #4188
> feat[gc/build-log-collector]: Added minimum_succeeded_builds to build_log_retention

- release-notes/latest.md
- web/elm/src/Pinned.elm
- web/elm/src/Resource/Resource.elm
- web/elm/src/Resource/Styles.elm
- web/elm/tests/Common.elm
- web/elm/tests/Data.elm
- web/elm/tests/PinnedTests.elm
- web/elm/tests/ResourceFeature.elm
- web/elm/tests/ResourceTests.elm
Fixes #4561.
* pin buttons on versions other than the pinned one are now clickable.
* clicking them will hit the PinVersion API appropriately
* there are reasonably-graceful visual transition states (spinners on both versions being switched between).
> web: pin switching

- fly/commands/format_pipeline.go
- fly/integration/fixtures/format-expected.yml
- fly/integration/fixtures/format-input.yml
- fly/integration/format_pipeline_test.go
- release-notes/latest.md
The `format-pipeline` command had logic to suppress output in the case where the formatted pipeline was unchanged from the input. This complicates use of the command in automated workflows, where we'd like to use `format-pipeline` as a canonicalization step. The new behavior lets the output be consumed unconditionally. For example, one can find out whether two pipelines - say, one stored in git and one retrieved from `fly get-pipeline` - are the same after `format-pipeline` has been applied to both.
Also add tests for the command, to demonstrate how a given input pipeline with various formatting oddities will be converted into a standard form, and that reformatting will preserve that form.
> fly: always emit output in format-pipeline

- atc/api/containerserver/report.go
- atc/api/volumeserver/report.go
- atc/db/container_repository.go
- atc/db/container_repository_test.go
- atc/db/dbfakes/fake_container_repository.go
- atc/db/dbfakes/fake_volume_repository.go
- atc/db/volume_repository.go
- atc/db/volume_repository_test.go
- atc/metric/emitter/newrelic.go
- atc/metric/emitter/prometheus.go
- atc/metric/metrics.go
- release-notes/latest.md
Fixes #3600
Fixes #4571 
*  when reporting containers from worker, create destroying containers in the db for any unknown containers
*  these new destroying containers will then get gc-ed on the next gc tick
* metrics to be added in #4571
> GC unknown containers and volumes from workers

- atc/db/resource_type.go
- atc/db/resource_type_test.go
> Fix resource types tree lookup when resource type name and type are the same

- package.json
- web/elm/elm.json
- yarn.lock
Elm 0.19.1 fixes a bug that was, until now, preventing us from using the `--debug` flag for `elm make`. While I was at it, I just ran `ncu -u`.
* Upgrade everything in `package.json` to latest
* Add `--debug` flag back to `elm make` in yarn scripts like `yarn build-debug`
> web: upgrade dependencies

- atc/db/build.go
- atc/db/build_event_source.go
- atc/db/build_factory.go
- atc/db/check.go
- atc/db/container_repository.go
- atc/db/job.go
- atc/db/job_factory.go
- atc/db/pipeline.go
- atc/db/pipeline_factory.go
- atc/db/resource.go
- atc/db/team_factory.go
- atc/db/volume_repository.go
- atc/db/volume_repository_test.go
- atc/db/worker.go
- go.sum
- release-notes/latest.md
Fixes #4373 
When multiple queries are made, changed the use of conn to use transactions instead.
Also cleaned up some queries that could be made in a single query instead.
> api query transaction

- release-notes/latest.md
- web/elm/src/Job/Job.elm
- web/elm/src/Job/Styles.elm
- web/elm/tests/JobTests.elm
Fixes #4493.
* say 'no builds for job JOBNAME' instead of loading forever
* styles involve some magic numbers, but we don't expect this page to live much longer with https://github.com/concourse/concourse/projects/12 on the horizon.
* overflow behaviour (horizontal scrollbar, not the end of the world):
> web: add no builds message on job page

- atc/config.go
- atc/worker/db_worker_provider.go
- atc/worker/gclient/factory.go
- worker/container_sweeper.go
- worker/workercmd/worker.go
Co-authored-by: Divya Dadlani <ddadlani@pivotal.io>
Fixes #4467.
> What are the changes included in this PR? Feel free to add as many lines as needed below.
* add a DefaultGardenClientWithTimeout in `gclient`
* use the new garden client in the `worker` for the `container_sweeper`
* the baggageclaim client already has a timeout set
> use basic garden client with timeout in container sweeper

- go.mod
- go.sum
Update AWS Go SDK  to version 1.25.18
AWS recently added a new feature to EKS to allow attaching IAM roles to Kubernetes service accounts (see links below). Changes were made to the AWS SDK to support this new authorization method (see links below). Until the latest version of the SDK is used in Concourse, it is not possible to use Concourse in EKS where this feature is used.
Links:
- [IAM Roles for Service Accounts](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/)
- [SDK commit adding required functionality](https://github.com/aws/aws-sdk-go/commit/2e1d76a9c838cb2bf0e03de2ced6666dc2f3eaa4#diff-0036fa6db507a6d8080c6ce74494bb71)
Update the version of the AWS Go SDK
> Update AWS Go SDK  to version 1.25.18

- topgun/k8s/baggageclaim_drivers_test.go
- topgun/k8s/container_limits_test.go
- topgun/k8s/dns_proxy_test.go
- topgun/k8s/ephemeral_worker_test.go
- topgun/k8s/external_postgres_test.go
- topgun/k8s/external_worker_test.go
- topgun/k8s/garden_config_test.go
- topgun/k8s/https_web_tls_termination_test.go
- topgun/k8s/k8s_suite_test.go
- topgun/k8s/kubernetes_creds_mgmt_test.go
- topgun/k8s/mainteam_role_test.go
- topgun/k8s/prometheus_test.go
- topgun/k8s/rebalance_test.go
- topgun/k8s/tsa_node_port_test.go
- topgun/k8s/web_scaling_test.go
- topgun/k8s/worker_lifecycle_test.go
fixes #4320
fixes https://github.com/concourse/ci/issues/182
closes #4581
closes #4613
Running k8s-topgun outside of the k8s cluster has been flakey. These changes
allow us to run these tests inside or outside of the cluster with a new
environment variable `IN_CLUSTER`.
We created an `Endpoint` interface and switch implementations based on the value
of `IN_CLUSTER`. The `Endpoint` implementation always returns an address, which
is either:
1. an address of a port-forwarding session (you're running the test suite
outside the cluster)
2. an internal (to the cluster network) address of either a k8s service/pod
(you're running the test suite inside the cluster)
We also:
- removed `--wait` from the helm installation command. We already have a way of
waiting for all pods to come up. Having …
> Enable k8s-topgun to run inside k8s cluster

- atc/db/container_repository.go
- atc/db/migration/bindata.go
- atc/gc/gc_suite_test.go
- atc/metric/emitter/newrelic.go
- fly/commands/login.go
- fly/commands/unpin_resource.go
- fly/integration/workers_test.go
- topgun/k8s/container_limits_test.go
- topgun/runtime/build_artifact_transfer_test.go
[k8s topgun builds are failing](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/2163#L5db181c1:3:5). While I was at it, I figured I might as well run `goimports` on everything.
* pure refactor
* remove unused import in container limits k8s topgun test
* format imports in other go files
> atc, fly, topgun: run goimports

- release-notes/latest.md
- web/elm/src/Build/Output/Output.elm
- web/elm/src/Build/StepTree/StepTree.elm
- web/elm/tests/BuildStepTests.elm
Fixes #3942.
* in the `timestamps` Dict on a `Step`, the keys are now line _numbers_ rather than line _indices_
> web: fix build log timestamps

- atc/atccmd/command.go
- atc/creds/dummy/flags.go
- atc/creds/dummy/manager.go
- atc/creds/dummy/manager_factory.go
- atc/creds/dummy/secrets.go
- atc/creds/dummy/secrets_factory.go
this is primarily to make testing credential management functionality a
bit easier
> atc: add a dummy credential manager

- atc/creds/vault/vault.go
- atc/creds/vault/vault_test.go
No
For credential manager Vault, secrets should be fetched from only "prefix/team/pipeline", "prefix/team", or "prefix/shared". It should never fetch secrets directly from "prefix/". But there is a bug, when `vault-shared` is not configured, it will fetch secrets directly from "prefix/".
Change is simple. When shared path is not configured, it should not be appended to search path.
> fix: (creds/vault) fixed a bug when "vault-shared" is not configured, secrets under prefix can be fetched.

- atc/exec/task_step.go
I was trying to enumerate the various scenarios that might cause an `on_error` hook to evaluate [here](https://github.com/concourse/docs/issues/267#issuecomment-546555199), and when trying to describe this case I realized there never actually was an error thrown.
* pure refactor, just changing a function signature
> atc: remove error from TaskStep.registerOutputs

- hack/trace
@huguesalary rightly observed that the script in this configuration is kinda unusable :grimacing::
https://github.com/concourse/concourse/pull/4593#issuecomment-547104894
* just a dev script, no code changes!
* adds the correct `-p` flag to docker
* bails with usage text if no service name is provided
* refactored a bit to ease my own mental model
> hack/trace: ensure dlv server port is forwarded

- atc/engine/builder/delegate_factory.go
- atc/engine/builder/delegate_factory_test.go
- release-notes/latest.md
Fixes #4656 .
When split a multi-line secrets by "\n", last element will be an empty string. We should not treat an empty string as a secret.
I can reproduce the bug in unit test, so I have updated the unit test as well.
> fix: fixed of bug of secret redaction. issue #4656

- release-notes/v5.7.0.md
> notes: add missing release notes for 5.7

- fly/commands/workers.go
- web/elm/src/Build/StepTree/StepTree.elm
- web/elm/src/Build/Styles.elm
- web/elm/tests/BuildStepTests.elm
We no longer planning to ship a v5.6.1 - instead we will just ship the relevant fixes in v5.7.0 and encourage an upgrade.
* reverting the last few commits on the branch
* just clean-up so that anybody referring back to this branch doesn't get confused
> rewind to v5.6.0

- atc/wrappa/compression_wrappa.go
- release-notes/v5.7.0.md
- testflight/download_cli_test.go
Fixes below error and progress bar displaying wrongly when running `fly sync`.
```
warning: failed to parse Content-Length: strconv.ParseInt: parsing "": invalid syntax
```
By https://github.com/concourse/concourse/pull/4470, the gzip handler removes `Content-length` during its process caused the above error
Skip gziphandler gzips `DownloadCLI` endpoint
> atc: skip gzip on download cli endpoint

- release-notes/v5.7.0.md
Release note for vault shared path bug.
> notes: add release note for vault shared path bug

- atc/config.go
- atc/task.go
- atc/validate.go
This PR mostly changes a few locations where we have empty slices assigned, into variable declarations that implicitly achieve the same thing but in a more Go idiomatic way. Also get rid of a constant that we don't use anymore.
> Small style fixes and remove an unused constant

- atc/db/build_factory.go
- atc/db/build_factory_test.go
No
As the subject, this bug causes `db.AllBuilds()` to return wrong builds, in turn causes the API `api/v1/teams/<team>/builds?timestamp=<unix time>` to return wrong builds if specified time is newer than all builds.
This bug also blocks my PR #4673.
* The bug is in function `getBuildsWithDates()`. If query by time returns no date, then the fucntion should just return rather than going on to call `getBuildsWithPagination`.
> fix(db): fixed a bug where if query builds with a date that newer than all builds, it should return nothing but it actually returned all builds.

- release-notes/v5.7.0.md
> notes: add 5.7.0 note about stalled worker gc

- release-notes/v5.7.0.md
adds a release note for fixing the builds api
> notes: wrong builds release notes for 5.7.0

- release-notes/v5.2.5.md
Although we got 5.2.5 (that addresses CVE-2019-17596) all tested and ready to ship in the release-5.2.x pipeline, we didn't have a release note about it.
* add a release note for 5.2.5
- ~Unit tests~
- ~Integration tests (if applicable)~
- ~Updated documentation (located at https://github.com/concourse/docs)~
> release-notes: add v5.2.5

- go.mod
- go.sum
v5.7.0 was released with a breaking change and no way to opt out. We can afford to more carefully consider how to extend the CF auth connector without excluding certain use cases.
* downgrade dex
> revert #4661

- topgun/k8s/baggageclaim_drivers_test.go
- topgun/pipelines/pipeline-that-fails.yml
Test to ensure real btrfs disk is cleaned up properly in the helm chart: https://github.com/helm/charts/issues/13284
The `initContainer` script in the helm chart should clean up the btrfs disk properly. If it does then this test passes.
A PR in helm/charts needs to be merged first, otherwise this test will fail.... forever....: ~~https://github.com/helm/charts/pull/12398~~
https://github.com/helm/charts/pull/14941
CC @pivotal-bin-ju
> [topgun/k8s] Add test that uses real btrfs disk

- atc/atccmd/command.go
- atc/config.go
- atc/worker/db_worker_provider.go
- atc/worker/db_worker_provider_test.go
- release-notes/latest.md
- worker/workercmd/worker.go
- worker/workercmd/worker_linux.go
- worker/workercmd/worker_nonlinux.go
Fixes #4652.
In some cases documented in the issue, we've seen evidence of the hardcoded 5 minute timeout being reached.
Rather than using a hardcoded timeout of 5 minutes for http requests to the Garden server, both from the web and from the workers, this PR makes this value configurable. From an operational perspective, operators should have greater flexibility to determine what constitutes  a reasonable timeout.
Note: This timeout is configured in both the web and the worker because they use independent garden clients for different reasons. The web's timeout represents the time that the web will wait for Garden to spin up a build container (the UI will turn orange when this timeout is hit); whereas the worker's timeout is used internally for sweeping unused containers.
and …
> atc/worker: make garden client timeout configurable

- atc/metric/emitter/newrelic.go
- atc/metric/emitter/newrelic_test.go
- release-notes/latest.md
Fixes #4540
This PR adds three flags to the NewRelic emitter:
- `CONCOURSE_NEWRELIC_BATCH_DURATION`
- `CONCOURSE_NEWRELIC_BATCH_SIZE`
- `CONCOURSE_NEWRELIC_COMPRESSION_DISABLED`
This change will allow users to adjust the batch size that the
NewRelic emitter uses with the `CONCOURSE_NEWRELIC_BATCH_SIZE` flag.
They can also adjust the frequency that data is emitted by
changing `CONCOURSE_NEWRELIC_BATCH_DURATION`.
We now compress the batch by default. Users can turn this off
by using the `CONCOURSE_NEWRELIC_COMPRESSION_DISABLED` flag.
This also includes the changes made by @xtreme-sameer-vohra in #4617 
CC: @pivotal-bin-ju @xtreme-sameer-vohra 
> This section is intended for the core …
> Add batching to new relic

- release-notes/v5.7.1.md
[#4699](https://github.com/concourse/concourse/pull/4699)
for v5.7.1 patch release
> Add release notes for dex downgrade

- atc/atccmd/command.go
- atc/config.go
- atc/worker/db_worker_provider.go
- atc/worker/db_worker_provider_test.go
- release-notes/latest.md
- release-notes/v5.7.1.md
- worker/workercmd/worker.go
- worker/workercmd/worker_linux.go
- worker/workercmd/worker_nonlinux.go
This contains two cherry-picked features from master, to go out as a v5.7.1 patch.
1. Revert the CF auth RBAC change
1. Add configurability for Garden client(s) HTTP timeout
> cherry-picking stuff over to 5.7.1 patch branch

- release-notes/v5.7.1.md
Release notes got out of sync between master and the 5.7.1 branch because of some merge conflicts and back-and-forth. This PR pulls the latest correct version of the v5.7.1 release notes into master.
> Keep release notes synced for 5.7.1

- hack/dlv/Dockerfile
by setting the EDITOR environment variable, and having `vim` installed,
we're able to jump from the view of a frame to the source code "like
magic"
- add `vim` to the image
- have `EDITOR` set to `vim` so that `dlv $ edit` uses it.
-  ~Unit tests~
-  ~Integration tests (if applicable)~
-  ~Updated documentation (located at https://github.com/concourse/docs)~
-  ~Updated release notes (located at
https://github.com/concourse/concourse/tree/master/release-notes)~
> hack: add `vim` to dlv image

- fly/commands/watch.go
- fly/integration/watch_test.go
Sometimes you just want to fire whatever you're looking at into the
console, and for that, the quickest way is `fly watch --url <Paste>`
Should work with both regular team/pipeline/job URLs and raw /builds/
URLs.
Signed-off-by: hfinucane <h.finucane@gmail.com>
> Support `fly watch --url`

- atc/db/build.go
- atc/db/build_event_source.go
- atc/db/build_factory.go
- atc/db/container_repository.go
- atc/db/job.go
- atc/db/job_factory.go
- atc/db/pipeline.go
- atc/db/pipeline_factory.go
- atc/db/resource.go
- atc/db/team_factory.go
- atc/db/volume_repository.go
- atc/db/volume_repository_test.go
- atc/db/worker.go
- go.sum
- release-notes/v5.2.5.md
cherry picking fix of #4373  from master to 5.2.x. Should solve customer problem that many dashboards opened that satuated the API connection pool to DB causes huge memory usage that will eventually fail the web node.
> Use transaction instead of open connection for api queries

- topgun/common/common.go
- topgun/deployments/concourse.yml
Currently for our newer release pipelines that have the refactored
version of bosh topgun (5.7.x), when we want to run all test suites we
don't specify `SUITE` and run `ginkgo` with the recursive flag. This
allows us to run all topgun suites.
The problem, that this commit resolves, is that the release referened in
the deployment yaml gets the wrong name. By moving the `-` out of the
deployment yaml, the naming will now be correct.
From CI we currently get this error:
```
Task 26668 | 19:56:13 | Error: Release 'concourse-' doesn't exist
```
because `concourse-((suite))` resolves to `concourse-` because `SUITE`
is empty. Now this commit appends the dash as part of the `((suite))`
variable.
> [release/5.7.x] Allow topgun to run all tests suites

- topgun/common/common.go
- topgun/deployments/concourse.yml
Currently for our newer release pipelines that have the refactored
version of bosh topgun (5.7.x), when we want to run all test suites we
don't specify `SUITE` and run `ginkgo` with the recursive flag. This
allows us to run all topgun suites.
The problem, that this commit resolves, is that the release referened in
the deployment yaml gets the wrong name. By moving the `-` out of the
deployment yaml, the naming will now be correct.
From CI we currently get this error:
```
Task 26668 | 19:56:13 | Error: Release 'concourse-' doesn't exist
```
because `concourse-((suite))` resolves to `concourse-` because `SUITE`
is empty. Now this commit appends the dash as part of the `((suite))`
variable.
> Allow topgun to run all tests suites

- topgun/common/common.go
Same problem that #4764 tried to fix
I just moved where the issue occurred in the last commit. Needed logic
around what `suite` should be equal to.
> [release/5.7.x] Fix topgun for release pipeline

- topgun/common/common.go
Same problem that #4764 tried to fix
I just moved where the issue occured in the last commit. Needed logic
around what `suite` should be equal to.
> Fix bosh-topgun for concourse pipeline

- topgun/operations/add-other-worker.yml
- topgun/operations/bbr-concourse-link.yml
- topgun/operations/bbr-with-properties.yml
Some tests in bosh topgun are still failing because they use these
ops-files which still have the hyphen.
I should have looked at the commit where `SUITE` was introduced to
ensure I covered everything. This commit catches everything that was
missed and I checked the commit where `SUITE` was introduced to 
ensure nothing else will come up because of this change.
> [release/5.7.x] Remove hyphens from ops-files for bosh topgun

- topgun/k8s/k8s_suite_test.go
since we are now using concourse/concourse-chart.
We would need to have this fix for all our release branches otherwise the job there won't work.
> fix k8s topgun test charts path

- worker/workercmd/containerd.go
Without the constraint, `concourse` will simply not compile as such file
contains constructs only present in `linux`-based compilations.
Also, given that at the moment we're focusing solely on the linux
implementation, there's no need to bother about the other cases (darwin
& windows).
e.g., on Windows:
unknown field 'Pdeathsig' in struct literal of type
syscall.SysProcAttr Error: exit status 2
ref: https://golang.org/pkg/go/build/#hdr-Build_Constraints
add `linux` build constraint on `containerd.go` under `workercmd` pkg.
- ~Unit tests~
- ~Integration tests~
- ~Updated documentation (located at https://github.com/concourse/docs)~
- ~Updated release notes (located at …
> worker: add build constraints to `containerd.go`

- web/elm/src/Application/Application.elm
- web/elm/src/Dashboard/Dashboard.elm
- web/elm/tests/SideBarFeature.elm
Helps #4372, #4646, #4482 & #2776.
This follows up on @pivotal-jamie-klassen and @zoetian work to reduce the number of API calls issued from the dashboard page. It remove the duplicated call to `/api/v1/pipelines` that take place every 5 seconds.
* Replaces the duplicated call to `fetchPipelines` by forwarding the list of pipelines received from `fetchData` to the sidebar.
* Fix tests accordingly
Note: This is my first experience with elm, so don't be afraid to point out stupid issues with my changes.
Thanks to @aledeganopix4d, @marco-m and @wagdav for the help!
> Dashboard fetch pipelines once

- atc/engine/builder/delegate_factory.go
- atc/engine/builder/delegate_factory_test.go
Fixes #4749.
This is a quick change to only redact secrets whose lengths are longer than 1.
> Don't redact single-char secret. mitigate #4749.

- atc/atccmd/command.go
- cmd/concourse/main.go
Fixes #4731 .
concourse cmd with `--help` exit with status code 1
Follow what fly cli is doing, handle error and exits with 0 if it is a help error
> Handle help error in concourse cmd properly

- atc/db/build.go
- atc/db/build_test.go
- atc/db/pipeline_factory_test.go
- atc/db/pipeline_test.go
- atc/scheduler/runner.go
- testflight/download_cli_test.go
Adopting rerun build inputs and pipes should also flip inputs ready to
be true.
> Rerun build inputs and pipes should make inputs ready be true

- atc/db/worker_factory.go
There is no where in our code where `tagsMatch` from the `db` package is being used (not even tests), making this method essentially unnecessary.
- remove `db/tagsMatch`
-  ~Unit tests~ 
- no new functionality or code previously tested changed
- ~Integration tests (if applicable)~ 
- (same as ^)
-  ~Updated documentation (located at https://github.com/concourse/docs)~ 
- no changes in functionality or behavior
- ~Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)~ 
- just internal refactoring
> atc: eliminate unused `tagsMatch` method

- web/elm/benchmarks/Benchmarks.elm
- web/elm/src/Build/Build.elm
- web/elm/src/Build/Header/Header.elm
- web/elm/src/Build/Header/Models.elm
- web/elm/src/Build/Models.elm
- web/elm/src/Message/Callback.elm
- web/elm/src/Message/Effects.elm
- web/elm/src/SideBar/SideBar.elm
- web/elm/tests/Build/HeaderTests.elm
- web/elm/tests/BuildTests.elm
- web/elm/tests/Common.elm
- web/elm/tests/SideBarFeature.elm
I'm pretty sure this field was added as a correlation ID for parallel in-flight requests to fetch builds or plans. From my manual testing I've validated that it seems no longer to be possible to have multiple in-flight requests to those endpoints - pressing 'H' and 'L' doesn't do anything until the page has loaded.
* remove browsingIndex from Build Model
* remove browsingIndex from build/plan fetching effects/callbacks
* just a refactor, but might be worth some cursory checks for regressions
> web: remove browsingIndex from Build page

- worker/container_sweeper.go
- worker/container_sweeper_test.go
This adds a regression test to validate that container sweeper doesn't block when the garden client is configured with a timeout.
Note: This test just validates the non-blocking functionality if the timeout is configured. It doesn't validate that the configuration utilized by the worker includes a timeout.
Enhances #4582
Demonstrate that container sweeper is non-blocking when gardenClient calls hang and GC doesn't stop occurring in this event
Adds container_sweeper test
> Test for container sweeper ctx timeout

- go.mod
- go.sum
- release-notes/v5.7.2.md
This backports #4804 to the v5.7.x line.
> bump golang.org/x/crypto

- topgun/k8s/external_postgres_test.go
- topgun/k8s/k8s_suite_test.go
- topgun/k8s/prometheus_test.go
the chart directory of the new chart (https://github.com/concourse/concourse-chart.git) starts from the root directory, so the hardcoded `stable/concourse` is not needed anymore.
We do still rely on some charts from the `helm/charts` repo, so the `CHARTS_DIR` was renamed to `HELM_CHARTS_DIR`.
Related to https://github.com/concourse/ci/pull/200
The `topgun` testsuite hardcoded the chart directory `stable/concourse`. the new chart directory starts from root of the repo https://github.com/concourse/concourse-chart.git
Fixes https://github.com/pivotal/concourse-ops/issues/117
It is mandatory if we migrate concourse helm chart to the new repo.
remove the hardcoded chart path `stable/concourse`, since the new chart is hosted at the root directory.
and [Helm](https://github.com/concourse/helm) …
> Adopt the new concourse helm chart repo.

- release-notes/latest.md
https://github.com/concourse/registry-image-resource/pull/79
@vito pushed a fix to the retryer logic in registry-image. He found that a retryer via the transport messed up some invisible digest calculation.
> add release notes for registry-image invalid digest fix

- atc/lidar/scanner.go
Fixes #4807
The bug causes ATC to intermittently crash.
Problem code is:
```go
for _, resource := range resources {
waitGroup.Add(1)
go func(resource db.Resource, resourceTypes db.ResourceTypes) {
defer waitGroup.Done()
err = s.check(resource, resourceTypes) // The bug is here!!!
s.setCheckError(s.logger, resource, err)
}(resource, resourceTypes)
}
```
All go routines share the caller function's variable `err`, so that there is a race condition against `err` over all go routines. The fix is simple, just change the go routine to use a local `err`, which will avoid race condition.
> fill out …
> bug: fixed a lidar bug that caused ATC crash.

- atc/engine/builder/delegate_factory.go
- atc/engine/builder/delegate_factory_test.go
- vars/vars_tracker.go
Fixes #4799 .
When secret redaction is not enabled, use `newDBEventWriter` to create stdout and stderr.
> fix(atc): when secret redaction is not enabled, should not buffer build log lines

- vars/vars_tracker.go
Fixes #4845  .
Without this fix, ATC with secret redaction may crash.
This is a lock for read/write accessing the var tracker map, but unfortunately we copied the lock, which made the lock to not really work. The fix is just to change to use pointer.
> fix(atc): fixed a crash from credVarsTracker.

- atc/exec/in_parallel.go
- atc/exec/in_parallel_test.go
- release-notes/latest.md
Fixes #4746 
The way concourse handles errors from in parallel steps does not capture wrapped context.Canceled
Based on https://github.com/golang/go/blob/master/src/net/url/url.go#L22-L28 and https://github.com/golang/go/blob/master/src/net/http/client.go#L702
use `errors.Is` for error comparison
> atc: handle wrapped context canceled error

- CONTRIBUTING.md
When using the original command in `CONTRIBUTING.md` on macOS and a Linux container
I was getting a few errors:
```
$ go build atc/db/migration/cli -o mig
can't load package: package atc/db/migration/cli: malformed module path "atc/db/migration/cli": missing dot in first path element
can't load package: package -o: malformed module path "-o": leading dash
can't load package: package mig: malformed module path "mig": missing dot in first path element
```
The updated command successfully compiles the cli app on macOS and Linux.
Trying to remove any developer friction.
> Update steps for creating a migration

- tsa/README.md
- tsa/commands.go
- tsa/tsacmd/remote_cli.go
- tsa/tsacmd/server.go
> #4566: removed register-worker command from tsa

- fly/integration/fixtures/team_config_empty_users.yml
- fly/integration/set_team_test.go
- skymarshal/skycmd/flags.go
Fixes #4852 .
Just silently discard roles that have no user and group.
This is a pure `fly` side change, data sent to the server side is not changed at all.
> fix(fly): set-team discards roles with no user and group from team config file.

- fly/commands/internal/hijacker/hijacker.go
- fly/integration/hijack_test.go
Fixes #4849 
Showing err when hijack fail is not enough for debugging
Show response status as well. So if an viewer wants to hijack into a container the error would be `403 Forbidden websocket: bad hanshake`. It would be obvious that it is about authorization failure.
> fly: show status of websocket dial when hijack err

- atc/exec/set_pipeline_step.go
- release-notes/latest.md
This PR adds a warning message to the `set_pipeline` step, which can be removed when its RFC, concourse/rfcs#31 is resolved.
I also added release notes, which include a refresher on the v10 roadmap and where the `set_pipeline` step lives within it.
I'll submit another PR to the docs repo which documents the `set_pipeline` step and marks it as "experimental".
/cc @evanchaoli 
* adds warning
* adds release notes
> set_pipeline warning + release notes

- worker/backend/integration/Dockerfile
- worker/backend/integration/README.md
- worker/backend/integration/start.sh
- worker/backend/spec/spec.go
This commit adds a Dockerfile and readme to the integration test folder for the new containerd track of work, because running integration tests with a real containerd daemon is better to do in a sandboxed environment like Docker.
Note: The pipelines are not yet set up to run these tests, we should perform this integration when this track of work is further along.
Addresses #4850
> worker: Add Dockerfile to run integration tests locally

- fly/commands/login.go
- fly/integration/login_test.go
- release-notes/latest.md
Fixes #4587 .
This PR solve the issue #4587.  When the the super admin login without providing the CACert after the first successful login, the CACert will be loaded from `.flyrc`.
> fixes #4587 when cert is not given, super admin loads the cert from `.flyrc`.

- atc/metric/metrics.go
Signed-off-by: kyrylo.bilchenko <kirya7@gmail.om>
Fixes # .
Fixes #3856
> fix worker state default metric value

- topgun/k8s/baggageclaim_drivers_test.go
- topgun/k8s/container_limits_test.go
- topgun/k8s/dns_proxy_test.go
- topgun/k8s/ephemeral_worker_test.go
- topgun/k8s/external_postgres_test.go
- topgun/k8s/external_worker_test.go
- topgun/k8s/garden_config_test.go
- topgun/k8s/https_web_tls_termination_test.go
- topgun/k8s/k8s_suite_test.go
- topgun/k8s/kubernetes_creds_mgmt_test.go
- topgun/k8s/mainteam_role_test.go
- topgun/k8s/prometheus_test.go
- topgun/k8s/rebalance_test.go
- topgun/k8s/tsa_node_port_test.go
- topgun/k8s/web_scaling_test.go
- topgun/k8s/worker_lifecycle_test.go
Back-porting #4643, which adds the `IN_CLUSTER` parameter. Currently k8s-topgun in the 5.5.x release pipeline has test failures related to [port-forwarding breaking](https://nci.concourse-ci.org/teams/main/pipelines/release-5.5.x/jobs/k8s-topgun/builds/10#L5de9362c:21684). The entire test suite does pass because now we use ginkgo's [`--flakeAttempts` flag](https://github.com/concourse/ci/blob/43d09072d69eeecafd547596a0e608bc9941e184/tasks/scripts/k8s-topgun#L28).
> 5.5.x - Add k8s IN_CLUSTER param

- atc/db/check.go
- atc/db/check_factory.go
- atc/db/check_lifecycle.go
- atc/db/check_lifecycle_test.go
- atc/db/check_test.go
- atc/db/db_suite_test.go
- atc/db/dbfakes/fake_check_lifecycle.go
- atc/db/dbfakes/fake_checkable.go
- atc/db/dbfakes/fake_resource_type.go
- atc/db/resource_type.go
- atc/db/resource_type_test.go
- atc/engine/engine.go
- atc/engine/engine_test.go
- atc/exec/check_step.go
- atc/gc/checks_collector.go
- atc/lidar/checker.go
- atc/lidar/scanner.go
- atc/metric/emitter/newrelic.go
- atc/metric/emitter/prometheus.go
- atc/metric/metrics.go
- atc/metric/periodic.go
Fixes #4554
So we could have metrics available when Lidar is enabled.
Added below metrics for Lidar
- `check_started`
- `check_finished`
- `check_enqueue`
- `check_queue_size`
- `checks_deleted`
> Adding lidar metrics

- release-notes/v5.8.0.md
Part of #4859.
* no code changes, just release notes
> Add release notes for v5.8.0

- atc/atccmd/command.go
- atc/atccmd/command_test.go
- go.mod
- go.sum
- release-notes/v5.5.7.md
original PRs: https://github.com/concourse/concourse/pull/4804, https://github.com/concourse/concourse/pull/4869
> backport let's encrypt bump + default fix to 5.5.x

- atc/auditor/auditor.go
- atc/auditor/auditor_test.go
Implements #4854 
Modified ValidateAction to panic when route is not handled. Removed the loggingLevels map and explicitly listed out all of the cases in ValidateAction so that it is more obvious that new routes need to be added in the switch case.
> Panic when route is unhandled in auditor

- topgun/k8s/mainteam_role_test.go
The next version of the chart makes the ConfigMap for you. The test can
now pass in the YAML for the main team instead of manually making the
ConfigMap first.
k8s-topgun will break when the next major version of the chart is released because the expected value of `mainTeam.config` has changed: https://github.com/concourse/concourse-chart/pull/33#pullrequestreview-332844796
I locally ran this test on the `topgun` GKE cluster and it passed.
> Update main team config test

- worker/backend/backend.go
- worker/backend/backend_test.go
- worker/backend/integration/README.md
- worker/backend/libcontainerd/client.go
This PR incorporates code review feedback from #4784, refactors out error types, and adds additional edge case handling to the runtime backend. Some interface methods are not yet implemented (`BulkInfo`, `BulkMetrics`, `Lookup`, and `GraceTime`) because they either read properties of a concrete implementation of the Garden `Container` interface, or they need to return this concrete type. That work will be delivered after #4877.
Everything is behind a feature flag that isn't exposed yet in any packaging, so is safe to continuously merge into master.
Addresses #4783 .
* Create backend error types that can wrap client-side errors 
* Use context with timeout for all function calls that cross the backend/client boundary
* Add more error checks for Destroy edge cases
* Add godocs for backend …
> Improve containerd implementation of Garden backend interface methods

- topgun/k8s/mainteam_role_test.go
Reverts #4915
I'll change how helm-prs work to this:
- `helm-prs` will use `master` of concourse/concourse
- `helm-prs-5.7.x` will use `release/5.7.x` of concourse/concourse
and so on...
> Revert "Update main team config test"

- release-notes/v5.2.6.md
- Adds release notes for 5.2.6
> Release notes 5.2.6

- release-notes/v5.7.3.md
- Adds release notes for 5.7.3
> update relase-notes for 5.7.3

- topgun/k8s/container_limits_test.go
- topgun/k8s/k8s_suite_test.go
5.5.x is the older version of k8s-topgun where all of topgun hasn't been
broken into smaller packages. Therefore there were some incompatibilities
when backporting the IN_CLUSTER param
Tested that it works by running `ginkgo -dryRun ./topgun/k8s/`
> Fix the backport of IN_CLUSTER param for k8s-topgun

- topgun/k8s/https_web_tls_termination_test.go
- looks like some structuring has made the k8s topgun folder structure different leading to the failure of one of the tls termination tests.
> Fix k8s topgun 5.5.x

- atc/creds/vault/manager.go
The value is a map, so it should be plural. the flag is singular because you pass it once per param.
This code hasn't shipped yet so this is 'no impact'. Just a quick fix. Noticed this while writing docs.
* `auth_param` -> `auth_params`
There is currently no test coverage for this stuff. Maybe we can tackle that once we add coverage for these in a testflight-style suite? :thinking: I've added a note here: https://project.concourse-ci.org/projects/MDc6UHJvamVjdDI5OTk2OTQ=
> atc: rename auth_param config to auth_params

- atc/api/info_test.go
- atc/creds/vault/api_client.go
- atc/creds/vault/manager.go
- atc/creds/vault/manager_factory.go
- atc/creds/vault/manager_test.go
- atc/creds/vault/reauther_test.go
- go.mod
- go.sum
Fixes #4934.
Fixes #4935.
* leverage mapstructure for type validation and coercion
* take literal values for ca/client cert/key instead of file paths
* backfill unit tests
> redo vault var source config flow

- atc/db/migration/migrations/1575922657_version_md5_resource_cache.down.sql
- atc/db/migration/migrations/1575922657_version_md5_resource_cache.up.sql
- atc/db/pipeline.go
- atc/db/resource_cache.go
- atc/db/resource_cache_factory.go
- atc/db/resource_cache_factory_test.go
- atc/db/resource_cache_lifecycle.go
- atc/db/versions_db.go
- atc/db/volume.go
- atc/db/volume_test.go
look up by version_md5 (text)  is faster than version (jsonb) 
added `version_md5` column to `resource_caches` table. Use version_md5 when quering.
> add version_md5 to resouce_cache table

- atc/atccmd/command.go
Renaming the max jobs in flight ATC flag to job scheduling max in flight in order to be more explicit with the purpose of the flag. This was raised because of this comment https://github.com/concourse/concourse/issues/4351#issuecomment-556037324.
> Rename job max in flight flag

- atc/worker/worker.go
- atc/worker/worker_test.go
- release-notes/v5.8.0.md
fixes #4932
In `atc/worker/worker.go`'s garden's FindOrCreateContainer
implementation, there's an early return for the case when the error
returned in that creation is of a specific kind, but not for other
possible errors that could happen.
That meant that any error other than that specific one would lead to a
NPE as further steps would rely on a non-nil return.
These changes fix that by actually returning the err, making further
assumptions on "not being nil" not problematic anymore.
* add a `return` with the non-specific err
- ~Integration tests (if applicable)~
- ~Updated documentation (located at https://github.com/concourse/docs)~ not user-facing
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration …
> atc: fail in non-specific error in db container creation

- testflight/volume_mounting_test.go
We are going to pend this failing testflight test for now until it gets resolved, the issue is unrelated to any concourse code changes and is blocking PR pipelines from running.
> Temporary pend failing testflight test

- atc/db/migration/migrations/1575922657_version_md5_resource_cache.down.sql
- atc/db/migration/migrations/1575922657_version_md5_resource_cache.up.sql
- atc/db/resource_cache.go
to avoid trouble when running down migration if version can not be found for given version_md5
it will be used only when inserting.
> add version column back to resource_caches

- web/elm/benchmarks/Benchmarks.elm
- web/elm/src/Application/Application.elm
- web/elm/src/Build/Build.elm
- web/elm/src/Build/Header/Header.elm
- web/elm/src/Build/Header/Models.elm
- web/elm/src/Build/Models.elm
- web/elm/src/Concourse.elm
- web/elm/src/Message/Callback.elm
- web/elm/src/Message/Effects.elm
- web/elm/tests/Build/HeaderTests.elm
- web/elm/tests/BuildTests.elm
Fixes #4962.
The bug was observed in cases where you triggered a new build -- it turns out the important part of this flow was simply viewing a pending build. In such cases, the UI polls the GetBuild and GetBuildPrep endpoints with a 1-second delay. It is quite possible that, during this delay, the user will switch tabs and view a different build. Then, after the delay, the app will receive callbacks containing the build/prep for the pending build that was originally viewed. It is necessary to gracefully handle this data without displaying invalid or irrelevant data.
The fix ended up being to carefully ignore messages containing data from irrelevant builds - including build events being received and build/prep being fetched. This replaces the old `browsingIndex` method and has better (but …
> web: fix build-history-tab-switching bug

- release-notes/v5.8.0.md
Final checkbox in https://github.com/concourse/concourse/issues/4859#issue-534024173.
* Added a release note with a link to the new docs (which will be deployed after v5.8.0 ships)
* A bit more detail in the `--config-rbac` release note too
> add release note for `var_sources`

- atc/metric/emitter/prometheus.go
- release-notes/latest.md
before this change the build_duration metrics exposed to prometheus are not very useful to us, as it bundles
together all builds across an entire pipeline. Since a build duration from one
job is usually very distinct from a build of another job, bundling them
together makes it hard to extract useful information such as:
* Which job(s) in the pipeline are performing badly?
* Under what conditions cause job A to perform badly?
Or create alerts/indicators based on the metric such as:
* Job X should always run within Y minutes
By allowing the build_durations metric to contain the job label, these
things become possible.
* includes the job name as a label in build_duration metrics exposed to
prometheus so that it is possible to gain insights into where time is
being spent in a complex …
> job label for prometheus build_duration metrics

- release-notes/v5.8.0.md
`var_sources` is early in its development, and we should not give Concourse users the impression that it is operationally stable or that we will guarantee backwards compatibility in its future configurations.
* Just a release note change
> notes: warn that var_sources is experimental

- topgun/both/atc_shutdown_test.go
- topgun/both/hijack_container_gc_test.go
- topgun/both/image_resource_gc_test.go
- topgun/both/worker_landing_test.go
- topgun/both/worker_stalling_test.go
- topgun/core/containers_scoped_to_team_test.go
- topgun/core/syslog_test.go
- topgun/core team test
- topgun/both worker land test
- topgun/both image resource gc test
- topgun/both worker stalling test
- topgun/both atc shutdown test
- topgun/both hijack container gc test
We encountered a bunch of race conditions when working on the [runtime refactor](https://nci.concourse-ci.org/teams/main/pipelines/runtime-refactor/jobs/bosh-topgun), where tests were blocked indefinitely till the 24h global timeout. 
This PR addresses the common patterns we observed when the tests got into a deadlock
- wrapping attempts to hijack with an Eventually
- adding an additional assertion when waiting for a script to start executing to ensure it had indeed started rather than just being in initializing state
> Are the following items included as part of this PR? Please delete checkbox …
> Fix flakey topgun tests

- README.md
N/A
The helm chart installation link under Quick Start still points to the deprecated helm chart location.
Update the link to https://github.com/concourse/concourse-chart
> Update Quickstart Helm Chart Installation Link to New Location

- atc/exec/build/repository_test.go
Addresses @deniseyu's  comment in https://github.com/concourse/concourse/pull/4825
- unit test had a false positive with first_artifact == second_artifact
due to the way fakes were compared
- refactored variable names to be clearer
- [x ] Unit tests
> Fix repository_test.go

- atc/db/job.go
- atc/db/migration/migrate_job_configs_to_job_pipes_test.go
- atc/db/migration/migrations/1576696018_migrate_job_configs_to_job_inputs_and_outputs.up.go
- atc/engine/engine.go
- atc/engine/engine_test.go
This PR includes two bug fixes:
1. Concourse v6.0 expects all types of serial groups to be in the `jobs_serial_groups` table but prior to it, there was a bug where only one type of serial group was inserted into that table on set pipeline. This PR includes a migration that will move over all the serial groups into the table.
2. We will now error and finish a check step if it fails when it is being created in the engine. This was added in order to avoid cases where creating a check step will never succeed because it has outdated information in it's metadata.
> Migrate all types of serial groups and error checks that fail to create check step

- atc/scheduler/interval_runner.go
- atc/scheduler/runner.go
- atc/scheduler/runner_test.go
- go.mod
- go.sum
The scheduler will now wait for all the jobs to finish scheduling before
it will run another tick. This change was made to make sure that we
don't stampede the same jobs to schedule if the environment is being
slow to finish scheduling.
fixes #5022
> Wait for all jobs to finish scheduling

- atc/db/build.go
- atc/scheduler/build.go
- atc/scheduler/buildstarter.go
- atc/scheduler/buildstarter_test.go
Schedule rerun builds separate from regular scheduler builds (and
manually triggered) so that if a rerun build cannot find its inputs, it
will not result in blocking the scheduler for that job.
fixes #4960
> Schedule rerun builds separately

- atc/db/migration/migrations/1579207767_alter_parent_id_constraint_on_volumes.down.sql
- atc/db/migration/migrations/1579207767_alter_parent_id_constraint_on_volumes.up.sql
- atc/db/volume_repository.go
- atc/db/volume_repository_test.go
Fixed the RemoveMissingVolumes GC query to be able to garbage collect missing volumes that are referenced by other volumes.
> Garbage collect missing parent volumes along with it's child volumes

- worker/backend/backend.go
- worker/backend/backend_test.go
- worker/backend/container.go
The source needed to be formatted.
Giving the source formatting its own PR will make further PRs easier to at a glance figure out the really valuable changes.
**there are no behavior our actual significant source changes in this PR**
- format all `worker/backend` files (`containerd`-related source code)
- update import order
- ~[ ] Unit tests~
- ~[ ] Integration tests (if applicable)~
- ~[ ] Updated documentation (located at https://github.com/concourse/docs)~
- ~[ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)~
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration …
> worker/backend: source formatting

- atc/db/migration/migrations/1575922657_version_md5_resource_cache.down.sql
- atc/db/migration/migrations/1575922657_version_md5_resource_cache.up.sql
- atc/db/volume.go
Switch to using the version column in resource caches within the code because there can be cases where the resource config version does not exist for a resource cache (for example, with image resources we never save its versions into the database as a resource config version)
> Use version column in resource caches

- fly/commands/pause_pipeline.go
- fly/commands/unpause_pipeline.go
- fly/integration/pause_pipeline_test.go
- fly/integration/unpause_pipeline_test.go
- will pause and unpause all pipelines
before making changes to my concourse I like to pause every pipeline so I don't get stuck in a state where a worker starts to drain, and the change can happen more quickly. I wrote some hacky bash to make this happen but I thought it would be nice to add it into fly as a first class feature.
Signed-off-by: Josh Zarrabi <jzarrabi@pivotal.io>
> adds '--all' to the pause and unpause commands

- atc/db/job_factory.go
- atc/db/resource_cache.go
- atc/db/resource_cache_factory.go
- atc/db/resource_cache_factory_test.go
Order the passed jobs before aggregating them. Fixes a flaky test (https://ci.concourse-ci.org/teams/main/pipelines/release-6.0.x/jobs/unit/builds/26) that expects them to be ordered a certain way every time.
Also added back version to resource cache object in order to get the code to compile. It seems to have broke with the removing of resource cache version commit (https://github.com/concourse/concourse/commit/fc805aa8a76a354b465a028c9a3e5352734df235#diff-aec4784b5c20d59cb9d946e4a4752ca1)
> Order passed jobs for dashboard job inputs

- atc/db/worker.go
- atc/metric/metrics.go
- atc/metric/metrics_test.go
Fixes #4985.
The key change is to ensure that 0 values for state counts are emitted. I have a bit of a concern around the scalability of this - before this change we only emitted metrics for states where the count of workers was greater than zero, but now we're guaranteed 5 worker state metric events every tick. I guess a typical healthy cluster probably tends to have all running workers most of the time, so this could effectively mean 5 times as many worker state metrics events.
I don't know what the typical "utilization rate" of the metrics queue is (like how many events tend to be queued up as a proportion of the max length and in particular the typical proportion of the queue's max length that are worker state metrics), but if a cluster has a tendency to get that "queue-full" error I …
> atc: always emit a metric for each worker state

- CONTRIBUTING.md
- hack/overrides/prometheus.yml
in the same way that we can have jaeger configured locally, we could do
the same for Prometheus.
here I introduce an override file that when tied together with the base
docker-compose file, brings Prometheus already pointing at
Concourse.
add docker-compose override file that contains the config to target concourse.
> hack: add prometheus docker-compose override file

- topgun/fly.go
- topgun/k8s/https_web_tls_termination_test.go
I remember having seen failures like https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/61 in the tls termination tests a few times before, so we decided to investigate a little.
We noticed that these test cases were not making use of the same retry logic built into the `Login` helper function - so we extended that function to handle arbitrary extra arguments to `fly login` and reused it in the tls termination tests.
So now those tests will also retry logging in, allowing us to wait more gracefully for the web node to handle login requests.
> topgun/k8s: improve tls termination flake

- atc/db/versions_db.go
- atc/scheduler/algorithm/algorithm_test.go
- atc/scheduler/algorithm/compute.go
- atc/scheduler/algorithm/table_helpers_test.go
Context is in https://github.com/concourse/concourse/issues/5063#issuecomment-579337229
> previously, there was a good chance that the 'outputs over inputs'
> behavior of the algorithm would be lost due to a sort.Slice call which
> was not exhaustive and could therefore result in the order shifting for
> versions belonging to the same resource
* order only by resource ID, preserving order of the resource's versions present in the db
* expand test to make use of more inputs so that it has a higher chance of demonstrating the issue
* run test for 100 iterations
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that …
> atc algorithm: fix non-deterministic version order

- atc/builds/tracker.go
- atc/builds/tracker_test.go
- go.sum
rather than unconditionally firing off a goroutine for each in-flight
build (which then locks and short-circuits if the build is already
tracked), only do so if we don't have a goroutine for it already.
n/a
This PR attempts to address a gradual increase in memory utilization observed in the `algorithm` environment, which is current creating ~25k builds per hour and can have ~1,000 builds running at a time.
Heap dumps don't seem to account for the used memory reported by the OS, so the working theory is that it's being used on the stack, probably through goroutines that are leaking or "piling on" through periodic things like the build tracker and job scheduler. The scheduling pile-on situation was addressed in #5025.
* Keep track of builds …
> atc: fix piling on build tracking

- atc/api/accessor/handler_test.go
This PR fixed a nit typo, making the code better.
> nit: fix a typo.

- atc/db/build_test.go
- atc/db/dbfakes/fake_check_lifecycle.go
- atc/db/dbfakes/fake_conn.go
- atc/db/dbfakes/fake_tx.go
- atc/db/open.go
- atc/db/versions_db.go
- atc/db/versions_db_test.go
- atc/scheduler/algorithm/compute.go
- atc/scheduler/algorithm/firstoccurrence_test.go
- atc/scheduler/algorithm/group_resolver.go
- atc/scheduler/algorithm/individual_resolver.go
- atc/scheduler/algorithm/input_mapper.go
- atc/scheduler/algorithm/pinned_resolver.go
- atc/scheduler/algorithm/regression_test.go
- atc/scheduler/algorithm/resolver.go
- atc/scheduler/algorithm/suite_test.go
- atc/scheduler/algorithm/table_helpers_test.go
- atc/scheduler/build.go
- atc/scheduler/buildstarter.go
- atc/scheduler/buildstarter_test.go
- atc/scheduler/runner.go
- atc/scheduler/runner_test.go
- atc/scheduler/scheduler.go
- atc/scheduler/scheduler_test.go
- atc/scheduler/schedulerfakes/fake_algorithm.go
- atc/scheduler/schedulerfakes/fake_build_scheduler.go
- go.mod
Fixes #5094.
The actual bugfix here isn't captured in a separate issue, but there is (some) context in https://github.com/concourse/concourse/issues/5063#issuecomment-580271863.
A bug with the algorithm's pagination logic (used for walking over chunks of 100 builds at a time) caused it to get stuck in a loop when looking for builds prior to a rerun.
This PR slings a bunch of code around in service of introducing tracing, which allowed this issue to be discovered and diagnosed pretty easily!
* fix pagination bug
* backfill unit tests for `VersionsDB` covering this scenario and a few others
* introduce tracing, and the ability to use tracing for algorithm tests
* threads `ctx` through `VersionsDB` and uses it to trace the incremental migrations
* adds support for `context.Context` in our …
> algorithm: fix pagination of rerun builds, add tracing

- atc/atccmd/command.go
`RunCommand.ResourceTypeCheckingInterval` is not used anywhere, in other words, `concourse web` CLI option `--resource-type-checking-interval` doesn't take effective at all.
Leaving this option would make users confused, why it's configured but no any effect?
In the mean time, it's also a breaking change. Those `concourse web` commands that has `--resource-type-checking-interval` option will fail. I think which is not bad, because which forces users to remove a useless option.
A single line code deletion.
and [Helm](https://github.com/concourse/helm) packaging; …
> Remove unused CLI option resource-type-checking-interval.

- web/elm/src/Dashboard/Dashboard.elm
- web/elm/src/Dashboard/Filter.elm
- web/elm/src/Dashboard/Group.elm
- web/elm/tests/DashboardSearchTests.elm
Fixes #5107.
* Makes sure that pipelines actually get filtered based on the user's input, and makes sure that the filtering algorithm uses the correct jobs.
> web: fix dashboard filtering

- atc/scheduler/runner.go
- atc/scheduler/runner_test.go
Fixes #5092.
Currently, if a job reveals a regressive performance case with the new algorithm, that will prevent all other jobs from scheduling.
We originally made scheduling not wait, but that led to piling on and scheduling the same job a bunch of times concurrently if it took more than the scheduler tick interval.
Instead of waiting for all the jobs to complete scheduling within the tick, just prevent scheduling the same job by keeping track of them in a `*sync.Map`.
There is further refactor opportunity here, captured in #5122 and #5123.
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed …
> scheduler: don't wait on jobs completing

- atc/exec/get_step.go
- atc/exec/get_step_test.go
- atc/exec/put_step.go
- atc/exec/put_step_test.go
- atc/exec/task_step.go
- atc/exec/task_step_test.go
- atc/runtime/types.go
- atc/worker/client.go
- atc/worker/client_test.go
- atc/worker/container.go
- atc/worker/fetch_source.go
- atc/worker/fetch_source_test.go
- atc/worker/gclient/connection/connection.go
- atc/worker/workerfakes/fake_client.go
Fixes #4969  .
This cleans up the return results form client.RunXStep funcs. Previously they used values such as -1 exit code to indicate concourse errors which didn't fit go paradigms and just were'n't that transparent.
> Newputget error cleanup

- release-notes/latest.md
- web/elm/src/Dashboard/Group/Tag.elm
- web/elm/tests/DashboardTests.elm
Fixes #4399.
It's possible to configure a team's auth such that a single user might have multiple roles - for example, if you grant "viewer" status to all members of a GitHub org, but "member" status to members of a specific GitHub team within that org. The UI only shows a single role in the pills on the team headers on the dashboard. The choice of which role to show was, until now, determined by whatever the API put first in the list of roles returned by the userinfo endpoint.
Users have justifiably found this confusing or misleading, and it generally seems sensible to show the most-privileged role a user has on any given team, since roles are in a strict hierarchy and the most-privileged role will be the one that determines the actions a user is authorized to take. 
With this change, …
> web: show most-privileged role on team pills

- atc/api/present/dashboard.go
- atc/dashboard_job.go
- atc/db/job_factory.go
- atc/db/job_factory_test.go
- atc/db/pipeline.go
- atc/db/pipeline_test.go
Fixes #5129.
The output resources no longer show up in the pipeline UI page. This was because the outputs were removed from the DashboardJobs response from the ListJobs and ListAllJobs endpoints.
The ListJobs and ListAllJobs endpoints will now return the outputs associated to the jobs.
> Dashboard jobs endpoints returns job outputs

- atc/worker/artifact_source.go
- atc/worker/artifact_source_test.go
- atc/worker/image/image_resource_fetcher.go
- atc/worker/image/image_resource_fetcher_test.go
- fly/commands/internal/executehelpers/downloads.go
- fly/commands/internal/executehelpers/uploads.go
- fly/integration/execute_multiple_inputs_test.go
- fly/integration/execute_overriding_inputs_test.go
- fly/integration/execute_test.go
- fly/integration/execute_with_outputs_test.go
- go.mod
- go.sum
Signed-off-by: Alex Suraci <asuraci@pivotal.io>
Fixes #4621
* converts datadog/zstd dependency to klauspost/compress/zstd
> switch to pure go impl of zstd

- fly/integration/execute_test.go
Some fly integration tests were not update when we switched from the
cgo-based zstd library to the new go-based one in #5024.
This made `fly`'s integration tests not compile (thus, not run lol)
Update the tests to properly leverage `zstd.NewReader`.
> fly: fix use of zstd reader in tests

- atc/worker/worker_helper.go
- atc/worker/worker_test.go
* This declaration is necessary for platforms where this is not
the standard networking behavior (like windows).
Fixes #5028 .
* Explicitly whitelist all traffic from concourse containers. This is already done implicitly for the linux platform, but we need it to **explicit** for behavior parity with the windows platform.
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text). 
@jfeeny @genevieve
> Explicitly whitelist all traffic from concourse containers

- testflight/volume_mounting_test.go
Previously, we had marked the test where we create a copy-on-write of a copy-on-write pending so that we could have our pipelines unblocked (see more here: https://github.com/concourse/concourse/issues/4964)
Now that we've got a fix (see https://github.com/concourse/baggageclaim/pull/35) , there's no
need to have this test skipped anymore.
ps.: I'm currently marking this as a draft because it's not complete - it must come with a commit that bumps the version of `baggageclaim` (as the PR didn't get in yet, we don't have a tag to reference in `go.mod`).
Reverts the commit where we skipped a failing test.
--
depends on https://github.com/concourse/concourse/pull/5160
> Revert "tf: temporary pend failing testflight test"

- release-notes/latest.md
- worker/workercmd/worker.go
Fixes #4847 
Set default rebalance-interval to `4h`
> [#4847] Set default rebalance-interval

- atc/atccmd/command.go
Fixes #5157
With the previous default being 6 hours, this caused a lot of build up
of checks within large scale deployments and results in slowness to
the gc query. It was only decided to be a long time period for the
default to allow for operators to find information on the checks that
had previously happened.
We decided to optimize for a faster checks GC rather than more
checks history by default, and if the user deems it necessary to keep
around the history for longer they can configure the GC interval to be
longer.
and …
> Change checks gc default to 1m

- atc/db/job_factory.go
- atc/db/job_factory_test.go
Fixes #5142
If we try to schedule any jobs that are under these conditions, the algorithm will not be able to find any candidates because of the state of the job. So let's just not bother trying to schedule them and only schedule the jobs after they have been unpaused or brought back to active. (We request schedule for any of those triggers)
JobsToSchedule will no longer grab jobs that are either inactive, paused or in a paused pipeline.
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the …
> Do not schedule any jobs that are paused, inactive or in a paused pipeline

- atc/db/migration/migrations/1581350441_remove_unused_idx_and_add_checks_idx.down.sql
- atc/db/migration/migrations/1581350441_remove_unused_idx_and_add_checks_idx.up.sql
Remove the succeeded builds index because it is no longer being used
anymore. Also added an index to speed up a checks query.
Clean up any unused indexes.
Fixes #5045 .
After all these incremental changes to the algorithm, there might be some indexes that were forgotten about. After deploying the changes to a large scale environment, figure out which indexes are not used anymore by using pg_stats.
Removed an unused index for succeeded builds and also found an index that would speed up the checks query from 400 ms to less than 1 ms.
> fill out this …
> Remove unused index and add missing index for checks

- atc/db/job.go
- atc/db/resource_config_scope.go
- atc/db/resource_config_scope_test.go
Fixes #5127.
The check order of versions were being bumped everytime it is saved into the db, regardless if the version already existed. This caused a bug in the mock-resource, when a version is pinned it becomes the latest version because of it's check order being bumped. It also would be best if we didn't have to increment the check order everytime a check is run for it. The reason why this was probably implemented this way was that lidar no longer knew about what the "from" version was, so it was unable to determine when the check order should be bumped or not.
I changed it so that the versions are only bumped if there is at least one new version within the list of versions returned by the check. This should reflect the behaviour we expect, …
> Only bump resource version check order if there are new versions

- atc/lidar/scanner.go
- atc/lidar/scanner_test.go
Fixes #5158
If there are multiple resources that use the same resource type, lidar
will try to create the same resource type check for each resource that
uses it. This can potentially cause a lot of duplicate work with the
SetResourceConfig method for every check created.
In order to avoid this duplication, there is now a sync map for resource
types so that if a check is already created for this resource type, we
won't try to create another check. This map is created every interval
tick and once we add a resource type into the map, it isn't removed
until the whole map is removed through the end of the scanner tick. This
is to ensure that once we have created a check for a resource type
within this interval tick, we will not try to create another …
> Within one scanner tick, only create one check for a resource type

- atc/lidar/scanner.go
- atc/lidar/scanner_test.go
Reverts concourse/concourse#5166
Just noticed the `if` conditional exits out of the whole thing. It probably shouldn't?
> Revert "Within one scanner tick, only create one check for a resource type"

- atc/db/migration/migrations/1579713181_add_to_build_id_index_to_build_pipes.down.sql
- atc/db/migration/migrations/1579713181_add_to_build_id_index_to_build_pipes.up.sql
- atc/db/migration/migrations/1581447344_drop_build_inputs_indexes_and_create_index_for_algorithm.down.sql
- atc/db/migration/migrations/1581447344_drop_build_inputs_indexes_and_create_index_for_algorithm.up.sql
- atc/db/versions_db.go
- atc/scheduler/algorithm/algorithm_test.go
- atc/scheduler/algorithm/group_resolver.go
- atc/scheduler/algorithm/individual_resolver.go
Fixes #5125
Before this change for a version every input, the algorithm would grab
the latest build of a job and try to use the next version after that
build in order to satisfy the version every constraint. This is great
until you have the situation where the latest build used an old pinned
version, and now the "next" version would be the version after that old
pinned version. This will cause the algorithm to produce builds for
versions it has possibly already ran before until it reaches the latest
version.
In order to avoid the possibility of pinning versions to produce builds
using old versions it has already used before, we will now have the
algorithm grab the latest version (rather than build) that has passed
through this job. Then using that …
> atc: change how algorithm deals with version every

- atc/api/accessor/accessor_test.go
- atc/api/accessor/role_action_map.go
The rerun build endpoint was not added to the action role map so only admin users were allowed to rerun builds.
Fixes #5115.
The correct permissions for rerunning builds should be the same creating builds, which is a pipeline-operator role action so rerunning builds was added to the role action map for a pipeline-operator role.
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if …
> Assign pipeline operator role to RerunJobBuild route

- atc/api/accessor/accessor_test.go
- atc/api/accessor/role_action_map.go
Fixes #5176
I noticed after adding the tests #5175 for making sure all routes are assigned to either a role or is admin only that GetWall is missing an assigned role. I added a role for GetWall in the PR for adding the test but it is built ontop of the use-dex-token branch which will not be merged until after the 6.0.0 beta release.
In order to give GetWall a role for the beta 6.0 release, we should probably assign it a role onto master for now. I assigned it to viewer role because anyone should be able to see the wall, but I might be wrong?
> fill out …
> Add role for GetWall

- atc/worker/artifact_source.go
- atc/worker/artifact_source_test.go
- atc/worker/image/image_resource_fetcher.go
- atc/worker/image/image_resource_fetcher_test.go
- fly/commands/internal/executehelpers/downloads.go
- fly/commands/internal/executehelpers/uploads.go
- fly/integration/execute_multiple_inputs_test.go
- fly/integration/execute_overriding_inputs_test.go
- fly/integration/execute_test.go
- fly/integration/execute_with_outputs_test.go
- go.mod
- go.sum
Reverts concourse/concourse#5024
We're seeing failures in CI when streaming volumes in the [`dev-image` build][1].
Also seeing high memory usage on the `web` nodes. We should probably [set a memory limit][2] on decoding? (Not sure if we need to do anything about encoding.)
[1]: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/dev-image/builds/150
[2]: https://pkg.go.dev/github.com/klauspost/compress@v1.10.0/zstd?tab=doc#WithDecoderMaxMemory
> Revert "switch to pure go impl of zstd"

- worker/backend/backend.go
- worker/backend/backend_test.go
Fixes #5184.
In #5114 the way containers are destroyed in a worker was modified. This made the old tests for the destroy functionality irrelevant, and now new ones needed.
* Add unit tests for all the failure cases and the success case for destroying a container
> worker: backfill tests for updated container destroy behaviour

- atc/db/check_factory.go
- atc/db/check_factory_test.go
Fixes #4940
This change is based on @vito 's comment https://github.com/concourse/concourse/issues/4940#issuecomment-568079344 and @pivotal-jwinters 's comment https://github.com/concourse/concourse/issues/4940#issuecomment-568083030.
If a resource is put-only, then no need to run checks against it.
In this commit, added a left join to `job_input` to `resourceQuery`, this way avoids to query `job_input` in the for loop of `resources` in lidar scanner. But side effect is the `ListResources` API will no longer return put-only resources. I feel that should be ok.
@vito please see if you are ok with this change.
> This section is intended for the core maintainers only, to track review …
> feat(atc): skip resource check for put-only resources.

- worker/backend/backend.go
- worker/backend/backend_test.go
- worker/backend/container.go
- worker/backend/container_test.go
Fixes #5134  .
* Implement getter/setter for grace time
> containerd: implement getter/setter for grace time

- topgun/k8s/garden_config_test.go
- topgun/tasks/garden-deny-network.yml
Even though #5198 is resolved in #5199, there are still no tests for this behaviour. This PR addresses that need. This PR will not pass CI until #5199 is merged.
* New k8s-topgun test asserting that GARDEN_DENY_NETWORK actually denies the network
* We could have gone with bosh-topgun but wanted the quicker feedback for a property that is probably a bit of an edge case.
> topgun/k8s: test GARDEN_DENY_NETWORK

- atc/api/teams_test.go
- atc/api/teamserver/get.go
- fly/commands/get_team.go
- fly/commands/hijack.go
- fly/commands/jobs.go
- fly/commands/pause_job.go
- fly/commands/trigger_job.go
- fly/commands/unpause_job.go
- fly/integration/error_handling_test.go
- fly/integration/get_team_test.go
- fly/integration/hijack_test.go
- fly/integration/jobs_test.go
- fly/integration/login_insecure_test.go
- fly/integration/login_test.go
- fly/integration/pause_job_test.go
- fly/integration/suite_test.go
- fly/integration/trigger_job_test.go
- fly/integration/unpause_job_test.go
- fly/rc/rcfakes/fake_target.go
- fly/rc/target.go
- fly/rc/target_test.go
- go-concourse/concourse/client.go
- go-concourse/concourse/concoursefakes/fake_client.go
- go-concourse/concourse/concoursefakes/fake_team.go
- go-concourse/concourse/internal/connection.go
- go-concourse/concourse/internal/connection_test.go
- go-concourse/concourse/internal/http_agent.go
- go-concourse/concourse/team.go
- go-concourse/concourse/teams.go
- go-concourse/concourse/teams_test.go
Fixes #5126 
`--team` does not return any helpful error messages for when:
- User does not belong to a team
- The team does not exist
This PR adds error messages for both of those cases.
* Added an `httpAgent` which will replace `connection` in the `go-concourse` client library. Expanding `connection` was painful because it does too many things (send HTTP requests AND parse the response). `httpAgent` does one thing: send HTTP requests.
* Removed the mock HTTP server `adminATCServer`. It was not needed and was added in the context of Super Admin stories done in September.
* Refactored the existing `--team` tests so they make sense.
* With all the above refactoring we were able to add better error messages for when `--team` fails.
* User is not on a team user gets `you do not have a role on …
> fly: Better error messages for --team

- worker/backend/container.go
- worker/backend/container_test.go
- worker/backend/spec/devices.go
- worker/backend/spec/mounts.go
- worker/backend/spec/spec.go
- worker/backend/spec/spec_test.go
Fixes #5111 .
* Convert garden spec for resource limits to OCI spec
**Note:** this change does not yet achieve full parity with `gdn`, as `gdn` can be configured through flags to go beyond the Garden spec for resource limits. See #5226
> containerd: implement basic resource limits

- worker/container_sweeper_test.go
Test started failing more often with upgrade to go 1.14. Error message is now different.
Updated error message.
> worker: fix container-sweeper test

- testflight/suite_test.go
Fixes concourse/ci#276.
There was a time when it was typical for dev builds of concourse to fail
to serve the CLI download endpoint. Since we have been using
docker-compose consistently, we have also been packaging fly into the
dev image, so it is safe for testflight to assume the CLI download API
will be working correctly. Hopefully this improves the dev/CI parity and
helps to surface problems in our CI builds of fly more clearly.
> testflight: download fly instead of building

- atc/api/jobs_test.go
- atc/api/pipelines_test.go
- atc/wrappa/api_auth_wrappa.go
- atc/wrappa/api_auth_wrappa_test.go
fixes #996
Signed-off-by: Joe Hosteny <jhosteny@carnegierobotics.com>
Fixes #996.
Make the badge routes public, so that we can see the build status for private pipelines and jobs without authentication (e.g., in a github README).
* Make PipelineBadge public 
* Make JobBadge public
> feat(atc): make pipeline and job badge API routes public

- atc/api/pipelines_test.go
- atc/api/present/pipeline.go
- atc/db/dbfakes/fake_pipeline.go
- atc/db/migration/migrations/1580135204_add_pipelines_last_update.down.sql
- atc/db/migration/migrations/1580135204_add_pipelines_last_update.up.sql
- atc/db/pipeline.go
- atc/db/team.go
- atc/pipeline.go
- fly/commands/pipelines.go
- fly/integration/pipelines_test.go
- release-notes/latest.md
Record pipelines creation/update time #4809
Fixes #4809.
* Add a new column into the `pipelines` table called `last_updated`
* When the pipeline is (re-)set the `last_updated` column is set to the current time
* Add a column in the output of `fly pipelines` to display the last updated date of the pipelines being displayed
> Record and expose pipelines last update date.

- atc/db/job.go
- atc/db/migration/migrations/1581621620_add_unique_index_on_build_names.down.sql
- atc/db/migration/migrations/1581621620_add_unique_index_on_build_names.up.sql
- atc/scheduler/algorithm/table_helpers_test.go
Fixes #5185
Spamming rerun build requests should not result in two or more of the same build being created.
If there are two requests trying to create the same rerun build, one of them will fail using the unique constraint and will retry again in order to make a separate rerun build.
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not …
> Do not allow duplicate rerun builds

- topgun/common/common.go
- topgun/operations/add-credhub.yml
Co-authored-by: Jeremy Alvis <jalvis@pivotal.io>
Co-authored-by: Kira Boyle <kboyle@pivotal.io>
requires https://github.com/concourse/concourse-bosh-release/pull/93
Talked with @cirocosta 
Talked with @cirocosta to test Credhub with UAA. Most people don't deploy Credhub with mutual TLS because it's not as secure or extensible.
* Test changes to topgun
* add UAA to topgun for Credhub 
- [N/A] Unit tests
- [N/A] Updated documentation (located at https://github.com/concourse/docs)
- [N/A] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the …
> Add uaa to topgun testing

- release-notes/latest.md
- web/elm/src/Application/Application.elm
- web/elm/src/Build/Build.elm
- web/elm/src/Build/Header/Header.elm
- web/elm/src/Build/Shortcuts.elm
- web/elm/src/Message/Callback.elm
- web/elm/src/Message/Effects.elm
- web/elm/src/Message/ScrollDirection.elm
- web/elm/src/Routes.elm
- web/elm/src/SubPage/SubPage.elm
- web/elm/tests/BuildTests.elm
Existing Issue
Fixes #3994  .
In addition to #3994, there are several other issues with highlights on the build page:
* Highlighting a build log refreshes the page
* Loading a page with a highlight always jumps to the top, rather than jumping to the highlighted log message
* Track route transitions to check if we "came from" the same build page (the only difference being the highlight changed) - if so, don't reload
* Capture a `ScrollCompleted` event to remove the highlight (but not from rendering) when we scroll to it. This fixes #3994
* Use `Browser.Dom.getElement` instead of `Browser.Dom.getViewportOf` to determine the position to scroll to. `Browser.Dom.getViewportOf` always gives coords (0, 0) for the build log since it doesn't have a scrollable viewport, so it's scrollTop/scrollLeft …
> web: fix highlighting logs on build page

- atc/engine/builder/step_factory.go
- atc/exec/check_step.go
- atc/exec/check_step_test.go
- atc/worker/client.go
- atc/worker/client_test.go
- atc/worker/workerfakes/fake_client.go
- testflight/resource_check_timeout_test.go
- vars/template.go
fixes #4957 
- move the garden logic from the `exec` package to `worker`
ps.: this is strictly a refactor (no changes in behavior) 
- ~[ ] Integration tests (if applicable)~
- ~[ ] Updated documentation (located at https://github.com/concourse/docs)~
- ~[ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)~
> atc: check step refactor (move from `exec` to `worker`)

- atc/db/build.go
- atc/db/build_test.go
- atc/db/job.go
There was a bug where the next build id of a job was not updated to the
correct build if the build was a rerun of a rerun. This was fixed by
having the rerun_of be compared to a non rerun build rather than the
latest completed build.
I also removed updating the next build id column on the Start method
because it should not be needed, since builds are added to the list of
possible "next build ids" when they are either pending or started and
since builds always go from pending -> started, we only need to update
the next build id when we create a new pending build (and then also
update it when we finish builds).
Fixes #5236
> The running state of a build that is a second rerun should show in the pipeline UI

- atc/db/migration/migrations/1583868323_add_pipelines_last_update.down.sql
- atc/db/migration/migrations/1583868323_add_pipelines_last_update.up.sql
Related to concourse/concourse#5271. Merging this PR and waiting for it to pass CI is actually part of the acceptance criteria.
* bump timestamp on the migration that went out of date in our smoke environments
> atc/db: behaviour: bump last update migration time

- atc/db/migration/migrations/1580135204_add_pipelines_last_update.down.sql
Related to #5271. Let's not close the issue until the bin-smoke and bosh-smoke jobs are green.
* We considered the case where the "same" migration would be running twice during an upgrade, but forgot the downgrade case. Here's hoping this covers it!
> atc/db: behaviour: last_update down is idempotent

- CONTRIBUTING.md
While trying to accept concourse/concourse-chart#79, I saw the instruction to
run k8s-topgun and I struggled with the existing instructions - they're a bit
off.
* Most importantly, fix the description of the required environment variables. With that done the instructions at least allow you to run the test suite.
* While doing so, I noticed that the link to the concourse chart was out of date, so I updated it.
> fix up k8s-topgun instructions

- fly/commands/sync.go
- fly/integration/sync_test.go
- removed any need for the `-t` flag
- added a new flag `-c` to specify the URL to sync t to specify the URL to sync to
Able to run `fly -t target sync -c concourse-url`
> fly : #2944 ability to sync without having `-t`

- Dockerfile
Fixes #5295 .
To reduce redundancy and possibly conflicting packages for containerd related dependencies in the Docker image. 
The dependencies are now installed in the [concourse/dev image](https://github.com/concourse/ci/blob/master/dockerfiles/dev/Dockerfile) through the [dev-image job](https://github.com/concourse/ci/blob/1719a3d11bc6b70b44e97411849b27ab39410420/pipelines/concourse.yml#L260). That job ensures that the base image used for bringing up Concourse via docker-compose is built with the latest versions of the dependencies.
* Removed installation of containerd, runc, iptables
* Remove assignment of CONTAINERD_NAMESPACE
> remove containerd dependencies from Dockerfile

- atc/api/jobs_test.go
- atc/api/pipelines_test.go
- atc/wrappa/api_auth_wrappa.go
- atc/wrappa/api_auth_wrappa_test.go
Reverts concourse/concourse#5252
We do want a change sort of like this but we'll need to talk about it a bit more. For now, just going to revert it as it's backwards-incompatible.
See https://github.com/concourse/concourse/pull/5308#issuecomment-600283564 for details.
> Revert "feat(atc): make pipeline and job badge API routes public"

- worker/container_sweeper_test.go
- go 1.14 changes the error for a http.Client timeout
the test was too coupled and hence refactored the test to be agnostic
the format changed from
`net/http: request canceled (Client.Timeout exceeded while awaiting headers)`
to
`context deadline exceeded (Client.Timeout exceeded while awaiting headers)`
Signed-off-by: Sameer Vohra <vohra.sam@gmail.com>
> Decouple container_sweeper_test assertion to be go version agnostic

- atc/db/job.go
- atc/db/job_test.go
- atc/scheduler/algorithm/table_helpers_test.go
- atc/scheduler/build.go
- atc/scheduler/buildstarter.go
- atc/scheduler/buildstarter_test.go
- atc/scheduler/job_scheduling_test.go
Fixes #5312 
A job configured with serial: true will currently end up with builds stuck in a pending state if a re-run is triggered and then a non-rerun is triggered before the re-run is scheduled.
This PR will change the way the pending builds are ordered to schedule in order to ensure that the the bug can never happen. It will order the pending builds according to the same ordering as the algorithm, but in ascending order. For example, the pending builds will be ordered 1, 1.1, 1.2, 2 rather than before this change it would've order the rerun builds first in 1.1, 1.2, 1, 2. 
> fill out this …
> Builds can get stuck in pending state with a mixture of rerun and non rerun builds

- CONTRIBUTING.md
- topgun/deployments/concourse.yml
- despite us not enforcing that contributors add topgun tests / run topgun when
submitting PRs, sometimes we need to do so, but that flow isn't documente
anywhere.
- BOSH lite seems to have problems with `btrfs`, making testing locally not
possible w/out a manifest change.
- update the contributing section with instructions to get started with running
topgun locally
- update the base manifest to use `overlay` rather than the default (detect,
which will prioritize btrfs)
---
cc @jtarchie
> contributing: add topgun section

- atc/api/api_suite_test.go
- atc/api/handler.go
- atc/api/jobserver/list_all.go
- atc/api/jobserver/server.go
- atc/atccmd/command.go
This endpoint definitely has performance problems, and issues like concourse/concourse#4373 just scratch the surface. With this change, you can pass the `--disable-list-all-jobs` flag or set `CONCOURSE_DISABLE_LIST_ALL_JOBS="true"` and the `/api/v1/jobs` endpoint will always return an empty JSON array. The most significant end-user impact of this change should be that the dashboard will no longer display pipeline previews.
> atc: add flag to disable `ListAllJobs`

- skymarshal/skyserver/skyserver.go
Previously concours use `url.String()` for redirect URL, whose path is actually escaped. With the recent fix https://github.com/concourse/concourse/commit/d19f4a560c416e49e086f538759f4aef7eb647b9 changed that. 
Use the same way to construct redirect URL by escaped path
> skymarshal: use escaped path for redirect URI

- atc/db/job.go
- atc/db/job_test.go
With the changes from #5270, we no longer update the next build ID for a job when a build is started because we rely on the creation of the pending build to update the next build ID. Whenever the scheduler creates a new build, it will call EnsurePendingBuildExists which originally did not update the next build ID. This caused a bug where any builds created by the scheduler will not show up in the next build ID column or be returned back by any api endpoints.
Also the EnsurePendingBuildExists method does not call the `createBuild` method, so it will need to also add the `needs_v6_migration = false` to the query for creating the pending build.
Update the next build id for a job when a new build is created by the scheduler through EnsurePendingBuildExists. Have any builds created through …
> Update next build for job for scheduler builds

- atc/atccmd/command.go
- package.json
Fixes https://github.com/concourse/concourse/issues/5333.
* Small change to package.json to allow for `yarn build` on window's powershell
* Added configurable RunnerInterval to get around hard-coded runner limits of 10s
> Configurable Runner Interval

- atc/api/artifacts_test.go
- atc/api/builds_test.go
- atc/api/buildserver/eventhandler_test.go
- atc/api/cc_test.go
- atc/api/checks_test.go
- atc/api/cli_test.go
- atc/api/config_test.go
- atc/api/containers_test.go
- atc/api/http_header_matcher_test.go
- atc/api/info_test.go
- atc/api/jobs_test.go
- atc/api/pipelines_test.go
- atc/api/resources_test.go
- atc/api/teams_test.go
- atc/api/users_test.go
- atc/api/versions_test.go
- atc/api/volumes_test.go
- atc/api/wall_test.go
- atc/api/workers_test.go
- atc/testhelpers/http_header_matcher.go
- atc/wrappa/versioned_handler_test.go
Signed-off-by: Dimitry Besson <dbesson@pivotal.io>
No existing issue.
Refactor for readability and more information on test assertion failure messages.
* Introducing custom matcher for http response header. This helps reduce the number of `Expect` needed for testing http response headers.
* Simplify a couple of tests
> Add custom Gomega matcher for http response header

- web/elm/src/Dashboard/Dashboard.elm
- web/elm/tests/DashboardCacheTests.elm
- web/public/elm-setup.js
#5262 introduced a bug if there were many thousands of jobs - the `localStorage` capacity could be exceeded, causing Javascript to error and the UI to break.
* Bound the number of jobs cached to 1000. Based on some numbers I've seen (on Hush House), this equated to around 1MB (compared to the localStorage limit of 5-10MB, depending on the browser)
* Catch errors when writing to localStorage/sessionStorage, so even if that still manages to exceed the limit, we can handle that case gracefully
> web: behaviour: bound cached jobs to 1000

- web/elm/tests/DashboardPreviewTests.elm
- web/elm/tests/DashboardSearchTests.elm
- web/elm/tests/DashboardTests.elm
- web/elm/tests/Data.elm
- web/elm/tests/DragAndDropTests.elm
- web/elm/tests/PipelineCardTests.elm
- web/elm/tests/PipelineTests.elm
- web/elm/tests/SideBar/PipelineTests.elm
- web/elm/tests/SideBar/TeamTests.elm
- web/elm/tests/SideBarFeature.elm
- web/elm/tests/SideBarTests.elm
- web/elm/tests/TopBarTests.elm
- web/elm/tests/WelcomeCardTests.elm
Useful for: #5321 
Currently, pipelines are being defined as record literals in many places throughout the tests. This makes it difficult to, say, add a new field to the Pipelines type alias (e.g. `archived`)
This commit does not change the tests in any meaningful way (if it does, I made a mistake!), nor does it change any behaviour.
* Change every Pipeline record definition to use the `Data.pipeline` function.
* Add some `Data` helpers (e.g. `Data.withName`, `Data.withPaused`, etc.) to modify those pipelines
> web: structure: use Data.pipeline in tests

- fly/commands/curl.go
- fly/integration/curl_test.go
- release-notes/v6.0.1.md
Fixes #5366 
#4048 introduced a `Query` arg that break passing extra curl options when doing `fly curl -- -some-option`
Parse the `Path` argument so it won't encode `?` to produce a wrong URL as mention in #4048 and thus allowing passing extra curl options back to normal
> fly: fix curl command when passing options

- topgun/k8s/garden_config_test.go
- worker/integration/README.md
- worker/integration/integration_test.go
- worker/integration/suite_test.go
- worker/workercmd/containerd.go
Fixes #5294
Create the worker dir if it does not exist, similar to what concoures does in https://github.com/concourse/concourse/blob/master/worker/workercmd/worker_linux.go#L108-L111
> atc: create worker dir if not exist when using containerd

- release-notes/v6.0.1.md
- web/elm/src/Dashboard/Styles.elm
- web/elm/tests/PipelineCardTests.elm
Existing Issue
Fixes #5374  .
* Change `height: 100%` to `display: flex` on the parent: https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent
> web: behaviour: fix dashboard preview on safari

- release-notes/v6.0.1.md
- web/elm/src/Dashboard/Group.elm
- web/elm/src/Message/Message.elm
- web/elm/tests/PipelineGridTests.elm
Fixes #5376 .
* Respond to `mouseOver` and `mouseOut` events on the `.pipeline-wrapper`, and increase the z-index in that case.
Similar to e664c21e1228b465921192221c45e844b2f3b356, but for the pipeline name tooltip instead of the job name tooltip.
Note: using `mouseOver` and `mouseOut` since I don't want `mouseLeave` events to trigger when hovering over child elements (e.g. the jobs).
> web: behaviour: fix tooltip for long pipeline names

- atc/api/pipelines_test.go
- atc/pipeline.go
- fly/integration/pipelines_test.go
Fixes #5314.
* Add 'archived' field to the JSON obejcts in the resposes from the following endpoints:
* `ListAllPipelines`
* `ListPipelines`
* `GetPipeline`
* The value is always `false` for now
> atc/api: add 'archived' field to pipelines

- release-notes/v6.0.1.md
- web/elm/src/Application/Application.elm
- web/elm/src/SubPage/SubPage.elm
- web/elm/tests/BuildTests.elm
Fixes #5384 .
* Keep track of the route we came from for OneOffBuilds (the same approach as for JobBuilds)
**note:** this was fixed for the JobBuild page in #5275
> web: behaviour: fix log highlighting on OneOffBuild page

- release-notes/latest.md
- release-notes/v6.0.1.md
- web/elm/benchmarks/Benchmarks.elm
- web/elm/src/Build/Header/Header.elm
- web/elm/src/Build/Header/Views.elm
- web/elm/src/Message/Effects.elm
- web/elm/src/Message/Message.elm
- web/elm/src/StrictEvents.elm
- web/elm/tests/BuildTests.elm
Fixes #5383 .
* Introduce `scrollCoordsSimple` function for dealing with simple cases of computing scroll position (that don't require knowing the coordinates of the source and parent elements)
* Replace the deprecated DOM event `mousewheel` with `wheel`, which fixes scrolling on Firefox (which seems to have been broken for a while)
Note that this behaviour could be shoehorned in to the more complicated `scrollCoords` function, but there is a noticeable performance hit in scrolling due to the increased number of calls out to `Elm.Browser`.
> web: behaviour: fix scroll on build history list

- release-notes/v5.5.11.md
- web/elm/src/Dashboard/Dashboard.elm
- web/elm/src/Dashboard/Styles.elm
- web/elm/tests/DashboardTests.elm
Fixes #2935 .
* Add a loading screen to the dashboard rather than rendering nothing when waiting for API responses
Looks very similar to the sketch in #2935:
> web: behaviour: add loading view to dashboard

- atc/atccmd/command.go
Signed-off-by: TJ Higgins <tj@architect.io>
Fixing a typo I noticed from my pr to add ComponentRunnerInterval  https://github.com/concourse/concourse/pull/5342. Sorry!
> Fix typo with ComponentRunnerInterval env

- web/elm/src/Concourse.elm
- web/elm/src/Dashboard/Dashboard.elm
- web/elm/src/Dashboard/Group/Models.elm
- web/elm/tests/DashboardArchiveTests.elm
- web/elm/tests/Data.elm
~Branched off of: #5369 - merge this first~  MERGED
Fixes #5321  .
* Add archived field to Pipeline model
* Filter out archived pipelines for rendering
> web: behaviour: don't render archived pipelines

- worker/backend/process_killer_test.go
- remove fmt.Print from process_killer_test
Minor - removed floating print statement so that we don't pollute test logs.
> worker: Remove unneccesary print statement

- hack/overrides/jaeger.yml
Related to concourse/concourse#5382.
* jaeger override now includes elasticsearch & kibana
* as tracing features get expanded, using this override means you can immediately create sophisticated queries/visualizations across the whole span database
> hack/jaeger: add elasticsearch backend w kibana

- worker/backend/cni_network.go
- worker/backend/cni_network_test.go
- worker/backend/integration/integration_test.go
- worker/backend/integration/sample/main.go
- worker/backend/process_killer_test.go
- worker/workercmd/containerd.go
- worker/workercmd/worker_linux.go
Fixes #5138
This PR allows users to pass a custom DNS server for use in worker containers.
It does this by making CONCOURSE_GARDEN_DNS_SERVER flag have the same functionality for `containerd` runtime as it does when using `guardian`.
> containerd: support custom dns configuration

- atc/db/migration/migrations/1583868323_add_pipelines_last_update.down.sql
- atc/db/migration/migrations/1583868323_add_pipelines_last_update.up.sql
- docker-compose.yml
Fixes #5391.
To support postgres 9.5
The migration that caused the syntax error is a duplicate to fix an earlier migration error. We could just remove the migration.
> Remove duplicate migrations that not postgres 9.5 friendly

- hack/dlv/Dockerfile
the way that we're currently asking `dlv` to be installed (via `go get`
in a directory that is module aware), it's as if we were making dlv a
dependency of concourse, which is not really what we want.
```
#6 5.952 github.com/go-delve/delve/pkg/terminal
#6 5.967 # github.com/go-delve/delve/pkg/terminal
#6 5.967 /go/pkg/mod/github.com/go-delve/delve@v1.4.0/pkg/terminal/command.go:959:28: cannot use ([]rune)(args) (type []rune) as type string in argument to argv.Argv
#6 5.967 /go/pkg/mod/github.com/go-delve/delve@v1.4.0/pkg/terminal/command.go:959:36: undefined: argv.ParseEnv
#6 5.967 /go/pkg/mod/github.com/go-delve/delve@v1.4.0/pkg/terminal/command.go:960:3: cannot use func literal (type func([]rune, map[string]string) ([]rune, error)) as type argv.Expander in argument to argv.Argv
------ …
```
> hack: fix dlv installation

- release-notes/v5.5.11.md
- web/elm/src/Dashboard/Dashboard.elm
- web/elm/src/Dashboard/Models.elm
- web/elm/tests/DashboardTests.elm
Fixes #5424. This is a backport of (part of) the functionality in #5023, and I have duplicated the release note from that feature.
* pretty straightforward - add a flag to the Dashboard model - on every 5 seconds this flag is set to `True`, and every time an `APIDataFetched` callback returns it is set to `False`.
* This means that you will never have two `FetchData` effects in flight at the same time
Similar to https://github.com/concourse/concourse/pull/5023#issue-362785585, I patched my `ListAllJobs` endpoint so it sleeps for an extra 10 seconds.
Before this patch:
After this patch:
> [5.5.x] web: behaviour: do not pile on dashboard API calls

- .github/pull_request_template.md
Previously, the PR template was very focused on describing the changes
that were made, leaving less space for a presentation of why the given
change is even needed in the first place.
Although it did incentivize the user to provide an issue (where previous
discussion would've been held), it's not always the case that a given PR
is a 1:1 with the issue that it references.
By forcing ourselves to reiterate why we're submitting the PR, it might
prompt us to better think about whether we're solving the problem in the
right way.
- have a section specifically focused on reiterating why a given PR is needed
This is supposed to lead us to rethinking not only whether PR is important or
not, but also communicate the impact of it.
- have another section focused only on what the PR is fixing.
With a …
> github: update PR template to focus on "why"

- worker/workercmd/containerd.go
Fixes #5139 
When CONCOURSE_GARDEN_DNS_ENABLE flag is set on the worker while running containerd as a backend, a proxy DNS server will be run, and added to the list of DNS servers for a container.
Note:
Given that topgun/k8s already tests all of the possible scenarios involving configuring DNS servers, we rely on that suite for ensuring that this is properly done - there might be other possibilities for 
making this not rely on the topgun suite though - please let us knowif you have any ideas!
See https://github.com/concourse/concourse/blob/fab3de1722a2ce998d3710bd066453594f24ec57/topgun/k8s/dns_proxy_test.go
**UPDATE**: Issue #5473 opened to address the testing
> This section is intended …
> support dns proxy in containerd

- go.mod
- go.sum
- skymarshal/dexserver/dexserver.go
- skymarshal/dexserver/dexserver_test.go
Fixes #5428 
- you can now configure dex with bcrypted client secrets
- if they are in plaintext concourse will bcrypt them and then pass them to dex.
corresponding dex commit:
https://github.com/concourse/dex/commit/dcbe94f
> skymarshal: bcrypt client secrets

- release-notes/latest.md
- web/elm/src/Dashboard/Dashboard.elm
- web/elm/src/Dashboard/Models.elm
- web/elm/tests/DashboardTests.elm
- web/elm/tests/DragAndDropTests.elm
If any network request fails once, the dashboard will be stuck in the
"show turbulence" page view forever (until you refresh the page). This
happens fairly frequently to me at least - if you have the dashboard
open, close your laptop for a little, and come back, the page will be
unusable due to the turbulence view.
Allow the turbulence view to disappear if all of the once failing network requests start succeeding.
Rather than just keeping track of whether we should display the turbulence view (which was previously never unset), keep track of whether each endpoint is failing. If any of the endpoints are still failing, display the turbulence view.
One change is that the dashboard no longer considers the "team pipelines" endpoint response for displaying the show turbulence view - if it ever …
> web: behaviour: recover from turbulence view

- topgun/k8s/container_limits_test.go
[k8s-topgun](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun) has been failing since April 17th, blocking our ability to ship a new minor version of Concourse.
After investigating the output of k8s-topgun, I realized that the failure was the result of an unnecessarily-brittle test - the underlying behaviour of the system was still correct. This PR is trying to address the robustness of the test.
Replace a fairly strict regex with a more flexible one that shoudl effectively verify the same behaviour. I am confident this is a reasonable pattern to use, as it is employed by testflight in a very similar scenario.
I tested this by focusing the container limits test that has been failing on master, and running:
```
fly -t ci execute \
-c …
```
> topgun/k8s: more flexible regex in container limits test

- Dockerfile
The dev image, upon which we base our image for testing, sets some environment
variables pointing to various keys. This is done as a convenience for images
layered on top, but it doesn't really make sense because these environment
variables are actually set to point to nonexistent paths.
The idea here is to pave the way for creating images where the key-generation
and configuration-setting are done in the opposite order.
This change should have no impact for the moment -- it sets environment
variables that, at this point, are already set. In general it makes more
sense to generate the keys before pointing to them with environment variables.
Once we switch to a stricter version of go-flags, this change will be necessary
to prevent the `concourse generate-key` commands from failing.
> Dockerfile: set key env vars after generating keys

- worker/workercmd/containerd.go
- worker/workercmd/worker.go
- worker/workercmd/worker_linux.go
Fixes #5140  .
add `container-network-pool` flag to worker command. It will be passed to garden server flag `network-pool` or containerd cni network config.
The env var will be `CONCOURSE_CONTAINER_NETWORK_POOL`
> Add worker flag to configure container network pool

- atc/creds/kubernetes/secrets.go
- atc/db/pipeline.go
- atc/db/pipeline_test.go
Global credential managers are currently queried before pipeline-level var sources, which doesn't seem right. Normally it should just find nothing (since named vars have a `:` in their secret path, making it an unlikely match) - however the Kubernetes secret manager actually uses `:` internally so it would choke on any named var source.
fixes #5413
* Swap the order, so that pipeline-level var sources are tried first. I think this should be fine and may have been the original intention - paging @evanchaoli just to make sure I haven't missed anything here!
* Switch the K8s secret manager from `:` for `/` for clarity. This should actually have no user impact, because the K8s secret manager was constructing its own strings using a `:` as a separator - we just switched it to `/`.
> This …
> atc: behavior: try named var sources before global ones

- topgun/k8s/kubernetes_creds_mgmt_test.go
we're currently unable to ship due to `k8s-topgun` failing.
part of that is the fact that the tests that relate to credential management are not 
up to date with the expectations of the chart. fixing that would then let us move on
with 6.1.x, and continue to have our PRs to that repo being properly tested.
it tries to fix part of the failures that we're currently seeing - that part being
the cred mgmt tests.
there are a set of tests in that suite that requires the user to provide
their own namespaces for the teams that the `web` nodes are supposed to
retrieve credentials from:
1. create namespace
2. tell concourse that team & pipeline credentials should come
from that specific namespace
3. put secrets in that namespace
4. have `web` nodes reading secrets from that namespace
now, despite …
> topgun: fix creds mgmt tests

- atc/db/notifications_bus_test.go
Fixes a race condition in the notifications bus
Adds a regression test for the deadlock
> atc: fix race condition in notifications bus test

- atc/db/job.go
- release-notes/latest.md
Fixes #5452.
There is a bug where if you create a new pending build and then trigger a rerun pending build, all the builds will be stuck in pending state. This is because the ordering of the builds that are scheduled are different than the ordering of the builds that are used to check if the job has reached max in flight. The pending builds are scheduled in the same order as the algorithm where it takes into account rerun builds and orders them in the order of the build it is a rerun of. For example, if you have three pending builds that were created in this order, 5, 6.1, 2.1, where 6.1 and 2.1 are reruns, we will schedule them in the order 2.1, 5, 6.1. This is because we schedule builds from oldest -> latest and since 2.1 is a rerun of 2, it gets scheduled first. Then 5 is scheduled …
> Fix ordering of max in flight check

- atc/atccmd/command.go
Make the default 5m because this was the old garden default
> atc: change default hijack grace period

- hack/dlv/Dockerfile
without performing the update to the local apt repository state that
keeps track of the possible packages to install, we can end up having
problems trying to install versions of packages that are not tracked in
the upstream repositories anymore.
this will prevent failures like the following:
404  Not Found [IP: 91.189.88.142 80]
Err:5 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libpython3.5-stdlib amd64 3.5.2-2ubuntu0~16.04.9
404  Not Found [IP: 91.189.88.142 80]
Err:7 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libpython3.5 amd64 3.5.2-2ubuntu0~16.04.9
404  Not Found [IP: 91.189.88.142 80]
> hack: update apt repos before install

- atc/api/accessor/accessor.go
- atc/api/accessor/accessor_test.go
NOTE: we don't log failed type conversions. This is probably something
we want to start doing once we allow users to bypass dex. For now its
probably ok to fail silently because our token structure will be
consistent for the time being.
https://github.com/concourse/concourse/projects/49#card-31357785
https://github.com/concourse/concourse/projects/49#card-36796693
> atc: handle groups claims properly

- CONTRIBUTING.md
without the ability to test our changes locally, iterating on k8s-topgun could be a big barrier to most contributors who don't have access to a testing cluster / don't want to mess up other clusters. we used to also assume that the user had already properly configured Tiller, which might not be true in many cases.
the end goal here is to lower the barrier to running `k8s-topgun` by making the creation of a cluster that can run `k8s-topgun` very few commands away, as well as describing how to set up tiller, a requirement for our current testing (which relies on helm 2).
it does to by adding instructions that guide the user to the creation of the cluster, and set up of tiller.
- ~Unit tests~
- ~Integration …
> contributing: add tiller install instructions

- atc/db/check_factory.go
- testflight/custom_resource_check_test.go
- testflight/resource_type_test.go
When a resource's parent type has no version you see this error on the resource's page:
```
parent type has no version
```
Noticed this error message myself and it wasn't clear to me what was
wrong. Someone on discord also mentioned that the error message was not
helpful with their troubleshooting.
This error message should guide the user to look at the likely source of
the error: the parent resource type's config.
Change the error message when no parent type exists to:
```
resource's parent type 'name-of-parent-resource-type' has no version
```
and …
> atc/db: less cryptic error message

- cmd/concourse/concourse_test.go
- cmd/concourse/web.go
ps.: this should be cherry-picked to `master`
The `system-claim-key` and `system-claim-value` flags exist so you can tell concourse which requests should have 'system' privileges. These system privileges grant access to perform various actions required by the TSA, mainly around the lifecycle of workers.
By default we grant these 'system' privileges to any request presenting a token that was issued using the `concourse-worker` client (the token will have the `aud` claim set to `concourse-worker`). 
If a user wants to change the `tsa-client-id` then they probably won't know that they need to change the `system-claim-value` as well. So we automagically configure it for them behind the scenes.
> automatically fill system-claim-values

- topgun/k8s/prometheus_test.go
With `stable/prometheus` going from having `kube-state-metrics` embedded in its set of templates to a separate dependency, `k8s-topgun` started failing:
```
Error: found in requirements.yaml, but missing in charts/ directory: kube-state-metrics
```
Without this PR, we can't have `k8s-topgun` running without having the version of `helm/charts` pinned to an old commit, which would force us to have that commit hardcoded in the release branches, as well as the main pipeline.
It tries to make the installation of `prometheus` possible regardless of how its dependencies are set up (either through `requirements.yaml` - the new way of doing thing -, or the old one - embedded). 
It does so by running `helm dependency update` before running `helm install`.
Given that such command will not fail in …
> k8s/topgun: update prometheus dependencies and disable worker

- .github/auto_pr_team.yml
This just simply adding a configuration file for this (bot)[https://github.com/xtremerui/auto-pr-team/blob/master/index.js] so an owner of a pull-request against concourse/concourse could be added to `concourse` org `contributor` team.
> add config file for PullRequest bot automation

- atc/configvalidate/validate.go
- atc/creds/ssm/manager.go
- atc/creds/ssm/manager_factory.go
[Anti-patterns page]: https://github.com/concourse/concourse/wiki/Anti-Patterns
The `var_sources` only supports `dummy` and `vault` and I've the need to support `aws ssm`.
This PR adds `aws ssm` support for `var_sources`
I followed the guidelines that @vito gave me in discord and followed the approached used for Vault.
This is my first time doing go so be kind 😅 
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in …
> Add `aws ssm` support for `var_sources`

- CONTRIBUTING.md
Since for me, a newbie to go, was not clear what code style is used in the codebase I believe adding a note in the contributing process to run `goimports` will help others.
> Add note to use `goimports` in Contributing.md

- CONTRIBUTING.md
- atc/api/jobserver/create_build.go
- atc/api/resourceserver/check.go
- atc/api/resourceserver/check_resource_type.go
- atc/api/resourceserver/check_webhook.go
- atc/db/check.go
- atc/db/check_factory.go
- atc/db/check_factory_test.go
- atc/db/check_test.go
- atc/db/dbfakes/fake_check.go
- atc/db/dbfakes/fake_check_factory.go
- atc/db/migration/migrations/1588860260_add_span_context_to_checks.down.sql
- atc/db/migration/migrations/1588860260_add_span_context_to_checks.up.sql
- atc/db/span_context.go
- atc/lidar/checker.go
- atc/lidar/lidar.go
- atc/lidar/scanner.go
- atc/plan.go
- tracing/tracer.go
There are a few recurring scenarios where concourse seems to "hang" and not give clear feedback about why. The work in this PR is focused around improving observability in the "I pushed a new commit, but my test job isn't triggering" workflow, which has sizeable overlap with the `create-and-run-new-pipeline` SLI.
The end goal is to enable a single execution of the `create-and-run-new-pipeline` SLI to correspond to a single trace - failing that, it would be nice to have a collection of traces that observe the flow of execution between all the exercised components: `scanner -> checker -> scheduler -> buildstarter -> exec` to enable a (stochastic) answer to the question "why is this SLI timing out?"
related to #5547.
The straightforward part is just emitting traces from the …
> Lidar tracing

- web/wats/helpers/palette.js
- web/wats/helpers/web.js
- web/wats/package.json
- web/wats/test/build.js
- web/wats/test/dashboard.js
A light at the end of the tunnel
Currently, the [watsjs job](https://ci.concourse-ci.org/teams/contributor/pipelines/prs/jobs/watsjs) in our pipelines is mostly red due to flaky tests. For a while, my automatic instinct when a wats test failed was to retrigger the build - only after failing multiple times did I look into why it failed. Recently, however, retriggering the build rarely seems to get the build to go pass.
closes #5626  .
* wait for changes to occur, rather than hoping they were quick enough to have already happened
* run wats tests serially
---
P.S. I'm guessing there'll still be some flakes, but hopefully they'll be much fewer
> reduce watsjs flakiness

- atc/engine/engine.go
- atc/engine/engine_test.go
- atc/worker/fetcher.go
- go.mod
- go.sum
- release-notes/latest.md
Without this change you can't really trust the "errored" state since it can sometimes be caused by someone aborting builds with a particular build plan.
fixes #5515 
Making use of `errors.Is` to detect whether the build was interrupted, and bumping `go-multierror` to support `.Unwrap`.
> atc: behavior: check deeply for context.Canceled

- atc/db/job.go
- atc/db/pipeline.go
- atc/db/resource.go
- atc/db/volume_repository.go
There are a few db methods that are missing tx.Rollback() to ensure that the queries will be rolled back if one of the queries fail within the transaction. The places that @aoldershaw found were Resource.UnpinVersion, Job.GetNextBuildInputs, VolumeRepository.RemoveMissingVolumes and Pipeline.LoadDebugVersionsDB.
Adds the missing rollbacks to methods that open a transaction but did not add a transaction rollback in case the method fails in the middle of the transaction. Some of these methods only have select queries so the rollback is technically not necessary but I added it to keep it consistent and safe in case there are future refactors that add any queries that modify data.
closes #5557.
> This section is …
> Add missing transaction rollbacks

- atc/db/build.go
- atc/db/resource_cache_lifecycle_test.go
- atc/db/versions_db.go
- atc/scheduler/algorithm/compute.go
Improve the efficiency of queries in order to lower database CPU usage. This PR tackles a couple of vectors that could be the cause of some db slowness that was noticed on the concourse's team `hush-house` deployment.
closes #5577 
* Update `FirstOccurrence()`  query to use the index available in the `build_resource_config_version_inputs` table
* Rewrite the query for deleting any old build image resource caches when finishing a build in order to speed up its performance
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration …
> atc: Optimize db queries

- web/elm/src/Dashboard/Dashboard.elm
- web/elm/src/Dashboard/Models.elm
- web/elm/tests/DashboardTests.elm
Fixes #5466 
cherry picking from same fix of 5.5.x https://github.com/concourse/concourse/pull/5483/commits/da38f56362d57cfde318326909269624974b786c
The differences are
1. The retry logic is for ListAllJobs endpoint only
2. The retry will be added to the retry pool only when there is no same retry exists. Without doing this the size of pool keep increased with same FetchJobs effect and every second all of them will be executed.
> Retry on 503 when concurrent request control enabled

- release-notes/latest.md
- web/elm/benchmarks/Benchmarks.elm
- web/elm/src/Build/Build.elm
- web/elm/src/Build/Models.elm
- web/elm/src/Message/Callback.elm
- web/elm/src/Message/Effects.elm
- web/elm/src/Message/Subscription.elm
- web/elm/tests/BuildTests.elm
- web/public/elm-setup.js
Fixes #5454 .
* Add `scrollToId` port that periodically checks if the parent and target element exist, and once both do, scrolls the target to the top of the parent
* Remove now unused `ScrollCompleted` callback
With concourse/concourse#5275, I had attempted to fix scrolling to IDs
on the build page. While this sometimes worked, if it takes a long time
to render the log lines (common when there are many log lines), we would
fail to scroll since the ID did not yet exist on the page.
To fix this, revert the `scrollToId` behaviour to before
495904da500188d89a9c9e62071d4ac0e3205ed7 i.e. use ports for this. Note
that the behaviour isn't exactly the same - rather than using
`scrollIntoView`, which moves the top of the element to the top of the
screen, set the `scrollTop` of the parent to …
> web: behaviour: convert scrollToId to use a port

- README.md
Per issue: https://github.com/concourse/concourse/issues/5636
[Anti-patterns page]: https://github.com/concourse/concourse/wiki/Anti-Patterns
The onboarding documentation is harder to follow without the change in this PR
Making the onboarding documentation easier to follow
closes #5636
Changes the relevant section of the readme
No tests are included, since the readme isn't a tested section of the repo
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are …
> Changing "$target" to "ci" in the readme

- atc/db/pipeline_factory.go
- atc/db/team.go
- atc/db/team_factory.go
- atc/db/team_factory_test.go
- release-notes/latest.md
Per https://github.com/concourse/concourse/discussions/5412#discussioncomment-7929, the UI shows teams in order of creation time, which doesn't make much sense, because nobody would remember when teams are created, so that such order roughly equals to random order.
Some users might be many teams, such "random" team order makes users hard to find a team on the UI.
To sort teams on the UI by team name.
Just changing order by team id to order by team name.
There is already an index on team name, thus order by team name should not hurt sql query performance.
and …
> Sort team by name on the UI.

- worker/workercmd/guardian.go
fixes #5643
Making `guardian.go` Linux-only.
> cmd/concourse: only build Guardian code on Linux

- .github/pull_request_template.md
took a stab at the PR template, in the hope that it becomes simpler and
easier to fill.
- The current PR template might be a bit too much for folks contributing to Concourse, as it has been a little too much for the Concourse team themselves.
- Based on feedback from the team, and going through a lot of PR templates in other popular repos. I came up with this slightly changed format.
- [rendered md](https://github.com/concourse/concourse/blob/pull-request-template/.github/pull_request_template.md)
> A more simple PR template

- atc/db/team.go
- atc/db/team_test.go
- release-notes/latest.md
Fixes https://github.com/concourse/concourse/issues/5606
It filters out the jobs which need updates when the provided old job name is the same as the existing job name.
> atc: db: fix panic when old job name is unchanged

- fly/commands/unpause_pipeline.go
- fly/integration/error_handling_test.go
- fly/integration/unpause_pipeline_test.go
Currently the only way for users to unpause pipelines from different teams with Fly is to create multiple targets. See #5215 
Allow unpausing pipelines in teams other than the default configured for the target.
Adds `--team` flag to `unpause-pipeline` command which overrides the default configured for the target.
> fly: add --team flag to unpause-pipeline

- atc/exec/task_step.go
- release-notes/latest.md
- testflight/fixtures/task_vars.yml
- testflight/task_vars_test.go
> Make task vars to be interpolated from var_sources and load_var.

- atc/atccmd/command.go
- atc/builds/tracker.go
- atc/engine/engine.go
- atc/engine/engine_test.go
- atc/engine/enginefakes/fake_engine.go
- atc/engine/enginefakes/fake_runnable.go
- atc/lidar/checker.go
- atc/lidar/checker_test.go
- atc/scheduler/algorithm/suite_test.go
- tracing/tracer.go
- tracing/tracer_test.go
Refactor - closes #5654.
Some interesting refactors around the tracing package allowed us to make more effective use of the testtrace package from opentelemetry. Hopefully this will assist tracing-related testing efforts in the future.
Having the correct context available for the check step should unblock efforts to propagate span context into check containers (#5423) or resource versions (#5602).
Commit messages are fairly thorough. …
> atc: structure: check step runs in the same context as checker

- atc/creds/vault/api_client.go
This PR allows you to use the [Vault Okta Auth Backend](https://www.vaultproject.io/docs/auth/okta)  for authenticating to vault.  Like the [previous PR for Vault LDAP](https://github.com/concourse/concourse/pull/3884) using the okta backend works differently from a REST convention standpoint.  
As this is a one line change that is only adding behavior to something that requires a lot of integration tests, I believe the reasoning given in https://github.com/concourse/concourse/pull/3884 would also apply here.
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/ …
> feature: support vault okta backend auth

- topgun/k8s/external_worker_test.go
Fix the concourse.worker.tsa.hosts for
https://github.com/concourse/concourse-chart/pull/96
With pull request concourse/concourse-chart#96 tsa (workerGateway) k8s service is separated. `concourse.worker.tsa.hosts` is updated in tests to support this
Update k8s test for concourse/concourse-chart#96 
@taylorsilva reviews concourse/concourse-chart#96  …
> topgun: behavior: fix concourse.worker.tsa.hosts

- web/elm/src/Application/Application.elm
- web/elm/src/Build/Build.elm
- web/elm/src/Build/Styles.elm
- web/elm/src/Dashboard/Dashboard.elm
- web/elm/src/Dashboard/Models.elm
- web/elm/src/Dashboard/Pipeline.elm
- web/elm/src/Dashboard/Styles.elm
- web/elm/src/FlySuccess/FlySuccess.elm
- web/elm/src/HoverState.elm
- web/elm/src/Job/Job.elm
- web/elm/src/Message/Callback.elm
- web/elm/src/Message/Effects.elm
- web/elm/src/Message/Message.elm
- web/elm/src/NotFound/NotFound.elm
- web/elm/src/Pipeline/Pipeline.elm
- web/elm/src/Resource/Resource.elm
- web/elm/src/SideBar/SideBar.elm
- web/elm/src/SideBar/Styles.elm
- web/elm/src/SubPage/SubPage.elm
- web/elm/src/Tooltip.elm
- web/elm/tests/BuildTests.elm
- web/elm/tests/DashboardTooltipTests.elm
- web/elm/tests/Data.elm
- web/elm/tests/PipelineCardTests.elm
- web/elm/tests/PipelineGridTests.elm
- web/elm/tests/SideBarTests.elm
- web/elm/tests/TooltipTests.elm
When the `ListAllJobs` endpoint is disabled, the 'sync' icon that appears on pipeline cards is just _begging_ to be clicked, but it's not clickable. This will very-probably frustrate users.
Add an explanatory tooltip when hovering over the icon.
closes concourse/concourse#5578.
Use the functions from the `Tooltip` module, and refactor the other tooltips in the Dashboard modules to follow suit.
At least for now (@matthewpereira may jump in and change this requirement), the style matches the current visibility tooltip:
> web: behaviour: add tooltip to sync icon

- fly/commands/login.go
- fly/integration/login_insecure_test.go
- fly/integration/login_test.go
- fly/integration/rename_pipeline_test.go
- fly/integration/rename_team_test.go
- fly/integration/suite_test.go
- release-notes/latest.md
closes #5624
Before 6.1.0 fly would exit 1 and display an error if the user logged in
with an invalid team. This commit brings back this behaviour. …
> fly: tell user when team is invalid

- atc/db/build.go
Fixes #5612
There has been some noticeable slowness to the starting of builds after a change was made to the scheduler where it is no longer responsible to start the build that it scheduled 3a6a9b8#diff-ec5d156bedf6973365a4b99c7af3d828L197. This means that after a build is marked as `started` by the scheduler 
https://github.com/concourse/concourse/blob/c57de700a5a038ed7db3fe27f109cb0a7eda725f/atc/scheduler/buildstarter.go#L216-L220
it will have to wait for the next tick of the `build tracker` before the build is "actually" started (actually started as in the steps are run).
https://github.com/concourse/concourse/blob/c57de700a5a038ed7db3fe27f109cb0a7eda725f/atc/builds/tracker.go#L56-L60
The build tracker runs on it's own 10 second interval so users can see an extra 10 second delay after …
> Send a notification to the build tracker when a build starts

- web/elm/src/Dashboard/Dashboard.elm
- web/elm/tests/DashboardCacheTests.elm
closes #5669.
In the old model of `FetchResult`, there were three distinct states for the entire set of pipelines -- `None`, `Cached` and `Fetched`. However, part of the work done in #5529 was preliminary refactoring to allow each pipeline to have its own `.stale` state. This would be important for implementing #5556. However, I kinda got it wrong by just reusing the `changedFrom` funtion. This way ensures that stale data cannot overwrite fresh data -- the only way stale data results in a UI change is if there was previously no data at all!
For manual verification, I found it valuable to inject some slowness to the interactions with localStorage. This makes the reproduction steps described by @aoldershaw in #5669 very consistent.
```diff
diff --git …
```
> web: behaviour: fresh data over stale

- atc/metric/emitter/newrelic.go
- release-notes/latest.md
checks field was not initialized so "checks delete" event causes an error "invalid memory address or nil pointer dereference"
* Bug Fix: checks field was not initialized so "checks delete" event causes an error "invalid memory address or nil pointer dereference"
* Feature: Proxy support for NewRelic emitter
closes: #5222  …
> atc: structure: fix NewEmitter structure by adding checks field

- atc/db/build.go
- atc/db/build_test.go
closes #5477
- We utilized `resolve_error` in the next_build_inputs table to recode an readeble error if the build input version has disappeared from the db.
- this resolve_error would then be picked up during build preparation stage and shown in UI
- ~~We are still unable to reproduce the main error in a manual test~~ reproduce/acceptance steps see in first comment …
> atc/db: readable error for missing input version

- atc/worker/artifact_source.go
- atc/worker/image/image.go
- atc/worker/volume.go
- atc/worker/worker.go
- release-notes/latest.md
- tracing/tracer.go
Fixes #5572 
See #5572 
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text). 
- Update the `docker-compose.yml` with two diff. workers to use diff. tags (e.g we used `workerb` in the following example)
- Run `docker-compose -f docker-compose.yml -f hack/overrides/jaeger.yml up --build -d` 
- You can use the following `pipeline.yml` for testing
```pipeline.yml
---
resources:
- name: my-image
source:
repository: busybox
jobs:
- name: create-and-consume
public: true
plan:
- get: my-image
- task: make-a-file
tags: [workerb]
image: my-image
config: …
```
> Tracing for Image Streaming

- atc/exec/load_var_step.go
- atc/exec/set_pipeline_step.go
- release-notes/latest.md
To add tracing to steps `load_var` and `set_pipeline`.
This is a tiny change, just added tracing to steps `load_var` and `set_pipeline` similar to `get/put/task/check` steps.
NA
> added tracing to load_var and set_pipeline.

- atc/db/build_test.go
Fix https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/unit/builds/293.1#L5ecac689:164:167 
that introduced by PR #5675 
Change:
use a suitable omega matcher and the resource that has only one version for testing.
> fix flaky test for resolve error

- worker/runtime/integration/integration_test.go
The `containerd-integration` build seems to be kind of flaky - I'm guessing the 1 second timeout is just too short when the worker is running multiple things.
Bump the 1 second timeout to 10 seconds, and also clean up the process and tmpdir if starting fails. (TearDownSuite won't run if StartUpSuite failed.)
**note**: I also changed the `containerd` path to just `containerd` instead of an absolute path and passed a `--state` flag pointing to our tmpdir, in the interest of making these tests easier to run on a Linux dev machine, but that effort hasn't paid off since the tests need to be run as `root` anyway. :/ If this passes in CI as-is I think it'd be worth merging anyway but I may be missing some other reason for hardcoding the path. Happy to back it out since it's not technically …
> containerd integration: fix some setup flakiness

- atc/atccmd/command.go
Documentation
I edited the description for `max-checks-per-second` in the concourse-bosh-release so I wanted to keep it consistent throughout the repositories.
https://github.com/concourse/concourse-bosh-release/pull/110#discussion_r438995788 …
> Edit description of max checks per second

- web/elm/benchmarks/Benchmarks.elm
- web/elm/src/Application/Application.elm
- web/elm/src/Build/Build.elm
- web/elm/src/Dashboard/Footer.elm
- web/elm/src/Job/Job.elm
- web/elm/src/Message/Effects.elm
- web/elm/src/Message/Message.elm
- web/elm/src/Message/Storage.elm
- web/elm/src/Message/Subscription.elm
- web/elm/src/NotFound/NotFound.elm
- web/elm/src/Pipeline/Pipeline.elm
- web/elm/src/SideBar/SideBar.elm
- web/elm/src/SideBar/State.elm
- web/elm/src/SideBar/Styles.elm
- web/elm/src/SideBar/Views.elm
- web/elm/tests/ApplicationTests.elm
- web/elm/tests/Build/HeaderTests.elm
- web/elm/tests/DashboardTests.elm
- web/elm/tests/PipelineGridTests.elm
- web/elm/tests/PipelineTests.elm
- web/elm/tests/ResourceTests.elm
- web/elm/tests/SideBarFeature.elm
- web/elm/tests/SideBarTests.elm
closes #5462  .
This is especially relevant for 6.4.0 as we try to improve the usefulness of the sidebar (and, in effect, make the sidebar more narrow with the addition of the favouriting icon).
* Add an invisible resize handle to the right side of the sidebar
* Store sidebar size in session storage (along with whether it's open or not) …
> web: resizable sidebar

- hack/oc-agent/config.yml
- hack/overrides/jaeger.yml
A mild improvement to developer experience.
Let's start exercising the opencensus agent, which is good at adapting to other tracing backends. This change adds it as a pass-through middleman but should have no other notable impact on dev workflows.
To verify, it should be enough to `docker-compose -f docker-compose.yml -f hack/overrides/jaeger.yml up -d`, see the opencensus agent running and still see traces properly displayed in jaeger. …
> hack: add opencensus agent when jaeger is enabled

- release-notes/latest.md
To avoid an additional review cycle in #5758 (which did not have a release note), I added one here.
tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-d …
> add release note for task vars fix

- release-notes/latest.md
- web/elm/src/Application/Application.elm
- web/elm/src/SideBar/Styles.elm
- web/elm/tests/ApplicationTests.elm
- web/elm/tests/SideBarFeature.elm
* Minor style changes that were bothering me:
* Change the cursor from `ew-resize` to `col-resize`
* Disable highlighting when resizing sidebar
* Added release note in #5782
the …
> web: style changes to resizable sidebar

- web/assets/css/utils.less
- web/elm/src/Build/Header/Header.elm
- web/elm/src/Dashboard/Styles.elm
- web/elm/src/Job/Job.elm
- web/elm/src/Pipeline/Pipeline.elm
- web/elm/src/Resource/Resource.elm
- web/elm/src/Resource/Styles.elm
- web/elm/tests/Build/HeaderTests.elm
- web/elm/tests/JobTests.elm
- web/elm/tests/PipelineTests.elm
- web/elm/tests/ResourceTests.elm
- web/elm/tests/TopBarTests.elm
* Fix search bar appearance on small screens and on Firefox
* Remove access to buttons in Pipeline, Job, Build, and Resource views for archived pipelines
* Search bar appearance issues:
* [master] on small screens, looks like:
* [master] on Firefox, looks like:
* To test removal of buttons for archived pipelines:
1. `fly archive-pipeline` a pipeline with resources and builds
1. Navigate to it using the sidebar
1. Check out the various screens for that pipeline (Pipeline, Job, Build, and Resource) - you shouldn't be able to perform any actions
* For Resource, you should test it with and without a pinned version, since there are different buttons available in each case
[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT. …
> web: archived pipelines UI beyond Dashboard

- atc/config.go
- atc/exec/set_pipeline_step.go
- atc/exec/set_pipeline_step_test.go
- atc/plan.go
- atc/public_plan.go
- atc/public_plan_test.go
- atc/scheduler/factory/build_factory.go
- testflight/fixtures/set-pipeline.yml
- testflight/set-pipeline-step_test.go
Feature
Allow "team" parameter to be used for "set_pipeline" steps
- Omitting the parameter uses the current team
- Specifying it targets a particular team
- Specifying it requires the team to be an Admin team (main)
We currently use the [`concourse-pipeline-resource`](https://github.com/concourse/concourse-pipeline-resource) to manage a few pipelines for other teams.
It would be more elegant if this could be done via the `set_pipeline` step. We currently have a local user for each of our tenant teams, for this purpose.
Pertains to https://github.com/concourse/rfcs/pull/31:
- Requested: https://github.com/concourse/rfcs/pull/31#issuecomment-601621064
- Vito comments: https://github.com/concourse/rfcs/pull/31#issuecomment-625273371
I think admin teams (main) be able to set pipelines is …
> Allow set_pipeline can be used across teams

- hack/opa/policy.rego
- hack/overrides/opa.yml
closes # .
(for example, if they are Garden …
> hack: add opa override and no-op setup

- fly/commands/internal/flaghelpers/completion.go
- fly/commands/pipelines.go
- fly/integration/pipelines_test.go
- fly/integration/print_table_matcher_test.go
- release-notes/latest.md
> fly: Include archive flag

- fly/commands/login.go
- fly/integration/login_test.go
- go.mod
- go.sum
- release-notes/latest.md
closes #5717 .
On OSX, there's some magic constant of 1024 characters, which is the
length of some TTY buffer. Not sure of the specifics, but essentially
you weren't able to paste tokens longer than 1024 characters in `fly
login` for the "or enter token manually" option.
Rather than doing a `fmt.Scanf`, use a module that enables raw mode and
doesn't impose any limits on the line length. It was surprisingly
difficult to find a module that did what I wanted in a nice way.
* vito/go-interact depends on golang.org/x/crypto/ssh/terminal which
imposes a seemingly arbitrary line length limit of 4096. We could
remove this limit, but then we'd need to maintain a fork.
* chzyer/readline is *really* slow when pasting long text. I think it
re-renders for every …
> fly: allow pasting long tokens into login

- testflight/resource_type_check_test.go
Fix a flaky testflight test
closes #5820 .
Run a fly `check-resource` to make sure initial version is fetched first.
There are two possible cases for this test
Scenario 1
```
---- scanner run just finished (so there is a 10s interval before next tick)
---- pipeline unpaused
---- fly check-resource-type -r custom-rsource-type -f newVersion
<------ check 1 for custom-resource-type is created.
<------ checker got notified since it is manually triggered. 
<------ check 1 is ran and newer version returned.
---- build triggers
---- get step
---- run a check on resource my-resource-image using custom-resource-type image with new version
---- test garanteed to pass
```
Scenario 2
```
---- pipeline unpaused
---- scanner run ticked
---- scanner check my-resource-image
---- scanner check …
```
> make sure version checking synchronously in testflight flaky test

- fly/commands/login.go
Our unit test suite was failing on our darwin and windows workers due to
the following error message: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/unit/builds/323#L5eea6b9f:103
```
error: liner: function not supported in this terminal
```
This occurs in the liner package when running the `PasswordPrompt` when
one of the following occurs:
1. the terminal isn't supported (which we were already covering)
2. the number of columns is 0
Rather than trying to infer from the error message (which is generally
considered bad practice and could be brittle), fallback to the
non-password prompt on any error (that isn't a Ctrl+C or EOF).
Note that I haven't actually tested this since I'm not sure how to
simulate a zero-width terminal
[Code of …
> fly: behaviour: fix manual token input on zero-column terminals

- atc/lidar/scanner.go
This is a tiny fix of a lidar log. I found this bad log during debugging an issue today. No need to mention this fix in release note. …
> fixed a bad lidar log.

- fly/commands/login.go
- fly/pty/open_raw_term_windows.go
- fly/pty/readline.go
- go.mod
- go.sum
There's more context in the first commit message, but tl;dr the library we switched to for reading in the token on stdin didn't behave so well on Windows (at least on git bash and in the test suite, seemed fine in Powershell).
The library tried to be smart about things based on the width of the terminal (because the library does smart things), but Windows was reporting that the terminal had 0 width for some reason. However, we don't really *need* a library that does smart things - we just need to read a line of text from the terminal and hide the output. 
* Ditch peterh/liner in favour of using raw mode ourselves and reading the input character-by-character, dealing with some special characters (ctrl+C, backspace, new line/carriage return).
This …
> fly: fix fly login manual input on windows

- cmd/concourse/concourse_test.go
No code change, just resolving a flaky test.
Whenever this test flakes, it seems like a timing issue, so let's be a bit more generous.
I've noticed this test flaking for a while now, and it's integrating across a wide boundary -- I think it's OK to simply make it a bit more permissive.
On the other hand, it's a very small piece of validation logic that is being tested, which would be a natural candidate for a unit test. We may have a bit of a separation problem here.
On the other _other_ hand, we're going to revisit configuration soon so it might make sense to pay down this pre-existing tech debt later when we're doing the right thing anyway. …
> cmd: structure: increase timeout for system claim error test

- web/elm/src/Resource/Resource.elm
- web/elm/tests/ResourceTests.elm
Bug Fix
A quick text changed for `checking successfully`
> web: behaviour: text change for resources `checked successfully`

- web/elm/src/SideBar/Views.elm
It was no longer being displayed after a regression in
concourse/concourse#5778 since the dom id was being applied to the full
width of the pipeline element rather than the text element itself,
meaning the `clientWidth` never differed from the `scrollWidth`. This
results in us not knowing when the text is ellipsized.
Place the Dom ID on the text container rather than the outer wrapper element …
> web: behaviour: fix tooltip on pipeline names

- topgun/common/common.go
related: concourse/ci#278
- This fixes an issue with the 2 regexes that get the bosh instances and jobs, since an extra field was added after bosh 6.
- This will also be backwards compatible.
- it needs to pass bosh tests. …
> topgun: Fix regex to support bosh 6.x

- atc/builds/tracker.go
- atc/builds/tracker_test.go
- atc/engine/engine.go
- atc/engine/engine_test.go
- atc/exec/aggregate.go
- atc/exec/aggregate_test.go
- atc/exec/in_parallel.go
- atc/exec/in_parallel_test.go
- atc/lidar/checker.go
- atc/lidar/checker_test.go
- atc/lidar/scanner.go
- atc/lidar/scanner_test.go
- atc/scheduler/runner.go
- atc/scheduler/runner_test.go
- release-notes/latest.md
Feature 
closes #3594.
Add `recover()` to go routines around core scheduler, lidar and build engine. It will capture the panic and log it in stderr and logger.
> Add recover to concourse core to prevent panic

- CONTRIBUTING.md
- release-notes/v6.4.0.md
> release-notes: structure: update 6.4.0 release notes

- atc/configvalidate/validate_test.go
- atc/exec/retry_step.go
- atc/exec/retry_step_test.go
- atc/step_validator.go
- release-notes/latest.md
closes #5077  .
* Step validation now disallows `attempts: 0`
* Don't panic if `RetryStep` doesn't have a `LastAttempt`
Prior to this fix, the panic is easy to reproduce - just set a pipeline with some step that has `attempts: 0`.
We don't have a reproducible where `RetryStep` panics even with `attempts > 0`, but this should fix that issue as well. …
> atc/exec: don't panic on RetryStep

- atc/configvalidate/validate.go
- atc/configvalidate/validate_test.go
- atc/job_config.go
- atc/step_validator.go
- atc/steps.go
- atc/steps_test.go
Sibling PR to #5878 for the 6.4.x release branch
(for example, if they are Garden …
> 6.4.x: atc: ignore unknown step fields when reading from DB

- release-notes/v6.4.0.md
- add attribution for community PRs
Update 6.4.x release notes and shoutout for community PRs
tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distrib …
> release-notes: structure: update 6.4.x

- topgun/common/common.go
Build failures - https://ci.concourse-ci.org/teams/main/pipelines/release-6.4.x/jobs/bosh-topgun/builds/11
Cherry-pick [this fix](https://github.com/concourse/concourse/commit/3295bbd95ad6b84d923fad6b777fb6970067f1a0) onto the release/6.4.x branch
closes # . …
> Fix bosh topgun 

- fly/commands/internal/setpipelinehelpers/atc_config.go
- fly/integration/set_pipeline_test.go
Feature: The `fly set-pipeline` command printed a helpful hint about the pipeline being paused, on initial pipeline creation. Some users have reported being confused when they missed this message, tried to update a pipeline later on, and did not see builds running. That might happen because the pipeline was always paused, or because they didn't realize somebody else had paused it at some point in the several months since they last thought about it. This PR causes the helpful hint to be shown whenever the configuration of a paused pipeline is successfully created _or updated_.
This is limited to the client side in `fly`. The `showPipelineUpdateResult` helper gets an extra flag `paused` to tweak its behavior depending on whether or not the pipeline is paused, and this controls the printed …
> fly: always warn on set-pipeline if pipeline is paused

- atc/exec/set_pipeline_step.go
- atc/exec/set_pipeline_step_test.go
- testflight/set-pipeline-step_test.go
This is a substitution of #4857 as it is too out-of-date, no way to rebase, so I just start over.
In #4857, "self" is replaced with real pipeline name in the first place, which leads to a lot of interface changes. In this change, I just do that in the set_pipeline step, so this is a tiny change. I take the way because:
1. I forget what was the comment that requested me to replace "self" in the first place.
2. If we do the replacement in the first place `build_factory`, then that also requires a lot of interface changes. As this is considered as an experimental feature, could be reverted in future, it's better to constraint the change scope.
3. Also, if we replace in the first place, as we need to print warning message in set_pipeline step, then we have to add a flag in SetPipelinePlan to …
> feat(atc): support "set-pipeline: self"

- web/elm/src/FlySuccess/FlySuccess.elm
- web/elm/src/FlySuccess/Models.elm
- web/elm/src/FlySuccess/Styles.elm
- web/elm/src/FlySuccess/Text.elm
- web/elm/src/Message/Message.elm
- web/elm/tests/FlySuccessFeature.elm
Some customers have security policies to disable automated copy/paste in the browser.  Copying using the 'manual' (ctrl+c / right-click + copy) methods still work as expected.  This change allows the user to manually copy the token.
Fixes #4914.
* This change allows the user to manually copy the token, by adding the token text to the `fly_success` page
> Add the token text to the fly_success page.

- go.mod
- go.sum
- tsa/tsacmd/command.go
This pull request fix the issue #1105 by adding TSA support for reloading authorized keys without restart based on signal `SIGUSR1`
As described in #1105 and #3551 it is really handy for HA purpose to be able to add worker keys without having to restart a Concourse web/TSA process.
It also rely on this pull request that have been merged https://github.com/concourse/flag/pull/5
Provide a solution for user to dynamically add or remove worker keys without having to restart Concourse.
closes #1105 .
I choose to use signal `SIGHUP` that any user can send with the following command:
```
kill -s SIGHUP <PID of Concourse web>
```
The implementation is really simple and for a user point of view it's really easy to send this signal to concourse when you update any authorized keys file.
Signal usage …
> tsa: handling of SIGHUP to reload workers keys

- atc/exec/load_var_step.go
- atc/exec/load_var_step_test.go
Some resource types as well as tasks generate output files with tailing "\n", for example https://github.com/concourse/docker-image-resource#in-fetch-the-image-from-the-registry all output files have tailing "\n".
When `load_var` reads file as `raw` format, tailing "\n" may make following steps hard to use the var. For example:
```yaml
- load_var: image_repo
file: image/repository
- load_var: image_tag
file: image/tag
- some-step:
params:
uri: ((.:image_repo)):((.:image_tag))
```
The `uri` expects an image uri, like `some-image:some-tag`, but as `load_var` carries tailing newlines, `uri` will actually be `some-image:\nsome-tag\n". 
Add a params `trim_raw` to `load_var` step, if true, then trim heading and trailing spaces of content reading from file. …
> feat(load_var): add format trim and make it default

- go.mod
- go.sum
closes # .
This updates the Baggageclaim dependency to the latest release, [1.7.0](https://github.com/concourse/baggageclaim/releases/tag/v1.7.0). Baggageclaim 1.7.0 mounts the `btrfs` loopback device with the `discard` option. This punches holes in the underlying loop file making it sparse. It will potentially result in better disk utilization. …
> upgrade to baggageclaim 1.7.0

- atc/db/migration/migrations/1595347367_add_index_for_unencrypted_private_plans_to_builds.down.sql
- atc/db/migration/migrations/1595347367_add_index_for_unencrypted_private_plans_to_builds.up.sql
This index will help speed up the query that is run when we encrypt any plain text in the database. The query that I am referring to is this
https://github.com/concourse/concourse/blob/785b3ccadf83396e1a85026d8eb9dbf72c529d57/atc/db/open.go#L148-L153
which is currently being run whenever the web nodes start up and need to open a connection to the database. The specific query that this index speeds up is `SELECT id, private_plan FROM builds WHERE nonce IS NULL AND private_plan IS NOT NULL;`. If I run an explain analyze on it on our large scale environment, it takes approximately 1 minute to complete. 
```
Seq Scan on builds  (cost=0.00..401990.09 rows=1 width=36) (actual time=73848.522..73848.522 rows=0 loops=1)
Filter: ((nonce IS NULL) AND (private_plan IS NOT NULL))
Rows Removed by …
```
> Speed up querying for unencrypted builds 

- atc/db/job_test.go
- atc/db/team.go
closes #5906.
Very small change to a query, and added a test -- this feature seems to have regressed in #4933 when we did some refactoring of the database. While there _was_ a wats acceptance test covering this, I still think a DB test is much more economical.
If you use the pipeline in the linked issue you should see that the code on master allows you to trigger the job, whereas with this change you will get the expected 409 Conflict when you attempt to trigger the job.
Fixed the [`disable_manual_trigger:`](https://concourse-ci.org/jobs.html#schema.job.disable_manual_trigger) field on jobs -- since v6.0.0 it had no effect and jobs with this setting could actually still be manually triggered. …
> db: behaviour: save disable_manual_trigger on job

- worker/container_sweeper_test.go
Co-authored-by: Rui Yang <ryang@pivotal.io>
Fixes flakey container sweeper test by increasing sweeper timeout to 1sec. for tests.
We set the timeout to 500MS but it failed at 190th run. We arte setting it to 1 sec. just to be on safer side.
closes #5174 . …
> worker: Fix flakey container sweeper test

- fly/commands/destroy_pipeline.go
- fly/integration/destroy_pipeline_test.go
- fly/integration/error_handling_test.go
Allow for users to destroying pipelines for different teams
without switching targets
concourse/concourse#5215
Signed-off-by: Ka Hin Ng <kang@pivotal.io>
Feature
* Add `--team` flag for `fly destroy-pipeline` command.
[Helm](https://github.com/concourse/helm) …
> fly: add team option to destroy-pipeline command

- atc/engine/builder/delegate_factory.go
- atc/event/events.go
- atc/event/parser.go
- atc/event/parser_test.go
- atc/event/types.go
- atc/exec/build_step_delegate.go
- atc/exec/execfakes/fake_build_step_delegate.go
- atc/exec/execfakes/fake_check_delegate.go
- atc/exec/execfakes/fake_get_delegate.go
- atc/exec/execfakes/fake_put_delegate.go
- atc/exec/execfakes/fake_task_delegate.go
- atc/exec/get_step.go
- atc/exec/put_step.go
- atc/exec/task_step.go
- atc/runtime/runtimefakes/fake_starting_event_delegate.go
- atc/runtime/types.go
- atc/worker/client.go
- atc/worker/client_test.go
- fly/eventstream/render.go
- fly/eventstream/render_test.go
- release-notes/latest.md
- web/elm/src/Build/Output/Output.elm
- web/elm/src/Build/StepTree/Models.elm
- web/elm/src/Concourse/BuildEvents.elm
Fixes: #5795
This PR adds an opt-in feature where worker name can be injected into get/put step's metadata. 
The build log page and `fly watch` now display the worker name for `get/put/task` steps
[Helm](https://github.com/concourse/helm) packaging; otherwise, …
> feat: added a new event type SelectedWorker

- go.mod
- go.sum
Update to use latest version of concourse/dex that fixes concourse/dex#7
Anyone using gitlab to configure their teams will need to update their team config's if they were defined using Gitlab users. If teams were defined with Gitlab groups then no changes are needed. …
> Update go mod with latest changes in concourse/dex

- atc/path_flag.go
- fly/commands/set_pipeline.go
- fly/integration/set_pipeline_test.go
- release-notes/latest.md
feat: allow set-pipeline to take configure from stdin. this would make pipeline migration from one cluster to the other easier.
With this feature a user may migrate a pipeline from one cluster to the other with a single line command:
```bash
$ fly -t <target1> gp -p <pipeline-name> | fly -t <target2> sp -c - -p <pipeline-name> -n
```
Modified `PathFlag` to accept `-`. When `-` is given, it generate a temp file by reading from stdin.
I see a couple of problems with this implementation:
1. The second `fly sp` must be given `-n`, otherwise `apply configuration? [yN]: bailing out`. As the question/answer is done by @vito's packet `interaction`, I wonder if @vito has idea with that.
2. `set-pipeline` command actually takes multiple `PathFlag`, `-c`, `-l`, only at most a single flag can use …
> Allow `fly set-pipeline` to take configuration from stdin

- fly/integration/set_pipeline_test.go
636eade4355ec5e8ed40e434f25cfcf97bbc843d attempted to ignore a test for windows, but it added the `runtime.GOOS` check inside an `Expect(... ReceivedRequests()).To(Change(By(...)))`. So, since we short circuit on windows, the received requests doesn't change at all., and the test fails.
Moreover, a later commit in the PR #5861 (71305ef18c233c3e44fb00288195f39ed64d430d) removed the "ignore windows" behaviour - so we should just get rid of the `runtime.GOOS` check altogether.
[Signed]: …
> Remove ignored windows fly test case

- release-notes/latest.md
- tsa/cmd/tsa/register_test.go
- tsa/cmd/tsa/suite_test.go
- tsa/heartbeater.go
- tsa/heartbeater_test.go
- tsa/tsacmd/command.go
- tsa/tsacmd/remote_cli.go
- tsa/tsacmd/server.go
closes #5146 
- tsa uses the concourse/gclient rather than cloudfoundry/garden 
Since the gclient used by the TSA is used for heartbeating, I assumed its safe that it won't have explicit keep-alive configured. Furthermore, there is keepalive logic on the [TSA client](https://github.com/concourse/concourse/blob/master/tsa/keepalive.go) for the underlying ssh connection from the worker.
With the default heartbeat interval, I observed the keepalive timer resetting indefinitely using ` netstat -nto | grep GARDEN_PORT_ON_THE_WEB` on the web node 
Also, tried to pull the gclient into a more common path (eg. root of the repo) since it is used by atc, worker & tsa. However, it unfortunately has a bunch of dependencies on `atc/worker` at the moment and hence I felt it didn't make sense to move it …
> TSA uses concourse's gclient with a configurable timeout instead of the cloudfoundry/gardent/client

- .github/pull_request_template.md
Documentation
Edited the pr template to respect the new release note generation process. The title will be used to generate the release note for each pull request and the author also has the option of adding a description to the release note for the changes made in the pr under the `## Release Note` header.
#5768  …
> Edit pr template to include new release note generation process

- testflight/fixtures/set-pipeline.yml
Since we were calling `set_pipeline: self` but removing the job that set the pipeline initially,  the pipeline would occasionally get archived prior to triggering the "normal-job" job. This would cause fly to hang forever since archived pipelines are effectively paused.
> testflight: prevent pipeline from getting GC'd

- atc/db/migration/migrations/1595347367_add_index_for_unencrypted_private_plans_to_builds.up.sql
closes #5948 .
* Remove `private_plan` from index in existing migration
* When the `private_plan` was of moderate size (>2700 bytes), scheduling would error as the plan would not fit in the index (since the btree maximum size is 2704 bytes)
* The query won't be quite as fast since we can't just use the index, but it should still be faster than having no index since we don't need to scan the builds table …
> Remove private_plan from index

- atc/steps.go
- atc/steps_test.go
closes #5869
A small change to the json parsing logic used when parsing steps in a job plan. Basically adding a bool flag to let us know if a step contains any core step types or not. If none are found then an error is returned.
Now a user will get:
```
$ cat pipeline.yml
jobs:
- name: job
plan:
- attempts: 1
$ fly -t dev sp -p hope-this-doesnt-panic -c pipeline.yml
error: error unmarshaling JSON: while decoding JSON: no core step type declared (e.g. get, put, task, etc.)
```
If you use an old version of fly you'll only get the error after hitting the API when trying to set the pipeline. If you recompile fly based on this branch then fly will catch the error locally.
**Open question:** The original issue is about a panic. This PR prevents the panic …
> Return error when a step only contains modifiers

- web/elm/tests/ApiEndpointsTests.elm
- web/elm/tests/Build/HeaderTests.elm
- web/elm/tests/BuildTests.elm
- web/elm/tests/Common.elm
- web/elm/tests/DashboardPreviewTests.elm
- web/elm/tests/DashboardSearchTests.elm
- web/elm/tests/DashboardTests.elm
- web/elm/tests/DashboardTooltipTests.elm
- web/elm/tests/Data.elm
- web/elm/tests/JobTests.elm
- web/elm/tests/PauseToggleTests.elm
- web/elm/tests/PinMenu/PinMenuTests.elm
- web/elm/tests/PipelineCardTests.elm
- web/elm/tests/PipelineGridTests.elm
- web/elm/tests/PipelineTests.elm
- web/elm/tests/ResourceFeature.elm
- web/elm/tests/ResourceTests.elm
- web/elm/tests/SideBar/PipelineTests.elm
- web/elm/tests/SideBarFeature.elm
- web/elm/tests/SideBarTests.elm
- web/elm/tests/SubPageTests.elm
- web/elm/tests/TooltipTests.elm
- web/elm/tests/TopBarTests.elm
**tl;dr** this only cleans up tests - when we implement pipeline instances in the UI, we'll need to make changes to all of these tests anyway (else we'll encounter syntax errors)
Adding new fields to identifiers is a pain (as you can probably tell from this PR) because it introduces compiler errors in probably >100 tests.  Rather than each test defining its own identifiers, use default ones + helper functions (e.g. `withName "new-value"`) that transform the default values.
The motivation for this is to prepare for pipeline instances which will introduce a new parameter for identifying pipelines (and therefore also jobs, resources, and resource versions). With this change, when we add a new field to the identifier records, we'll only need to change the default values in the `Data` module. …
> Elm tests use Data module for identifiers

- hack/overrides/containerd.yml
- topgun/k8s/dns_proxy_test.go
- worker/integration/integration_test.go
- worker/workercmd/containerd.go
- worker/workercmd/guardian.go
- worker/workercmd/worker.go
- worker/workercmd/worker_linux.go
- worker/workercmd/worker_nonlinux.go
closes #5407.
`containerd` specific flags have been put under their own namespace and are now prefixed with `CONCOURSE_CONTAINERD` to prevent confusing them with Guardian flags and features.
Guardian flags will still be prefixed with `CONCOURSE_GARDEN`. However, this PR changes many internal references to the terms Garden, Guardian, server, and backend to reduce ambiguity for developers.
Corresponding update to Helm chart: https://github.com/concourse/concourse-chart/pull/131
Corresponding update to BOSH release: https://github.com/concourse/concourse-bosh-release/pull/112
Corresponding updates to CI:
https://github.com/concourse/ci/pull/356
https://github.com/concourse/ci/pull/357
Remaining TODO:
We recommend going over individual commits and commit …
> worker: prefix containerd specific flags with CONCOURSE_CONTAINERD

- atc/atccmd/command.go
- atc/engine/engine.go
- atc/exec/aggregate.go
- atc/exec/in_parallel.go
- atc/exec/on_abort.go
- atc/exec/on_error.go
- atc/exec/retry_error_step.go
- atc/exec/retry_error_step_test.go
- atc/exec/timeout_step.go
- atc/exec/try_step.go
Signed-off-by: kirillbilchenko <kirya7@gmail.com>
closes # .
Add case to cover issue like this `Put "/volumes/a2dc0c2a-5057-4d0e-794f-ae7607ce8638/stream-in?path=.": EOF` which causing all job to fail
Added test to cover this io.EOF case.
* The `--enable-rerun-when-worker-disappears` flag now supports rerunning builds after any network error from the ATC to the worker's baggageclaim. Such network errors are common when the worker disappears.
* Builds will now be rerun when this flag is enabled and the failing step is a nested step (e.g. within an `in_parallel`) …
> Rerun builds with baggageclaim network errors

- fly/commands/watch.go
- fly/eventstream/render.go
- fly/eventstream/render_test.go
Feature
closes #5938 
adding a toggle flag to `fly watch` that ignores parsing errors
of type;
- UnknownEventTypeError 
- UnknownEventVersionError
This prevents issues if a user were to trigger jobs on a version of
Concourse and then downgrade/upgrade Concourse to a version where an
event type is not recognized causing fly to bail. In such scenarios, the
user would have to determine the correct fly version to use to correctly
parse the build events, which seems quite cumbersome.
For testing, easiest method is to trigger a job in a pipeline, edit a record in the build_events_X table with a bogus event and attempt to `fly watch` the build  …
> Add flag ` --ignore-event-parsing-errors` to `fly watch` to ignore event parsing errors when an unknown event type or version is encountered. 

- topgun/k8s/dns_proxy_test.go
skip containerd dns tests which have dns proxy disabled and don't
specify dns servers to resolve in cluster addresses.
These tests should be un-skipped once
https://github.com/concourse/concourse/issues/5967 is closed …
> Skip failing k8s topgun tests for containerd without a dns proxy or dns servers configured

- atc/api/auth/check_build_read_access_handler_test.go
- atc/db/worker_lifecycle_test.go
- atc/exec/get_step_test.go
- atc/exec/load_var_step_test.go
- atc/exec/set_pipeline_step_test.go
- atc/exec/task_step_test.go
- atc/scheduler/job_scheduling_test.go
- atc/worker/choose_task_worker_test.go
- atc/worker/client_test.go
Go 1.15 added automated vetting in tests for this particular case, and it's causing our unit tests to fail.
https://golang.org/doc/go1.15#vet
Properly convert integers to strings
[Helm](https://github.com/concourse/helm) packaging; …
> fix go 1.15 int-to-string conversion warning in tests

- atc/api/auth/check_build_read_access_handler_test.go
- atc/db/worker_lifecycle_test.go
- atc/exec/get_step_test.go
- atc/exec/load_var_step_test.go
- atc/exec/set_pipeline_step_test.go
- atc/exec/task_step_test.go
- atc/scheduler/job_scheduling_test.go
- atc/worker/choose_task_worker_test.go
- atc/worker/client_test.go
Go 1.15 added automated vetting in tests for this particular case, and
it's causing our unit tests to fail.
https://golang.org/doc/go1.15#vet
Ported #5983 over
(for …
> fix go 1.15 int-to-string conversion warning

- atc/metric/emitter/prometheus.go
- atc/metric/emitter/prometheus_test.go
- atc/metric/metrics.go
- atc/metric/periodic.go
- atc/metric/periodic_test.go
- atc/worker/choose_task_worker_test.go
- atc/worker/client.go
- release-notes/latest.md
When exporting the Prometheus metric `tasks_waiting` assigns labels to easily distinguish which sets of workers the tasks are awaiting execution on.
Feature
The `TasksWaiting` metric is now assigned labels for:
* Team ID
* Worker tags: when multiple tags are defined they are joined
* Platform
of the tasks that are waiting to be executed.
Since one of the most interesting aspect of the metric is to be able to AutoScale the workers instances, the added labels allow for a more specific scaling since they differentiate the groups the workers might belong to.
Also add metric to track the amount of time the tasks spend waiting to be executed.
the …
> tasks scheduling: metrics: enhance TasksWaiting metric.

- atc/db/resource.go
Feature
This PR makes it so that we will only update the check error to nil if the check error is not already nil. This will help reduce the amount of work that the database will need to do in order to update the check error for every resource. This query is run within `SetCheckSetupError`
https://github.com/concourse/concourse/blob/d32357aeee93f6a650644dd81094b31a93a8bdae/atc/db/resource.go#L260-L278
which is called by every resource that is checked through the lidar scanner
https://github.com/concourse/concourse/blob/40d2c5af96af67b7ad15d13fe43d9d6badf1c846/atc/lidar/scanner.go#L93
In our large Concourse deployment called `hush-house`, I found that this query ranked 4th on the queries that the database spent the most total time on.
Even though the average time taken to run the query is …
> Remove unnecessary updates to the resource's `check_error` value

- atc/atccmd/command.go
- atc/db/db_suite_test.go
- atc/db/dbfakes/fake_pipeline_lifecycle.go
- atc/db/migration/migrations/1597342429_add_deleted_pipelines_table.down.sql
- atc/db/migration/migrations/1597342429_add_deleted_pipelines_table.up.sql
- atc/db/pipeline.go
- atc/db/pipeline_lifecycle.go
- atc/db/pipeline_lifecycle_test.go
- atc/db/pipeline_test.go
- atc/db/team_test.go
- atc/gc/build_log_collector.go
- atc/gc/build_log_collector_test.go
closes #5287  .
* Remove `pipeline_build_events_delete_trigger`, which previously dropped the `pipeline_build_events_x` table when the corresponding pipeline was deleted
* Instead, deleting a pipeline marks it as deleted in a new `deleted_pipelines` table
* Modify the build log collector to drop the `pipeline_build_events_x` table for each pipeline that is marked as deleted in `deleted_pipelines`
The motivation for this change is elaborated more in https://github.com/concourse/concourse/issues/5287#issuecomment-673472967, but essentially, having only one place where build events are deleted removes the risk of deadlocking here.
An alternative approach we considered was to compare …
> Prevent potential deadlock after pipeline deletion

- atc/api/policychecker/checker.go
- atc/api/policychecker/checker_test.go
- atc/policy/checker.go
Feature
Passing in the roles of the current user into the policy checks for API calls allows for a policy server like OPA to implement even more fine grained controls such as "owners can create pipelines with privileged containers but members cannot." This should allow for even more customisable roles without burdening Concourse itself with supporting all these use cases.
Should be pretty simple. I tested this with a team with a `member` and an `owner` and the correct Rego to deny members creating privileged containers and it worked as expected.
The user's team roles will now be passed to the policy checker for all API checks …
> Pass user roles to policy checker for API calls

- atc/api/api_suite_test.go
- atc/api/policychecker/checker.go
- atc/api/policychecker/checker_test.go
- atc/api/policychecker/handler.go
- atc/api/policychecker/handler_test.go
- atc/api/policychecker/policycheckerfakes/fake_policy_checker.go
- atc/policy/checker.go
- atc/policy/checker_test.go
- atc/policy/opa/opa.go
- atc/policy/opa/opa_test.go
- atc/policy/policyfakes/fake_agent.go
- atc/worker/worker.go
- hack/opa/policy.rego
- hack/overrides/opa.yml
Feature
Allow OPA documents to include an `allowed` and a `reasons` field that
gives a bit more feedback to the user about why something failed. This
allows OPA operators to write rules that are self explanatory as to why
things are getting denied.
Fly does not appear to print the full error message currently but this
works for the UI.
This represents a breaking change to the OPA API (if you can call it that) - the document returned will no longer just be a boolean and will instead be objects (though the reasons are optional, it will need to be an object of at least `{ "allowed": true/false }`
I figured whilst this feature was new was probably the time to break the contract between Concourse and OPA though rather than later when it has general opt-in 😁
I'm also happy to write some …
> atc: Allow OPA integration to return reasons for failures (breaking change)

- fly/commands/internal/executehelpers/inputs.go
- fly/integration/execute_test.go
closes #4828
Upload the current directory if:
- the name of the current directory matches one of the input names
- the input was not provided by a `--input NAME=PATH` flag as well
[Helm](https://github.com/concourse/helm) packaging; …
> fly/exec: only upload current directory if it's an input

- atc/api/accessor/claims_cacher.go
- atc/api/accessor/claims_cacher_test.go
Bug Fix
We saw a panic in concourse `v6.5.0` related to the new claims cache. It appears the claims cache makes use of a non-concurrent safe structure.
* This adds a test that can trip the race detector when tests are run with `-race`
* Adds a lock to serialise access to the LRU cache to make it safe (and pass the test)
I'm confident there is a problem here, however this may not be the correct place for the lock.
Avoid potential race in access token caching …
> atc: ensure claims LRU cache is safe for concurrent use

- fly/commands/internal/validatepipelinehelpers/validate.go
- fly/commands/internal/validatepipelinehelpers/validate_test.go
- fly/commands/validate_pipeline.go
Bug Fix: closes #6026
Feature: polishes support of `across` from #5887.
Two changes were made:
First, this adds the flag `--enable-across-step` to fly's `validate-pipeline` command in order to validate pipelines using `across` steps.
Second, in order to support testing of error conditions during validation, `validatepipelinehelpers.Validate` no longer calls `os.Exit(1)` (via `displayhelpers.Failf()`) when errors are encountered during parsing. Instead, it returns an error and relies on `main.handleError()` to do the right thing with it.
Please take a look at #6026 which explains the problem being addressed here. There's test coverage added to `fly/commands/internal/validatepipelinehelpers/validate_test.go` which should also help understand the impact.
Enable `fly validate-pipeline` to …
> Enable fly validate-pipeline to accept "--enable-across-step"

- skymarshal/skycmd/saml_flags.go
Feature
addresses #1036
[concourse/dex](https://github.com/concourse/dex) already includes the saml connector, this PR simply adds the skycmd flags required to enable saml authentication.
`--help` text).
> Support SAML 2.0 as an auth backend

- atc/api/config_test.go
- atc/api/configserver/save.go
- fly/commands/login.go
- fly/integration/login_test.go
closes #5939 
Before this PR admins could log into any teams, even those that
don't exist. If the admin did log into a team that did not exist they
would get unclear error messages when running other commands that then
tried to target the non-existant team (e.g. HTTP 500 error from
set-pipeline command).
Now an admin will know if they successfully logged into another team or
not.
The `SaveConfig` endpoint will now return a 404 when the team is not found. It previously returned 500. It's sibling endpoint, `GetConfig`, already returned 404 in this situation, so this actually brings `SaveConfig` inline with `GetConfig`.
Previously admins could log into any team, even if the team did not exist. Admins can still log into any team but now fly verifies that …
> fly: admins can login to any team that exists

- topgun/k8s/dns_proxy_test.go
- worker/runtime/cni_network.go
- worker/runtime/cni_network_test.go
- worker/runtime/integration/integration_test.go
- worker/runtime/resolvconf_parser.go
- worker/runtime/resolvconf_parser_test.go
- worker/runtime/suite_test.go
- worker/workercmd/containerd.go
The nameserver values could come from manually defined properties
or the host itself
Revert "k8s topgun: behaviour: skip containerd dns tests"
This reverts commit 0b03e84c5a1109855351787fd74296430efbcc14.
Signed-off-by: Bishoy Youssef <byoussef@pivotal.io>
Co-authored-by: Vikram Yadav <vyadav@pivotal.io>
Feature
closes #5967  .
The resolv.conf is injected into the containers created by containerd on a worker. The approach is similar to Garden behaviour: https://github.com/cloudfoundry/guardian/blob/ca905e542c224efde27f5c2070ac6c6f9bc37c0c/kawasaki/resolv.go#L30.
When setting the configuration, the priority is given to the configuration provided by the user by setting `concourse_garden_dns_servers` property. If the user …
>  use the configured resolv.conf for containerd

- atc/atccmd/command.go
- atc/db/encryption/fallback_strategy.go
- atc/db/encryption/fallback_strategy_test.go
- atc/db/migration/encryption.go
- atc/db/migration/encryption_test.go
- atc/db/migration/migration.go
- atc/db/migration/migration_test.go
- atc/db/migration/open_helper_test.go
- atc/db/open.go
- atc/postgresrunner/postgresrunner.go
**Bug Fix** | **Feature** | Documentation
closes #5959 
Also useful for #5960
* `concourse migrate` can be called with `--old-encryption-key` to rotate the encryption key (or disable encryption)
* Fixed a bug which prohibited running a migration and rotating the key (if the migration requires decrypting from the DB)
* `concourse migrate` can be called with `--old-encryption-key` to rotate the database encryption key as a one-time operation
* `concourse web` still accepts `--old-encryption-key`
* You should stop any ATCs prior to running this command
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTIN …
> Allow rotating the encryption key via `concourse migrate`

- atc/api/pipelines_test.go
- atc/api/present/pipeline.go
- atc/config.go
- atc/config_diff.go
- atc/config_diff_test.go
- atc/configvalidate/validate.go
- atc/configvalidate/validate_test.go
- atc/db/dbfakes/fake_pipeline.go
- atc/db/migration/migrations/1599738693_add_pipeline_display_info.down.sql
- atc/db/migration/migrations/1599738693_add_pipeline_display_info.up.sql
- atc/db/pipeline.go
- atc/db/pipeline_test.go
- atc/db/team.go
- atc/pipeline.go
- web/elm/src/Concourse.elm
- web/elm/src/Dashboard/Dashboard.elm
- web/elm/src/Pipeline/Pipeline.elm
- web/elm/src/Pipeline/Styles.elm
- web/elm/tests/Data.elm
- web/elm/tests/PipelineTests.elm
Allows users to quickly identify a particular pipeline visually for when pipelines are shown on dashboards and the structure may not be enough to differentiate them.
Bug Fix | _Feature- | Documentation
closes #1756
Replaces #6020 
Allow users to specify a custom background image which is put at 30% opacity, grayscaled and blended into existing background. This allows for some level of pipeline customisation without creating too many visual problems for the UI. Uses the CSS property `background-image: url('blah')` so either hyperlinks or `data:image/png;base64` etc. strings can be used. Background is rendered on update by Elm so can be hot-reloaded. 
Examples:
I made the `Display` field a pointer so that a missing field wouldn't be included in the JSON output but this means some `Maybe` …
> Custom background image

- fly/commands/login.go
- fly/commands/sync.go
- fly/rc/rcfakes/fake_target.go
- fly/rc/target.go
- fly/rc/target_test.go
- fly/rc/targets.go
- fly/rc/targets_test.go
This PR adds the ability to declare client certificates when using the `login` command for use by fly's http transport.
This stems from the fact our Concourse deployment is imposed some security requirements that are not fulfilled natively by Concourse's authentication mechanisms. With client certificates attached to every request, this allows us to _pre-authenticate_ requests at the proxy or load-balancer level before requests reach ATC without having to resort to more traditional techniques like IP allow-lists.
Just to be clear, this feature is useful as-is without anything being implemented in ATC.
This works towards fulfilling some of the asks in #578 .
This PR does mainly two things:
- It adds the ability to tack-on client certificates to the http transport for consumption by a …
> Allow the fly http transport to use client certificates

- fly/commands/sync.go
This is a follow-up to #6017, which added a new `--client-cert` flag to
`fly login` and `fly sync` - only, the latter had the flag as
`--client-certificate`, not `--client-cert`.
This was due to a review comment I left that wasn't totally clear, and I
didn't feel it was worth another review cycle to get this changed, so
here we are! …
> Make `--client-cert` flag name consistent between `fly login` and `fly sync`

- atc/atccmd/command.go
- atc/creds/manager.go
- atc/creds/pool.go
- atc/creds/pool_test.go
- atc/db/pipeline_test.go
Secret fetch has retry and cache abilities, but unfortunately those abilities don't work for `var_sources`. I missed them when I developed `var_sources`. This PR is to enable retry and cache for `var_sources`.
I have tested the code change locally.
Enable secret fetch retry and cache for `var_sources`.
[Helm](https://github.com/concourse/helm) …
> Enable secret cache for var_source.

- atc/api/configserver/save.go
- atc/builds/planner_test.go
- atc/creds/task_validation.go
- atc/exec/task_config_source.go
- atc/exec/task_config_source_test.go
- atc/plan.go
- atc/steps.go
- atc/steps_test.go
Refactor
Rather than parsing task step `params:` into an `atc.Params` type and converting values to strings when the step runs, parse into an `atc.TaskEnv` type which already handles the string conversion and is a bit more clear as to what the data is used for.
`atc.TaskEnv` was introduced a while back but could not be integrated at this level because we had one big `atc.PlanConfig` type and we couldn't change the `params:` field only for the task step. Now that it has its own `atc.TaskStep` type (#5504), this is easy!
This also fixes a subtle bug with `fly set-pipeline --check-creds`; previously we would actually validate `params:` *twice* if `file:` was set. Now we only validate it once. The main goal of this PR is the refactor, I just noticed this issue along the way and fixed it.
This …
> Use atc.TaskEnv type in task step

- package.json
- web/elm/elm.json
The `Skinney/murmur3` elm dependency was moved to `robinheghan/murmur3` which caused our elm compiling to break - https://github.com/robinheghan/murmur3/issues/5. We decided to remove the elm dependency `elm-explorations/benchmark` that uses that package until it gets fixed. We created an issue in the dependency here
https://github.com/elm-explorations/benchmark/issues/21. Once it is fixed we can restore it back to before. …
> Skip yarn benchmark until dependency is fixed

- worker/workercmd/guardian.go
- worker/workercmd/worker_linux.go
Feature
Part of https://github.com/concourse/concourse/issues/5985
If `--network-pool` is unset Guardian defaults to `10.80.0.0/22` which allows 1024 addresses, implicitly limiting a
Guardian worker to 250 containers (4 addresses reserved per container). This is true even if max-containers is set to
a higher value.
We set network-pool to `10.80.0.0/16` to increase the allowable addresses significantly ensuring the container
count is only limited by the explicit max-containers flag. If a user passes a custom value we use that instead.
**Update**
* Exposing both flags as options in the worker command now.
* Defaulting the maximum container limit to 250 to avoid stamping herd problem.
* Defaulting containerd max-container value to do the same.
More details on reasoning in an issue …
> Add new default values Guardian network-pool and max-containers

- atc/api/artifactserver/create.go
- fly/commands/execute.go
- fly/commands/internal/executehelpers/inputs.go
- fly/commands/internal/executehelpers/uploads.go
- go-concourse/concourse/artifacts.go
- go-concourse/concourse/artifacts_test.go
- go-concourse/concourse/concoursefakes/fake_team.go
- go-concourse/concourse/team.go
closes #5672.
When issuing `fly execute` and selecting a platform
where there are *only* tagged worker the command fails
because DetermineInputs does not pass along the tags
specified in the command and thus, at the end of the chain,
SelectWorkers will return that no worker satisfy the
request (because the are no untagged workers).
This commit passes the worker tags along the chain so that
the input can be set up.
[Signed]: …
> Fly execute: pass worker tags to input.

- web/public/index.html
Some people don't have JavaScript enabled all the time, this PR tells them they need it to use rather than showing a blank screen.
`--help` text).
> Remind people they need JS to run the browser app

- web/assets/css/build.less
closes #5999
Trim any trailing white spaces and wrap text on full words.
~~- [ ] Updated [Documentation]~~
~~- [ ] Added release note (Optional)~~
the …
> web: fix horizontal scrolling on build page

- fly/commands/get_team.go
- fly/integration/get_team_test.go
- go-concourse/concourse/build_inputs.go
- go-concourse/concourse/build_outputs_of.go
- go-concourse/concourse/builds.go
- go-concourse/concourse/check_resource.go
- go-concourse/concourse/check_resource_type.go
- go-concourse/concourse/concoursefakes/fake_team.go
- go-concourse/concourse/configs.go
- go-concourse/concourse/containers.go
- go-concourse/concourse/jobs.go
- go-concourse/concourse/pipelines.go
- go-concourse/concourse/resource.go
- go-concourse/concourse/resourceversions.go
- go-concourse/concourse/team.go
- go-concourse/concourse/teams.go
- go-concourse/concourse/teams_test.go
- go-concourse/concourse/version_resource_types.go
- go-concourse/concourse/volumes.go
Bug Fix
This is documented, implemented-ish, and tested-ish, but didn't work: doing `fly -t tgt get-team --team-name foo --json` would always produce the syntactically-valid but boring response `{}`. This is because the code uses the go-concourse `Team` object, which has no data members and so does very little of interest when serialized.
There was originally a test for the YAML-formatted output, but that did not run for the reasons described in 2e5d954, and there were no tests for JSON. That commit also changed the test to look at the tabular format. It appears tests of the JSON path were accidentally skipped over in the refactoring.
We now synthesize a JSON object with team and auth contents, plus the team ID (originally discarded in `go-concourse` but now stashed for this purpose). …
> Return real JSON from "fly get-team --json"

- worker/workercmd/guardian.go
- worker/workercmd/worker_linux.go
Bug Fix
CI currently breaking on this [test](https://github.com/concourse/concourse/blob/64a12a7023f7a68993730c3add624e38773eb9fd/topgun/k8s/garden_config_test.go#L61-L62). `config.ini` values get overridden by default values for Guardian.
Move `gdn` binary specific flags to own struct called, `GdnBinaryFlags`.
Using go-flags to set Concourse specific defaults for gdn binary flags overrides any value the user may pass via the config.ini file for Guardian. These are now set manually when the values are not present in the config and the defaults are still stated in the command description.
Following conditions are met in the order given
1. Sets GdnBinaryFlag when it has been set by user either via env or CLI option
2. …
> Only set Guardian flag default when flag not provided by user

- worker/workercmd/guardian.go
k8s topgun was failing because the value for `CONCOURSE_GARDEN_MAX_CONTAINERS` was quoted, while the flag was a
`*int`. Let's just unmarshal it as a string, pass it on to guardian as is, and allow guardian to do the validation.
You can test this by setting `CONCOURSE_GARDEN_MAX_CONTAINERS: '"100"'` in `docker-compose.yml` - it will fail on master, but will work with this fix. Doing this worked before #6087 was merged
[Signed]: …
> Parse `--garden-max-containers` as a string

- worker/workercmd/guardian.go
In the [`bin-smoke` job](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke/builds/289) the test was timing out. We figured out the worker wasn't coming up and found this error in the logs:
```
error: /etc/concourse/garden.ini:2: unknown option: dns-server
```
We started parsing the garden ini as part of #6087. After that PR the
worker would fail to come up if the garden.ini contained any unknown
keys (unknown to Concourse).
This commit will unblock the pipeline. We should spend some time
thinking about this area of the codebase and figure out what the best
strategy moving forward should be. …
> Fix: ignore unknown keys in garden ini

- topgun/k8s/external_postgres_test.go
- topgun/k8s/k8s_suite_test.go
- topgun/k8s/prometheus_test.go
closes #5219 .
* Behaviour around namespaces changed in Helm 3.
* Every helm command is now scoped to a namespace just like kubectl.
* We now need to specify the namespace in each helm command.
* as of helm 3.2.0, we can add `--create-namespace` to the `helm upgrade` command which will allow helm to create the namespace if it doesn't exist, following the same behaviour that was in helm2 versions.
* Tiller is no longer required either, the `init` command was removed because of this.
This PR depends on https://github.com/concourse/concourse-chart/pull/146 and https://github.com/concourse/ci/pull/375.
This PR should be merged once we have migrated topgun cluster to use helm3. …
> Update k8s-topgun for Helm v3

- fly/integration/archive_pipeline_test.go
- fly/integration/checklist_test.go
- fly/integration/destroy_pipeline_test.go
- fly/integration/expose_pipeline_test.go
- fly/integration/get_pipeline_test.go
- fly/integration/hide_pipeline_test.go
- fly/integration/ordering_pipelines_test.go
- fly/integration/pause_pipeline_test.go
- fly/integration/rename_pipeline_test.go
- fly/integration/unpause_pipeline_test.go
36848225a496d5920dfa7ff7ba2680456f4ee2ec added some fly integration tests that asserted on error messages like
> invalid argument for flag `-p, --pipeline'
For windows, the flag format that is printed is `/p, /pipeline', causing these tests to fail on windows.
* Use the `osFlag` helper in place of the hardcoded flags …
> Fix fly integration tests on windows

- web/elm/src/Dashboard/Dashboard.elm
- web/elm/tests/PipelineGridTests.elm
This has been an intermittent bug that I've noticed since #5118 - if the
sidebar is open and you refresh the page, occasionally the pipeline
cards will be rendered as if the sidebar was not opened (meaning that
the lazy rendering computation thinks it has more room to work with, and
a column may be rendered partially off-screen)
* Request dashboard size when pipelines are fetched. We recompute the dashboard position when we fetch sidebar state from session storage, but the sidebar will not open until the pipelines have been fetched.
* We could probably get away with re-requesting the dashboard size after the first `AllPipelinesFetched` response, but doing it every time doesn't …
> Fix pipeline cards being rendered off-screen when sidebar was open

- go.mod
- go.sum
just addressing a bit of tech debt -- since our PR got merged, we might as well switch back to the mainline dependency.
You can see there's been no official release of go-flags since v1.4.0. I picked https://github.com/jessevdk/go-flags/commit/c17162fe8fd7 because it seems like @jessevdk merged a batch of PRs on July 11 2020, and that was the latest commit after that batch. I've looked over the other PRs that got merged and I pretty much trust that they won't cause us any issues, but you can look yourself:
* https://github.com/jessevdk/go-flags/pull/293 -- ini parser which we don't use?
* https://github.com/jessevdk/go-flags/pull/296 -- ini and man page features we don't use
* …
> switch back to upstream go-flags

- worker/runtime/backend.go
- worker/runtime/spec/mounts.go
- worker/runtime/spec/spec.go
- worker/runtime/spec/spec_test.go
- worker/workercmd/containerd.go
- worker/workercmd/worker_linux.go
closes #5984 
Add a flag to containerd options and string that all the way down to where we're creating Garden containers. …
> Add flag to concourse worker to overwrite init binary path

- atc/exec/check_step.go
- atc/metric/emit.go
- atc/metric/periodic.go
Bug Fix
This PR is a followup for #6022 that re-introduces the check start/finish
metrics, previously emitted by the LIDAR checker, now emitted by the check
step.
n/a
tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env …
> Emit start/finish metrics from check step

- vars/template.go
- vars/template_test.go
Bug Fix
closes #6107 .
When the variable name is parsed into the path and fields in `vars/template.go`, we remove the escaped quotes from the path but not from the fields.
This breaks lookups for variable nested fields that contain characters such as `.`. 
The documentation already states that we can quote parts of the variable interpolation syntax when they contain special characters such as `.` or `:` so I didn't need to make any changes there.
The PR can be tested as described in the linked issue #6107.
Fix interpolation of quoted variable fields containing special characters. …
> Fix quoting for var subkeys

- worker/runtime/cni_network.go
- worker/workercmd/containerd.go
- worker/workercmd/worker_linux.go
**Feature**
containerd is currently failing on BOSH as the path for CNI network plugins is different there. Error from the worker logs:
```
$ tail -1 /var/vcap/sys/log/worker/worker.stdout.log
{"timestamp":"2020-10-05T20:00:40.964319903Z","level":"error","source":"worker","message":"worker.garden.garden-server.create.failed","data":{"error":"starting task: network add: cni net setup: failed to find plugin \"bridge\" in path [/usr/local/concourse/bin]","request":{"Handle":"734ee021-98da-4081-40fa-1b9fdd464cc8","GraceTime":0,"RootFSPath":"raw:///var/vcap/data/worker/work/volumes/live/be9b09ac-28c9-438f-650a-c7d232d84f39/volume","BindMounts":[{"src_path":"/var/vcap/data/worker/work/volumes/live/727c3689-1a2a-4925-5509-0669 …
```
> make CNI plugins directory configurable

- vars/template.go
- vars/template_test.go
What does this PR accomplish?
Fix a bug raised in https://github.com/concourse/concourse/pull/5898#issuecomment-704309084
allow `@` sign in the var path match regex
> allow @ sign in var

- topgun/k8s/baggageclaim_drivers_test.go
- topgun/k8s/container_limits_test.go
- topgun/k8s/dns_proxy_test.go
- topgun/k8s/ephemeral_worker_test.go
- topgun/k8s/external_postgres_test.go
- topgun/k8s/external_worker_test.go
- topgun/k8s/garden_config_test.go
- topgun/k8s/https_web_tls_termination_test.go
- topgun/k8s/k8s_suite_test.go
- topgun/k8s/kubernetes_creds_mgmt_test.go
- topgun/k8s/mainteam_role_test.go
- topgun/k8s/prometheus_test.go
- topgun/k8s/tsa_node_port_test.go
- topgun/k8s/web_scaling_test.go
- topgun/k8s/worker_lifecycle_test.go
closes #6121
- keep track of which releases were successfully deployed by helm
- delete all know deployed releases on test suite exit
tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-en …
> cleanup k8s topgun releases if failure outside of `It` block

- fly/commands/get_pipeline.go
- fly/integration/error_handling_test.go
- fly/integration/get_pipeline_test.go
Allows fly cli to get pipeline for different teams
without having to switch targets
concourse/concourse#5215
Signed-off-by: techgaun <coolsamar207@gmail.com>
Feature
references #5215 .
- Allows fly cli to get pipeline for different teams
without having to switch targets by adding `--team` fly CLI switch …
> fly: add --team option to get-pipeline command

- web/assets/css/build.less
The fix made for horizontal scrolling on build outputs #6083 caused whitespaces to be collapsed. Changing the property to `break-spaces` will keep the original fix of preventing horizontal scrolling but also preserving whitespaces. This will result in trailing whitespace being wrapped rather than trimmed. Maybe we can possibly trim it instead?
Bug Fix
closes #6149 .
Change the property to `break-spaces`.
How to reproduce:
1. Run `docker-compose up --build -d` and `yarn build` without this fix
1. Set a following pipeline that will output text formatted as a table:
```
---
jobs:
- name: hello
plan:
- task:
config:
source: {repository: ubuntu}
run:
path: sh
args:
- -c
- |
apt-get update -y
apt-get install bsdmainutils -y
mount | column -t …
```
> Preserve whitespace within build output

- atc/exec/set_pipeline_step.go
- atc/exec/set_pipeline_step_test.go
- release-notes/latest.md
This PR seeks to address issue #6111 by preventing a `runtime error: invalid memory address or nil pointer dereference` when `set_pipeline` is run with a `file:` whose YML contains unexpected content.
This PR attempts to prevent the runtime error in the most minimal way possible by _only_ attempting to invoke `pipeline.SetParentIDs(step.metadata.JobID, step.metadata.BuildID)` _if_ a pipeline is found by `team.Pipeline(pipelineRef)`, in effect avoiding a scenario where `pipeline` doesn't exist and where `pipeline.SetParentIDs()` causes a runtime error.
One could imagine other solutions, such as perhaps improved [configvalidate#Validate](https://github.com/concourse/concourse/blob/master/atc/configvalidate/validate.go#L25) functionality to protect against this. However, the solution …
> Prevent set_pipeline runtime error

- fly/commands/ordering_pipeline.go
- fly/integration/error_handling_test.go
fly: add --team flag to order-pipelines
Allow for users to order pipelines for different teams
without switching targets
#5215
Signed-off-by: witjem <witjem@pm.me>
Feature  …
> fly: add --team flag to order-pipelines

- atc/api/config_test.go
- atc/configvalidate/validate.go
- atc/configvalidate/validate_test.go
- atc/exec/set_pipeline_step_test.go
Bug Fix | Feature | Documentation | **Enhancement**
From concourse/concourse#6111 we found that it was possible for any yaml
to pass pipeline validation and that ended up having some side-affects that
brought down the ATC. This commit will now ensure that any yaml someone
tries to pass off as a pipeline needs to contain at least one job. A
pipeline without a job is not very useful.
More context in this comment:
https://github.com/concourse/concourse/pull/6116#issuecomment-708449186
When validating a pipeline using the `confgivalidate` package, validation should ensure that at least one job is present in the pipeline. If no job is found than an error is returned. …
> Check that a pipeline contains at least one job

- atc/exec/set_pipeline_step.go
- atc/exec/set_pipeline_step_test.go
closes #6162. `set_pipeline` of a pipeline YML config with no diff now reports "no changes to apply," which is consistent to `fly set-pipeline`'s behavior in the same scenario.
`set_pipeline` of a pipeline YML config with no diff now reports "no changes to apply," which is consistent to `fly set-pipeline`'s behavior in the same scenario.
While there may be a good way to DRY up the occurrence of the "no changes to apply" string -- which now occurs across two locations in source code -- this is the most simple, minimal change to make the messaging consistent.
`set_pipeline` now prints "no changes to apply" and thereby behaves similarly to `fly set-pipeline` when a pipeline config contains no changes. …
> set_pipeline prints 'no changes to apply'

- atc/db/build.go
- atc/db/build_test.go
- atc/db/check_factory.go
- atc/db/db_suite_test.go
- atc/db/dbfakes/fake_checkable.go
- atc/db/dbfakes/fake_resource.go
- atc/db/dbfakes/fake_resource_config_version.go
- atc/db/dbfakes/fake_resource_type.go
- atc/db/dbtest/builder.go
- atc/db/dbtest/scenario.go
- atc/db/job_test.go
- atc/db/pipeline_test.go
- atc/db/resource.go
- atc/db/resource_cache_lifecycle_test.go
- atc/db/resource_config_check_session_lifecycle_test.go
- atc/db/resource_config_scope.go
- atc/db/resource_config_scope_test.go
- atc/db/resource_config_version.go
- atc/db/resource_test.go
- atc/db/resource_type.go
- atc/db/resource_type_test.go
- atc/db/team_test.go
- atc/db/versions_db_test.go
- atc/db/volume_test.go
- atc/db/worker_factory_test.go
- atc/gc/gc_suite_test.go
- atc/gc/resource_cache_collector_test.go
- atc/gc/resource_config_check_session_collector_test.go
- atc/gc/resource_config_collector_test.go
This PR introduces an `atc/db/dbtest` package for setting up test scenarios using higher-level (i.e. more stable) constructs. The aim of this pattern is to reduce the amount of churn whenever we make changes to how we model the internals, and also to reduce the amount of global test suite setup we've got going in under `atc/db`, primarily in `db_suite_test.go`.
* Introduce `dbtest.Builder` which provides higher-level methods (e.g. `WithPipeline`, `WithResourceVersions`) for constructing a `dbtest.Scenario`.
* Convert all tests which used to use `(db.Resource).SetResourceConfig` to use `dbtest` instead.
* Removes `(db.Resource).SetResourceConfig`, as it's no longer used in production code, and with this PR, no longer used in tests. …
> Introduce dbtest package for higher-level test setup

- worker/runtime/spec/devices.go
closes #6118.
Just edits the set of devices that privileged containers get access to by default, removing `/dev/console` for parity with https://github.com/opencontainers/runc/commit/60e21ec26e15945259d4b1e790e8fd119ee86467.
It is possible to reproduce the behaviour in #6118 by `fly execute`-ing the `containerd-integration` job against a docker-compose-deployed concourse. So you can do so, and then do the same with this patch to see the job go green!
* If you are running concourse with the containerd backend inside a runc-managed process and your version of runc is v1.0.0-rc91 or above, creating privileged containers no longer fails with EPERM.
[Contributing …
> containerd does not grant access to /dev/console

- atc/engine/builder/build_step_delegate.go
- atc/engine/builder/build_step_delegate_test.go
- atc/event/events.go
- atc/exec/check_step.go
- atc/exec/check_step_test.go
- atc/exec/get_step.go
- atc/exec/get_step_test.go
- atc/exec/put_step.go
- atc/exec/put_step_test.go
- atc/exec/task_step.go
- atc/exec/task_step_test.go
- atc/public_plan.go
- atc/task.go
- atc/worker/choose_task_worker_test.go
- atc/worker/client.go
- atc/worker/client_test.go
- atc/worker/container_spec.go
- atc/worker/fetch_source_test.go
- topgun/runtime/resource_certs_test.go
**Bug Fix**
This contains two fixes for topgun:
* Fixes a regression introduced by #6153 - when all workers are tagged, image fetching would fail because the tags configured on the step were not respected during image fetching, which resulted in looking only for untagged workers. Now the tags configured either on the resource type (`check`/`get`/`put`) or the step (`task`/`check`/`get`/`put`) will be respected.
* In addition, `tags:` may now be specified on task's `image_resource`. This was added because the `atc.ImageResource` type is used for fetching all this, and it seems reasonable to allow it to be configured there anyhow. (This is technically a new feature I guess.)
* When sending `ImageCheck` and `ImageGet` events, send only the *public* build plan, not the full build plan. This …
> Respect tags when fetching images, send public plans in fetching events

- atc/worker/client.go
- atc/worker/worker.go
- atc/worker/worker_test.go
Today we encounter many errors saying like:
```
{"timestamp":"2020-10-21T07:57:34.458990024Z","level":"info","source":"atc","message":"atc.checker.errored","data":{"check":1288594293,"cluster":"Runway CI","error":"run check step: find or create container: runc state: runc: fork/exec /var/gdn/assets/linux/bin/runc: resource temporarily unavailable: ","session":"19"}}
```
To debug the error, we had to find on which worker it failed to create container. But Concourse doesn't provide any clue, nothing about worker in either logs and db.
Add worker name to the log message.
This is a tiny change but will help a lot on debugging container creation failure issues.
Add worker name to logs of container creation error.
[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_COND …
> Enhanced some logs to add worker name.

- topgun/tasks/http-proxy.yml
This test isn't happy with GNU `wget`, and I don't really have time to investigate why - it consistently failed with [this error](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bosh-topgun-runtime/builds/403#L5f92985f:2555:2558):
+ wget -Y on example.com
--2020-10-23 13:54:02--  http://example.com/
Resolving proxy.example.com (proxy.example.com)... failed: Name or service not known.
wget: unable to resolve host address 'proxy.example.com'
Not sure what would be so different between busybox `wget` and GNU `wget`.
In any case, going to just bring this back to busybox for now to unblock the pipeline. I suspect we'll *have* to fix this at some point, but we can deal with that after v6.7.0 is out.
[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CON …
> topgun: use busybox for http proxy... for now

- web/public/index.mjs
Bug Fix
i set omitempty for the trigger field, which resulted in `=== false` not
being satisfied, since it became `undefined`. so let's just switch it to
`!== true`.
for anyone wondering why this isn't a simple bool check: the CSS sets
`stroke-dasharray` for non-trigger inputs, which could be set as the
default, but it's not super obvious what you'd set to remove the
dasharray when the .trigger class is present.
i guess you could set `.edge:not(.trigger)` to have a dasharray, but
don't really have an appetite to rock the boat in "legacy" CSS/SVG
logic. …
> Fix pipeline UI non-trigger input edges showing up as trigger

- atc/exec/check_step.go
- atc/exec/check_step_test.go
follow-up for #6022
previously the check step would only update the last check end time when
the check succeeded. this meant that if the check failed or errored,
we'd actually check again immediately, which is a bit too aggressive.
this brings it back to the old behavior, which is to update the last
check end time on failure/error. …
> Update last check end time on check failure/error

- atc/db/build.go
- atc/db/build_test.go
- atc/db/check_factory.go
- atc/db/check_factory_test.go
- atc/db/dbfakes/fake_checkable.go
- atc/db/dbfakes/fake_resource.go
- atc/db/dbfakes/fake_resource_type.go
- atc/db/resource.go
- atc/db/resource_test.go
- atc/db/resource_type.go
- atc/db/resource_type_test.go
follow-up for #6022
previously the check factory would create a build and then start it in a
separate database call. if the web node was shut down in between, the
pending build would be left there, but nothing would ever start it, and
checking would just stop until someone comes in and creates a new build.
now the build will be created and started in a single transaction.
a better refactor IMO would be to introduce a `builds.Starter` and use
it to simplify the job build starting and serial groups logic. but i
ain't got time for that! …
> Fix race condition with check build creation + starting

- atc/builds/planner.go
- atc/builds/planner_test.go
- atc/exec/across_step.go
- atc/exec/across_step_test.go
- atc/exec/in_parallel.go
- atc/plan.go
- atc/public_plan_test.go
- atc/steps.go
**Refactor**
* When `max_in_flight: all` is specified on an `across` step, determine the effective max in flight at runtime rather than at plan time
* This will make it possible to implement the dynamic across step, where the number of var values is not known until runtime
Despite changing the type of `atc.AcrossVar.MaxInFlight`, this won't break unmarshaling existing `across` plans. All valid integers can also be unmarshaled as a valid `atc.MaxInFlightConfig` - now, the value `"all"` is also supported …
> Determine `across` step's `max_in_flight` at runtime

- atc/atccmd/command.go
- atc/component.go
- atc/db/migration/batch/build_events_bigint.go
- atc/db/migration/batch/build_events_bigint_test.go
- atc/db/migration/batch/runner.go
- atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.down.sql
- atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.up.sql
- atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.down.sql
- atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.up.sql
- atc/db/open.go
fixes #6199
follow-up to #6022
This introduces a handful of migrations which convert `build_id` foreign key references to `bigint` in-place. For `build_events` that approach would grind everything to a halt because it can have millions of rows, so this PR adds a batch migration component which will migrate build events in batches of 100,000 (by default) every 10 seconds (by default). Flags are also added for both settings just in case operators feel that it's too aggressive or too slow depending on their situation.
The migration first renames `build_events.build_id` to `build_events.build_id_old`, and then adds a "new" `build_id bigint` column and updates the indexes. This rename dance ensures other `web` nodes which may be running mid-upgrade will write their events as `bigints`, so that …
> Migrate build_id references to bigint, batch event migration

- atc/db/resource.go
- atc/db/resource_test.go
- atc/db/resource_type.go
- atc/db/resource_type_test.go
With #6022, we delete the previous build for a resource/resource type
check when we create a new one. However, since there's no foreign key
contraint on build_events.build_id, the build events never actually get
deleted.
We actually don't want a cascading delete on build_events, though, since
deleting pipelines would become super slow (currently, we're able to
just truncate/drop the pipeline_build_events table, but if deletes
cascaded, we'd end up performing a ton of row deletions, which is much
slower in postgres). So instead, let's just delete the build events when
we delete the corresponding build.
[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_COND …
> Clear build events from previous resource/resource type check

- fly/commands/expose_pipeline.go
- fly/integration/error_handling_test.go
- fly/integration/expose_pipeline_test.go
Allows fly cli to expose pipeline for different
team without having to switch targets
concourse/concourse#5215
Signed-off-by: techgaun <coolsamar207@gmail.com>
Feature
references #5215 .
Allows fly cli to expose pipeline for different
team without having to switch targets
[Helm](https://github.com/concourse/helm) packaging; otherwise, ignored …
> fly: add --team option to expose-pipeline command

- atc/metric/emit.go
- atc/metric/emitter/newrelic.go
- atc/metric/emitter/prometheus.go
- atc/metric/periodic.go
- atc/worker/artifact_source.go
This PR adds a new metrics "volume stream", which will help measure volume streaming.
Just add a counter metrics.
I have tested the new metrics locally:
Added a new metrics "volume streamed".
tests](https://github.com/concourse/ci/tree/master/tasks/scrip …
> feat(atc): add a new metrics "volumes streamd"

- atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.down.sql
- atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.up.sql
We were seeing deadlocks when trying to perform this migration due to
concurrent queries acquiring AccessShareLocks on builds, and interacting
with the tables which we `ALTER TABLE` on.
Signed-off-by: Aidan Oldershaw <aoldershaw@pivotal.io>
closes # . …
> Acquire lock on `builds` table in `build_id` migrations

- atc/api/resources_test.go
- atc/api/resourceserver/list.go
- web/elm/src/Concourse.elm
- web/elm/src/Message/Callback.elm
- web/elm/src/Message/Effects.elm
- web/elm/src/Pipeline/PinMenu/PinMenu.elm
- web/elm/src/Pipeline/Pipeline.elm
- web/elm/tests/PinMenu/PinMenuTests.elm
- web/elm/tests/PipelineTests.elm
- web/elm/tests/SerializationTests.elm
I *think* this fixes a bug that I *think* was introduced by #6137 - but I haven't figured out how to reproduce it. Please read the first commit message, as it contains more context, but I was seeing an Elm runtime error on CI which prevented the pipeline page from being updated.
And even if it doesn't fix the bug, at least it's a decent refactor!
* Use proper types (`List Concourse.Job`, `List Concourse.Resource`) instead of the generic `Json.Encode.Value` on the pipeline page
* Resource server returns `[]` instead of `null` when a pipeline has no resources
The function that errored is as follows (see the first commit message for context):
```javascript
function K(r, n, e, t) {
if …
```
> Use proper types for jobs and resources on pipeline page

- topgun/k8s/k8s_suite_test.go
Be less smart about deleting namespaces; always try and ignore errors.
(for example, if they are Garden configs that are not …
> [topgun/k8s] Stop leaking namespaces in test env

- atc/builds/planner_test.go
- atc/db/job_factory.go
- atc/db/job_factory_test.go
Follow up to #6079.
We noticed that the defaults we set for `get` and `put` steps backed by base
resource types weren't being applied since we only check the pipeline's
resource types to apply defaults. Note that we properly check the base
resource type for task image fetching.
* If parent resource type is not found in pipeline's resource types, check in base resource types when applying default
* We do the same thing when we `Deserialize` the pipeline's resource types - https://github.com/concourse/concourse/blob/e1c0dbd1b1eee14e3ac1526ca5f44e4d416e06ce/atc/db/resource_type.go#L86-L100. If the resource isn't backed by a pipeline-local resource type though (e.g. uses …
> Use base resource type defaults in `get`/`put` steps

- topgun/k8s/baggageclaim_drivers_test.go
- topgun/k8s/k8s_suite_test.go
safer to rewrite topgun than to bump dependencies everywhere else
> [release/6.7.x] use k8s/client-go v11.0 for topgun

- topgun/k8s/baggageclaim_drivers_test.go
Back-porting the baggageclaim fix from #6185 
`--help` …
> back-porting baggageclaim test change

- .github/pull_request_template.md
The format of the release note section in a pr description should be in a list. It looks best like that in the generated release note :D
I added an example that shows the format of the release note section should be in a list. …
> Add an example for the release note section in the pr template

- fly/commands/pin_resource.go
- fly/integration/pin_resource_test.go
closes #6094.
add the `required` struct tag to the `Version` field, and an integration test -- just in case we ever change flag libraries.
Previously, you could run the command on an unpinned resource without passing a version -- it would run and succeed, but do nothing. Now the command will fail and print an error message. …
> `fly pin-resource` requires a version if the resource is unpinned

- atc/api/containerserver/hijack.go
- atc/hijack_payload.go
- atc/worker/transport/hijack_streamer.go
- atc/worker/transport/hijack_streamer_test.go
- fly/commands/hijack.go
- fly/commands/internal/hijacker/hijacker.go
- fly/commands/internal/hijacker/hijacker_test.go
- fly/integration/hijack_test.go
Bug Fix | Feature
Fixes  #5877
The intent of this PR was to allow `fly hijack` commands with no path specified, to assume the user just wants some shell, and if `bash` isn't available, try again with `sh`. This required some changes to atc to unmarshal a `garden.ExecutableNotFoundError` sent from the container, and turning that into a special message sent back to fly.
It feels a little inelegant to pass back another return variable (a `bool`) in a couple places where we already pass an exit status `int`, but I didn't have enough understanding of the exit status codes to feel comfortable just passing back `254`, and figured if golang supports it, another return var is better then some weird edge case where `254` is …
> Fallback hijack to sh when bash is missing

- atc/builds/tracker.go
- atc/builds/tracker_test.go
- atc/db/lock/lock.go
- atc/engine/check_delegate.go
- atc/engine/check_delegate_test.go
- atc/engine/engine.go
- atc/engine/engine_suite_test.go
- atc/exec/aggregate.go
- atc/exec/check_step.go
- atc/exec/exec_suite_test.go
- atc/exec/in_parallel.go
- atc/lidar/lidar_suite_test.go
- atc/lidar/scanner.go
- atc/scheduler/runner.go
- atc/scheduler/scheduler_suite_test.go
- atc/util/panic_dump.go
fixes #6217
* Cleans up all the panics from test output.
* Don't re-use resource type check containers, since they really shouldn't need caching semantics (they're almost always `registry-image`).
* Only acquires the resource config scope lock when checking a resource. …
> Check step only acquires lock for periodic pipeline resource checks

- worker/workercmd/guardian.go
closes #6236
closes https://github.com/concourse/concourse-bosh-release/issues/128
Signed-off-by: Taylor Silva <tsilva@pivotal.io>
Co-authored-by: Bohan Chen <bochen@pivotal.io>
Always try and remove the guardian assets dir [(`/var/gdn/assets`)](https://github.com/cloudfoundry/guardian/blob/3837782d5e8fb8b7374e2b9109860690db15a5da/guardiancmd/command.go#L120)
* The worker will now clear out any existing Guardian assets on start-up (`/var/gdn/assets`)
* This fixes in-place upgrade scenarios where guardian was using old versions of runc …
> Remove any existing guardian assets

- fly/integration/builds_test.go
Couldn't easily reproduce the error locally, but I'm just going to extend the delta so we don't run into this. Seems odd that our windows/darwin workers are so slow on this test, though.
* 
[Helm](https://github.com/concourse/helm) …
> fly: give more leeway for slow test

- atc/atccmd/command.go
- atc/worker/artifact_destination.go
- atc/worker/artifact_source.go
- atc/worker/artifact_source_test.go
- atc/worker/choose_task_worker_test.go
- atc/worker/client.go
- atc/worker/client_test.go
- atc/worker/image/image.go
- atc/worker/volume.go
- atc/worker/workerfakes/fake_artifact_destination.go
- atc/worker/workerfakes/fake_volume.go
- go.mod
- go.sum
- versions.go
This PR implements P2P Volume Streaming (https://github.com/concourse/rfcs/pull/82). In deployments where workers can reach to each other, P2P Volume Streaming should:
* Speed up volume streaming between workers
* Reduce ATC's cpu/memory/network usages that spend on volume streaming
Corresponding baggeclaim part code change is https://github.com/concourse/baggageclaim/pull/39
I have done a PoC. In the PoC, I run the 20 pipelines with the following code:
```yaml
resources:
- name: timer
type: time
source:
interval: 1m
jobs:
- name: test
public: true
plan:
- get: timer
trigger: true
- task: t1
config:
source: {repository: busybox}
outputs:
- name: out1
run:
path: sh
args:
- -exc
- dd bs=1024 count=50000 </dev/urandom >out1/f1.bin
- task: …
```
> feat: P2P Volume Streaming

- atc/lidar/scanner.go
This is a small bug fix. The metrics `checks-enqueued` should only be increased when a check is created.
Just check if `created` is true.
None
Fixed a bug of the metrics `checks-enqueued` where its value might be higher than checks have been created. …
> atc(bug): checks-enqueued should only be inc when a check is created

- atc/db/build.go
- atc/db/build_test.go
cherry-picking the commit https://github.com/concourse/concourse/pull/6242/commits/ec9b0f637020e4eaa004baf8bf20cb5e737b5bc1 from master to 6.7.x
Needed to update the test setup to the old way.
> atc: abort a rerun build if input version gone

- atc/lidar/scanner.go
This is a small bug fix. The metrics checks-enqueued should only be increased when a check is created.
Only inc `checks-enqueued` if created is true.
#6272 for same bug fix on master branch has been merged. This is PR is back-porting the fix to 6.7.2, as 6.7.2 is a version we are waiting for.
Fixed a bug of the metrics checks-enqueued where its value might be higher than checks have been created. …
> act(bug): 6.7.x: only inc `checks-enqueued` when a check is created.

- topgun/k8s/worker_lifecycle_test.go
Skipping a failing test
This test started failing because the retryHttp package was bumped,
causing a change in behaviour. Now the test is stuck waiting for `fly
watch` to exit, whereas before it would exit after ~5mins
retryHttp was bumped in concourse/concourse#6186
Existing issue that contains reproducible steps is
concourse/concourse#3011
Signed-off-by: Taylor Silva <tsilva@pivotal.io> …
> [topgun] skip failing topgun/k8s test

- fly/integration/login_test.go
- fly/integration/suite_test.go
- fly/integration/sync_test.go
- fly/integration/version_test.go
No Impact
closes #6291.
- fly: remove redundant login test
The goal of the Versions Checks suite is to validate the behaviour for
version discrepency between fly and the atc. Previously, this was being
tested by keeping the atc mock servers's version constant, and changing the
version of fly in each test. Since fly isn't mocked out it has to be
rebuilt each time which even a single repetition of the build process
considerably (5x by our count) slowing down the whole suite. This slow
down can cause jobs on CI to timeout.
The test coverage can be achieved by keeping the fly version constant
and changing the atc mock server's version each time. This means fly
will only have to be built once speeding up the suite significantly.
- fly: optimize version checks test suite
This logic is already …
> Optimize fly tests

- atc/configvalidate/validate.go
- atc/configvalidate/validate_test.go
- atc/db/team.go
- atc/db/team_test.go
- go.mod
- go.sum
Allow groups to list jobs via globs rather than just strict matches. It isn't uncommon to have an `all` group which you need to remember to add any new jobs to and it is easy to forget to `fly validate-pipeline` first. With this feature, the groups could just be (quoting to prevent being seen as YAML anchor):
```yaml
- name: all
jobs:
- "*"
- name: deploy
jobs:
- deploy-*
```
Bug Fix | _Feature_ | Documentation
When validating/saving groups that a job is in, use `glob.Glob` rather than `Lookup`/map keys which strictly check equality. Add/modify some tests to ensure behaviour is covered.
There are 2 commits here - the first uses a regular expression and the second converts it to using globs. I think globs seem nicer so I would _prefer_ to use globs and just squash these 2 commits but I …
> Allow globs in groups

- atc/exec/set_pipeline_step.go
- atc/exec/set_pipeline_step_test.go
Back port #6116 to 6.7.x and hopefully include in release 6.7.2.
We hit ATC crash today due to this bug. As we are waiting for 6.7.2, back port the fix to 6.7.x.
`set_pipeline` of a YML pipeline configuration file with no `jobs`: or `resources`: no longer causes a `runtime error: invalid memory address or nil pointer dereference`. …
> Backport #6116 to 6.7.x: Prevent set_pipeline runtime error

- atc/api/config_test.go
- atc/configvalidate/validate.go
- atc/configvalidate/validate_test.go
- atc/exec/set_pipeline_step_test.go
Bug Fix | Feature | Documentation | **Enhancement**
Backports #6159
Check that a pipeline contains at least one job; otherwise return an error
* Pipelines are now validated to ensure that they contain at least one job - pipeline configs with no jobs will be rejected. …
> Backport #6159: Ensure pipelines contain at least one job

- web/elm/src/Dashboard/Pipeline.elm
- web/elm/tests/PipelineCardTests.elm
It was annoying to see a pipeline with only green and blue jobs but still marked red. Logically the status of a paused job should be "paused" and not the status of the last build.
- The UI will no longer consider paused jobs when figuring out the overall status of a pipeline …
> Ignore paused jobs when determining pipeline status

- atc/creds/retryable_secrets_test.go
- atc/creds/secret_var_lookup_rules.go
- fly/commands/execute.go
- fly/commands/internal/executehelpers/inputs.go
- fly/commands/internal/flaghelpers/input_mapping_pair_flag.go
- fly/commands/internal/flaghelpers/input_pair_flag.go
- fly/commands/internal/flaghelpers/output_pair_flag.go
- fly/commands/internal/flaghelpers/variable_pair_flag.go
- fly/commands/internal/flaghelpers/yaml_variable_pair_flag.go
- fly/commands/internal/flaghelpers/yaml_variable_pair_flag_test.go
- fly/commands/internal/templatehelpers/yaml_template.go
- fly/commands/internal/templatehelpers/yaml_template_test.go
- fly/commands/set_pipeline.go
- fly/commands/validate_pipeline.go
- fly/integration/fixtures/nested-vars-pipeline.yml
- fly/integration/fixtures/vars-pipeline-params-types.yml
- fly/integration/fixtures/vars-pipeline.yml
- fly/integration/set_pipeline_test.go
- vars/named_vars.go
- vars/named_vars_test.go
- vars/reference_test.go
- vars/static_vars.go
- vars/static_vars_test.go
- vars/template.go
- vars/template_test.go
- vars/variables.go
closes #6279 .
cherry-picks #6170 to release/6.7.x (the non-instance vars stuff)
This was a bit of a doozy to cherry-pick since it built off of a couple refactors that I didn't include - hopefully I didn't break anything
* A regression was introduced in 6.5.0 that prevented the use of nested fields when setting a pipeline variable via `fly set-pipeline --var`
* For instance, pre 6.5.0, `fly set-pipeline --var foo.bar=123 --var foo.baz=456` would create the variable `foo` with value `{bar: 123, baz: 456}` (that can be referenced in the pipeline config as `((foo.bar))`, `((foo.baz))`)
* In 6.5.x/6.6.x, the same command would create variables `"foo.bar" = 123` and `"foo.baz" = 456` …
> Fix regression preventing the use of nested fields with `fly set-pipeline --var`

- testflight/intercept_shell_test.go
- testflight/suite_test.go
- worker/runtime/cni_network_test.go
- worker/runtime/container.go
- worker/runtime/container_test.go
#6098 changed the behaviour of `fly intercept` to fallback to `sh` as the default command if the container doesn't have `bash`. However, this requires cooperation with the runtime to return a specific garden error, which containerd did not follow.
* Return a `garden.ExecutableNotFoundError` when the executable is not found (logic copied from [Guardian](https://github.com/cloudfoundry/guardian/blob/3da697a62154c6d1f797aede3a0fb23f2297e6cd/rundmc/runcontainerd/runcontainerd.go#L201-L221))
* Add testflight coverage
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTIN …
> `fly intercept` falls back to `sh` when `bash` is missing (containerd runtime)

- fly/commands/sync.go
- fly/commands/version.go
- fly/integration/login_test.go
- fly/integration/sync_test.go
- fly/integration/version_test.go
- fly/rc/target.go
Rather than re-compiling `fly` with the version var overridden, allow faking out the client version via an env var. This speeds up the `fly` integration suite (11m48s -> 6m18s) and should reduce timeout flakiness in CI on the Windows/Darwin workers. …
> fly: structure: avoid recompiling in tests

- atc/engine/step_factory.go
- atc/exec/set_pipeline_step.go
- atc/exec/set_pipeline_step_test.go
Signed-off-by: Chris Ludden <chris.ludden@gmail.com>
Bug Fix - adds policy check to `set_pipeline` step
closes #5931.
Enforces `SaveConfig` policy check (when enabled) in `set_pipeline` step
[Helm](https://github.com/concourse/helm) packaging; otherwise, ignored …
> Enforce SetPipeline policy check in set_pipeline step

- atc/db/build.go
- atc/db/build_test.go
- atc/db/check_factory.go
- atc/db/check_factory_test.go
- atc/db/pipeline_test.go
- atc/db/resource.go
This is a re-submit of #5149 that was released in 6.0.0 and reverted in 6.6.0 because of two side effects:
1. Put-only resource's custom resource type is not auto checked.
2. Put-only resources don't show version history on the UI.
This PR is going to re-enable #5149 and solves the side effects.
* Pick up #5149
* As @vito suggested, I modified `db.build.SaveOutput()` to call `resource.SetResourceConfigScope()`. So that put-only resource get its `resource_config_scope_id` field populated.
Based on my tests, problem 1 has been resolved by recent @vito 's refactor. Now every `put` embeds a `check` and a `get` for image fetching, so `put` will always fetch up-to-date image. I have tested: 1) update image without bumping image tag; 2) update image with bumping image tag, in both cases, `put` …
> atc(feat): master - skip checking put-only resources

- fly/integration/execute_with_outputs_test.go
- fly/integration/sync_test.go
Name the executable `fly.exe` instead of `fly` (by using the same original filename)
`--help` …
> Fix 'fly sync' Windows tests

- atc/atccmd/command.go
- atc/worker/placement.go
- atc/worker/placement_test.go
Currently if a container placement strategy results multiple candidate workers, then it will randomly pick up one from the candidates.
Say, if `volume-locality` strategy results 2 candidate workers, why choose the one that has less containers or tasks?
With PR implements a strategy chain, so that if one strategy results multiple candidate workers, then next strategy can be applied.
Organizes multiple strategies as a chain.
Please review from the design perspective first. If you are ok with the design, I'll add more tests for chained strategies. This enhancement should not break any existing strategy.
* Enhanced container placement strategy to support chained strategies, for example `CONCOURSE_CONTAINER_PLACEMENT_STRATEGY=volume-locality,fewest-build-containers` …
> feat(atc): support chained container placement strategies.

- atc/api/api_suite_test.go
- atc/api/handler.go
- atc/api/workers_test.go
- atc/atccmd/command.go
Bug Fix | Feature | Documentation | **Enhancement**
closes #6311
give worker registration its own dbConn pool
* Give the worker registration endpoint its own database connection pool to avoid the situation where the API connection pool is maxed out and workers fail to register and stall
[Helm](https://github.com/concourse/helm) packaging; …
> atc: give worker registration its own dbConn pool

- atc/db/build.go
- atc/db/build_test.go
- atc/db/dbtest/builder.go
- atc/db/migration/migrations/1606489231_remove_versions_with_check_order_of_0.down.sql
- atc/db/migration/migrations/1606489231_remove_versions_with_check_order_of_0.up.sql
- atc/db/pipeline.go
- atc/db/resource.go
- atc/db/resource_config_version.go
- atc/db/resource_test.go
- atc/db/resource_type.go
Previously, Concourse would save a resource version with a check order of 0 using the method `SaveUncheckedVersion` for get steps that would try to save metadata on a version that can possibly not exist (because it got deleted within the time that the version was checked and the get step finished running). This has been changed to saving the metadata using `UpdateMetadata` on a resource which will not update the metadata if the version does not exist.
Even though we no longer use the SaveUncheckedVersion method (meaning we no longer save versions with check order of 0), the logic for dealing with versions with check order of 0 was never deleted. Within this commit, I added a migration
that deletes all rows within the database that has a check order of …
> Remove legacy logic for dealing with resource versions that have a check order of zero

- hack/dc
- hack/ldap/config.ldif
- hack/oidc/config.json
- hack/oidc/users.json
- hack/overrides/ldap.yml
- hack/overrides/oauth.yml
- hack/overrides/oidc.yml
- hack/overrides/saml.yml
The SAML one might be a bit weird to work with, but the others should be straight forward and mimics what we can expect from a real life scenario.
> Add docker-compose overrides for SAML, LDAP, OAuth, and OIDC

- atc/worker/placement.go
- atc/worker/placement_test.go
- atc/worker/worker.go
- atc/worker/workerfakes/fake_worker.go
To minimum volume streaming, we are using the container placement strategy "volume-locality". But sometime, this strategy makes busy worker busier, the following "worker containers" chart is from our prod cluster:
From the chart, we can see a spike. At that time, what we saw is, many build failed with error, "insufficient workers", spiked workers stalled, etc. In the meantime, there were a lot of other workers not busy, but they didn't share workload with those spiked workers.
Though garden support max containers restriction, the control is on worker, it's too late. Ideally, ATC should avoid to dispatch too many containers to a worker to make the worker overloaded.
With #6208, we will be able to chain multiple strategies. This PR is adding two new strategies `limit-max-containers` and …
> atc(feat): add new container placement strategies: limit-max-containers and limit-max-volumes.

- worker/runtime/integration/integration_test.go
- worker/workercmd/containerd.go
Bug Fix
part of #6246
It is [recommended](https://github.com/containerd/containerd/blob/master/docs/ops.md) that containerd be started with an `oom_score` of -999. We want it to be at the level of other system daemons. This is so that containerd never runs into an out of memory state before the containers it's managing are cleaned up. At the same time it should not be unkillable.
To test change the following in the worker section `docker-compose.yml`:
- Change `CONCOURSE_GARDEN_DNS_PROXY_ENABLE` to `CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE`
- Set `CONCOURSE_RUNTIME: "containerd"`
```
docker-compose up --build
#get onto the worker
docker exec -it concourse_worker_1 bash
ps auxww
#pick the PID of containerd daemon from the …
```
> start containerd with low oom_score

- worker/runtime/spec/mounts.go
- worker/runtime/spec/spec.go
- worker/runtime/spec/spec_test.go
Bug Fix
part of #6246
* Set the appropriate permissions for mounts in privileged containers. 
* Use the Linux default size for `/dev/shm` (shared memory) mount.
Bring up Concourse.
```
docker-compose -f docker-compose.yml -f ./hack/overrides/containerd.yml  up --build
``` 
Create the following pipeline: `build.yml`
```
---
resources:
- name: concourse-examples
type: git
icon: github
source:
uri: https://github.com/concourse/examples.git
branch: master
jobs:
- name: build
plan:
- get: concourse-examples
- task: build-task-image
privileged: true
config:
source:
repository: vito/oci-build-task
inputs:
- name: concourse-examples
outputs:
- name: image
params:
CONTEXT: …
```
> Fix mount issues on containerd

- atc/worker/client.go
- atc/worker/client_test.go
closes #6356
Limit active tasks is supposed to wait for a worker to become available.
This broke in #6339. This commit fixes it when limit-active-tasks is one
of the placement strategies.
Also added a test to ensure the waiting for worker path is executed.
I tried to modify the code so all strategies would wait for workers but
I think this kind of waiting needs to happen in the worker.pool which
would break the metrics for limit-active-tasks which happens in
worker.client.chooseTaskWorker().
Follow the reproducible steps in #6356 for acceptance.
Release notes are not needed. This is fixing a bug in an unreleased feature (#6339). …
> atc/worker: fix limit-active-tasks

- atc/api/accessor/accessor.go
- atc/api/accessor/accessor_test.go
Bug Fix 
closes #6367 .
This is a small logic error in function `hasPermission()`, and fixed the bad logic.
Fix an authorization bug, when a user has multiple roles in a team, then it may randomly hit "forbidden" error. …
> atc(fix): fix an authorization bug, when a user has multiple roles in a team, then it may randomly hit "forbidden" error.

- go.mod
- go.sum
- skymarshal/dexserver/dexserver.go
closes #6366 
Bumps Dex to 2.27.0 which fixes a vulnerability in the go XML library: https://mattermost.com/blog/coordinated-disclosure-go-xml-vulnerabilities/
* Bump Dex to 2.27.0 which fixes a vulnerability in the go XML library
the …
> Bump dex to include the XML patch

- fly/commands/completion.go
Feature
Add the autocomplete for fish.
#4012 introduce the `fly completion` command. and I can add fish completion code to this subcommand.
The interface looks like
and for subcommand:
If someone wants to use or test this path, need to run this command first (in fish):
```fish
fly completion --shell fish | source
```
then type `<tab>` randomly while using fly.
* fly: add autocomplete for fish. …
> fly: Add fish auto complete

- atc/builds/planner.go
- atc/builds/planner_test.go
- atc/exec/check_step.go
- atc/exec/check_step_test.go
- atc/exec/get_step.go
- atc/exec/get_step_test.go
- atc/exec/log_error_step.go
- atc/exec/log_error_step_test.go
- atc/exec/maybe_timeout.go
- atc/exec/put_step.go
- atc/exec/put_step_test.go
- atc/exec/task_step.go
- atc/exec/task_step_test.go
- atc/plan.go
- atc/steps.go
- atc/steps_test.go
- atc/worker/client.go
- atc/worker/client_test.go
- atc/worker/workerfakes/fake_client.go
- testflight/resource_check_timeout_test.go
Feature
* Adds a `timeout:` field to the `task`, `get`, and `put` steps which gets parsed before the more general `timeout:` step modifier. This allows the `task`/`get`/`put` steps to enforce the timeout more narrowly - around the running of the actual process, so that it doesn't include the time spent fetching images.
* Bumps `retryhttp` to v1.1.0 to fix an issue I noticed during testing: if the timeout is reached while making a request to Baggageclaim, `retryhttp` considered the `context.DeadlineExceeded` error to be retryable, so rather than timing out it'd go into a retry loop.
* Tweaks the `check` step timeout to be consistent with `task`/`get`/`put`, i.e. enforced at the step level rather than being passed to the `worker.Client`.
I'm not 100% sure if this is a good idea. It feels …
> Don't enforce timeouts during image fetching

- atc/pipeline.go
(unreleased)
when parsing the key-value pairs for pipeline instances from API
requests.
this is unlikely to matter, since internally, we only use the query
params in two ways:
* ?vars={...full JSON...}
* ?vars.foo=123&vars.bar.baz="def" (i.e. every var in non-overlapping)
initially I figured we could just use the order that the query params
were specified in, but since `url.Values` is a `map`, iteration order is
non-deterministic. while we *could* use `url.RawQuery` and parse it
ourselves to maintain the order, this didn't seem worthwhile
* Sort key-value pairs so that result is deterministic …
> Deterministic ordering of `?vars` params for instanced pipelines API

- atc/api/config_test.go
- atc/api/resources_test.go
- atc/config.go
- atc/config_test.go
- atc/db/check_factory.go
- atc/db/check_factory_test.go
- atc/db/dbfakes/fake_checkable.go
- atc/db/dbfakes/fake_resource.go
- atc/db/dbfakes/fake_resource_type.go
- atc/db/resource.go
- atc/db/resource_test.go
- atc/db/resource_type.go
- atc/db/resource_type_test.go
- atc/lidar/scanner.go
- atc/lidar/scanner_test.go
This PR allows a user to disable automatic checking of a resource by setting `check_every: never` in a resource's definition. We've seen this request come up when people only want checking to happen via a webhook. The workaround has always been setting `check_every` to some large value like `99h`. 
Lidar runs every ~10s. I tested using this pipeline:
```yaml
---
resources:
- name: every-30s
type: time
check_every: never
icon: clock-outline
source:
interval: 1s
jobs:
- name: job
public: true
plan:
- get: every-30s
trigger: true
- task: simple-task
config:
source: { repository: busybox }
run:
path: echo
args: ["Hello, world!"]
```
* Automatic resource checking for individual resources can be disabled …
> Disable resource checking for individual resources

- atc/api/accessor/accessor.go
- atc/api/accessor/accessor_test.go
Bug Fix 
Just `git cherry-pick` commits from #6368.
Fix an authorization bug, when a user has multiple roles in a team, then it may randomly hit "forbidden" error. …
> Backport #6368 to 6.7.x: fix auth bug

- fly/commands/internal/setpipelinehelpers/atc_config.go
- fly/commands/internal/setpipelinehelpers/atc_config_test.go
- fly/commands/set_pipeline.go
Bug Fix
closes #6333.
If `--team` option is specified to `fly set-pipeline`, then add `--team` to prompted `fly unpause-pipeline` command.
```
$ concourse.fork/fly/fly -t dev sp -c test-timer.yml -p test-timer --team main
<... omit pipeline content ...>
pipeline name: test-timer
apply configuration? [yN]: y
pipeline created!
you can view your pipeline here: http://localhost:8080/teams/main/pipelines/test-timer
the pipeline is currently paused. to unpause, either:
- run the unpause-pipeline command:
concourse.fork/fly/fly -t dev unpause-pipeline -p test-timer --team main
- click play next to the pipeline in the web ui
```
NA
Fixed a bug of `fly set-pipeline` where `--team` option was missing in the prompted unpause pipeline command. …
> fly(fix): set-pipeline promoted unpause-pipeline command should have --team option.

- atc/configvalidate/validate_test.go
- atc/configwarning.go
- atc/configwarning_test.go
closes #6070 .
(for example, if they are Garden configs …
> Allow underscore in identifiers

- fly/commands/internal/setpipelinehelpers/atc_config.go
- fly/commands/internal/setpipelinehelpers/atc_config_test.go
- fly/commands/set_pipeline.go
Bug Fix
Just backport of #6336.
NA
Fixed a bug of `fly set-pipeline` where `--team` option was missing in the prompted unpause pipeline command.
(for example, if …
> Backport #6336 to 6.7.x

- atc/db/build.go
- atc/db/build_test.go
closes #6343 .
the prometheus emitter relied on a specific attribute name being set
("team_name"), but we had renamed it to "team" which broke the metric.
* Rename `team` attribute to `team_name`
* this was broken in checks-as-builds, so doesn't affect any released version
* this changes the attribute name for traces as well - since it's experimental we figured it wouldn't be too big a problem 🤷  …
> Fix build finished metric for prometheus

- web/elm/src/Build/Header/Header.elm
- web/elm/src/Job/Job.elm
- web/elm/src/Resource/Resource.elm
- web/elm/src/Routes.elm
- web/elm/tests/Build/HeaderTests.elm
- web/elm/tests/JobTests.elm
- web/elm/tests/ResourceTests.elm
When we archived the `prs` pipeline and added some `prs` instance pipelines (with the same name as the old pipeline), the UI was rendering the pages as if the pipelines were archived. This is due to a bug in the pipeline lookup logic to check if the pipeline is archived - we were only considering the team name and pipeline name for uniqueness, and ignoring the instance vars.
* Use the common `SideBar.lookupPipeline` helper to look up the pipeline …
> Fix archived pipeline check on the resource/job/build page for an instanced pipeline

- skymarshal/skycmd/bitbucketcloud_flags.go
Signed-off-by: Aidan Oldershaw <aoldershaw@pivotal.io>
closes #6419 .
* Due to changes in upstream dex, we need to set `IncludeTeamGroups` to `true`
I'm not exactly sure how this worked before, ~and don't have a bitbucket cloud account to test this with, so 🤷~ but have tested this with a bitbucket cloud account and it seems to work fine. Here's how I tested it:
1. Created a new workspace in Bitbucket cloud (e.g. `testconcourse`)
2. Created a test group in the workspace and added my user account to it (e.g. `testgroup`)
3. Configured an OAuth app with redirect URI http://localhost:8080/sky/issuer/callback within the workspace, granting access to `Account > {Email, Read}` + …
> Add team groups to Dex response for Bitbucket connector

- atc/atccmd/command.go
Related to concourse/concourse-cart#194
This PR adds a `--migrate-to-latest-version` flag to the `migrate`
command. It will migrate the db to the latest version.
While doing concourse/concourse-chart#194 we found that the migrate
commnd does not automatically migrate to the latest db version. You can
do some shell scripting to accomplish that task using migrate and its
flags. We didn't want to write a script to do this in the chart though
and this seemed like a useful thing to add to the migrate command.
* add a `--migrate-to-latest-version` flag to the `migrate` command. This flag has concourse perform database migrations to the latest database version. …
> Add a flag to migrate to the latest db version

- atc/api/config_test.go
- atc/api/configserver/save.go
- atc/api/pipelines_test.go
- atc/api/pipelineserver/rename.go
- atc/api/teams_test.go
- atc/api/teamserver/rename.go
- atc/api/teamserver/set.go
- atc/configvalidate/validate.go
- atc/configvalidate/validate_test.go
- atc/configwarning.go
- atc/configwarning_test.go
- atc/step_validator.go
- fly/commands/internal/flaghelpers/pipeline_flag.go
- fly/commands/set_pipeline.go
- fly/commands/set_team.go
fixes #6405
These steps should always have names provided. Our docs note that names
are required but our validation doesn't return an error for empty
strings on these steps.
Put and Get steps are safe from this because the validator checks that
their resources exist.
* Return an error when no identifier is provided for task, set_pipeline, and load_var steps …
> Ensure task, set_pipeline, load_var steps have names

- package.json
- skymarshal/skycmd/oidc_flags.go
Bug Fix 
closes #6435
Since Dex has the option InsecureEnableGroups set to false by default and concourse did not overwrite this, the OIDC connector ignores the groups coming from the upstream provider. This seems to be pretty bad for concourse, since its current RBAC model heavily relies on groups and many users (including myself) use those to manage access.
Adding an --oidc-enable-groups flag allows to override this behavior (if necessary) and thus to use groups again.
Added an --oidc-disable-groups flag that by default fetches groups claims from an upstream OIDC provider. …
> Proposing fix for OIDC groups

- skymarshal/skycmd/oidc_flags.go
Update the flag description of `--oidc-scopes` to be cleared on the scopes that being used during auth.
> make it clear on oidc scopes configuration

- topgun/k8s/k8s_suite_test.go
Fix a CI error https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/406#L600541ac:1319
where web scalling test trying to set web replica from 1 to 0 when `clusterIP` is not specified (with value ""). The cause of the failure can be found here https://github.com/helm/helm/issues/6378#issuecomment-557746499
So in our testing, or in real world use case, we should not use --force with helm upgrade when clusterIP is not set. Actually we might not need to use --force at all. The fact that --force was used IMO was inherited from helm 2. With helm 3 that doing 3-way diff it is smart enough to do an upgrade without enforcing a replacement strategic.
> Remove --force in k8s-topgun test

- skymarshal/skycmd/oidc_flags.go
Add --oidc-disable-groups flag to OIDC connector configure.
Fixed a regression that introduced in 6.7.3 that OIDC connector by default not fetching groups claim. Now OIDC connector always fetches groups claim unless `--oidc-disable-groups` flag is set. Backport of https://github.com/concourse/concourse/pull/6436.
> Fix OIDC connector not fetching groups claim

- fly/commands/sync.go
- fly/commands/version.go
- fly/integration/execute_with_outputs_test.go
- fly/integration/sync_test.go
- fly/integration/version_test.go
- fly/rc/target.go
Backport of #6317 and #6320 for release/6.7.x. Now that we've bumped Dex, the fly windows tests are super slow and flaky. …
> Optimize fly windows tests

- topgun/core/vault_test.go
After #6115 was merged, all the Bosh Topgun tests exercising Vault
started failing. This is not due to the Vault integration being broken
(well, not really) - Bosh topgun is just using such an old (custom)
version of Vault that is no longer compatible I gather.
Since we're going to end up replacing all these tests shortly with a new
test suite (introduced in #6479), let's just skip these Vault tests for
now
[Signed]: …
> Skip Vault tests in Topgun

- web/elm/src/Dashboard/Filter.elm
- web/elm/tests/DashboardSearchBarTests.elm
since instanced pipelines are still experimental and we need to figure
out the UX for them, it's confusing to suggest the "group:" filter in
the search bar, especially because instanced pipelines are disabled by
default.
with this commit, we hide the "group:" filter from the dropdown so you
don't stumble upon it. note that if you want to apply a "group:" filter,
you still can, and it'll still give suggestions after you've typed
"group:"
> hide "group:" dropdown suggestion in search

- atc/db/db_suite_test.go
- atc/db/lock/lock_suite_test.go
- atc/db/lock/lock_test.go
- atc/db/migration/migration_suite_test.go
- atc/gc/gc_suite_test.go
- atc/integration/integration_suite_test.go
- atc/integration/team_migration_test.go
- atc/postgresrunner/ginkgo.go
- atc/postgresrunner/postgresrunner.go
- atc/scheduler/algorithm/suite_test.go
- cmd/concourse/concourse_test.go
- skymarshal/dexserver/dexserver_suite_test.go
Make tests that require running a local Postgres server faster (~2x faster on my machine)
```
ginkgo -p ./atc/db  560.68s user 1597.73s system 754% cpu 4:46.20 total
ginkgo -p ./atc/db  172.06s user 645.53s system 777% cpu 1:45.15 total
```
On CI, it seems to be a *bit* faster, but not as drastic - the DB suite went from ~3 minutes to ~2 minutes
* Create a `TEMPLATE DATABASE` once after migrations were run and replace the `testdb` after each test with a copy of the template
* `postgresRunner.Truncate` avoids needing to re-run migrations, but surprisingly to me, turned out to be pretty slow - it's a (relatively) constant time operation (regardless of the size of the tables), but for such small tables, it seems to be …
> Optimize postgres runner for db tests

- web/elm/src/SideBar/SideBar.elm
- web/elm/src/Views/TopBar.elm
- web/elm/tests/TopBarTests.elm
The instance group badge in the top bar (visible when you're viewing the pipeline/job/resource page for an instanced pipeline) displays a count that's inconsistent with the sidebar/dashboard because we weren't filtering out (non-favourited) archived pipelines …
> Ignore archived pipelines for instance group count in top bar

- atc/metric/emitter/prometheus.go
Bug Fix
closes #6505
Prometheus histogram `tasks_wait_duration` had a too thin partitioning that recorded only up to 20m. This means that everything >20m was clumped together, making it impossible to plot meaningful quantiles.
Detailed explanation, with plots, can be found in the associated ticket #6505
Better way is to have a look at the associated ticket #6505.
Metrics: `tasks_wait_duration` histogram will now record up to 1h (closes: #6505) …
> metrics: make tasks_wait_duration histogram record up to 1h

- atc/db/check_lifecycle.go
- atc/db/migration/migrations/1612565824_add_index_on_build_ids_to_resources.down.sql
- atc/db/migration/migrations/1612565824_add_index_on_build_ids_to_resources.up.sql
This PR adds an index to help speed up the deletion of the check builds and also adds a small refactor to the check lifecycle query. It should help speed up the query a little by using the `build_id` column on the resources table to figure out whether or not a check build needs to be gced or not.
The index will help speed up the `constraint resources_build_id_fkey on builds` from the checks gc query, here is the `EXPLAIN ANALYZE` of the query without the added index https://explain.depesz.com/s/Gl3M …
> Add index and mini refactor to the check lifecycle query

- atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.down.sql
- atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.up.sql
- atc/db/migration/migrations/1606068653_build_events_partitions_bigint.down.sql
- atc/db/migration/migrations/1606068653_build_events_partitions_bigint.up.sql
- atc/db/migration/migrations/1612457776_add_check_build_events_partition.down.sql
- atc/db/migration/migrations/1612457776_add_check_build_events_partition.up.sql
This PR removes a few indexes that should be unnecessary. Any queries that query on the `build_id` column can actually use the unique multi column index on `build_id` and `event_id`. Since the build events tables are updated really frequently, limiting the number of indexes that are applied to the table will help with the speed of inserts or updates.
These changes to existing migrations should be okay because it is not released yet with v7.0 but we did upgrade `ci` and `hush-house` with the migrations without this change so we will need to remove the indexes from those environments manually. …
> Removes unnecessary indexes from build events tables

- worker/runtime/spec/devices.go
- worker/runtime/spec/spec.go
- worker/runtime/spec/spec_test.go
Misc
Related to #6475
CC @taylorsilva 
~~We did a bunch of testing to verify that this rule is truly a no-op. We
even wrote a garbage rule:~~
```
{Allow: false, Access: "akdsjasdjasd"},
```
~~and the container was created successfully. With or without that rule
the list of devices in
/sys/fs/cgroup/devices/[container-id]/devices.list was the same as the
unprivileged containers under
/sys/fs/cgroup/devices/garden/[container-id]/devices.list~~
~~We later learned that this default list of devices is very permissive
and "arguably insecure" in the words of a runc dev.~~
~~In future it might make sense to further restrict unprivileged
containers, specifically removing the first two rules which allow mknod
for all block and char devices, which basically gives you read-write for
any device...~~ …
> worker/runtime: remove no-op device rule

- fly/rc/target_test.go
Go 1.16 CertPool [loads certs lazily now](https://github.com/golang/go/commit/e8379ab5964a920e59dbcc5bc4eaa1bbf5a88e90), which messes up the ordering of the certs and causes `reflect.DeepEquals` to not resolve it properly
Assert equivalence on the fields of the `TLSClientConfig` directly instead of the struct as a whole …
> Fix unit test after go 1.16

- fly/rc/target_test.go
backport of https://github.com/concourse/concourse/pull/6545
> [Backport 6.7.x] Fix unit test after go 1.16 

- fly/rc/target_test.go
> [Backport 7.0.x] Fix unit test after go 1.16

- web/elm/src/Build/Build.elm
It was pointing to a dead link. Now, it'll point to the new section created in concourse/docs#407 …
> Fix "reaped" link in UI

- atc/lidar/scanner.go
- atc/lidar/scanner_test.go
closes #6582
Lidar creates checks for parent resource types even if the resource has check_every set to true
Issue has steps to reproduce so you can do a before/after.
There are some other edge cases related to this issue, but to keep scope to a minimum and fix the most common situation I think people will run into, this PR should be enough.
* Resources that had `check_every: never` who's type was defined in `resource_types` in their pipeline, would fail to check because the parent resource type would never be checked …
> Check parent resource types

- worker/runtime/spec/mounts.go
- worker/runtime/spec/spec_test.go
closes #6578 (more context in the issue comments)
* Remove the `/run` mount - it's neither mounted by Guardian nor Docker (from what I can tell)
* Mount `/tmp/gdn-init` after all the other default mounts
* The bug was fixed by removing `/run`, but would have also been fixed by mounting `/tmp/gdn-init` last
* I figure that, while not strictly necessary for this bug fix, mounting it after the other mounts is a bit safer since it mirrors how we mount the other "normal" mounts (regular filesystem mounts, e.g. task inputs)
* Fix an issue on the containerd runtime where processes fail to run with certain container images …
> containerd: fix mount issues with certain images

- web/elm/elm.json
closes #6542 .
see vito/elm-ansi#8
With the following `task.yml`:
```yaml
source: {repository: python}
run:
path: python
args:
- -c
- |
def colorized8(text, n):
print(f"\033[48;5;{n}m{text}\033[m", end='')
def colorized24(text, r, g, b):
print(f"\033[48;2;{r};{g};{b}m{text}\033[m", end='')
print("8 bit")
print("-----")
for i in range(16):
for j in range(16):
colorized8("    ", i * 16 + j)
print()
print("24 bit")
print("------")
r = 127
for g in range(0, 256, 4):
for b in range(0, 256, 2):
colorized24(" ", r, g, b)
print()
```
With elm-ansi v9.0.1:
With elm-ansi 10.0.0:
* Fixes a bug where ANSI escape codes for 8-bit/24-bit colors …
> Bump elm-ansi to support 8-bit and 24-bit ANSI colors

- worker/runtime/spec/namespaces.go
Feature
closes #6474 .
[cgroup namespaces]() give a process its own set of cgroup root directories. This allows for better isolation from the host or parent/ancestor processes.
Support for this feature was [introduced](https://phoronix.com/scan.php?page=news_item&px=CGroup-Namespaces-Linux-4.6) in Linux Kernel 4.6. The minimum Kernel version we support with containerd is 4.4 on Ubuntu 16.04. Fortunately, Ubuntu's own distribution of Kernel 4.4 (used on 16.04 Xenial) had the feature [backported](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1546775) via a patch.
This can be confirmed by running a VM with the latest Ubuntu 16.04 image (e.g. `generic/ubuntu1604` in Vagrant). `cgroup` is listed under namespaces.
```diff
vagrant@ubuntu1604:~$ uname -a
Linux ubuntu1604.localdomain …
```
> Start non-privileged containers in their own cgroup namespace

- integration/docker-compose.yml
- integration/worker/mtu_test.go
- integration/worker/overrides/bridge_mtu.yml
- integration/worker/overrides/custom_mtu.yml
- integration/worker/tasks/assert_mtu.yml
- worker/mtu/mtu.go
- worker/mtu/mtu_test.go
- worker/runtime/cni_network.go
- worker/workercmd/containerd.go
- worker/workercmd/worker_linux.go
closes #6613
potentially fixes #6599 
* Match Guardian's behaviour of inferring the MTU to use for the container's bridge network by finding the network interface corresponding to the host's external IP - see https://github.com/cloudfoundry/guardian/blob/15a56cca9deaa1ad04c9c10f91054e7ce82bf3c0/guardiancmd/command.go#L420-L426
* As with Guardian, the MTU and external IP can still be configured
* In prior versions of Concourse, the Containerd runtime always set the MTU of the container bridge network to the system default
* Now, the Containerd matches Guardian's behavior by:
* Detecting the external IP of the host (can be set explicitly using `CONCOURSE_CONTAINERD_EXTERNAL_IP`)
* …
> containerd: infer MTU from host's network interface

- go.mod
- go.sum
closes #6620
Bump baggageclaim to v1.11.0
New version uses overlay's metacopy feature when creating COW volumes.
This will result in faster initialization time for privileged tasks.
From testing on my machine:
- (Before) privileged container initialization: 51s
- (After metacopy enabled) privileged container initialization: 3s
* Privileged container initialization will be much faster for workers using OverlayFS as the baggageclaim driver and if their kernel supports OverlayFS's metacopy feature …
> Bump baggageclaim to v1.11.0

- atc/api/present/pipeline.go
- atc/pipeline.go
- fly/commands/internal/setpipelinehelpers/atc_config.go
- fly/integration/set_pipeline_test.go
closes https://github.com/concourse/concourse/issues/5814.
This PR resolves the last missing piece to complete [RFC #31](https://github.com/concourse/rfcs/blob/master/031-set-pipeline-step/proposal.md). With this change `fly set-pipeline` will notify the operator that the pipeline has been configured with `set_pipeline` step and all changes may be lost on the next `set_pipeline` step execution. 
<details><summary>set-pipeline command output</summary>
<p>
```
❯ ./fly-darwin -t local sp -p hello -c pipeline.yml
resource types:
resource type registry-image-resource has changed:
name: registry-image-resource
source:
-   repository: xxx/registry-image-resource1
+   repository: …
```
> Show warning for pipelines configured with 'set_pipeline' step

- worker/runtime/integration/integration_test.go
- worker/runtime/libcontainerd/client.go
- worker/runtime/libcontainerd/container.go
- worker/runtime/libcontainerd/helper.go
closes #6622 
In case `CONCOURSE_CONTAINERD_REQUEST_TIMEOUT` is set to 0 we should get a context with no deadline
* When `CONCOURSE_CONTAINERD_REQUEST_TIMEOUT` is set to 0 that means there is no timeout …
> runtime: timeout set to 0 means there is no timeout

- atc/builds/tracker.go
- atc/engine/engine.go
- atc/exec/check_step.go
- atc/metric/emit.go
- atc/metric/emitter/newrelic.go
- atc/metric/emitter/prometheus.go
- atc/metric/metrics.go
- atc/metric/periodic.go
- atc/scheduler/buildstarter.go
**Bug Fix** | **Feature** | Documentation
closes #6614  .
* Exclude check builds from existing metrics `BuildsStarted`, `BuildsRunning`, `BuildStarted`, `BuildFinsished`
* Add check build metrics: `CheckBuildsStarted`, `CheckBuildsRunning`, `CheckBuildStarted`, `CheckBuildFinsished`
We should deprecate `CheckStarted`, `ChecksFinishedWithSuccess` and `ChecksFinishedWithError`. Maybe we should only delete them after a few releases to educate users to new the check build metrics.
* Fixed metrics `BuildsStarted`, `BuildsRunning`, `BuildStarted`, `BuildFinsished` to exclude check builds.
* Added check build metrics: `CheckBuildsStarted`, `CheckBuildsRunning`, `CheckBuildStarted`, `CheckBuildFinsished` …
> feat(atc): add check build metrics.

- .github/CODEOWNERS
- .github/auto_pr_team.yml
- .github/dependabot.yml
* remove no-longer-used auto-team-invite bot config
* remove no-longer-used (and empty) stale bot config
* update `CODEOWNERS` to reflect new teams from governance model
* enable dependabot
tests](https://github.com/concourse/ci/tree/master/tasks/scripts …
> github config updates

- worker/runtime/process_killer.go
- worker/runtime/process_killer_test.go
Bug Fix
When killing a process gracefully containerd might exceed the waitperiod. When this happens it returns an error in a format that couldn't be handled properly. We now look at the specific grpc code for better handling.
Signed-off-by: Bohan Chen <bochen@pivotal.io>
Co-authored-by: Muntasir Chowdhury <mchowdhury@pivotal.io>
closes #6587.
```diff
diff --git a/worker/runtime/process_killer.go b/worker/runtime/process_killer.go
index 5dc61a2e4..668752f82 100644
--- a/worker/runtime/process_killer.go
+++ b/worker/runtime/process_killer.go
@@ -54,7 +54,10 @@ func (p processKiller) Kill(
waitCtx, cancel := context.WithTimeout(ctx, waitPeriod)
defer cancel()
-       statusC, err := proc.Wait(waitCtx)
+       waitCtx2, …
```
> better handling for containerd error message

- testflight/container_limits_test.go
- worker/runtime/spec/spec.go
- worker/runtime/spec/spec_test.go
closes #6649
The containerd runtime has been updated to check if swap limits is
enabled and will conditionally set them if they're enabled.
These testflight tests will always fail for Guardian if swap limits are
disabled on the host, unless Guardian is told to not set the swap limit.
This depends on using runc-93. Anything earlier will cause the tests to fail when they should be skipped, only for the Guardian runtime though.
* The containerd runtime will conditionally set memory swap limits if it detects that memory swap limits are enabled …
> runtime: check if swap limits is enabled

- atc/metric/emitter/newrelic.go
closes #6742
Backporting a fix already made on master to avoid occasional panics in the newrelic emitter
* Fix a panic in the New Relic metrics emitter
tests](https://github.com/concourse/ci/tree/master/tasks/scripts …
> release/6.7.x: check returned error before deferring resp.Body.Close()

- go.mod
- go.sum
closes #6743
the postgres driver had a regression where it wouldn't drop dead
connections resulting in all queries failing with tcp errors. The driver
never recovers and restarting your process is the only workaround. The
issue was resolved in 1.9.0 of the driver
related discussion: https://github.com/lib/pq/issues/835
This issue is hard to reproduce. We worked with the support team to verify that this fixes the issue.
* Bump lib/pq to 1.10.0 which fixes a regression where under certain circumstances the driver would not drop dead connections and never recover. …
> release/6.7.x: Bump lib/pq to 1.10.0

- topgun/k8s/k8s_suite_test.go
this happens after postgresql chart version bumped
we don't really need it with helm3 deployment
> remov --force in k8s topgun test set up

- skymarshal/web/templates/password.html
Was already added to the password field. This commit adds it to the form
and username tags.
* add `autocomplete="off" to the form and username tags on the login page …
> 6.7.x - Add autocomplete=off to all form tags

- atc/db/pipeline.go
- atc/db/pipeline_test.go
Backport #7327 to 6.7.x.
I saw there are a few pending PRs on branch 6.7.x, so just backport #7327 also. Once 6.7.8 is released, we'll upgrade to it immediately as we are now on 6.7.6.
* Optimized a SQL statement used to remove build logs. This optimization will specially benefit large deployments that have a lot of pipelines.
> Optimize build log collector

- worker/integration/integration_test.go
the old unit-image didn't support btrfs, so `driver: detect` would
default to overlay. the unit image isn't equipped to run btrfs (needs
"an unused loopback"). let's just use overlay here, which is now the
default on master
> Use overlay driver for worker integration test [6.7.x]

- skymarshal/skyserver/skyserver.go
- skymarshal/skyserver/skyserver_test.go
> 6.7.x: Prevent open redirect to other hosts

- integration/internal/cmdtest/cmd.go
- integration/worker/dns_test.go
- integration/worker/overrides/add_extra_dns_servers.yml
- integration/worker/overrides/disable_dns_proxy.yml
- integration/worker/overrides/enable_dns_proxy.yml
- integration/worker/tasks/cat_file.yml
- integration/worker/tasks/resolve_web_dns.yml
- topgun/k8s/dns_proxy_test.go
- worker/network/dns.go
- worker/workercmd/worker_linux.go
backporting https://github.com/concourse/concourse/pull/6947 for fixing the flaky test for dns proxy in k8s-topgun job in release pipeline 6.7.x
> refactor dns package and test

- fly/integration/suite_test.go
- worker/baggageclaim/integration/baggageclaim/suite_test.go
- worker/baggageclaim/integration/fs_mounter/suite_test.go
darwin worker had problem with external disk where we use as Concoures worker dir. It had to be reboot and unmount/mount the disk. The problem was gone since but the side effect of rebooting the machine was golang upgrade to 1.19.2, which seems now throwing error
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
so here we are adding the flag to go builds in where errors are thrown. This change is barkporting from master.
> add buildvcs=false to go build in integration tests v6.8.x
