concourse/concourse

.gitmodules
=> move gate repository url to https, as with all other submodule urls

CONTRIBUTING.md
i made a mistake in the last pull-request.
Reopened here.  Right sort of changes.
Sorry @vito
=> Documentation changes

ci/pipelines/concourse-redeploy.yml
=> Add pipeline config for redeploying concourse.

manifests/cloudformation.json
This is nice, since the hard coded bosh keypair isn't always desired
=> Add KeyName parameter support for selecting an existing keypair

docs/fly-cli.any
Closes #208
[finishes #108719616]
=> Update documentation to reflect fly execute API.

docs/README.md
=> Fix typo in docs README.

docs/concepts/resources.any
=> Add Pivotal Network to third-party resources.

manifests/bosh-init-aws.yml
Updates the versions and hashes to the current releases. Hoping this helps newcomers to Concourse.
=> Update bosh init manifest

docs/implementing-resources.any
[#11346088]
Signed-off-by: Utako Ueda <uueda@pivotal.io>
=> Update concourse docs to include ATC_EXTERNAL_URL

docs/concepts/resources.any
Signed-off-by: Anoop Gopalakrishnan <agopalakrishnan@pivotal.io>
=> Added link to the cloudformation resource

docs/restricting-access.any
https://github.com/concourse/atc/pull/60
=> Add docs for Github Enterprise config.

README.md
getting started link redirects to a 404
Nothing fancy, replaced it with introduction :)
=> Update README, getting started

docs/index.any
Matches http://concourse.ci/hello-world.html
=> Use image_resource instead of image

docs/using-concourse/resource-types.any
Added Hipchat Notification Resource to the resource-type page
=> Adding HipChat Notifications to resource-types

docs/using-concourse/hello-world.any
Use the correct pipeline name.
=> Fix documentation

docs/using-concourse/resource-types.any
Add Matrix Notification Resource type to Resource Types page of website
=> Add Matrix Notification Resource type

docs/using-concourse/resource-types.any
ami-resource checks for new Amazon Machine Images (AMIs).
debian-sources-resource checks for updated Debian and Ubuntu compatible package sources.
=> Add ami-resource and debian-sources-resource

docs/using-concourse/resource-types.any
- https://github.com/ljfranklin/terraform-resource
=> Add link to community terraform resource

docs/using-concourse/resource-types.any
=> Add rsync resource link

docs/using-concourse/resource-types.any
The resource allows to send simple notifications to the Telegram chat.
=> Add the link to the Telegram Resource

docs/using-concourse/resource-types.any
Adding Google Cloud storage resource made by ferdy @frodenas
=> Adding GCS resource

docs/using-concourse/fly-cli.any
https://github.com/concourse/fly/issues/85
https://github.com/concourse/fly/pull/100
https://github.com/concourse/go-concourse/pull/3
Add pause-resource and unpause-resource to fly-cli docs.
=> Add pause-resource and unpause-resource

jobs/atc/spec, jobs/atc/templates/atc_ctl.erb
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>
=> add auth_duration to ATC spec

jobs/atc/spec, jobs/atc/templates/atc_ctl.erb
This PR depends on https://github.com/concourse/atc/pull/104 being merged first.
=> add riemann service prefix

docs/using-concourse/resource-types.any
Updated documentation to show the existence of the hg resouce
=> Added hg resource to list

docs/using-concourse/fly-cli.any
=> Deprecate the self-deprecation

docs/configuring/jobs.any
As implemented in https://github.com/concourse/atc/pull/125.
=> Document job hooks.

docs/steps/put.any
Update the put step to include information about get_params with an example.
=> Document get_params.

docs/using-concourse/resource-types.any
This adds the GitLab merge request resource I have created.
=> Add GitLab merge request resource to docs

docs/using-concourse/fly-cli.any
=> Document validate-pipeline command.

docs/README.md
=> Docs now live at index.any

docs/using-concourse/resource-types.any
https://github.com/santoshjpawar/concourse-email-notification
=> Added formatted email resource

docs/using-concourse/resource-types.any
Added "Cloud Foundry Event" resource type for tracking application events within a given Cloud Foundry target.
=> Added "Cloud Foundry Event" resource type

docs/using-concourse/resource-types.any
Added cURL file resource to the resources list page.
https://github.com/pivotalservices/concourse-curl-resource
=> Add cURL File resource to the resources list

docs/tutorials/flight-school.any
It must locate under flight-school dir
=> Clarify location of build.yml file

docs/using-concourse/resource-types.any
1. Implemented with bash scripts
2. Can download multiple products in one operation.
3. You must specify exact product version that needs to be downloaded.
=> Download pivotal products and stemcells

docs/steps/put.any
=> Fix yaml example in document

docs/using-concourse/resource-types.any
I added the link to resource I did, differently from the other telegram resource this also support receiving messages.
=> Telegram resource

docs/using-concourse/resource-types.any
Add [resource](https://github.com/zarplata/concourse-git-bitbucket-pr-resource) to docs.
=> Add git bitbucket pull request resource

docs/using-concourse/fly-cli.any
=> Document the --tag option for fly

docs/lit/using-concourse/resource-types.lit
Hi I would like to add a new resource to the list. A resource that can trigger jobs using slack
=> A resource that can trigger jobs using slack

docs/lit/using-concourse/resource-types.lit
Also, update URL to Gerrit Resource (they now share a repo).
=> Add Repo Resource to Community Resources

CONTRIBUTING.md
Some steps copied from atc CONTRIBUTING.md.
=> Add a section for initial setup of local dev environment

jobs/atc/spec, jobs/atc/templates/atc_ctl.erb
Super want this in Garden-land.
=> Make container placement strategy BOSH settable

jobs/atc/spec, jobs/atc/templates/atc_ctl.erb
=> Add intercept timeout property.

.gitmodules, jobs/atc/spec, jobs/atc/templates/atc_ctl.erb, packages/atc/spec
This PR depends on https://github.com/concourse/atc/pull/229
=> Update spec with SSM parameter store credential management

CONTRIBUTING.md
I hit this issue, figured I'd document the fix.
=> troubleshooting tip for dev/worker on macOS

jobs/bbr-atcdb/spec, jobs/bbr-atcdb/templates/backup.sh.erb, jobs/bbr-atcdb/templates/config.json.erb, jobs/bbr-atcdb/templates/restore.sh.erb
inspired by: https://github.com/cloudfoundry/uaa-release/tree/develop/jobs/bbr-uaadb
depends on: https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release
=> Added bbr-atcdb job for use with backup-and-restore-sdk-release

jobs/atc/spec, jobs/atc/templates/atc_ctl.erb
=> Add ability to specify default and maximum number of build logs to retain

jobs/atc/spec, jobs/atc/templates/atc_ctl.erb
=> Add properties for emitting to Datadog to ATC

jobs/atc/spec
=> Fix oauth userinfo description

dev/atc-dockerdb
I fixed `atc` command in atc-dockerdb.
=> Fix atc command in dev/atc-dockerdb

atc/api/configserver/save.go, atc/config.go, atc/decode_hook.go, atc/exec/garden_factory.go, atc/exec/put_inputs.go, atc/exec/put_step.go, atc/exec/put_step_test.go, atc/plan.go, atc/scheduler/factory/build_factory.go, atc/scheduler/factory/factory_put_test.go, testflight/fixtures/put-inputs.yml, testflight/put_inputs_test.go
=> atc: add configurable inputs to the put step

CONTRIBUTING.md
Added a very simple contribution process to the top of this doc as a starting point. If there are any other Concourse-specific requirements for contributing, we can add more details.
=> Contribution process

atc/api/present/worker.go, atc/api/workers_test.go, atc/db/dbfakes/fake_worker.go, atc/db/migration/migrations/1543350138_add_active_volume_to_workers.down.sql, atc/db/migration/migrations/1543350138_add_active_volume_to_workers.up.sql, atc/db/worker.go, atc/db/worker_factory.go, atc/db/worker_factory_test.go, atc/worker/worker.go, atc/worker/workerfakes/fake_worker.go
Fix for [#2766](https://github.com/concourse/concourse/issues/2766).
Add active volumes to heartbeat.
=> Fix workers endpoint to show active_volumes

CONTRIBUTING.md
submitting this as a PR to test the DCO bot!
=> document DCO process, update testing docs

web/elm/src/StepTree.elm, web/wats/test/build.js, web/wats/test/login.js
seems to be failing consistently at the moment, found at least one root cause so far (hyphenating assets caused a selector mismatch)
=> fix watsjs

skymarshal/skyserver/skyserver.go, skymarshal/skyserver/skyserver_test.go
can't cherry pick the commits directly since the flow has changed a bit
fixes concourse/concourse#2999
=> atc: ports the changes from the security fix in 4.2.2

skymarshal/skyserver/skyserver.go, skymarshal/skyserver/skyserver_test.go
This reverts commit e088bfa50d113328167049220264b8594dbd3ab0.
fixes #2962
=> Revert "Add new endpoint to get token for manual fly login"

skymarshal/skycmd/flags.go
=> replaced atc start verbiage  with references to web instead

web/assets/css/layout.less, web/assets/css/notauthorized.less, web/elm/src/NotAuthorized.elm, web/elm/src/TopBar.elm, web/elm/tests/BuildTests.elm
Fixes #3118
`$ ag '_[A-Za-z]+\.svg'` has no output.
=> web: fix passport officer asset path

web/elm/src/Build.elm, web/elm/src/Build/Styles.elm, web/elm/tests/BuildTests.elm
=> web: Added 0 margins to buttons on the build page

web/elm/src/Build/StepTree.elm, web/elm/tests/BuildTests.elm
=> web: align resource version to right of step headers on build page

web/elm/src/BoolTransitionable.elm, web/elm/src/Colors.elm, web/elm/src/Resource.elm, web/elm/src/Resource/Models.elm, web/elm/src/Resource/Styles.elm, web/elm/tests/ResourceTests.elm
=> web: fix pinned version borders on resource page

ci/pipelines/concourse.yml, ci/pipelines/prs.yml
=> ci: add more workers for running prs

web/elm/src/Build.elm, web/elm/src/Callback.elm, web/elm/src/Dashboard.elm, web/elm/src/Effects.elm, web/elm/src/FlySuccess.elm, web/elm/src/Job.elm, web/elm/src/Layout.elm, web/elm/src/Pipeline.elm, web/elm/src/Resource.elm, web/elm/src/Resource/Models.elm, web/elm/src/Resource/Msgs.elm, web/elm/src/SubPage.elm, web/elm/src/TopBar.elm, web/elm/tests/BuildTests.elm, web/elm/tests/DashboardTests.elm, web/elm/tests/FlySuccessTests.elm, web/elm/tests/JobTests.elm, web/elm/tests/NewTopBarTests.elm, web/elm/tests/PipelineTests.elm, web/elm/tests/ResourceTests.elm, web/elm/tests/SubPageTests.elm
- Moved Callbacks into their own file
- Refactored Resource.elm a little
=> web: refactor

atc/db/migration/migration.go, atc/db/migration/migration_test.go, atc/db/migration/parser.go, atc/db/migration/parser_test.go
=> atc/db/migrations: allow for multiline non-transactional migrations

ci/pipelines/resources/template.jsonnet
=> ci: add s3 resource type to cf resource pipeline

CONTRIBUTING.md, Dockerfile, ci/dockerfiles/dev/Dockerfile
=> don't build web UI in Dockerfile

fly/commands/curl.go, fly/commands/fly.go, go.mod
Following discussion in https://github.com/concourse/concourse/pull/3056 and https://github.com/concourse/concourse/pull/3056 here is fly curl using actual curl.. :)
Three issues.
1. Does not work  with custom CA certs as I have no way of testing that.
2. Printing the curl command is borked, look at the comment in `printableCommand`
3. No tests, but I don't know if thats an actual problem currently as we mainly just pass data around
=> fly curl, take 3

web/elm/src/Build.elm, web/elm/tests/BuildTests.elm
=> web: fix alignment on build prep details

ci/dockerfiles/dev/Dockerfile, ci/pipelines/concourse.yml
=> ci: package all base resource types into binary

atc/resource.go, fly/commands/resources.go, fly/integration/resources_test.go, fly/ui/present.go
=> fly: replace 'paused' column with 'pinned'

CONTRIBUTING.md, hack/db
nicer ux, syntax highlighting, better completion, etc
=> hack/db: use pgcli if available

ci/pipelines/concourse.yml
...also make this a requirement for a new rc
=> ci: upgrade/downgrade earlier in pipeline

atc/atccmd/command.go, ci/pipelines/concourse.yml, topgun/operations/add-placement-strategy.yml
https://www.youtube.com/watch?v=G0zNWswcqMg
=> least -> fewest

web/elm/src/Build.elm, web/elm/src/Build/Models.elm, web/elm/src/Build/Msgs.elm, web/elm/src/Build/Output.elm, web/elm/src/Build/StepTree.elm, web/elm/src/Dashboard.elm, web/elm/src/Dashboard/Footer.elm, web/elm/src/Dashboard/Pipeline.elm, web/elm/src/DashboardPreview.elm, web/elm/src/Effects.elm, web/elm/src/Job.elm, web/elm/src/Job/Msgs.elm, web/elm/src/Layout.elm, web/elm/src/Msgs.elm, web/elm/src/NewestTopBar.elm, web/elm/src/Resource.elm, web/elm/src/Resource/Msgs.elm, web/elm/src/Routes.elm, web/elm/src/TopBar.elm, web/elm/src/TopBar/Msgs.elm, web/elm/tests/BuildTests.elm, web/elm/tests/JobTests.elm, web/elm/tests/NewestTopBarTests.elm, web/elm/tests/PipelineTests.elm, web/elm/tests/StepTreeTests.elm, web/elm/tests/TopBarTests.elm
Also a little build model shuffling to prevent dependency cycles
=> Web: navigation now (almost) all passes through routes rather than string construction

web/elm/src/Dashboard/Footer.elm, web/elm/tests/DashboardTests.elm
=> web: fix dashboard HD toggle

web/public/graph.js, web/public/index.js
Fixes #2967
Perhaps predictably, I'd feel better making changes to the pipeline view with tests. @vito does it feel worth backfilling a suite of tests for this with a rewrite for spaces on the horizon?
=> web: use hardcoded pin icon height in pipeline view

web/elm/src/NewTopBar/Styles.elm, web/elm/src/NewestTopBar.elm, web/elm/tests/NewestTopBarTests.elm, web/elm/tests/PipelineTests.elm
=> web: fixed paused top bar colouration on pin and on login separator

testflight/fixtures/put-inputs.yml, testflight/put_inputs_test.go
This PR adds a failing test case for #3246
=> Add failing test for #3246

ci/pipelines/resources/template.jsonnet
=> ci: update build args for registry-image pipeline

tsa/client.go
this was relying on map iteration order, which is not actually
guaranteed to be random - Go only sneaks randomness in there once in a
while so you don't depend on iteration order. turns out you can't depend
on random order, either, which is totally reasonable.
fixes #3214
=> tsa: improve random tsa host selection

atc/scripts/bump-migration
It finds the migrations that are not on master and renames them.
=> Add a script that bumps migration timestamps

web/assets/css/layout.less, web/elm/src/Application/Application.elm, web/elm/src/Colors.elm, web/elm/src/Pipeline/Pipeline.elm, web/elm/src/Pipeline/Styles.elm, web/elm/src/SubPage/SubPage.elm, web/elm/tests/PipelineTests.elm
=> web: fix styles on group bar

web/assets/css/layout.less, web/wats/package.json, web/wats/test/build.js, web/wats/yarn.lock
=> web: fix autoscroll on build page

skymarshal/skyserver/skyserver.go, skymarshal/skyserver/skyserver_test.go
=> Standardize the userinfo response

web/elm/src/BuildDuration.elm, web/elm/tests/BuildTests.elm
=> web: add tests and formatting

web/elm/src/Dashboard/Dashboard.elm, web/elm/src/Dashboard/Styles.elm, web/elm/tests/DashboardSearchTests.elm
Fixes #3342
This regression has reappeared a number of times, so this will put our testing strategy to the test!
=> web: fix layout/size of "no results" text on dashboard

fly/README.md
add correct `fly` dir, add `go get` step for Go dummies like me
=> Fix fly binary instructions

web/elm/src/TopBar/Msgs.elm, web/elm/src/TopBar/Styles.elm, web/elm/src/TopBar/TopBar.elm, web/elm/tests/PipelineTests.elm, web/elm/tests/TopBarTests.elm
=> web: made entire pipeline breadcrumb zone clickable

ci/pipelines/concourse.yml, ci/tasks/docker-semver-tags.yml
thankfully these were all pretty minor and easy to recover from!
=> ci: fix a few odds and ends for shipping

ci/tasks/scripts/prep-release-assets
=> ci: add version numbers to fly asset filenames

topgun/fly.go, topgun/k8s/external_worker_test.go
=> topgun/k8s: Add test coverage for external workers (fixes #3203)

web/elm/src/Build/Models.elm, web/elm/src/Build/Msgs.elm, web/elm/src/Dashboard/DashboardPreview.elm, web/elm/src/Dashboard/Group.elm, web/elm/src/Dashboard/Msgs.elm, web/elm/src/Job/Msgs.elm, web/elm/src/NotFound.elm, web/elm/src/Pipeline/Msgs.elm, web/elm/src/Resource/Msgs.elm, web/elm/src/TopologicalSort.elm, web/elm/tests/DashboardTests.elm, web/elm/tests/SubPageTests.elm, web/elm/tests/TopologicalSortTests.elm
=> web: fixed stackoverflow crash on circular pipelines

ci/pipelines/resources/template.jsonnet
=> ci (concourse-pipeline resource): fix glob for fly

topgun/fly.go, topgun/k8s/mainteam_role_test.go
fixes: concourse/concourse#3423
cc @pivotal-bin-ju
=> topgun/k8s: verify user roles with config map

atc/metric/emitter/prometheus.go, atc/metric/metrics.go
Hey,
This PR aims at addressing https://github.com/concourse/concourse/pull/2869#issuecomment-444898601.
Previously, `worker state` would report on a per-worker base the state of the worker:
worker_state (worker=worker1, state=stalled)
worker_state (worker=worker2, state=running)
...
While that works well for our push-based emitters (like Influx and Datadog), it presents some problems for pull-based ones (like Prometheus) as we end up needing to catch up with what are workers that are not around anymore and performing some GC (this could be remediated by using "const" metrics, but that'd require `emit` to send multiple metrics in a single event).
Assuming that the goal of the operator is to know whether there are any workers that are stalled, then a simple per-state gauge can be adopted, …
=> atc: replace per-worker state info by aggregated workers_registered metric

web/elm/src/Build/Build.elm, web/elm/src/Build/StepTree/StepTree.elm, web/elm/src/LoadingIndicator.elm, web/elm/src/Resource/Resource.elm, web/elm/src/Spinner.elm, web/elm/tests/BuildTests.elm
all it really needs is a margin parameter, not an arbitrary list of attributes.
=> web: refactor spinner

topgun/k8s/external_postgres_test.go, topgun/k8s/prometheus_test.go
=> topgun/k8s: add test to verify connectivity to external pg

.github/support.yml
=> configure support bot

topgun/k8s/kubernetes_creds_mgmt_test.go
- Added tests for consuming creds from an external namespace.
fixes: concourse/concourse#3107
=> topgun/k8s: Test external team namespaces

topgun/k8s/baggageclaim_drivers_test.go, topgun/k8s/container_limits_test.go, topgun/k8s/ephemeral_worker_test.go, topgun/k8s/external_postgres_test.go, topgun/k8s/external_worker_test.go, topgun/k8s/garden_config_test.go, topgun/k8s/k8s_suite_test.go, topgun/k8s/kubernetes_creds_mgmt_test.go, topgun/k8s/mainteam_role_test.go, topgun/k8s/prometheus_test.go, topgun/k8s/rebalance_test.go
- added tests for container_limits for both ubuntu and cos, ubuntu doesn't seem to be working.
- added rand number generator to fix the `--wait=false` problem
- fixed tests naming
for the issue: concourse/concourse#3102
=> topgun/k8s: container limits

ci/overrides/docker-compose.ci.yml, ci/overrides/docker-compose.no-build.yml, ci/pipelines/prs.yml, ci/tasks/docker-compose-testflight.yml, ci/tasks/docker-compose-watsjs.yml, ci/tasks/scripts/downgrade-test, ci/tasks/scripts/upgrade-test, ci/tasks/scripts/with-docker-compose
@pivotal-jwinters this is why #3307 was failing
=> ci: build from source for PRs

fly/commands/delete_target.go, fly/commands/edit_target.go, fly/commands/fly.go, fly/commands/logout.go, fly/integration/delete_target_test.go, fly/integration/edit_target_test.go, fly/rc/targets.go, fly/rc/targets_test.go
In reference to [#2659](https://github.com/concourse/concourse/issues/2659).
Additionally:
- Updated method signature for logout method to better represent functionality. (DeleteTarget -> LogoutTarget)
=> Add delete and edit target functionality

topgun/k8s/external_worker_test.go
- This fixes the team external workers test after merging helm/charts#12056
Signed-off-by: Bishoy Youssef <byoussef@pivotal.io>
=> topgun/k8s: New External workers functionality

cmd/concourse/worker.go, go.mod, go.sum, worker/container_sweeper.go, worker/tsa_config.go, worker/volume_sweeper.go
Requires https://github.com/concourse/baggageclaim/pull/17 to be merged in beforehand.
Fixes issue #2833
=> Parallelize container and volume GC on worker

topgun/k8s/baggageclaim_drivers_test.go, topgun/k8s/container_limits_test.go, topgun/k8s/ephemeral_worker_test.go, topgun/k8s/external_postgres_test.go, topgun/k8s/external_worker_test.go, topgun/k8s/garden_config_test.go, topgun/k8s/k8s_suite_test.go, topgun/k8s/kubernetes_creds_mgmt_test.go, topgun/k8s/mainteam_role_test.go, topgun/k8s/prometheus_test.go, topgun/k8s/rebalance_test.go
- Increase default timeouts for eventually and consistently
- refactor namespace & releaseName to suite level
- fix rand generator seeding for releaseName/namespace
- fix missing svc prefix in main_team_role test
=> topgun/k8s -  Fix tests

ci/dockerfiles/rc/Dockerfile
fixes https://github.com/concourse/concourse-docker/issues/38
=> ci: build rc image with 'file'

atc/db/build.go
=> fix resource not found bug

web/wats/test/build.js
it is now yielding diminishing returns.
=> remove flaky build page wats test

ci/deployments/smoke/smoke.tf, ci/pipelines/concourse.yml
two pretty unrelated commits but :man_shrugging:
=> ci: fix bin-smoke postgres install, switch logs to info level

atc/atccmd/command.go
the logic of initializing creds manager is pull ahead of construct api and backend members
=> atc: fix two creds manager instantiated

web/elm/src/Build/StepTree/Models.elm, web/elm/src/Build/StepTree/StepTree.elm, web/elm/src/Concourse.elm, web/elm/src/Network/BuildPlan.elm, web/elm/tests/BuildTests.elm
Branched from #3641, please merge it first.
Fixes #2235
=> Fix build page for one-off builds with inputs/outputs

web/elm/src/Build/Build.elm, web/elm/tests/BuildTests.elm
=> web: show breadcrumbs on job build visited by id

package.json, web/elm/elm.json, web/elm/src/Concourse.elm, web/elm/src/Concourse/PipelineStatus.elm, web/elm/src/Dashboard/Dashboard.elm, web/elm/src/Dashboard/Filter.elm, web/elm/src/Dashboard/SearchBar.elm, web/elm/src/Resource/Resource.elm, web/elm/tests/DashboardSearchTests.elm
=> web: fix "status: running" filter

topgun/k8s/baggageclaim_drivers_test.go
fixes: #3604 
- Add unpause pipeline (gotcha!)
- Add `-w` to the trigger command to make sure the task runs to completion.
cc: @xtreme-sameer-vohra
=> [topgun/k8s]: Baggageclaim extra coverage (#3604)

atc/scheduler/inputmapper/inputmapper.go, atc/scheduler/inputmapper/inputmapper_test.go
=> Use get step pinned version over api/config pinned version

NOTICE.md
this way we don't have to continuously update the year. this approach
seems to be cromulent - CF projects do the same thing.
=> say "Present" in NOTICE.md

atc/engine/build_step_delegate.go, atc/event/events.go, web/elm/src/Build/StepTree/StepTree.elm, web/wats/test/build.js
=> atc: attach timestamp to error events

web/elm/src/Pipeline/Pipeline.elm, web/elm/src/Pipeline/Styles.elm, web/elm/tests/PipelineTests.elm
=> web: fix styles on groups bar

ci/pipelines/concourse.yml
Reverts concourse/concourse#3289
=> Revert "temporarily disable fewest-build-containers"

atc/atccmd/command.go, atc/integration/configuration_test.go, ci/pipelines/concourse.yml
Please merge concourse/concourse-bosh-deployment#151 first.
=> ci: allow iframes on prod

atc/api/api_suite_test.go, atc/api/buildserver/events.go, atc/api/buildserver/server.go, atc/api/handler.go, atc/atccmd/command.go
Its not used. No one writes to this channel.
=> atc: remove unused drain in build server

ci/pipelines/concourse.yml, ci/pipelines/prs.yml, ci/pipelines/reconfigure.yml, ci/pipelines/release.yml, ci/pipelines/resources/template.jsonnet, ci/pipelines/upgrade-downgrade-pipeline.yml
https://materialdesignicons.com/
`resource type` => `material-design-icon-name`
- git => github-circle
- registry-image => docker
- github-release => package-variant-closed
- bosh-io-release => package-variant-closed
- bosh-io-stemcell => package-variant-closed
- s3 => cloud
- gcs => cloud
- semver => tag
- github-pull-request => source-pull
- shipit bosh releases => truck
=> ✨ use resource icons in pipelines ✨

atc/atccmd/command.go, atc/integration/configuration_test.go, docker-compose.yml, web/elm/src/Application/Application.elm, web/elm/src/Dashboard/Dashboard.elm, web/elm/src/Dashboard/Models.elm, web/elm/src/Dashboard/Styles.elm, web/elm/src/SubPage/SubPage.elm, web/elm/src/Views/Styles.elm, web/elm/tests/ApplicationTests.elm, web/elm/tests/BuildTests.elm, web/elm/tests/Common.elm, web/elm/tests/DashboardSearchTests.elm, web/elm/tests/DashboardTests.elm, web/elm/tests/FlySuccessTests.elm, web/elm/tests/JobTests.elm, web/elm/tests/PipelineTests.elm, web/elm/tests/ResourceTests.elm, web/elm/tests/SubPageTests.elm, web/elm/tests/TopBarTests.elm, web/indexhandler/handler.go, web/public/index.html
=> web, atc: add cluster name to dashboard

go.mod, go.sum, topgun/operations/add-credhub.yml
Also update topgun credhub manifest to work for 2.3.0.
concourse/concourse#2723
=> Upgrade credhub-cli

ci/pipelines/resources/template.jsonnet
=> ci/pipelines: renames major, minor and patch to publish

go.mod, go.sum
for sync upstream master and merging pagination fix in cf connector
=> update dex package to latest concourse/dex

cmd/concourse/worker.go
=> changing max volume sweep in flight to 3

atc/api/config_test.go, atc/api/configserver/save.go, atc/config.go, atc/creds/task_validation.go
=> atc: fix --check-creds panic

web/elm/src/Application/Application.elm, web/elm/src/Build/Build.elm, web/elm/src/Build/StepTree/StepTree.elm, web/elm/src/Build/Styles.elm, web/elm/src/Colors.elm, web/elm/src/Dashboard/Dashboard.elm, web/elm/src/Dashboard/SearchBar.elm, web/elm/src/Job/Job.elm, web/elm/src/Message/Effects.elm, web/elm/src/Message/Subscription.elm, web/elm/src/NotFound/NotFound.elm, web/elm/src/Pipeline/Pipeline.elm, web/elm/src/Resource/Resource.elm, web/elm/src/Session.elm, web/elm/src/SideBar/SideBar.elm, web/elm/src/SideBar/Styles.elm, web/elm/src/SubPage/SubPage.elm, web/elm/tests/BuildTests.elm, web/elm/tests/SideBarTests.elm, web/public/index.html
=> web: sidebar feedback

web/elm/src/Build/Build.elm, web/elm/src/Message/Effects.elm, web/elm/src/Message/Message.elm, web/elm/src/Message/Subscription.elm, web/elm/tests/BuildTests.elm, web/public/index.html
=> web: fix scrolling crash

cmd/concourse/worker.go
This PR addresses: https://github.com/concourse/concourse-bosh-release/issues/17
=> Added --external-garden-address flag to use non embedded garden

CONTRIBUTING.md, atc/builds/tracker.go, atc/builds/tracker_test.go, atc/db/build.go, atc/db/build_test.go, atc/db/dbfakes/fake_build.go, atc/engine/builder/delegate_factory_test.go, atc/engine/engine.go, atc/engine/engine_test.go, atc/engine/enginefakes/fake_engine.go, atc/event/events.go, web/elm/src/Build/Output/Models.elm, web/elm/src/Build/Output/Output.elm, web/elm/src/Build/StepTree/Models.elm, web/elm/src/Concourse/BuildEvents.elm, web/elm/tests/BuildTests.elm, web/wats/test/build.js
this should lessen the impact of these flakes on PRs and master.
=> atc, web: replace flaky watsjs with unit tests

atc/exec/artifact_input_step.go, atc/exec/artifact_output_step.go
=> atc: fix stack overflow in artifact errors

CONTRIBUTING.md, ci/pipelines/prs.yml, ci/tasks/scripts/yarn-benchmark, ci/tasks/yarn-benchmark.yml, package.json, web/elm/benchmarks/Benchmarks.elm, web/elm/benchmarks/Main.elm, web/elm/benchmarks/benchmark.js, web/elm/elm.json, web/elm/src/Dashboard/DashboardPreview.elm, yarn.lock
=> ci, web: fix dashboard preview performance

skymarshal/web/templates/password.html, web/wats/test/login.js
=> web: use autocomplete="off" on password input

atc/atccmd/command.go, atc/db/db_suite_test.go, atc/db/dbfakes/fake_task_cache_factory.go, atc/db/dbfakes/fake_volume_repository.go, atc/db/job.go, atc/db/job_test.go, atc/db/migration/migrations/1557152441_separate_worker_task_cache.down.sql, atc/db/migration/migrations/1557152441_separate_worker_task_cache.up.sql, atc/db/task_cache.go, atc/db/task_cache_factory.go, atc/db/task_cache_factory_test.go, atc/db/team_test.go, atc/db/volume.go, atc/db/volume_repository.go, atc/db/volume_repository_test.go, atc/db/volume_test.go, atc/db/worker_task_cache.go, atc/db/worker_task_cache_factory.go, atc/db/worker_task_cache_factory_test.go, atc/db/worker_task_cache_test.go, atc/exec/task_step.go, atc/worker/db_worker_provider.go, atc/worker/db_worker_provider_test.go, atc/worker/volume.go, atc/worker/volume_client.go, atc/worker/volume_client_test.go
=> atc: separate worker_task_cache table

atc/creds/vault/api_client.go
Currently vault with auth via ldap backend is not working.
Concourse currently assumes all auth backends authenticate via `auth/<backend>/login`.
But for ldap auth backend, it's `auth/<backend>/login/:username` as documented at https://www.vaultproject.io/api/auth/ldap/index.html#login-with-ldap-user
This PR is my attempt to add logic around that.
I was able to test, build and test this functionality and it seemed to work fine.  I passed params to the ldap auth backend like `username:someuser,password:secret`.
As it's my first time contributing to this project please let me know if there is anything else you'd like.  😄 
Signed-off-by: Jacob McCann <jacob.mccann2@target.com>
=> feature: support vault ldap backend auth

ci/tasks/yarn-benchmark.yml, package.json, web/elm/benchmarks/Benchmarks.elm, web/elm/src/Dashboard/DashboardPreview.elm, web/elm/tests/TopologicalSortTests.elm
there is a slight performance cost, but the functional behaviour is much better.
fixes #3889
=> web: fix regression in dashboard preview layout

web/elm/src/Build/Build.elm
=> web: update docs link in reaped screen

atc/db/pipeline.go, atc/db/pipeline_test.go
=> pausing pipeline does not clear resource config

topgun/worker_landing_test.go
However, let's do some followup investigation. Left a fairly thorough clarifying note.
=> topgun: pend flaky worker landing test

atc/db/container_owner.go, atc/db/container_owner_test.go, atc/db/container_repository_test.go, atc/db/resource_config_check_session_lifecycle_test.go, atc/db/team_test.go, atc/db/volume_test.go, atc/db/worker_factory_test.go, atc/db/worker_test.go, atc/gc/resource_config_check_session_collector_test.go, atc/gc/resource_config_collector_test.go, atc/radar/scanner_factory.go
=> removing gracetime check from check sessions

ci/pipelines/concourse.yml
=> pipeline: add `ci` as input for building unit image

atc/db/migration/migrations/1537546150_global_resource_version_history.up.sql
=> atc: handle duplicate disabled resource versions

topgun/k8s/kubernetes_creds_mgmt_test.go
Fixes https://github.com/concourse/concourse/issues/3808
CC @pivotal-bin-ju
=> [topgun/k8s] Add test for per-pipeline k8s credentials

atc/db/build.go, atc/db/build_preparation.go, atc/db/build_test.go
=> atc: more accurate build preparation

atc/worker/worker.go
=> adding parallel input streaming

fly/integration/help_test.go, fly/main.go
=> fly: print help for subcommands

topgun/k8s/external_worker_test.go
- Adds new tests to test registering an external worker that doesn't
belong to any team.
- Refactors the external worker tests
=> k8s/topgun: add external worker test without teams:

atc/exec/task_step.go
This is a follow-up of #4118 which introduced the new placement strategy: `limit-active-tasks`.
To improve the user experience this PR outputs to the UI when the task is waiting for a worker
to be free, that is warning the user that the system is at full capacity and the task will wait
for a worker to free up.
Once a worker is available and the task starts the interface informs the user that the task can
start and how long it has been waiting.
=> limit-active-tasks: warn when workers are busy.

atc/exec/task_step.go, atc/worker/client.go
- task_step - move event processing block closer to consumer
- worker/client.go - avoid hoisting to improve readability
=> Minor refactor

fly/commands/destroy_team.go, fly/commands/get_team.go, fly/commands/internal/flaghelpers/team_flag.go, fly/commands/internal/flaghelpers/worker_flag.go, fly/commands/land_worker.go, fly/commands/prune_worker.go, fly/commands/rename_team.go, fly/commands/set_team.go
I added worker(`-w`) and team(`-n`) completions.
worker:
* `prune-worker -w`
* `land-worker -w`
team:
* `get-team -n`
* `set-team -n`
* `destroy-team -n`
* `rename-team -o`
=> Add worker and team completions

go.mod, go.sum
=> bumping baggageclaim to 1.6.2

fly/integration/login_test.go, fly/rc/targets.go
fixes a problem with flyrc introduced by #3505 and caught by https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/downgrade/builds/391
=> fly: maintain flyrc backwards compatibility

atc/worker/image/image_resource_fetcher.go
=> closing zstd reader in image fetcher

web/elm/benchmarks/Benchmarks.elm
=> web: add Build.view to benchmark suite

atc/api/workerserver/heartbeat.go, atc/api/workerserver/register.go, atc/metric/emitter/prometheus.go, atc/metric/metrics.go
For #3036:
* Add `team`, `tags` for worker-volumes
* Add `team`, `tags` for worker-containers
=> Metric enhance: add team, tags for worker-volumes/worker-containers.

go.mod, go.sum
=> bump retryhttp to v1.0.2

atc/exec/try_step.go, atc/exec/try_step_test.go
Signed-off-by: jose <jose@autonomic.ai>
=> Fail the try_step if the inner step was aborted [#3989].

atc/api/config_test.go, atc/creds/kubernetes/kubernetes.go, atc/creds/kubernetes/kubernetes_factory.go, atc/creds/kubernetes/kubernetes_test.go, atc/creds/kubernetes/secrets.go, cmd/concourse/concourse_test.go, fly/integration/set_pipeline_test.go, go-concourse/concourse/configs_test.go, testflight/task_vars_test.go, vars/errors.go, vars/template.go, vars/template_test.go
also backfilled unit tests. the k8s library has a whole test fake system - pretty nice!
=> atc: fix k8s secret fetching

fly/integration/error_handling_test.go, fly/integration/login_test.go, fly/integration/version_test.go
=> fix the fly integration tests for windows

fly/integration/set_pipeline_test.go
no more unsanitized input to regex
=> fly: fix integration tests

web/elm/src/Build/StepTree/StepTree.elm, web/elm/src/Build/Styles.elm, web/elm/tests/BuildTests.elm
Reverts concourse/concourse#4206
Fixes #4210
=> Revert "use position fixed so tooltips can 'float' outside the container"

atc/api/artifacts_test.go, atc/api/artifactserver/create.go, atc/api/artifactserver/get.go, atc/api/configserver/save.go, atc/exec/artifact/artifactfakes/fake_registerable_source.go, atc/exec/execfakes/fake_task_config_source.go, atc/exec/get_step.go, atc/exec/get_step_test.go, atc/exec/put_inputs.go, atc/exec/task_config_source.go, atc/exec/task_config_source_test.go, atc/exec/task_step.go, atc/exec/task_step_test.go, atc/resource/resource_get_test.go, atc/resource/resourcefakes/fake_versioned_source.go, atc/resource/versioned_source.go, atc/worker/artifact_destination.go, atc/worker/artifact_source.go, atc/worker/image/image.go, atc/worker/image/image_resource_fetcher.go, atc/worker/image/image_resource_fetcher_test.go, atc/worker/image/image_test.go, atc/worker/volume.go, atc/worker/worker.go, atc/worker/worker_test.go, atc/worker/workerfakes/fake_artifact_destination.go, atc/worker/workerfakes/fake_artifact_source.go, atc/worker/workerfakes/fake_volume.go, go.mod, go.sum
=> pass context to baggageclaimclient.StreamIn/Out calls

go.mod, go.sum
fixes #4264 
Co-authored-by: Divya Dadlani <ddadlani@pivotal.io>
=> bump baggageclaim to fix overlay mounts

release-notes/v5.5.0.md
=> adding mount table fix release-notes

release-notes/v5.5.0.md, web/assets/css/layout.less, web/assets/css/production.less
=> CSS change to create sticky step headers on scroll

atc/creds/cached_secrets.go, atc/creds/cached_secrets_test.go
Fixes #3895 - added config parameter, one "if" condition, and a unit test
Signed-off-by: Roman Alekseenkov <ralekseenkov@gmail.com>
=> Added separate duration for secret not found responses

release-notes/v5.5.1.md
My hope here is that this explains itself, and it's just documentation!
=> add release note for bosh release fix

release-notes/latest.md
=> add release notes for PRs I merged

atc/lidar/checker.go, atc/lidar/scanner.go
- add start/end logs for scanner and checker
- change check-already-exists to debug level
=> atc: fix lidar logging

release-notes/v5.6.0.md
I spaced on adding release notes in #4442.  This fixes that.
=> release-notes/v5.6.0.md: include release notes for #4442

fly/integration/pin_resource_test.go, fly/integration/unpin_resource_test.go
fixes https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/unit/builds/1076#L5d7bf156:99
=> remove tests that are environment dependent

release-notes/v5.6.0.md
=> add release note

topgun/both/atc_shutdown_test.go, topgun/both/both_suite_test.go, topgun/both/build_container_gc_test.go, topgun/both/hijack_container_gc_test.go, topgun/both/image_artifact_test.go, topgun/both/image_resource_gc_test.go, topgun/both/pipeline_destroyed_test.go, topgun/both/resource_check_test.go, topgun/both/resource_containers_gc_test.go, topgun/both/resource_types_test.go, topgun/both/resource_volumes_gc_test.go, topgun/both/volume_gc_test.go, topgun/both/worker_landing_test.go, topgun/both/worker_retiring_test.go, topgun/both/worker_stalling_test.go, topgun/common/common.go
by pointing to the exposed variable names from topgun/common
=> fix topgun/both

topgun/k8s/k8s_suite_test.go
by referring to new FlyCli type from topgun package
=> fix k8s-topgun

topgun/common/common.go, topgun/deployments/concourse.yml, topgun/operations/add-other-worker.yml, topgun/operations/bbr-concourse-link.yml, topgun/operations/bbr-with-properties.yml
to reduce contention fo BOSH release lock together with concourse/ci#173
=> different release name for each suite

web/elm/src/FlySuccess/FlySuccess.elm, web/elm/src/FlySuccess/Models.elm, web/elm/src/FlySuccess/Text.elm, web/elm/src/Message/Callback.elm, web/elm/src/Message/Effects.elm, web/elm/src/Message/Message.elm, web/elm/src/Message/Subscription.elm, web/elm/src/SubPage/SubPage.elm, web/elm/src/UserState.elm, web/elm/tests/Common.elm, web/elm/tests/FlySuccessTests.elm, web/elm/tests/SubscriptionTests.elm, web/elm/tests/UserStateTests.elm, web/public/elm-setup.js
fixes concourse/concourse#4409
=> web: distinguish browser error from network error

atc/db/resource_config_scope.go, atc/db/resource_config_scope_test.go
=> only bump cache index when saving new versions

atc/db/lock/lock.go, atc/db/lock/lock_test.go
10s might not be a long enough. Going to revert for now and experiment more.
=> Revert mutex lock timeout

web/elm/src/Concourse.elm, web/elm/src/Message/Callback.elm, web/elm/src/Message/Effects.elm, web/elm/src/Network/Resource.elm, web/elm/src/Resource/Models.elm, web/elm/src/Resource/Resource.elm, web/elm/tests/Data.elm, web/elm/tests/ResourceTests.elm
=> web: Poll check endpoint while resource check in progress

atc/lidar/checker.go, atc/lidar/checker_test.go
so we don't create more and more goroutines all doing the same thing
=> keep track of checks

fly/integration/workers_test.go
Signed-off-by: Chao Li <chaol@vmware.com>
Resolve #4497
=> Fixed the flake 'fly workers' test.

release-notes/v5.6.0.md
=> add doc for get step version pinning

release-notes/v5.6.0.md
=> finalize release notes for v5.6.0

atc/engine/builder/delegate_factory.go, atc/engine/builder/delegate_factory_test.go
Resolve #4389
Highlights:
1. Given build logs are in random chunk, first thing to do is normalize build logs to lines. If the last line doesn't contains new-line, then cache the last line.
2. Add a `Close()` method to `dbEventWriter`, because as we normalize log lines, if don't close a writer, then the last line might be lost.
3. After normalize log lines, we can treat a multi-line secret as multiple secrets, meaning redact each line of a secret separately. Consider that, users may print a ssh to log with each line having several leading spaces, in that case, we have no way to replace the kay as a whole.
4. I also did some changes that directs image pulling logs are redirected to stderr, and `get`/`put`'s user logs are redirected to stdout. So that we only do redaction on stdout.
The …
=> feat: strengthen secret redaction to handle split secrets.

release-notes/v5.6.0.md
documents concourse/git-resource#271
=> document git resource paths fix

atc/engine/builder/delegate_factory.go, atc/engine/builder/delegate_factory_test.go, release-notes/v5.6.0.md
=> atc: use ((redacted)) syntax, update release notes

web/elm/src/Message/Effects.elm, web/elm/src/Network/Resource.elm, web/elm/src/Resource/Resource.elm, web/elm/tests/ResourceTests.elm
fixes concourse/concourse#4528
=> web: fix GetCheck api route

worker/workercmd/dns.go
=> feat: enable dns message compression

release-notes/v5.6.0.md
=> add release note for #4479

release-notes/v5.5.0.md
=> back fill a breaking doc for yaml parsing

.github/pull_request_template.md
As discussed in retro, I propose this PR template for any new PRs.
Please review and let me know if you want to add or remove anything.
=> add initial PR template

.github/pull_request_template.md
- As we got the pull request template in, it seems like folks are confused with comment lines.
- just adding to remind folks to remove the template comments.
=> # Why do we need this PR?

worker/workercmd/worker.go
=> add timeout to bclient for worker volumes gc

worker/README.md
Fixes #2860
Updated the ./worker/README.md to be more descriptive of the worker module.
=> Updating ./worker/README.md to give more information about the worker

atc/creds/vault/api_client.go
When tests with Vault dev server, renew lease is not allowed, thus ATC log is massed
with Vault renew error like:
web_1     | {"timestamp":"2019-09-29T14:07:18.982725900Z","level":"error","source":"atc","message":"atc.credential-manager.renew.failed","data":{"error":"Error making API request.\n\nURL: PUT http://192.168.1.11:8200/v1/auth/token/renew-self\nCode: 400. Errors:\n\n* lease is not renewable","name":"vault","session":"5.46"}}
This commit will skip renew once detects such error.
Signed-off-by: Chao Li <chaol@vmware.com>
=> feat: avoid to renew Vault lease every second if Vault server doesn't accept renew.

fly/commands/builds.go, fly/integration/builds_test.go
=> Set duration to n/a if startTime is n/a

atc/db/resource.go, atc/db/resource_test.go
=> API pin switching 

atc/api/jobs_test.go, atc/api/jobserver/badge.go, atc/api/pipelineserver/badge.go
Hello!
This PR allows users to change the "build" text on badges with ?title= param.
Fixes https://github.com/concourse/concourse/issues/4105
I've opened another PR since https://github.com/concourse/concourse/pull/4290 were "stalled" and had a quite big bug (it modifies a reference to the badges, hence subsequent calls are affected) .
Some considerations: 
1. with title longer than 5/6 chars, the badge is quite ugly since its dimensions are baked in multiple places. Probably a different PR for making this rendering "responsive" is better in terms of isolation.
2. It could be nice to have something also for the "content" (aka "success|failed|etc"), maybe set from a query parameter like `?content=<some-regex>` that uses the actual job's output.
Signed-off-by: Vittorio Camisa …
=> change: badge rendering considers "title" query param

release-notes/v5.6.1.md, web/elm/src/Build/StepTree/StepTree.elm, web/elm/src/Build/Styles.elm, web/elm/tests/BuildStepTests.elm
Fixes #4421 
Signed-off-by: Jamie Klassen <cklassen@pivotal.io>
=> add styling to get step metadata

release-notes/latest.md, release-notes/v5.6.1.md
Fix tagging on 5.6.1 release notes!
=> Add more release notes for latest

atc/metric/metrics.go
=> Add forgotten metric for the active tasks locks.

atc/api/config_test.go, atc/api/configserver/save.go, atc/api/pipelines_test.go, atc/api/pipelineserver/unpause.go, atc/db/dbfakes/fake_team_factory.go, atc/db/team_factory.go
It will notify scanner when pipeline is updated or unpaused.
fixes #4553
=> Notify scanner when pipeline set

atc/db/migration/helpers_test.go, atc/db/migration/migrations/1561558376_add_type_to_resources.up.go, atc/db/migration/resource_type_test.go
Fixes #4139.
fixes migration issue with old resources
=> atc: handle empty config in resource type migration

atc/worker/image/image_resource_fetcher_test.go, atc/worker/workerfakes/fake_worker.go
It appears that in some recent commit the fakes where
not re-generated and one of the tests was still including
a call to a function no longer existing.
To keep unit tests green and fakes updated :)
=> Regenerate counterfeit fakes and fix failing test.

release-notes/latest.md
* Update release notes for #4606
=> Add release note for log change #4606

release-notes/latest.md, web/elm/src/Routes.elm, web/elm/tests/RoutesTests.elm, web/elm/tests/TopBarTests.elm
Fixes #4313.
* use `Url.Builder` consistently
* workaround for around elm/url#32
=> web: fix url parsing

atc/db/container_repository.go, atc/db/volume_repository.go
Because the code on master doesn't compile, and everything is failing!
* introduce those transactions a little earlier in two spots, and pass them to the appropriate functions
=> atc: fix compile errors

atc/config.go, atc/worker/db_worker_provider.go, atc/worker/gclient/factory.go, cmd/concourse/worker.go, worker/container_sweeper.go
=> Release 5.5.x - PR 4582

release-notes/v5.5.4.md
Create release notes for 5.5.4 release
=> add release notes for 5.5.4

fly/commands/builds.go
Signed-off-by: Peter Tran <ptran@pivotal.io>
Signed-off-by: Michael Stergianis <mstergianis@pivotal.io>
Makes the code more readable.
* moves business logic of `buildCap` out of the main `Execute` method
* Test coverage for this area of the code already exists and has been run
=> Extract build cap logic into helper method

fly/commands/curl.go
=> [#4407] Update fly curl help text

atc/db/container_repository.go, atc/db/container_repository_test.go
* If containers from stalled workers are removed from ATC DB,
then ATC will be out of sync with worker filesystem when
worker returns to running state. This contributes to
problem of mysteriously high container count on workers.
Addresses #4536
Fixes #4536.
This PR solves one of a few possible edge cases that can contribute to upward-creeping container count on workers. This attempts to keep ATC DB's state closer to the filesystem reality of workers that are flipping between stalled and running state.
=> Skip over containers on stalled workers when deleting missing

release-notes/latest.md
Adds release notes for the component tracking work #4583
=> notes: add components release notes

go.mod, go.sum, release-notes/latest.md
Fixes #4535.
* includes the fix for cf connector that fetches all spaces for a user
=> bump concourse/dex dependency

atc/metric/emitter/newrelic.go, atc/metric/emitter/prometheus.go, release-notes/latest.md
=> atc: emit check finish event

.github/pull_request_template.md
We keep failing our own tests when environment config flags and BOSH/Helm keys don't get updated in lock step.
=> Add note to PR template for us to update packaging for new configs

.github/stale.yml
e.g. https://github.com/concourse/concourse/issues/4379#issuecomment-549526721
=> don't mark milestoned issues as stale

atc/db/migration/migration.go
Fixes #4689.
The way concourse use to check if legacy migration table exist relies on if posgres user have access to `information_schema` table otherwise it would query the table directly, which might show a `table not exist` error in logs when migration is running
use `to_regclass` (postgres 9.4+) to check if table exist. It will return NULL or the table name, which won't raise any error. In this way, the logs would be clean and migration won't need postgres user to be superuser.
=> atc: update table exist check for migration

fly/commands/builds.go
> Is there an existing issue related to this PR? Fill in the issue number as follows: Fixes #1234.
Fixes #4659
> What are the changes included in this PR? Feel free to add as many lines as needed below.
* separate execute function into helper functions
* isolated display logic
~~- [ ] Unit tests~~
~~- [ ] Integration tests (if applicable)~~
~~- [ ] Updated documentation (located at https://github.com/concourse/docs)~~
~~- [ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)~~
=> [Fly] refactor fly builds commands

atc/metric/emitter/newrelic.go, atc/metric/emitter/newrelic_test.go, release-notes/v5.5.5.md
=> Release/5.5.x PR 4698

skymarshal/token/issuer.go, skymarshal/token/issuer_test.go
=> skymarshal: don't split group claims

atc/metric/emitter/newrelic.go, atc/metric/emitter/newrelic_test.go, release-notes/v5.7.1.md
=> Release/5.7.x PR 4698

web/public/graph.js
Related to #4445.
This fixes a web bug.
By mistake, I submitted a pipeline to my Concourse instance which contained a loop.
This caused the web UI javascript to enter a tight loop in graph.js. This made the browser completely unresponsive (I couldn't even open devtools to find the code in question).
I have just changed graph.js to bail if it looks like it is in an infinite loop. There should then be an error in the javascript console which should help developers to track down the broken section of the pipeline.
I didn't add any unit tests for this, as there are not currently any tests on graph.js, and it felt out of scope here to introduce a js test framework to the project.
=> Avoid infinite loop in web ui when pipeline has loops

release-notes/v5.5.5.md
=> Add v5.5.5 release notes

fly/integration/fixtures/team_config_with_cf_auth.yml, skymarshal/skycmd/cf_flags.go
Refer to [discussion about using more accurate flags for cf auth role-based space configure](https://github.com/concourse/concourse/pull/4712#issuecomment-550519783)
=> update cf auth flags for space with role

atc/db/build.go, atc/db/build_event_source.go, atc/db/build_factory.go, atc/db/container_repository.go, atc/db/job.go, atc/db/job_factory.go, atc/db/pipeline.go, atc/db/pipeline_factory.go, atc/db/resource.go, atc/db/team_factory.go, atc/db/volume_repository.go, atc/db/volume_repository_test.go, atc/db/worker.go, go.sum, release-notes/v5.5.6.md
cherry picking fix of #4373 from master to 5.5.x. 
=> Use transaction instead of open connection for api queries

fly/rc/targets.go
=> #4549: Added error message if fail unmarshal .flyrc file

topgun/operations/add-other-worker.yml, topgun/operations/bbr-concourse-link.yml, topgun/operations/bbr-with-properties.yml
=> Remove hyphens from ops-files for bosh topgun

fly/integration/fixtures/team_config_with_cf_auth.yml, fly/integration/set_team_test.go, go.mod, go.sum, skymarshal/skycmd/cf_flags.go
=> Support org guid in cf auth

topgun/k8s/external_postgres_test.go, topgun/k8s/k8s_suite_test.go, topgun/k8s/prometheus_test.go
Back-porting #4735 
Will fix k8s-topgun in the release pipeline.
=> [release/5.7.x] 5.7.x use concourse chart

topgun/k8s/external_postgres_test.go, topgun/k8s/k8s_suite_test.go, topgun/k8s/prometheus_test.go
Back-porting #4735
Will fix k8s-topgun in the release pipeline.
=> adopt the new concourse helm chart repo.

release-notes/latest.md
also flesh out the note for registry-image resource bump
=> add release notes for #4808 and #4817

atc/engine/builder/delegate_factory.go, atc/engine/builder/delegate_factory_test.go, atc/lidar/scanner.go, release-notes/v5.7.2.md, vars/vars_tracker.go
=> Backport #4808 and #4817 to 5.7.2

release-notes/latest.md, web/assets/css/animation.less, web/elm/src/Dashboard/Styles.elm, web/elm/tests/Common.elm
=> antialias the striped progress bar

release-notes/latest.md
=> Add release notes for #4816

fly/integration/fixtures/team_config_with_cf_auth.yml, fly/integration/set_team_test.go, go.mod, go.sum, skymarshal/skycmd/cf_flags.go
=> Revert "atc: support org guid in cf auth connector"

fly/integration/fixtures/team_config_with_cf_auth.yml, fly/integration/set_team_test.go, go.mod, go.sum, skymarshal/skycmd/cf_flags.go
=> Revert 5 5 x

release-notes/v5.5.7.md
=> update relase-notes for 5.5.7

worker/backend/backend.go, worker/backend/backend_test.go, worker/backend/container.go
Fixes #4913 
Signed-off-by: Bin Ju <bju@pivotal.io>
=> implement Handle for backend/container

atc/db/component.go
Fix typo in atc/db/component.go
=> nit: fix typo atc/db/component

atc/exec/build/repository.go
addressing https://github.com/concourse/concourse/pull/4825#discussion_r363355199
remove dead code
=> atc: remove left-out comment

fly/commands/helpers_test.go
#4580 Why do we need this PR?
Increased test coverage
* Increases test coverage of atc/helpers.go#GetBuild 
and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text). 
Signed-off-by: Michael Stergianis <mstergianis@pivotal.io>
=> Increased coverage for atc/helpers GetBuild

tsa/tsacmd/command.go
Add new yaml-team-authorized-keys flag to provide authorized team key in one yaml file
Fix #3551
Allow users to provide a yaml file containing all team authorized key following this format :
```
- team: teamA
ssh_keys:
- ssh-rsa keyA
- team: teamB
ssh_keys:
- ssh-rsa keyB
```
=> Add new yaml-team-authorized-keys flag to provide authorized team key in one yaml file

atc/worker/worker.go
Add comment to package top level file to clarify the purpose of a package.
Inspired by @cirocosta's suggestion & goland docs [strings](https://golang.org/src/strings/strings.go?s=2326:2362#L5) 
Add comment to atc/worker package to clarify its purpose
=> Add worker package comment

skymarshal/skycmd/cf_flags.go
https://github.com/concourse/concourse/issues/2460
Good `space-guid`.
=> skymarshal: update cf-space-guid flag desc

.gitignore, CONTRIBUTING.md, hack/overrides/vault.yml, hack/vault/config/concourse-policy.hcl, hack/vault/config/config.hcl, hack/vault/setup
usage: ./hack/vault/setup and follow the instructions
=> add vault hack setup

release-notes/latest.md
Documents concourse/concourse#4092.
Just release notes, no code changes.
=> add release note for (un)pausing all pipelines

.gitignore, hack/dc, hack/vault/init, hack/vault/setup
* add `hack/vault/init` which does all the unsealing and setup for you
* add `hack/dc` which runs your docker-compose command with all overrides enabled
=> hack: easier vault setup, add hack/dc

go.mod, go.sum, release-notes/latest.md
fix cow-cow and switch zstd lib
i.  github.com/concourse/baggageclaim#34
ii. github.com/concourse/baggageclaim#35
fixes #4964 
fixes #4621 
* bump baggageclaim (see https://github.com/concourse/baggageclaim/releases/tag/v1.6.6)
=> go.mod: bump baggageclaim

atc/worker/worker_helper.go, atc/worker/worker_test.go
Reverts concourse/concourse#5159
Fixes #5198
=> Revert "Explicitly whitelist all traffic from concourse containers"

worker/workercmd/worker_linux.go
It's not ready yet - let folks know about that
=> containerd: mention that it's experimental

fly/integration/login_test.go
There is a typo in one of the fly integration tests preventing the suite from running.
=> fly: fix compiler error in test

testflight/suite_test.go
#5248 makes testflight downloads fly cli from configured ATC url instead of building it, in which case when docker-compose locally there is no way to running testflight against local fly binary
When running docker compose locally we want to use fresh built fly cli
Add an env var that allows choice between downloading fly ci or build it from source code.
=> Conditionally download fly cli when running Testflight

release-notes/v5.5.9.md, skymarshal/skyserver/skyserver.go, skymarshal/skyserver/skyserver_test.go
Cherry picking redirect URI fix from master to 5.5
=> Redirect URL fix for 5.5

release-notes/v5.2.8.md, skymarshal/skyserver/skyserver.go, skymarshal/skyserver/skyserver_test.go
Cherry picking open redirect fix from master to 5.2
=> skymarshal: strictly parsing redirect URI

go.mod, go.sum, release-notes/v5.8.1.md
=> Bump 5 8 x crypto

atc/api/handler.go, atc/api/jobserver/list_all.go, atc/api/jobserver/server.go, atc/atccmd/command.go
This endpoint definitely has performance problems, and issues like
concourse/concourse#4373 just scratch the surface.
Signed-off-by: Jamie Klassen <cklassen@pivotal.io>
Co-authored-by: Taylor Silva <tsilva@pivotal.io>
=> atc: add flag to disable `ListAllJobs`

release-notes/v5.8.1.md, skymarshal/skyserver/skyserver.go, skymarshal/skyserver/skyserver_test.go
cherry picked from master for open redirect fix in skymarshal
=> 5.8.x open redirect

release-notes/v5.5.10.md, skymarshal/skyserver/skyserver.go, skymarshal/skyserver/skyserver_test.go
cherry picked from 5.8.x replease pipeline.
=> skymarshal: strictly parsing redirect URI and construct URL from path and query param

release-notes/v5.2.8.md, skymarshal/skyserver/skyserver.go
cherry picked from 5.8.x to escaped path in redirect URL
=> 5.2.x open redirect

fly/commands/validate_pipeline.go, fly/integration/fixtures/var_sources_pipeline.yml, fly/integration/validate_pipeline_test.go
=> fly(fix): fixed validate-pipeline error on pipelines containing var_sources

web/public/elm-setup.js, web/public/index.html, web/public/index.mjs
Fixes #5361 .
* Dynamically create "icon-store" in Javascript, since it seems to get removed
* Export `addIcon` for use in the `renderSvg` port
=> web: behaviour: fix icon rendering

atc/db/migration/migrations/1584109185_add_last_hijack_to_containers.down.sql
Fixes https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/downgrade/builds/174
=> atc: fix error in container gc down migration

skymarshal/skyserver/skyserver.go, skymarshal/skyserver/skyserver_test.go
Fixes #4572 .
Brower shows broken page after skymarshal handling dex callback errors. 
Show the error message
=> fix broken page when skymarshal callback errors

atc/db/migration/migrations/1584564140_add_archived_to_pipelines.up.sql, release-notes/latest.md
Fixes #5474
* remove IF NOT EXISTS from archive migration
=> db: remove IF NOT EXISTS from archive migration

topgun/fly.go
Updates the Token URL that topgun uses to fetch an auth token.
=> topgun: update token endpoint

testflight/suite_test.go
Noticed there are some code are not used in testflight when I was trying to fix top-gun not-authorized error.
=> testflight: clean up unused code

atc/atccmd/command.go, atc/db/check_factory.go, atc/db/dbfakes/fake_checkable.go, atc/db/dbfakes/fake_created_container.go, atc/db/dbfakes/fake_destroying_container.go, atc/db/dbfakes/fake_resource.go, atc/db/dbfakes/fake_resource_type.go, atc/db/resource.go, atc/db/resource_test.go, atc/db/resource_type.go, atc/lidar/scanner.go, atc/lidar/scanner_test.go
=> atc(feat): add --resource-with-webhook-checking-interval to concouse web

atc/api/accessor/accessor.go, atc/api/accessor/accessor_test.go
Don't add duplicate roles to /api/v1/user response
fixes #5524
=> atc: remove duplicate team roles

CONTRIBUTING.md
related to https://github.com/concourse/concourse/pull/5564
Just in case folks don't know why they receive invite after they submit pull request
=> Update pull request process in contributing doc

atc/db/dbfakes/fake_created_volume.go, atc/db/dbfakes/fake_resource_cache_factory.go, atc/db/resource_cache_factory.go, atc/db/resource_cache_factory_test.go, atc/db/volume.go, atc/worker/artifact_source.go, atc/worker/artifact_source_test.go, atc/worker/client.go, atc/worker/container_test.go, atc/worker/db_worker_provider.go, atc/worker/image/image.go, atc/worker/pool.go, atc/worker/volume.go, atc/worker/worker.go, atc/worker/worker_test.go, atc/worker/workerfakes/fake_pool.go, atc/worker/workerfakes/fake_volume.go, atc/worker/workerfakes/fake_worker.go, release-notes/latest.md
=> Redundant Volume Streaming

CONTRIBUTING.md
Thanks for your work on Concourse! This seeks to address issue #5618
This seeks to make the development and contribution process a bit easier for newcomers.
This PR seeks to clarify the `CONTRIBUTING.md` instructions surrounding the creation of an example pipeline in development.
closes #5618.
This PR seeks to clarify the `CONTRIBUTING.md` instructions.
- [N/A] Unit tests
- [N/A] Integration tests
- [N/A] Updated documentation (located at https://github.com/concourse/docs)
- [N/A] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)
and …
=> clarify example job instructions in CONTRIBUTING.md

release-notes/latest.md
Update issue reference to correct issue number
=> Fix typo in latest.md

atc/creds/set_pipeline_plan.go, atc/creds/set_pipeline_plan_test.go, atc/exec/set_pipeline_step.go
> Is there an existing issue related to this PR? Fill in the issue number as follows: Fixes #1234.
Fixes #5276  .
=> atc(feat): set_pipeline step to support var.

CODE_OF_CONDUCT.md, NOTICE.md, vars/NOTICE.md
Bug Fix | Feature | **Documentation**
Pivotal is now VMware.
There is another line on the vars/NOTICE.md that mentions pivotal but with historic years, not sure if this should be changed as well 🤔
[Helm](https://github.com/concourse/helm) packaging; otherwise, …
=> update notice and concourse email

atc/worker/artifact_source.go, atc/worker/artifact_source_test.go, atc/worker/client.go, atc/worker/image/image.go, atc/worker/image/image_test.go, atc/worker/worker.go, atc/worker/worker_test.go, atc/worker/workerfakes/fake_image_fetching_delegate.go, atc/worker/workerfakes/fake_streamable_artifact_source.go
Simplify the interface
Remove logger which wasn't used
(for example, if they are …
=> Refactor Artifact Source - remove logger

atc/configvalidate/validate.go, atc/configvalidate/validate_test.go, atc/job_config.go, atc/step_validator.go, atc/steps.go, atc/steps_test.go
closes #5875 .
* Track unknown fields rather than erroring during unmarshaling
* Validate that there are no unknown fields when saving a pipeline
the …
=> atc: ignore unknown step fields when reading from DB

go.mod, go.sum
=> 6.3.x - Update go mod with latest changes in concourse/dex

go.mod, go.sum
=> 6.4.x - Update go mod with latest changes in concourse/dex

topgun/common/common.go
cherry pick https://github.com/concourse/concourse/pull/5884 to fix bosh topgun
=> topgun: Fix regex to support bosh 6.x

release-notes/v6.3.1.md
Signed-off-by: Bohan Chen <bochen@pivotal.io>
Co-authored-by: Taylor Silva <tsilva@pivotal.io>
=> release/6.3.x: add release notes

release-notes/v6.4.1.md
Signed-off-by: Bohan Chen <bochen@pivotal.io>
Co-authored-by: Taylor Silva <tsilva@pivotal.io>
=> release/6.4.x: add release notes

go.mod, go.sum
closes #5799 
Bumps Baggageclaim to [v1.8.0](https://github.com/concourse/baggageclaim/releases/tag/v1.8.0). …
=> Bump baggageclaim to v1.8.0 to fix deeply-nested volumes with overlay driver

topgun/fly.go
Broken after #5897, which expects you to use the `AccessToken` to authenticate with the Concourse API, rather than using the ID Token instead. …
=> Use access token for Concourse API in topgun

web/elm/src/SideBar/SideBar.elm, web/elm/tests/SideBarFeature.elm
closes # .
It's weird for archived pipelines to be displayed by default in the sidebar. Since the "show archived" toggle is only scoped to the dashboard, it doesn't make much sense to control the sidebar with it. Instead, just hide all archived pipelines from the sidebar. If users need to access them, they can do so through the dashboard. …
=> Archived pipelines are hidden from sidebar if not favorited

atc/db/build.go, atc/db/build_test.go
Bug Fix
closes #5935  .
Request schdule a job build when cancelling a pending build, so scheduler can handle the cancelled build when trying to schedule a new one.
This PR also include some refactor in build_test.go for removing dependencies of `CreateOneOffBuild` per comment here. https://github.com/concourse/concourse/blob/adffe19b0ea515b6b91aa8cc1ac482776bbc025e/atc/db/team.go#L644
Fix a bug that a build can't be cancelled if it is in pending state because of unsatisfiable inputs
=> Request schedule when cancelling a pending build

worker/runtime/spec/seccomp.go
Feature
closes #5677 
Update containerd's seccomp profile to allow the `statx` system call. This lets basic commands like `ls -l` to be executed. …
=> worker: allow statx in containerd

.deepsource.toml
closes # .
(for example, if they are Garden configs that …
=> Add DeepSource config

worker/runtime/rootfs_manager.go, worker/runtime/rootfs_manager_test.go
closes #6054
Copies what Guardian does
-  containerd runtime will now default to uid:gid 0:0 if username is "root" but `/etc/passwd` file does not exist
tests](https://github.com/concourse/ci/tree/master/tasks/script …
=> containerd: use default uid:gid if passwd file does not exist and username is "root"

topgun/k8s/k8s_suite_test.go
=> k8s topgun: fix panic

topgun/k8s/baggageclaim_drivers_test.go, topgun/k8s/container_limits_test.go, topgun/k8s/external_postgres_test.go, topgun/k8s/garden_config_test.go, topgun/k8s/k8s_suite_test.go, topgun/k8s/prometheus_test.go, topgun/k8s/worker_lifecycle_test.go, topgun/pipelines/task-waiting.yml
Fixes various outstanding bugs with our topgun/k8s suite of tests. Please see each commit message for details on every fix.
Review each commit individually. Each commit fixes one set of tests.. …
=> Fix topgun/k8s tests

atc/atccmd/command.go, atc/component.go, atc/db/migration/batch/build_events_bigint.go, atc/db/migration/batch/build_events_bigint_test.go, atc/db/migration/batch/runner.go, atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.down.sql, atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.up.sql, atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.down.sql, atc/db/migration/migrations/1603405319_prepare_build_events_for_bigint_migration.up.sql, atc/db/open.go, atc/db/resource.go, atc/db/resource_test.go, atc/db/resource_type.go, atc/db/resource_type_test.go
Just trying to rebase onto master but the release branch is write protected
=> fast forward release branch

atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.down.sql, atc/db/migration/migrations/1603401316_alter_build_integers_to_bigints.up.sql
This reverts commit ec69519dfbc2151cdf8c7404d4b713454efb7ad1.
it didn't work
Signed-off-by: Aidan Oldershaw <aoldershaw@pivotal.io>
closes # . …
=> Revert "migration: acquire lock on builds table in build_id migrations"

worker/runtime/spec/devices.go
containerd does not grant access to /dev/console
Copied from #6181
tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distrib …
=> containerd does not grant access to /dev/console

atc/worker/client.go
Bug Fix
Fixes the bug where more tasks than the chosen limit can land on the same worker, even though limit-active-task container placement strategy option with max-active-task-per-worker is selected.
This fix ensures that `chosenWorker = client.pool.FindOrChooseWorkerForContainer` returns nil if the first task already acquired the lock.
closes  https://github.com/concourse/concourse/issues/6206
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing- …
=> limit-active-task:structural: limit configured by limit-active-tasks is not respected and more tasks can land on a worker

atc/builds/tracker_test.go
rather than doing a full DeepEqual on the entire fake build, just
compare IDs
this failed with --race because the goroutines call .ID(), which with a
fake object causes mutation for all the internal bookkeeping around call
count / call args, resulting in a data race.
=> Fix up test data race for build tracker

atc/db/migration/migrations/1601993582_add_successful_build_outputs_rerun_of_index.down.sql, atc/db/migration/migrations/1601993582_add_successful_build_outputs_rerun_of_index.up.sql
Feature
closes #6269.
Adding changes from https://github.com/concourse/concourse/commit/38b12fa85e7269f0318271a250a5a70268862ad8 to this release for performance improvements.
Added an index to speed up pipeline deletion.
[Helm](https://github.com/concourse/helm) packaging; …
=> atc: behavior: add index to improve build deletion

CONTRIBUTING.md
Documentation
If someone is not familiar with `yarn` they may get stuck at the error shown when we try to simply `yarn build` first:
```
$ yarn run build-less && yarn run build-elm && yarn run build-js
$ lessc web/assets/css/main.less web/public/main.out.css && cleancss -o web/public/main.css web/public/main.out.css && rm web/public/main.out.css
/bin/sh: cleancss: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Adds the `yarn install` step to the section about building the web UI.  …
=> add yarn install step to web ui instructions

fly/commands/internal/setpipelinehelpers/atc_config.go, fly/integration/set_pipeline_test.go
To reduce the risk of users making mistakes when setting pipelines, `fly set-pipeline` prints:
```
$ fly -t dev sp -p some-pipeline -c pipeline.yml
... (diff)
pipeline name: some-pipeline
apply configuration? [yN]:
```
When there are instance vars set, it also prints those:
```
$ fly -t dev sp -p some-pipeline -c pipeline.yml -i foo=123 -i bar=456
... (diff)
pipeline name: some-pipeline
pipeline instance vars:
foo: 123
bar: 456
apply configuration? [yN]:
```
* Print info prompt before confirming with the user
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.m …
=> `fly set-pipeline` prints pipeline name and instance vars

go.mod, go.sum
=> bump baggageclaim to fix nesting again

atc/api/handler.go, atc/api/pipelines_test.go, atc/api/pipelineserver/rename.go, atc/api/team_scoped_handler_factory.go, atc/api/team_scoped_handler_factory_test.go, atc/api/teams_test.go, atc/api/teamserver/destroy.go, atc/api/teamserver/get.go, atc/api/teamserver/list_builds.go, atc/api/teamserver/rename.go, atc/api/teamserver/set.go, atc/api/volumes_test.go, atc/db/dbfakes/fake_pipeline.go, atc/db/dbfakes/fake_team.go, atc/db/pipeline.go, atc/db/pipeline_test.go, atc/db/team.go, atc/db/team_test.go, atc/wrappa/api_auth_wrappa.go, atc/wrappa/api_auth_wrappa_test.go, fly/commands/rename_pipeline.go, fly/integration/rename_pipeline_test.go, go-concourse/concourse/concoursefakes/fake_team.go, go-concourse/concourse/pipelines.go, go-concourse/concourse/pipelines_test.go, go-concourse/concourse/team.go
Previously, there was no way to rename an instance group - calling `fly rename-pipeline -o foo -n bar` would only rename the pipeline `foo` with no instance vars. Now, it renames all pipelines with the name `foo` into `bar`, keeping the instance vars as they were.
* Refactor some team-scoped API endpoints
* Replace `db.Pipeline.Rename(newName)` with `db.Team.RenamePipeline(oldName, newName)` - this new method renames all pipelines with a given `oldName`
This came up in https://github.com/concourse/concourse/pull/6105#issuecomment-733762041 …
=> `fly rename-pipeline` can rename an entire instance group

atc/configvalidate/validate_test.go, atc/configwarning.go, atc/configwarning_test.go, web/wats/fixtures/hooks-pipeline.yml, web/wats/fixtures/pipeline-with-long-output.yml, web/wats/fixtures/smoke-internet-pipeline.yml, web/wats/fixtures/states-pipeline.yml, web/wats/test/smoke.js
Duplicate of #6338 for 6.7.x
(for example, if they are …
=> Allow underscore in identifiers

Dockerfile
this will allow us to build local images using a base image other than
concourse/dev:latest - this is useful for testing PRs to release
branches (which have their own dev images)
note that this should also (hopefully) let us use the new `IMAGE_ARG`
behaviour in vito/oci-build-task, meaning we can `get: dev-image` and
pass the fetched image tarball as an image arg to use as the base image
[Signed]: …
=> docker: add build arg for base image

web/elm/benchmarks/Benchmarks.elm, web/elm/src/Build/Models.elm, web/elm/src/Build/StepTree/Models.elm, web/elm/src/Build/StepTree/StepTree.elm, web/elm/src/Build/Styles.elm, web/elm/src/Concourse.elm, web/elm/tests/BuildStepTests.elm, web/elm/tests/BuildTests.elm, web/elm/tests/StepTreeTests.elm
* Refactor `StepTree.Models.Step` to include `Concourse.BuildStep` - this allows us to be more flexible in what we put in the step headers, as we can use arbitrary data from the public plan for each step
* Display instance vars as key-value pairs (just as we render the `across` step's key-value pairs …
=> Show instance vars in `set_pipeline` step header

vars/build_vars.go
*Bug Fix* | Feature | Documentation
closes #6454  .
Add a mutex lock.
I made the fix on 6.7.x first, because our clusters are running 6.7.3. I want to get the fix in 6.7.4 in near future.
* When multiple `load_var` steps were running in parallel, there was the risk of the ATC crashing due to concurrent map writes …
=> Fix an ATC crash caused by parallel `load_var` steps

worker/runtime/container_test.go
Bug Fix | Feature | Documentation | **Misc**
closes #5184
Backfilling tests for existing functionality
(for example, if they are Garden configs that are not …
=> runtime: add test coverage for container.Stop()

skymarshal/skycmd/oidc_flags.go
Signed-off-by: Aidan Oldershaw <aoldershaw@pivotal.io>
`--oidc-force-email-verified` is kind of confusing/less discoverable than `--oidc-skip-email-verified-validation` …
=> rename OIDC skip email verified flag

atc/atccmd/command.go
Problem:
Previously it assumes `concourse migrate --migrate-to-version` runs only when web nodes are stopped and there are no other concurrent changes to DB ( so the cmd is used for running downgrade only).
`concourse migrate --migrate-to-latest-version` used the same code path. However, when the cmd runs in `initContainer` in concourse helm chart where migrations take certain amout of time due to huge amount of data, a race condition happens if two containers are initiating at the same time.
Change:
Add lock factory to `--migrate-to-latest-version` to ensure thread safe.
Unfortunately we don't have a proper way to test this since migrations in test environment finishes fast enough to mitigate the problem. The plan is to verify it during next hush-house version update.
=> add lock for concourse migrate to latest version cmd

atc/gc/build_log_collector.go, atc/gc/build_log_collector_test.go
closes #6520
* Skip over paused jobs in the build log collector
tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distributi …
=> Skip build log reaping process for paused jobs

atc/db/notifications_bus.go, atc/db/notifications_bus_test.go
Closes #7131 
Backport of #7120
=> [6.7.x]: fix memory leak in notification bus

atc/api/auth/check_pipeline_access_handler.go, atc/api/pipelineserver/reject_archived_handler_factory.go, atc/api/pipelineserver/scoped_handler_factory.go, atc/api/pipelineserver/scoped_handler_factory_test.go, atc/api/policychecker/checker.go, atc/api/policychecker/checker_test.go, atc/api/team_scoped_handler_factory.go, atc/api/teamserver/set.go
backporting https://github.com/concourse/concourse/pull/8566
=> fix team_name overwritten bug

topgun/k8s/container_limits_test.go
We could test it works in ubuntu again when GKE version is upgraded to v1.24 (where ubuntu image for node has newer kernel that allows memory configuration).
=> Container limit tests fix for v6.8.0

skymarshal/skycmd/cf_flags.go, skymarshal/skycmd/flags.go, skymarshal/skycmd/flags_test.go
backporting #8699 to release branch 6.8.x
=> fix cf connector error during web node startup

skymarshal/skycmd/flags.go
=> fix fly integration test for cf auth

atc/db/resource_check_rate_limiter_test.go, atc/scheduler/scheduler_test.go, skymarshal/skycmd/saml_flags.go, testflight/task_vars_test.go
[add yourself]: https://github.com/concourse/governance#individual-contributors
[PR requirements]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md#pull-request-requirements
closes # 
* 
=> chore: remove repetitive words
